### ISSUE TITLE
Shot Generator

### ISSUE THREAD

**Issue by gabe98532** [wonderunit/storyboarder#1006]
Just downloaded Storyboarder and I have a pop-up in the lower right corner that states, "For better performance on your machine, Shot Generator and Perspective Guide have been Disabled". 
Shot Generator would be a primary reason for me to use Storyboarder.
Is there a way for me to enable this?
I'm running Windows 10 Home on an HP Laptop 15-bs0xx.
OS Build is 15063.786
Installed RAM is 12.0GB
System type is 64-bit operating system, x64-based processor
Processor is Inel Core i3-7100U CPU @ 2.40GHz
Not sure how to read Graphics Card info, but it appears to be, Intel HD Graphics 620

**Comment by gabe98532** [comment]
How often should one expect a response on this forum?

**Comment by audionerd** [comment]
There's not a way to enable it in the current version of Storyboarder if your graphics card isn't listed as supported by Electron/Chromium (the software Storyboarder is built with).

We're going to try something, hopefully in the next release, that may allow more graphics cards to be supported.

**Comment by audionerd** [comment]
That is strange. Are you able to load WebGL content in Chrome?
https://get.webgl.org/
http://webglreport.com/

**Comment by EddieSoloProjects** [comment]
"For better performance on your machine, Shot Generator and Perspective Guide have been Disabled".
I got this as well on my VR Capable Asus Laptop with a High End Nvidia card. There needs to be a way to override this. My laptop is more then capable of handling this software.

**Comment by EddieSoloProjects** [comment]
It also just did it on my High End Tower that I render Feature Films on. There is No Way that it's not usable.

**Comment by setpixel** [comment]
Fixed in next release.
