### ISSUE TITLE
Export to Web

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1009]
# export zip

- [x] export each frame as a jpg (720p lowish quality)
- [ ] Convert audio to web-friendly format (mp4 mono / lowest acceptable bitrate)
  - currently exports to AAC MP4 64 kbps. do we want h264 or something else instead?
- [x] reference jpegs/audio in a new .storyboarder file
- [ ] create thumbnail, first frame, 400p lowish jpeg
  - thumbnail.jpg filename ok?
- [ ] create thumbnailanim.jpg [up to 10 frames, 200p lowish jpeg] 
  - currently exports ALL boards to sprite sheet
- [ ] package up in zip file

# upload

- [ ] Choose upload URL (default to our web service)

**Comment by setpixel** [comment]
This is done :D
