### ISSUE TITLE
Weird no pressure/lag/line with wacom tablet

### ISSUE THREAD

**Issue by StarboyAstro** [wonderunit/storyboarder#1016]
I updated storyboarder just this morning and has been doing this weird thing since then, i don't know what to do anymore. 
Its just like a lag but it won't do any curve, like drawing a stick on the floor-sorth of. 
![image](https://user-images.githubusercontent.com/36141023/35783731-bd86f416-09d1-11e8-9ac1-1b9db7ada08b.png)
Didn't this before but since the update it happened, i tried to do the usual with the wacom tablets, to unable the windows pen but nothing changed since. 
If i try to keep drawing it just lags a lot and won't change much anyway.
I'm working on a Windows 8.1, i got a AMD radeon graphic graphic card, with 12gb of RAM, at 1366x768 px.

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
