### ISSUE TITLE
Not really a bug, but a problem

### ISSUE THREAD

**Issue by RaeIsBestDragon** [wonderunit/storyboarder#1019]
So I don't actually have Photoshop, and when I try to use the Photoshop feature it instead goes to Autodesk, which is really cool. However, when I try to save the file it doesn't automatically load to storyboarder. On top of this, renaming the file and changing the extension to a psd doesn't work and I get a message saying I'm using an unsupported psd feature. It would be much better if this wasn't the case or if storyboarder would automatically accept tif files as well. It's pretty difficult for me to just draw in the app itself since I have one of those touch screen computers where you flip the keyboard back, and I don't see an undo button on the screen and my hand keeps bumping into the things on the right side of the screen (that's probably not much of an issue for most people, I know). I just think it would be much more convenient to have compatibility with Autodesk or if there's some way for it to work already, I would love to know.

**Comment by audionerd** [comment]
PSD reloading should be improved in the next release. Tracking as issue #1656.
