### ISSUE TITLE
Photo import through Mobile Browser

### ISSUE THREAD

**Issue by curatorsigma** [wonderunit/storyboarder#1032]
__Recreation:__
Have Storyboarder open, but not in Front. Import Photo through Mobile Browser.

__What should happen:__
New Board with the imported image gets created. (Works seamlessly when storyboarder is in Front btw.)

__What happens:__ 
Image gets imported on top of current board. All images get clumped together in one movable image.

__OS:__
OSX Yosemite 10.10.5

__Specs:__
3,2 GHz Intel Core i3 *Processor*
8 GB 1067 MHz DDR3 *RAM*
ATI Radeon HD 5670 512 MB *Graphics*

**Comment by audionerd** [comment]
This is fixed in the latest release. https://github.com/wonderunit/storyboarder/releases/tag/v1.7.1
