### ISSUE TITLE
Scenes save separately without script

### ISSUE THREAD

**Issue by Erentia** [wonderunit/storyboarder#1034]
Hey guys
I just started out with Storyboarder - great program by the way!. Just one problem, which can be ignorance as well.
When I saved my project and wanted to open it again to continue working, it only opened one scene. I've imported a final draft script and been working with it. Now the program only opens the two scenes separately and without the script. How do I get everything back in one document?!

**Comment by audionerd** [comment]
If you open the script again, it should start Storyboarder's scene mode, and you should see all your scenes. Does that work?

**Comment by Erentia** [comment]
Hi Eric

Thanx for your reply. I accidently got it right again! So it was ignorance
after all.

Really a great programms, thank you so much!

**Comment by audionerd** [comment]
👍
