### ISSUE TITLE
Storyboarder bag?

### ISSUE THREAD

**Issue by Xitaychin** [wonderunit/storyboarder#1042]
Hello!
After some time of wirking the workspace becomes gray, "file", "edit" etc. windows are clickable but don't work. Everything is preserved, just inability to continue.
Windows 10, AMD FX-4330 quad core processor, NVIDIA GeForce GTX 750 Ti, 8gb RAM, 1920х1080.

Kinds regards,
Alsu

**Comment by setpixel** [comment]
Can you explain this in more detail?
