### ISSUE TITLE
My suggestion on developing this application.

### ISSUE THREAD

**Issue by Masa-S-Ayarama** [wonderunit/storyboarder#1043]
Hi Developer,

I just download storyboarder application and start learning it. It would be great if the canvas adjustable, drawing tools is smaller, and can hide scene description panel.

Anyway thank you for making this great app.

**Comment by audionerd** [comment]
Thanks! Those are good suggestions!

You can hide the scene description panel by pressing the Tab key a few times to cycle the "view mode" into a full width drawing view.
