### ISSUE TITLE
"Cannot read property 'update' of undefined"

### ISSUE THREAD

**Issue by yumtime** [wonderunit/storyboarder#1045]
When trying to create a storyboard file using a script I get this error:
"Cannot read property 'update' of undefined"

 and then this pop up:
Uncaught TypeError: Cannot read property 'getIsDrawingOrStabilizing' of undefined
In file: /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/window/main-window.js#1873:29

And the file won't open. 

Tried both on Mac and Windows 10, using both a Fountain and a Final Draft file.

**Comment by audionerd** [comment]
Thanks for the report. Found the issue. Should be fixed in the next release.
