### ISSUE TITLE
.fountain import problem

### ISSUE THREAD

**Issue by timmrogers** [wonderunit/storyboarder#1046]
Trying to import a .fountain file. It does not import, and gives an error: 

"Cannot read property 'update' of undefined"

File is attached.

[No Loving Kindness.fountain.txt](https://github.com/wonderunit/storyboarder/files/1787777/No.Loving.Kindness.fountain.txt)

**Comment by audionerd** [comment]
Thanks for the report. Found the issue. Should be fixed in the next release.

Duplicate of #1045
