### ISSUE TITLE
program don't work in  desktop apple Mac Pro - OS X 10.11.6

### ISSUE THREAD

**Issue by gasiot** [wonderunit/storyboarder#1055]
the bugs
initial screen, don display all options. mount  text
(i dont speak English)
work space, don't display all features.
(i dont speak English)

recreate:
open de software. 

i expected:
initial screen, tex an image don't mount.  see all bottoms.
work space,  see all bottoms and the drawing space.

actually
 initial screen, text an image mount.  i don't see all bottoms,  and options.
work space, i don't see all bottoms and the drawing space, tools and options..

OS:
OS X 10.11.6

hardware
Mac Pro (principios de 2009), procesador 2,66 GHz Quad-Core Intel Xeon, memoria 8 GB 1066 MHz DDR3, gráficos NVIDIA GeForce GT 120 512 MB
wacom intuos 4
![captura de pantalla 2018-03-14 a las 12 07 11 p m](https://user-images.githubusercontent.com/22361414/37411476-a27d7488-2781-11e8-8f44-9e590298a5c3.png)
![captura de pantalla 2018-03-14 a las 12 17 52 p m](https://user-images.githubusercontent.com/22361414/37411532-c5ee09b4-2781-11e8-9d85-b65aa9a54432.png)

**Comment by setpixel** [comment]
Oh hmm.. We may not be able to support this software. It looks like the graphics card is not drawing properly. Did Storyboarder ever work properly for you?
