### ISSUE TITLE
ELECTRON ISSUE: Cant access top menu with stylus

### ISSUE THREAD

**Issue by EvangaLa** [wonderunit/storyboarder#1058]
Clicking just highlights the tabs. With a stylus (Wacom Bamboo) sometimes it opens but most times I have to use a mouse to get the menu to drop down. I have a double screen setup, when I move to the other screen and come back to the program the menus works until I click out of the menu tabs, then I cant access it again. All other menus and tools work perfectly.

Love the program. Thank you so much!

**Comment by setpixel** [comment]
This is on windows, correct?

Also which version of the OS?

**Comment by christiansass** [comment]
i get that bug on both my cintiq 21ux and companion both running windows 10

**Comment by EvangaLa** [comment]
Yes, this is on windows 10 pro 64bit.

Sent from Yahoo Mail on Android 
 
  On Mon, 2 Apr 2018 at 6:11 PM, Charles Forman<notifications@github.com> wrote:   
This is on windows, correct?

Also which version of the OS?

**Comment by ichbinmatthias** [comment]
same problem here. same OS

**Comment by cforcalvin** [comment]
same, same win 10, surface pro 4

**Comment by audionerd** [comment]
I'm going to mark this as closed as of Storyboarder 1.9.2. Please give that version a try, and let us know if we need to re-open this issue.

**Comment by EvangaLa** [comment]
Awesome. Thanks for the cool program. Will test it out. 

Sent from Yahoo Mail on Android 
 
  On Mon, 5 Nov 2018 at 7:00 PM, Eric Skogen<notifications@github.com> wrote:   
I'm going to mark this as closed as of Storyboarder 1.9.2. Please give that version a try, and let us know if we need to re-open this issue.
