### ISSUE TITLE
Used updater, now can't open Storyboarder (last three versions)

### ISSUE THREAD

**Issue by simon-shd** [wonderunit/storyboarder#1059]
Hi,
I'm using MacOS El Capitan - 10.11.6 on a MacBook Pro (Retina, 15-inch, Mid 2015).
I had installed Storyboarder a while ago but hadn't been using it -- last night I opened it up (not sure what version it was) and it prompted me to upgrade to the latest, so I did that. So it went through the download process and install process fine, but then when it started up Storyboarder I got a window stating "A JavaScript error occurred in the main process" (more on this below). 

So I thought - OK, maybe the update messed up somehow. So deleted the .app, and downloaded the .dmg from github for v1.5.1 and installed it. Same error. So figured, maybe its just the current version. So I tried installing v1.5.0 - no luck. Same with v1.4.1. Now I'm at a loss.

Details of the error:
When I double-click on the Storyboarder icon, it loads for a little bit, then an alert window pops up with "A JavaScript error occurred in the main process" as the title, and the following as the details:
```
Uncaught Exception:
TypeError: Cannot read property 'split' of undefined
    at versionCanBeMigrated (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/prefs.js:146:16)
    at Object.init (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/prefs.js:156:7)
    at Object.<anonymous> (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/main.js:11:12)
    at Object.<anonymous> (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/main.js:1268:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/Applications/Storyboarder.app/Contents/Resources/electron.asar/browser/init.js:171:8)
```
When I hit OK, the window closes and I have "Storyboarder" in the menu bar, but the only command under that menu is "Quit".

I figure that perhaps I have a prefs file left over from the previous installation? I don't know where I'd find it, though. I've emptied the trash after deleting app packages.

**Comment by setpixel** [comment]
@audionerd can you help debug this?

**Comment by audionerd** [comment]
Hi @simon-shd 
On a Mac, the preferences JSON file will be in `/Users/[USERNAME]/Library/Application Support/Storyboarder/pref.json`
Can you tell us what you see as the contents of that file?
It should start with a version number, e.g.:
```
{
  "version": "1.5.1",
  ...
}
```

If that file is corrupt somehow, it could cause problems. To fix it, you can try moving the `pref.json` file to the trash (make a backup of the file first if you want), and restart Storyboarder. Storyboarder will then re-create `pref.json` from defaults.

**Comment by simon-shd** [comment]
AHA. The JSON file must have gotten corrupted, or was maybe from a waay early version? It started with "recent documents" (full text below, filepath replaced by ***** for brevity), not "version". I deleted the file and started up Storyboarder 1.5.1, and I'm back running. 

Thanks!

contents of the old JSON file (full filepath replaced by ******):
`{"recentDocuments":[{"type":"script","sceneBoardsCount":0,"sceneCount":2,"totalMovieTime":26800,"title":"UNTITLED","filename":"******","time":1489083258116}]}`
