### ISSUE TITLE
Shot generator and file export

### ISSUE THREAD

**Issue by FernandoSou** [wonderunit/storyboarder#1061]
Hello I m new at storyboard I like it very much is great but I need to ask you this
Would it be better if actions in the Shot generator would be in alphabetical order/
How can I place a male and female in same window 
When i place two or three people in the window and I command Sitting only one is sitting the other are standing
When I export in for final cut or other ( except as gift) it does not show the dialogues in thee windows ( they disappear)

**Comment by setpixel** [comment]
Hi @FernandoSou 

We are working on a new version of the shot generator that will address these issues. As far as adding captions in Final Cut, I think this is impossible. UNLESS, you would like to bake the captions into the image. We may be able to do this. Please let us know.
