### ISSUE TITLE
Website: Download page is not working

### ISSUE THREAD

**Issue by benwinding** [wonderunit/storyboarder#1065]
To inform the developers, the download page: [https://wonderunit.com/storyboarder/](https://wonderunit.com/storyboarder/) is unavailable. 

My system:
 - Ubuntu 64bit
 - Google Chrome | 65.0.3325.181 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/11782590/38017790-9d6b5b60-32ba-11e8-8037-27bec1e6c405.png)

**Comment by pakastin** [comment]
Same thing with the latest Safari, Chrome and Firefox in macOS.

**Comment by pakastin** [comment]
Tip: if your website is static, try hosting it with GitHub Pages (it's free).. 😉

**Comment by setpixel** [comment]
@pakastin do you still have this issue? There was a DNS error on our side that should be fixed. Please comment if you still have this issue!

**Comment by srikarindl** [comment]
Yes i do have
