### ISSUE TITLE
website: "Just a few features..." images not showing up

### ISSUE THREAD

**Issue by RasmusWL** [wonderunit/storyboarder#1066]
The images are blank :cry:  pointing to `https://wonderunit.com/storyboarder/image.png`

![screenshot from 2018-03-28 15-10-18](https://user-images.githubusercontent.com/1054041/38030890-2ce34620-329a-11e8-88be-3283d02bc264.png)

Awesome project by the way! Love the fact that you're calling people out, and is not afraid to say fuck :heart:

**Comment by setpixel** [comment]
Ah yeah :) I need to actually make images. I actually need to update the site with all the new features. I'm going to track this outside of storyboarder repo. Thanks!
