### ISSUE TITLE
Warning: This is not Open Source Software

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [wonderunit/storyboarder#1067]
I believe this project is engaging in a bad-faith effort to pass itself off as being Open Source software with no intention to actually license the code under a FOSS license.

There have been two issues and one PR raised concerning the license situation: https://github.com/wonderunit/storyboarder/issues/567 https://github.com/wonderunit/storyboarder/pull/589 https://github.com/wonderunit/storyboarder/issues/588

The issues were silently closed without comments, and the PR has languished since summer 2017. The project's website contains a rather rambling post mudding the water on Open Source, but basically laying out a plan to create some sort of custom license allowing free personal usage, but not redistribution or commercial use: https://web.archive.org/web/20180130105751/https://wonderunit.com/thoughts-on-free-and-open-source/

Meanwhile, the previous licensing as ISC was rather quietly removed from ```package.json``` last year: [https://github.com/wonderunit/storyboarder/commit/2a87fa23d](https://github.com/wonderunit/storyboarder/commit/2a87fa23d9926bce80b069267dc1fea8efdbd3db#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

I believe contributors to this project expect their work to benefit Free Software as it's commonly understood. The issue was raised with the project owner multiple times, starting more than half a year ago. At this point, it is obvious that they are unwilling to clarify the situation, and prefer to instead profit from the deception they're creating.

Note that according to [Github's Terms of Service](https://help.github.com/articles/github-terms-of-service/#4-license-grant-to-us), publishing via a public repository already constitutes a license grant that appears to be incompatible with whatever usage restrictions the above-linked blog post is trying to articulate:

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking).

**Comment by setpixel** [comment]
Greetings, unhelpful Hacker News user,

Cool photo. I know you're angry, but it's probably because of something else in your life. Like, maybe other children on the playground were mean to you, or you love killing small animals? I actually don't care which one it is.

In any event, It is Open Source Software. The source is publicly viewable. You can see it. You can run it. You can use it.

I'm rather sure you don't make anything yourself. I'm also sure you can't draw anything except conclusions. I don't see how you're being helpful at all here.

Sorry I don't conform to the way you think the world should work. I hope you get through life peacefully. Stay away from AR-15s and don't be following any short Austrians!

<3

**Comment by bauerd** [comment]
I don't think "Open Source" means what you think it means. Maybe consult a search engine and familiarise yourself with the terms you use?

PS: Do I get a Hitler reference as well? I'm German after all.

**Comment by setpixel** [comment]
The source is open. As in, stores are open. Maybe try independent thought and familiarize yourself with dissenting opinion.

Hitler what? Congratulations on being German I guess? 

You annoy me.

**Comment by bauerd** [comment]
I'm not in the business of playing word games. Have a great day :-)

**Comment by drewcummins** [comment]
Yeah, and you CRIPPLED the comedy of Lagrange!
