### ISSUE TITLE
SUGGESTION: auto size boards based on time calculated by dialogue. 

### ISSUE THREAD

**Issue by christiansass** [wonderunit/storyboarder#1070]
An option to auto size boards or one click size them based on time calculated by dialogue would speed up my process greatly. I figure if you can already calculate the length of it, why not give us the option to just click it in instead of having to type it it ?? or maybe a menu option to size all board based on calculated time in the dialogue panel.

![image](https://user-images.githubusercontent.com/35471675/38108807-9e586d5a-335b-11e8-8db1-e8024d5d976b.png)

**Comment by christiansass** [comment]
![image](https://user-images.githubusercontent.com/35471675/38213496-057c3fba-3687-11e8-8bf8-857805e521f5.png)

Maybe this? maybe it would be more elegant to make the dialogue time info into a button?

**Comment by setpixel** [comment]
Fixed in next release!

**Comment by christiansass** [comment]
sweeet!
