### ISSUE TITLE
Suggestion: Unlink all boards from Photoshop at once

### ISSUE THREAD

**Issue by ichbinmatthias** [wonderunit/storyboarder#1077]
Hi, it regularly occurs to me that storyboarder gets really really slow once I edited a lot of my panels in photoshop. It is quite tedious to unlinke all the panels individually, especially as I have to doubleclick each panel with the mouse as the tablet is not recognized when doing that. Would be lovely if there was an option to unlink all panels at once.

**Comment by izzyholder** [comment]
I agree, this would be a time-saving function. I regularly switch between Storyboarder and my editing software, and notice a slowing down of drawing pace because of this.

**Comment by setpixel** [comment]
Going to move this issue into here: #963

**Comment by audionerd** [comment]
Should be improved in #1656.
