### ISSUE TITLE
problem with sound

### ISSUE THREAD

**Issue by fredericlafay** [wonderunit/storyboarder#1078]
Hi guys.
Thank you so much for Storyboarder, that's amazing software.
Unfortunately, I found a mistake with the sound.
I wanted to put a soundtrack on my board. I have selected the 1st shot and pressed play. 
The sound didn't match so I deleted it with the icon "trash". 
Then I keep working on my board, listening to music on my computer. 
I find another music and import it in Storyboarder. The music on background cut so that I can listen to the soundtrack in Storyboarder. I tell myself, that's nice that Storyboarder cuts the sound of other software, like that, I can work more quickly. 
Finally, the music didn't suit me, I deleted it. 
Unfortunately, now, I can't listen to music anymore. At whenever my project is open, the music, both on the internet and iTunes for example, is like put on hold. Impossible to listen to music, I just hear sometimes a little noise on mine speakers. 
I also made a mistake, I deleted the sound files in my "images" folder.
I think the code is searching for links that no longer exist.
The trouble now appears, every time I open my file.

I work with a NUC - Windows10 - 64bits
Processor: Intel i5-6260U CPU 1,80Ghz
Graphics Card: Intel(R) Iris(R) Graphics 540
RAM: 8,00 Go
Wacom Cintiq 13HDT

Thank you very much for your help and your work.
Fred

**Comment by fredericlafay** [comment]
Hi guys
In fact, I feel like having a problem with the Bluetooth connection of my speaker. 
I will continue to do tests.
Thank you

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the next release.

Fixed by https://github.com/wonderunit/storyboarder/commit/11c67fb0f7bb42293515eab9a57f68341989193f
