### ISSUE TITLE
I can't even open a blank artboard

### ISSUE THREAD

**Issue by egiova** [wonderunit/storyboarder#1082]
Windows 10 user: when I want to open a new *artboard*, *Storyboarder* ask me for an existing file after the thumbnails screen (about sizes). Is it possible to start from scratch? Or do I need an existing file? I'm confused.

**Comment by audionerd** [comment]
That's a "Save As" screen, to name your project. There you can enter a name, hit "Create" and you'll be ready to go :)

**Comment by egiova** [comment]
Didn't work, and your answer is quite obvious really.
But I downloaded a test file of yours, I opened it et voilà.
So, I'm good, thanks your reply.
