### ISSUE TITLE
Panel does not update after edited in SAI

### ISSUE THREAD

**Issue by izzyholder** [wonderunit/storyboarder#1085]
Hello, I set SAI as my editing software instead of PS.  The first time I opened a panel to edit it in SAI, it automatically updated in Storyboarder.  But every time after that, I've had to save the psd file in SAI, close it, then go back to Storyboarder and click the "edit in PS" button again before it would update.  Is this because it's connected to SAI, and not PS? 

I have a Windows 10 Surface Studio.

**Comment by izzyholder** [comment]
An update on this curious issue: I noticed that the panel will automatically update in Storyboarder if the edits in SAI are simple, like moving some lines, as opposed to scaling or rotating them.

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
