### ISSUE TITLE
Button for updating certain panels after they were changed in Photoshop

### ISSUE THREAD

**Issue by ichbinmatthias** [wonderunit/storyboarder#1086]
Storyboarder sometimes doesn't "get it" that I updated a panel in Photoshop and I have to close it entirely and start it again in order to have it load the latest version. Would be nice to have an "update" button.  Would also be nice to be able to "unsync" several panels from photoshop at the same time instead of having to doubleklick each one separately.

**Comment by bobbybutterfly** [comment]
same here, randomly a saved pic is not updated. Even a restart of Storyboarder does not bring that Picture in :/- in Autodesk Maya they have a "reload" button for the photoshop file. Other Programs have that too.

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
