### ISSUE TITLE
Image export should have size options

### ISSUE THREAD

**Issue by izzyholder** [wonderunit/storyboarder#1094]
When the sequence gets exported, it always is saved as a percentage smaller than full size. I use HD aspect ratio, so the images are always being exported as 1600 x 900 rather than 1920 x 1080. I see no option to change the size.

There should be an option to export full size, or half size, etc. It’s a bit annoying to deal with images that aren’t the right size for use somewhere else.

**Comment by audionerd** [comment]
Storyboarder uses an image height of 900px and variable width depending on aspect ratio. So the images you see when exported are as large as they can be given Storyboarder's internal setup.

If your aspect ratio is set to 16:9, Storyboarder internally is using 1600x900 for storage, not 1920 x 1080.
