### ISSUE TITLE
keeping text layers in photoshop

### ISSUE THREAD

**Issue by mikesperrey** [wonderunit/storyboarder#1098]
I'm using storyboard to brief animators creating corporate mographs (maybe not what you guys intended, but it works well for me!).
I'm sketching in Storyboard, and then adding text in photoshop. I would be good to keep those layers created in photoshop, so that I can go in and amend the copy in shop afterwards.

**Comment by setpixel** [comment]
Hi Mike!

We use a library that unfortunately doesn't handle photoshop's text layer at all. I wish it did, because I would love this same feature. But I am at the mercy of them. :(
