### ISSUE TITLE
Duplicating a board also duplicates the checked "New Shot" checkbox

### ISSUE THREAD

**Issue by ichbinmatthias** [wonderunit/storyboarder#1100]
This is a bit annoying as a duplicated board in 99% of the cases is NOT gonna be a new shot, at least in the way I work.

**Comment by setpixel** [comment]
Hmmm.. I can see this for duplicating shots, but not for copy and pasting.

**Comment by christiansass** [comment]
copy and past of frame content alone is a similar issue. i have make a request  about a similar thing.
