### ISSUE TITLE
drawing on edited Photoshop files not possible?

### ISSUE THREAD

**Issue by bobbybutterfly** [wonderunit/storyboarder#1111]
i edited a board via the "edit in Photoshop" button, saved it, and it reappeared as expected in Storyboarder. But now i cant draw on it anymore - it is locked.

Is this a bug or normal behavior?

Thanks

**Comment by setpixel** [comment]
You can double click and edit it, but it breaks the relationship to to the photoshop file. (all layers you had will be flattened)
