### ISSUE TITLE
Refactor LayersEditor

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1116]
LayersEditor shouldn't maintain its own model of opacity. 

Currently, LayersEditor manages a "temp" concept of opacity for the reference layer. So if you haven't drawn on the reference layer yet, we don't save a PNG and we don't add layer data. But, we need some place to keep the opacity data of the reference layer so you can adjust it. Then if you draw on it, once time elapses we write to the JSON file _with correct opacity data_.

A better solution would be to store the temporary reference layer data in a reducer. if a reference layer has an opacity change, but no drawing yet, we can store the opacity there. Then, if the user ever draws at all, we add the layer data (with _correct opacity_) to JSON and save the PNG.

---

LayersEditor should be a "dumb" component.
When board's layer opacity changes, layers editor should be notified, and update based on the board data.
When LayersEditor wants to change board layer opacity, it should dispatch a message.

see:  fix getReferenceOpacity in saveImageFile

**Comment by setpixel** [comment]
Are you basically saying that the model, view, and controller should be their own things? :D

**Comment by audionerd** [comment]
Lol. I would have written a shorter issue, but I did not have the time.

**Comment by audionerd** [comment]
Related: https://github.com/wonderunit/storyboarder/commit/a4de21e6ea36bafbe4b99e1f35960bf9640290f6
