### ISSUE TITLE
------------------------v1.6.0------------------------

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#1130]

**Comment by christiansass** [comment]
???

**Comment by setpixel** [comment]
its for this list: https://github.com/wonderunit/storyboarder/milestone/8

**Comment by audionerd** [comment]
we needed a horizontal rule 🙃

**Comment by christiansass** [comment]
why don't we have a v1.6.0 list seperate from 2.0 then?

**Comment by setpixel** [comment]
it's the march towards 2.0!
