### ISSUE TITLE
Music getting grating and I can't turn it off.

### ISSUE THREAD

**Issue by calebjackson** [wonderunit/storyboarder#1137]
**Describe the bug**
The musical notes get more and more distorted the more I draw, and I figured I'd just turn it off. However, I've tried Navigation > Stop All Board Audio and unchecked Drawing Melodies and User Interface Sound Effects and it's still playing the musical notes. Any idea what's wrong?

EDIT: Oh! Just had to close and reopen.

**Comment by audionerd** [comment]
Yeah currently if you modify those preferences you have to restart Storyboarder for them to take effect.
