### ISSUE TITLE
how the heck do you close the program???????????????????????????????????????????????????

### ISSUE THREAD

**Issue by critkillen** [wonderunit/storyboarder#1148]
why would it be even remotely anything but completely obvious how to close the program? How do i get out of it? seriously

**Comment by audionerd** [comment]
What operating system are you on? What did you try, what did you expect, what did you see instead?

**Comment by setpixel** [comment]
Can you post a screenshot???????????????????????????????????????????????????

**Comment by setpixel** [comment]
I've looked into this bug and it was between the steering wheel and the driver seat.

**Comment by JohnPurvis** [comment]
I imported a script from final draft but then did a page one rewrite on it. So how do I now delete the old project based on the old script? I imported the rewrite with no problem. But how do I delete the old? Also, I hit some key and a big window opened up that has a typewriter keyboard across the top and what looks to be the other tools below the keyboard. How do I close this window? Where is the "X" in the upper right corner that would close this?
