### ISSUE TITLE
Make a backup of scenes created by older versions of Storyboarder 

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1195]
When a scene is opened, check if it was created with an older version of Storyboarder. It is considered so if:
- at least one board's `url` (the "main" layer) references a file that _still exists_ in the images folder

If so:
- make a backup copy of the entire scene folder, `.storyboarder` file, images
- be sure to include all "main" layer (`board.url`) images
- when making the copy, ignore missing files (it won't have posterframes or thumbnails but we don't care)

The backup will be stored alongside the main folder, e.g.:
- `my-scene` > `my-scene-backup`

**Comment by setpixel** [comment]
I think we can just copy the folder to the adjacent location. Append
'backup' to the folder name.

**Comment by audionerd** [comment]
If an artists opens the created "backup" copy, it will attempt to make _another_ backup. Do we want some kind of flag to prevent this? We could just bypass the backup process if the folder already is called "-backup" _and_ there is a similarly named project alongside it?

**Comment by audionerd** [comment]
<img width="532" alt="screen shot 2018-06-08 at 1 30 29 pm" src="https://user-images.githubusercontent.com/23459/41174585-308697a0-6b20-11e8-9294-f0cb78b65024.png">
