### ISSUE TITLE
Wrong thumbnail 

### ISSUE THREAD

**Issue by DiteDo** [wonderunit/storyboarder#1199]
Hello,

Sometimes there is a problème with the shot that display the wrong thumbnail
![thumbnail2](https://user-images.githubusercontent.com/12872227/41186672-e3ad55a6-6b9a-11e8-98b9-1682d2f631a2.jpg)

![tumbail](https://user-images.githubusercontent.com/12872227/41186665-9e8d5728-6b9a-11e8-928f-b78ad9cfc44d.jpg)

**Comment by audionerd** [comment]
Thanks for the report. We have a fix for this problem in the next release which should be available very soon.


PS I dig the art style in these screenshots.

**Comment by DiteDo** [comment]
Ok thanks  

Sorry my english is not good I don't undestand "I dig the art style in these screenshots."  :D

**Comment by audionerd** [comment]
I like the artwork in the images you posted :)
