### ISSUE TITLE
 lag after update

### ISSUE THREAD

**Issue by quangsoi** [wonderunit/storyboarder#1217]
some shortcut key doesn't work correctly and the number of pencil and fill brush pen has been reverse. Before the update the draw tool was working very smoothly but after the update, the brush strokes not following my wacom 

i'am using asus gl753ve, 16gb ram, gtx1050ti 4gb

**Comment by audionerd** [comment]
what operating system are you using? can you post details about your computer speed, graphics card, RAM, etc?

when are you experiencing lag? while drawing? while navigating between boards?

**Comment by bobbybutterfly** [comment]
same here on a Surface pro 3, win 10 64bit - extreme lag on every drawing tool - unusable

also: my pen tip doubleclicks to open a board in Photoshop are not working - mouse works
        my pen tip does not open a the menus from the menu bar - mouse works
other than that, pen works

**Comment by bobbybutterfly** [comment]
the drawing runs extremely well on my workstation:16GB ram, i7 4790k, Geforce GTX 960 4GB
but on my older Workstation with FirePro v5900 and on my Surface pro 3 unusable slow
Maybe an option in the preferences would help - switching between high and low GPU power,
using the old drawing engine for slower PCs

**Comment by bobbybutterfly** [comment]
1.6.3 works very good now on my Surface 3 with "Efficiency Mode"

The spacing of the "Pastel Brush" is a little too wide for my taste, because now you see the circles.

A slightly reduced spacing for that brush would be great

**Comment by setpixel** [comment]
@bobbybutterfly awesome! I'm going to tighten the pastel brush for the next release.

**Comment by bobbybutterfly** [comment]
@setpixel great:) Thanks a lot!
