### ISSUE TITLE
Can't see the cursor

### ISSUE THREAD

**Issue by SirRubius** [wonderunit/storyboarder#1222]
After making some strockes the brush cursor dissapears. I can only make it appear for a short time by changing to other brush and return to the previous

**Comment by tobiaslittle** [comment]
I can't either!!! terrible!

**Comment by setpixel** [comment]
Can you take a screenshot?

**Comment by audionerd** [comment]
Is the cursor disappearing when you use the mouse? or pen/tablet?

**Comment by SirRubius** [comment]
I'm using Tablet. I start drawing and then the little circle dissapear
