### ISSUE TITLE
Job #1223 UPDATE

### ISSUE THREAD

**Issue by tobiaslittle** [wonderunit/storyboarder#1223]
Guys,

The latest update has really screwed my project. It's so glitchy and the brush strokes/ commands/ skin layers have all changed. I can't see the cursor over the image at times too. It's a nightmare. Please revert or fix asap.

**Comment by setpixel** [comment]
hi tobias

sorry about that.

we're working to fix the speed issues with the drawing engine.

you can download the older version here: https://github.com/wonderunit/storyboarder/releases/tag/v1.5.1

the newer version duplicated your old storyboarder project, so open the backed up version.

sorry!

**Comment by tobiaslittle** [comment]
hi setpixel

thanks for your response. I didn't back up my project before installing the latest version of storyboarder. is it just a case of installing the older version you've provided and my project will be there? is there a danger my work will be lost?

**Comment by tobiaslittle** [comment]
so I just import the latest images from the latest export. the link you provided doesn't seem to do anything other than take me to page full on links. could you tell me what to do from here? thanks

**Comment by audionerd** [comment]
There should be a "-backup" folder created automatically. For "my-project" it would be called "my-project-backup" for example. The backup is the 1.5.1 compatible version.

There are download links for Storyboarder 1.5.1 for each operating system at that release page.

macOS: https://github.com/wonderunit/storyboarder/releases/download/v1.5.1/Storyboarder-1.5.1.dmg

Windows: https://github.com/wonderunit/storyboarder/releases/download/v1.5.1/storyboarder-setup-1.5.1.exe

**Comment by tobiaslittle** [comment]
it has messed up all of my drawings!! now that I have gone back to the new version in the hope of it being re-stored it's saying a back-up exists and I should re-name it....but when I do another is generated....how do I import my imagines into a new project....It asks for the QR Code...what is this. please help ASAP this is a disaster

**Comment by setpixel** [comment]
@tobiaslittle can you send me a zip of the backup folder?

**Comment by tobiaslittle** [comment]
its too large....198mb even as a zip

**Comment by tobiaslittle** [comment]
please tell me how to import. ive all the exports....it asks for the QR Code...

**Comment by tobiaslittle** [comment]
![paint](https://user-images.githubusercontent.com/40281163/41449665-4a26c7f4-705a-11e8-94ed-70e1125f01d3.png)

**Comment by tobiaslittle** [comment]
![image](https://user-images.githubusercontent.com/40281163/41450429-990b4d36-705f-11e8-9ebd-2063a1283725.png)

**Comment by audionerd** [comment]
If you see that message, you're running Storyboarder 1.6 on a folder with files it can't understand.

If you want to get back to your old work, what you should do is:
- install Storyboarder 1.5.1 from the link above
- find the backup of the project that Storyboarder 1.6 created for you. This backup is a safety net. The backup is a version that can ONLY be opened properly by Storyboarder 1.5. It will have "-backup" in the folder name. Do not open this with Storyboarder 1.6.
- open the backup with 1.5.1

**Comment by tobiaslittle** [comment]
![image](https://user-images.githubusercontent.com/40281163/41451044-ec183766-7062-11e8-9e16-8df4ef8223ac.png)

**Comment by tobiaslittle** [comment]
![image](https://user-images.githubusercontent.com/40281163/41451060-fad92d78-7062-11e8-889d-80279d1e970c.png)

**Comment by tobiaslittle** [comment]
WHAT IS HAPPENING??

**Comment by audionerd** [comment]
If you're seeing those messages, that's not a 1.5.1 formatted project. So it's either not the correct `-backup` folder, or it's a backup folder that you somehow managed to open in 1.6 and it got confused.

Your work is still in the folders, we just might need to do a little work to get things back in order.

The best way for us to help is to send us a ZIP of ALL the project folders you have, and we can take a look.

If you have Dropbox or Google Drive or similar you could upload it there, and then email us a link.

**Comment by tobiaslittle** [comment]
I can send it via drive. what your email address? i've saved so many now i'm really getting confused about where i am. please help!! this has taken me months and my deadline is 25/6

**Comment by tobiaslittle** [comment]
link sent via tobiaslittle01@gmail.com thanks

**Comment by tobiaslittle** [comment]
please can you confirm that you've received the link and you're ok with it

**Comment by setpixel** [comment]
@tobiaslittle 

Alright first: You are freaking out. So just chill the fuck out. If you send another message with multiple question marks, we might just ghost on you. You don't want that dawg. We're trying to help you out.

Second: You didn't send me the right files. 

Can you take a screenshot of the folder structure of the files you do have? We are looking for the -backup folder. I want to see what you have, and what's in it. The way you sent the zip file, it's impossible to know what is where. I understand you aren't super tech savvy, so I'm trying to figure out what you have on your computer.

**Comment by setpixel** [comment]
@tobiaslittle Good news. I've recreated the file with what you sent.

It's important that you uninstall 1.6 and install 1.5.1, and do no upgrade. 

If you open this project in 1.5.1 it will work fine.

https://www.dropbox.com/s/jc249zd9znlx53d/Running%20-%20SSS%20Production%20Scene.zip?dl=0

**Comment by tobiaslittle** [comment]
Hi guys

thank you so much for fixing my problem but i've ran into the same issue on a different Storyboarder project. This too happened last night

I know i probably haven't done below correctly but can you take a look at the link that contains a zip of the images and file and work your magic once again. I promise to become more tech savvy after this.

https://drive.google.com/file/d/1u8TsbJ-d0edyJtL4j3HcGc40eD6z0fpo/view?usp=sharing

thank you

Toby

**Comment by tobiaslittle** [comment]
Hi

Here's a screen shot of the error message when trying to load my project

![image](https://user-images.githubusercontent.com/40281163/41482528-c4bd4696-70cd-11e8-8c2d-6d55cd5bfd97.png)

Thought it might help

Thanks

**Comment by setpixel** [comment]
Here you go:

https://www.dropbox.com/s/flnzwnjmxuioniv/Running%20-%20SSS%20Production.zip?dl=0

Again, make sure you only open it in 1.5.1

**Comment by tobiaslittle** [comment]
I can't thank you enough! Great job guys. This was my mistake and thank you for correcting it so urgently.

Regards

Tobias
