### ISSUE TITLE
Storyboarder crashes with Fountain script

### ISSUE THREAD

**Issue by redemprez** [wonderunit/storyboarder#1225]
1. Storyboarder 1.6.1:  Create blank storyboard with...
2. ... a script formatted with Fountain Markup Language (exported from Amazon Storywriter or Cinemavision Fountain Editor). 
3. Storyboarder crashes on load with the following message:

![image](https://user-images.githubusercontent.com/25802640/41497559-941ff6ac-7157-11e8-95e1-da84316f7f52.png)

Expected behaviour:
no crash! :)

Windows 10, x64.

**Comment by audionerd** [comment]
Can you provide a link to an example script that exhibits this behavior?

**Comment by redemprez** [comment]
Link to Script that crashes storyboard. Made in Amazon Storywriter: https://drive.google.com/file/d/1d55KP3tS8ErrVJnRz0vXwUv03jtsSMCY/view?usp=sharing

**Comment by audionerd** [comment]
Thanks for the reports. This will be fixed in the next release.
