### ISSUE TITLE
"Clear" button for Notes in Sidebar doesn't do anything

### ISSUE THREAD

**Issue by Artstax** [wonderunit/storyboarder#1226]
Clear note layer does not work - doesn't clear note pen drawings, but does clear pencil drawings.
SB 1.6. Win 10, Nvidia, Wacom

**Comment by audionerd** [comment]
hmm, i'm not able to recreate this bug. here's what i did:

- draw on the notes layer with the note pen
- press the <kbd>delete</kbd> key to clear the layer
- layer is cleared properly

can you describe the steps you took to recreate the bug?

**Comment by Artstax** [comment]
Draw with note pen
Shift to Ink pen and draw
Click "Notes Clear" Icon
Nothing happens
Press ALT + BACKSPACE
Inklayer clears but Note layer stays

(In general the "Notes Clear" button doesn't do anything)

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the next release, and the Notes "clear" button in the sidebar will clear the Notes Layer contents.
