### ISSUE TITLE
Pressure sensitivity missing

### ISSUE THREAD

**Issue by Artstax** [wonderunit/storyboarder#1228]
Pressure sensitivity for Wacom driver still doesn't work.
SB 1.6. Win 10, Nvidia, Wacom

**Comment by audionerd** [comment]
Which Wacom device?

**Comment by Artstax** [comment]
Wacom Intuos 4 with latest driver

**Comment by audionerd** [comment]
There are some tips and workaround in some of the issues linked at https://github.com/wonderunit/storyboarder/issues/690 and on the wiki https://github.com/wonderunit/storyboarder/wiki/Previously-Answered-Questions. Some people have reported success by re-configuring Windows Ink.

I'm going to close this for now as it's a known issue. Hopefully future versions of Electron (which Storyboarder depends on for pen tablet support) will improve it.

Dupe of https://github.com/wonderunit/storyboarder/issues/690
