### ISSUE TITLE
Shortcuts of drawing tools mixed up

### ISSUE THREAD

**Issue by BocDrown** [wonderunit/storyboarder#1240]
Just received the update and saw that the keyboard shortcuts of the drawing tools are mixed up. See below for documented vs actual shortcuts. The pen is currently not selectable using keybord shortcuts.

Tool             |  Documented Shortcut  | Actual Shortcut
| --- | --- | --- |
Light Pencil  |                 1                    |           1
Brush           |                 2                    |           4
Tone            |                 3                    |           3
Pencil           |                 4                    |           2
Pen              |                 5                    |           -
Note Pen     |                 6                    |           5
Eraser          |                 7                    |           6

**Comment by audionerd** [comment]
Looks like this bug will occur for anyone with a keymap generated by an older Storyboarder. So we should migrate the keymap file.

Either prompt and replace the keymap file _entirely_, or somehow detect the old format and replace _just those_ lines for tools.

**Comment by BocDrown** [comment]
I haven't ever edited the keymap.json. But yes, it's from a previous version of Storyboarder. 
Thanks so much for your support and the workaround hint of having the file re-created by Storyboarder!

**Comment by audionerd** [comment]
This is fixed now. The next release will include the fix.
