### ISSUE TITLE
Upgrade to Electron v3.0.0

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1245]
https://github.com/electron/electron/releases/tag/v3.0.0-beta.1

Will need to check for breaking changes.

**Comment by audionerd** [comment]
Electron fixed https://github.com/electron/electron/issues/13358, which we were waiting on.

**Comment by setpixel** [comment]
still waiting on: https://github.com/electron/electron/issues/14129

**Comment by audionerd** [comment]
This will be part of the next release.
