### ISSUE TITLE
No refresh with edited PSD

### ISSUE THREAD

**Issue by BeeDee123** [wonderunit/storyboarder#1258]
I am using Adobe Photoshop ELEMENTS 15. When I edit a panel and save it, when I go back to Storyboard, it is not refreshed and I don't see any way to do that. (like an F5 Refresh). I don't exit PsE because I don't want to have to wait for a re-start/re-load each time I edit. (am I missing something?)

Adobe Photoshop Elements Version: 15.0 (20160905.m.97630)  x64
Operating System: Windows 10 64-bit
Version: 10 or greater
System architecture: Intel CPU Family:6, Model:14, Stepping:3 with MMX, SSE Integer, SSE FP, SSE2, SSE3, SSE4.1, SSE4.2, AVX, AVX2, HyperThreading
Physical processor count: 4
Logical processor count: 8
Processor speed: 3408 MHz
Built-in memory: 8095 MB
Free memory: 2589 MB
Memory available to Photoshop Elements: 3093 MB
Memory used by Photoshop Elements: 70 %

**Comment by audionerd** [comment]
Do you see any type of notification or error in Storyboarder?

Can you try opening the Storyboarder Developer Tools (`View > Toggle Developer Tools`) and paste a screenshot of what you see immediately after saving in Photoshop?

**Comment by BeeDee123** [comment]
Yeah, it's getting errors. I couldn't copy it as text so I did a snapshot image. (redacted) That is the file name and location that I "saved as" in PsE. So it's not seeing it for some reason. Although it looks like it did notice that it was modified, it just "wasn't there", or got programmatically confused or something. I don't see how it could be a difference between Photoshop and Photoshop Elements, but maybe. Or a Windows 10 thing? My default browser is Pale Moon, an old-style Firefox branch, but I wouldn't think you would be using the user's default browser.  (I'm a computer programmer, but I didn't look at anything beyond that, although I found it interesting that you are treating it all like a web page and doing it in JS)
![storyboardsnapshot01](https://user-images.githubusercontent.com/19714624/41932685-2d752f54-7971-11e8-96d2-c385b3557002.png)

**Comment by audionerd** [comment]
OK we'll look into it. Looks like Storyboarder is erroneously getting notified about only the _folder_ changing (instead of the actual PSD file), and doesn't know what to do with that information.

Looks like there is a space between the words `katydid storyboard`? (Not sure if that's causing a problem necessarily, but it might be something to look into).

**Comment by BeeDee123** [comment]
I think there probably is a SPACE there. But it should be able to deal with any Windows file specification and directory structure.

**Comment by audionerd** [comment]
Totally. You didn't do anything wrong by having a space in the filename. 

Just trying to get to the root of the issue for potential causes that we can address in the fix.

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
