### ISSUE TITLE
1.6.3 won't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by SlayerDUDE** [wonderunit/storyboarder#1266]
**Running the appimage from terminal getting:**
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_StorybF88Ewj/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**To Reproduce**
drag&drop the appimage-file to a terminal and press enter

**Expected behavior**
open up as 1.6.2 did

**Desktop:**
 - Linux mint 18 (based on Ubuntu 16.04)
 - Chrome Browser
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by rogper** [comment]
I'm on Linux Mint 18.3, Opera browser as default and I have this exact same problem.

**Comment by setpixel** [comment]
Can you please try this build: https://www.dropbox.com/s/p5gs8ci1lk75ie8/Storyboarder-1.6.3-linux-x86_64.AppImage?dl=0

**Comment by setpixel** [comment]
Also, could you let me know if it worked for you?

**Comment by rogper** [comment]
For me, that new build it works perfectly now :)

**Comment by SlayerDUDE** [comment]
Thank you, It worked. Successfully updated to 1.7.0.
