### ISSUE TITLE
Slow preprint formatting

### ISSUE THREAD

**Issue by Artstax** [wonderunit/storyboarder#1269]
Formatting even a short storyboard for printing to pdf/printer in new version 1.6.3 is VERY slow (5 minutes or so for 18 frames), and very much slower than in the previous version.

(Windows 10)

**Comment by CheesecakeCG** [comment]
Same issue here, it was taking about 15 minutes with ~30 boards on Pop!_OS (Ubuntu 17.10) with an i3-2100 and 8GB of RAM.

**Comment by audionerd** [comment]
I wasn't able to replicate this bug. I just tried PDF export with Storyboarder v1.7.1 and 100 boards took ~12 seconds to preview. Not blazing fast, but pretty good.

Can you retry and let us know if this is still an issue?

**Comment by setpixel** [comment]
Of that 12 seconds, what % of it is pdf generation, vs displaying the pdf?

**Comment by Artstax** [comment]
I have just checked this on the latest version of Storyboarder (1.7.1), using a storyboard with 49 boards. From the moment i selected "Print or export to PDF" to when the file preview showed up, ready for PDF saving or printing, took 7 minutes and 35 seconds!!
Until this is being repaired, the program is completely useless, and I have gone back to my old trustworthy Springboard Storyboard program.

**Comment by setpixel** [comment]
Yeah - something is def rotten in denmark.

@Artstax what type of computer is it?

**Comment by setpixel** [comment]
@audionerd something is definitely slower than previous versions. I don't know what it is exactly

**Comment by Artstax** [comment]
HP PC with NVidia Geforce graphics and Wacom Intuos 4 tablet.
![ys](https://user-images.githubusercontent.com/32501570/44214267-0a899d00-a170-11e8-8872-264a4fc8e39f.png)

**Comment by Artstax** [comment]
In addition the command "Print a Storyboarder worksheet" takes around a minute from selected to the page is ready to print (or save as PDF)!!
