### ISSUE TITLE
How to increase Shot board size

### ISSUE THREAD

**Issue by revanthfilmmaker** [wonderunit/storyboarder#1274]
Hello
This is Revanth, Film director from India.
First of all I am really impressed with your software. It made my work easy to show my shot division to my team.
but I have one issue , shot board size is too small. I checked  Some videos on YouTube. they have pretty big size board. can you please help me to sort this issue•
I am also attaching screenshot 
![sketch](https://user-images.githubusercontent.com/40877547/42359335-d7b0fd56-80fe-11e8-850c-44993389c1a0.png)

**Comment by audionerd** [comment]
The <kbd>Tab</kbd> key will cycle through view modes (also available from the View menu), which will hide parts of the user interface to make more space for drawing. You could also try the new zoom feature in Storyboarder 1.7.
