### ISSUE TITLE
No opacity slider

### ISSUE THREAD

**Issue by denisvanw** [wonderunit/storyboarder#1275]
**Describe the bug**
Contrary to what is said in the release notes, there is no opacity menu...
Under the brush color, there is nothing. No slider, nothing that I could click and drag...

**To Reproduce**
open new versionof  StoryBoarder

**Expected behavior**
A new color menu ?

**Desktop (please complete the following information):**
Windows 10, Intuos pro

**Comment by setpixel** [comment]
Can you post a screenshot of your interface?

**Comment by denisvanw** [comment]
Sure !
Here it is :
![cap](https://user-images.githubusercontent.com/40484955/42384538-8ca75684-813a-11e8-8d4b-e661e3b5fe4a.PNG)

**Comment by setpixel** [comment]
under the palatte of current color it says: 100%

click and hold on top and drag left.
