### ISSUE TITLE
Can't import image

### ISSUE THREAD

**Issue by krakensurf** [wonderunit/storyboarder#1276]
I tried to import image, but I get a pop up that says to use browser or phone 192.168.0.28:1888.  Which doesn't work either.

I just want to paste an image that I've already captured for the board shot.

**Comment by audionerd** [comment]
What kind of image file is it? Do you see the file selector dialog when you try to import?
Can you drag the file onto the Storyboarder window?

**Comment by krakensurf** [comment]
Oh Nice.

Yes drag and drop works.  But it creates a new shot instead of adding it to the current shot.  no big deal, that I can live with it.  I was editing it in ps then opening the image and saving it...that was a stupid work flow.
No dialog box ever opened, just a pop up with IP instructions.  I'm using Win7 64bit.

This program is pretty cool.  Is there a way to add notes or shot generation to pdf export?   Do you have a manual?

Thanks Eric.
________________________________

**Comment by audionerd** [comment]
> But it creates a new shot instead of adding it to the current shot.
We're working on improvements to allow import/paste to current board this for an upcoming release.

> Is there a way to add notes or shot generation to pdf export?
PDF export will use the dialogue and action fields, but not notes. 
PDF export should show Boards you create with the Shot Generator. Are you having problems with that?

No manual yet, but we're working on a better FAQ.

**Comment by krakensurf** [comment]
No problems with shot generation...other than its hard to get it to make the shot you want.  Still learning how to use it.

Default ms just shows "ms" instead of 2000 as listed in preferences.
Deleting a frame with trash can icon still pops up "Backspace" tool tip even though I've turned off tool tips in preferences.  Minor bugs.  Overall really satisfied with work flow.
Second day of using it.  See how it goes.

Thanks for the fast response.
________________________________
