### ISSUE TITLE
Ctrl + Z doesn't work

### ISSUE THREAD

**Issue by TheFeebasTheory** [wonderunit/storyboarder#1277]
Pretty much what the title says, I can't undo using this shortcut in Storyboarder, although I can do it in other programs. The only way I can undo at the moment is manually going to edit then undo.

**Comment by audionerd** [comment]
I noticed you closed the issue. Does Ctrl+Z work for you now?

**Comment by TheFeebasTheory** [comment]
It worked momentarily but stopped again after I closed it.

**Comment by audionerd** [comment]
This should be fixed in the latest release.
