### ISSUE TITLE
canvas size issue

### ISSUE THREAD

**Issue by bluechocowitz** [wonderunit/storyboarder#1289]
![image](https://user-images.githubusercontent.com/35284647/42696494-73880d76-86e2-11e8-8154-1cc12b087be4.png)

the canvas is stuck at that size,, i'm unable to draw because of that.
i found out that turning on fullscreen makes the canvas _just_ a little bit larger, but once the fullscreen is off it reverts back. the two still makes it very hard to draw.

**Comment by setpixel** [comment]
Can you update to a newer version?

There is zooming in the newest version!

**Comment by bluechocowitz** [comment]
thank you!!
