### ISSUE TITLE
The preferences menu is missing in the Linux version.

### ISSUE THREAD

**Issue by CheesecakeCG** [wonderunit/storyboarder#1292]
**Describe the bug**
The preferences menu is missing in the Linux version.

**To Reproduce**
Run Storyboarder 1.7.1 on a Linux computer from the AppImage.

**Expected behavior**
Hitting Control + "," or going to the edit menu should allow access to the preference menu.

**Screenshots**
![screenshot from 2018-07-15 13-03-54](https://user-images.githubusercontent.com/32441086/42736209-28865180-8830-11e8-83cf-ad07a90c7fc3.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS (Ubuntu 17.10)
 - Desktop Enviroment: XFCE4 w/ some GNOME parts
 - Version: 1.7.1

**Additional context**
The [FAQ](https://wonderunit.com/storyboarder/faq/#How-do-I-open-the-Preferences-window) you just put up doesn't mention Linux anywhere, is Linux officially supported?

**Comment by setpixel** [comment]
@CheesecakeCG dang. it isnt under file is it?

I dont have a linux machine so we haven't tested it much. 

This is def a bug tho.

**Comment by CheesecakeCG** [comment]
Nope, not under File either:
![image](https://user-images.githubusercontent.com/32441086/42736277-f8edba4c-8831-11e8-80c8-7b70d3417234.png)

**Comment by audionerd** [comment]
This will be fixed in the next release. On Linux it will be found in "Edit > Preferences"
