### ISSUE TITLE
Naming PSD layer to 'Background[anything]' causes SB to not display layer

### ISSUE THREAD

**Issue by AVTPJ** [wonderunit/storyboarder#1297]
As the title says, naming any layer in Photoshop to 'Background' or any derivative of it (e.g. 'Background Copy', 'BackgroundBoo') will cause it to not to be displayed in Storyboarder.

1. Open board in Photoshop
2. Create a new layer
3. Draw something onto layer
4. Rename said layer to 'Background Copy' or similar.
5. Save document

**Expected behavior**
Renamed layer should be displayed in Storyboarder unless and only unless two layers with the exact names are present in PSD. For instance, duplicating a background layer from another document causes layer name to be 'Background Copy' which then doesn't appear in Storyboarder.

Video: [https://www.dropbox.com/s/2nyfnsgmd1tz010/Storyboarder%20bug.mov?dl=0](https://www.dropbox.com/s/2nyfnsgmd1tz010/Storyboarder%20bug.mov?dl=0)

**Comment by audionerd** [comment]
Yeah, Storyboarder ignores any layer containing the string "Background".

Storyboarder will import specific named layers (e.g.: reference, tone, fill, pencil, ink, notes).

Can you use "reference" instead?

**Comment by AVTPJ** [comment]
Sure, just thought I'd mention it.

Awesome tool, by the way! 👍😱



*PJ Palomaki* • Creative Digital Content Manager

AVT House • 7 Stone Street
<https://maps.google.com/?q=7+Stone+Street%C2%A0+%E2%80%A2+%C2%A0Brighton%C2%A0+%E2%80%A2+%C2%A0BN1+2HB&entry=gmail&source=g>
•
<https://maps.google.com/?q=7+Stone+Street%C2%A0+%E2%80%A2+%C2%A0Brighton%C2%A0+%E2%80%A2+%C2%A0BN1+2HB&entry=gmail&source=g>
 Brighton
<https://maps.google.com/?q=7+Stone+Street%C2%A0+%E2%80%A2+%C2%A0Brighton%C2%A0+%E2%80%A2+%C2%A0BN1+2HB&entry=gmail&source=g>
•
<https://maps.google.com/?q=7+Stone+Street%C2%A0+%E2%80%A2+%C2%A0Brighton%C2%A0+%E2%80%A2+%C2%A0BN1+2HB&entry=gmail&source=g>
BN1
2HB
<https://maps.google.com/?q=7+Stone+Street%C2%A0+%E2%80%A2+%C2%A0Brighton%C2%A0+%E2%80%A2+%C2%A0BN1+2HB&entry=gmail&source=g>

e: pj@avtconnect.com •  t: +44 (0)1273 299001 • w: www.avtconnect.com

AVT Ltd t/as AVT Connect. If you have received this message in error,
please immediately notify the sender. Internet communications are
not secure and therefore AVT Ltd does not accept legal responsibility for
the contents of this message. Although AVT Ltd operates anti-virus
programmes, it does not accept responsibility for any damage whatsoever
that is caused by viruses being passed. Any views or opinions presented are
solely those of the author and do not necessarily represent those of AVT
Ltd. AVT Ltd, Registered in England & Wales under No. 1196354. Registered
Office: AVT House, 7 Stone Street, Brighton, BN1 2HB
