### ISSUE TITLE
Cannot reliably open toolbar menu options

### ISSUE THREAD

**Issue by Soldiershak** [wonderunit/storyboarder#1303]
It's nearly impossible to open the toolbar menu options with the Wacom stylus for some reason. I'm only able to open it with touch, but even then its very inaccurate. I'm using a Wacom mobile Studio pro

**Comment by Soldiershak** [comment]
anyone?

**Comment by audionerd** [comment]
We think this is probably caused by a problem in one of the software libraries Storyboarder uses (electron). Electron has an update on the way that might improve things.

Is this on Mac or Windows? When you say the "toolbar menu options" do you mean the application menu, or Storyboarder's toolbar (for brushes, color palette, etc)?

This is related to: https://github.com/wonderunit/storyboarder/issues/1058

**Comment by Soldiershak** [comment]
It turns out someone else is having the same issue, they're stressfully mention Windows ink vs no wineries ink here's a l link to the thread

https://github.com/wonderunit/storyboarder/issues/1313

**Comment by toonvault** [comment]
had the same issue, seems it is related on how M$ changed (again) something between 1607 and 1803 that breaks other stuff.

**workaround:**
run this from a commandline (or manually set hat required registry key):

`reg add HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Pen /v LegacyPenInteractionModel /t REG_DWORD /d 1 /f`

to disable this again (if something else breaks.. with this OS you may never know):

`reg add HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Pen /v LegacyPenInteractionModel /t REG_DWORD /d 0 /f`

(or just delete the registry key entry for "LegacyPenInteractionModel ")

This workaround + UseInk @ wacom settings (app specific) I get pressure sensitivity and a working menu.

**Comment by Soldiershak** [comment]
Thanks for the info I'll try it out when I get the chance to dig through the reg. I noticed things act strangely when Windows ink is enabled in the Wacom settings. It's difficult to select text in google chrome now and sometimes it's impossible to activate mouse-over menus. It's something with Windows ink I knew these constant updates would break things first my sound now this.
