### ISSUE TITLE
There is no function for importing a single image to the current board

### ISSUE THREAD

**Issue by will2power71** [wonderunit/storyboarder#1304]
This feature is crucial to how I work, yet it doesn't exist in your application as far as I can see. I have the ability to import a folder of images, but apparently you can't import a single image. Lacking this key feature makes the application unusable to someone like me. I go frame by frame and I want to be able to work with single images rather than importing a folder of images. Please add the capability to import a single image at the current frame.

**Comment by audionerd** [comment]
You can do this in Storyboarder 1.7.1. "File > Import Image and Replace"
