### ISSUE TITLE
lagging

### ISSUE THREAD

**Issue by potatopixie** [wonderunit/storyboarder#1305]
Hello! I just downloaded storyboarder to help me make a project I'm working on, the only problem I have so far is that when I actually draw on it, it lags soo much and I can't draw well on it unless I draw painfully slow. I've already redownloaded it twice and restarted my computer. One other smaller thing is that I cannot find how to zoom into the drawing, I chose the HD size but it's much too small to really draw on.

**Comment by setpixel** [comment]
Did you turn off enhanced drawing engine in settings?

**Comment by potatopixie** [comment]
thanks or the help! although do you know how to zoom in perhaps? I just tried to from the view bar but then it only shows the corner of the screen and I have no way of moving the canvas

**Comment by setpixel** [comment]
https://wonderunit.com/storyboarder/faq/#Can-I-zoom-into-the-drawing-so-I-can-draw-finer-detail
