### ISSUE TITLE
Shot duration

### ISSUE THREAD

**Issue by Gerpgrep** [wonderunit/storyboarder#1318]
Hello,
I am an animation teacher who just discovered Storyboarder, and who is overwhelmed with emotion. What an incredible tool to create storybords quickly and with amazing results.
Quick question: is it possible to modify shot durations individually?
Thanks for this amazing tool!
Pierre
Montreal, QC, Canada

**Comment by audionerd** [comment]
Hi Pierre, glad you're enjoying Storyboarder!

In the sidebar you can type a duration for the board in milliseconds or frames (based on scene frame rate).

If you switch to Timeline Mode (View > Toggle Boards/Timeline Mode) you can drag the edges of board thumbnails to change their duration.

Hope that helps!

**Comment by Gerpgrep** [comment]
Hi Eric,

Quite right! I was too excited and I didn’t take the time to have a good look.

And after sending out my question I found the “export to Premiere” option, which is quite nice as well.

Thanks for your quick answer, I will go on exploring.

Storyboarder is quite a nice alternative to TB Storyboard Pro! Much, much more intuitive.

Pierre

Pierre Grenier
Enseignant | Coordonnateur
Département de cinéma d’animation
Cégep du Vieux Montréal
514-982-3437 poste 2059
www.cvm.qc.ca/animation
[LOGO_DEPT_2013_noir_petit_pour_courriel]




De : Eric Skogen [mailto:notifications@github.com]
Envoyé : 15 août 2018 14:50
À : wonderunit/storyboarder <storyboarder@noreply.github.com>
Cc : Grenier Pierre <PGRENIER@cvm.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [wonderunit/storyboarder] Shot duration (#1318)


Hi Pierre, glad you're enjoying Storyboarder!

In the sidebar you can type a duration for the board in milliseconds or frames (based on scene frame rate).

If you switch to Timeline Mode (View > Toggle Boards/Timeline Mode) you can drag the edges of board thumbnails to change their duration.

Hope that helps!
