### ISSUE TITLE
Really annoying Storyboarder tip window on the right

### ISSUE THREAD

**Issue by philip2003** [wonderunit/storyboarder#1325]
How do you remove this feature. It appears over your timeline... adds more clicks etc. I am not using the product because of this feature!

**Comment by setpixel** [comment]
you have a tough life bruh. 

but go to preferences and figure it out like a non-retard.

**Comment by philip2003** [comment]
I went to preferences, changed them, restarted the app and the pop ups still appear.

**Comment by philip2003** [comment]
No need to be offensive.
