### ISSUE TITLE
White launcher

### ISSUE THREAD

**Issue by AssAsIN10556** [wonderunit/storyboarder#1343]
**Describe the bug**
When you mark the .appimage as an executable and run it, the launcher will display normally for a second, but then turn completely white.

**To Reproduce**
Launching the .appimage.

**Expected behavior**
Having the launcher start up normally, i use storyboarder on windows aswell and it works fine there.

**Screenshots**
![image](https://user-images.githubusercontent.com/15184982/44947103-3790ad80-ae08-11e8-9c0d-325c91b54466.png)
![image](https://user-images.githubusercontent.com/15184982/44947111-5abb5d00-ae08-11e8-9d54-3f6a278f7f4c.png)

**Desktop**
 - OS: Ubuntu 18.04 LTS 64bit

**Comment by audionerd** [comment]
Can you try opening the developer console (View > Toggle Developer Tools) and let us know what you see there?

Are you able to start the Storyboarder executable via command line to see any debug messages that might be helpful?

**Comment by AssAsIN10556** [comment]
Doing that made it for up just fine. Guess I'll just start it up like this from now on.

**Comment by audionerd** [comment]
Interesting. I wonder why it works when run from the command line but not when run directly.

**Comment by audionerd** [comment]
Closing for now. Let us know if you still see this bug with Storyboarder 1.9.2.
