### ISSUE TITLE
Why it needs firewall authorization ?

### ISSUE THREAD

**Issue by Alomphega** [wonderunit/storyboarder#1344]
Hello,

Just I wonder why just after installed, Windows firewall asked me to allow StoryBoarder to pass thru ?

Thanks for any explanation,
Cheers,
Guy

**Comment by audionerd** [comment]
Storyboarder has a feature which allows you to import images from your phone. Storyboarder starts a local web server listening on port 1888 to allow your phone to connect and upload photos.
