### ISSUE TITLE
Suggested Features

### ISSUE THREAD

**Issue by AlstonJones** [wonderunit/storyboarder#1348]
I think you have a great product and the fact that it's free is amazing.  I want to suggest that you try to creating software pairing features for other high quality free software like Krita and Blender, the way you have for Photoshop.  Photoshop is clearly a great asset that many people have access to but I also think you would find plenty of people who are trying to use open source and less expensive alternatives.  
Thanks for creating this wonderful program.

**Comment by audionerd** [comment]
Thanks for the feedback! You can edit Storyboarder boards in other programs, like Krita. In the Storyboarder preferences window, you can choose any PSD editor you like. Does that help?

**Comment by AlstonJones** [comment]
That helps perfectly!  This is exactly what I was looking for and you already had it!  Thanks!
