### ISSUE TITLE
Download link on webpage doesn't work.

### ISSUE THREAD

**Issue by ProLoser** [wonderunit/storyboarder#135]
The download button does nothing: https://wonderunit.com/software/storyboarder/

**Comment by setpixel** [comment]
Thanks! That whole page basically doesn't work yet. We've yet to put real content in it.

Were you able to download a build from GH?

**Comment by ProLoser** [comment]
Yes but if you're interested in getting more users you might want to at the
very least have it link to the downloads section on GitHub.

**Comment by setpixel** [comment]
Great point. Glad to have you on the case. :D

**Comment by setpixel** [comment]
Merged into #268 for release soon
