### ISSUE TITLE
How to work with the Shot Generator?

### ISSUE THREAD

**Issue by nickmadedesign** [wonderunit/storyboarder#1352]
Hello champs,

Perhaps my coffee has failed me and I am missing something, but how do you work with the Shot Generator?

E.g. 

- How can I delete the reference I (accidentally) double clicked on so I don't see the shot generator reference image?
- Can I clear out the Shot Gen thumbnails on the right?

I didn't see any help docs that support this, and after drawing out a board, I'm stuck with a reference of an over the shoulder shot of a bald man running on top of my lovely sailboat drawing :)

**Comment by setpixel** [comment]
![screenshot 2018-09-07 13 36 11](https://user-images.githubusercontent.com/441117/45234207-04846900-b2a3-11e8-8987-07f27a2eb3a0.png)

hi! click "clear" on light light layer.

**Comment by nickmadedesign** [comment]
That helped along with the Wiki page on how the drawing tools operate on different layers (e.g. reference = pencil but the Shot Gen also operates on that layer).

Thanks!
