### ISSUE TITLE
Color palette won't  add colors

### ISSUE THREAD

**Issue by Albois** [wonderunit/storyboarder#1359]
Hi,
Working with the color palette.
I can choose the colors but I can't change the 3 swatches

![swatches](https://user-images.githubusercontent.com/34041453/45503223-33438900-b754-11e8-87d4-b297d45c2f3f.jpg)

**Comment by setpixel** [comment]
hold the mouse down on it for like 2 seconds. it will pop up!

**Comment by Albois** [comment]
Great Thanks!
I guess I’m not patient enough!
