### ISSUE TITLE
Just a few words...

### ISSUE THREAD

**Issue by amedeux** [wonderunit/storyboarder#1371]
...to say that I like the user friendly approach of your software.
You are doing some great work and I can't wait for any new release.

I think that some of the missing features are preventing some users from adopting it, but with some tweaks it could become even more amazing. 

I work in animation, I am currently teaching it in a VFX/ animation school in London and I think your software has such potential that I am implementing it into my classes, and after evaluating some commercial solutions I ended up picking Storyboarder for my personal projects, too.

Keep up the good work!

**Comment by setpixel** [comment]
Thanks! What are the top missing features in your opinion?
