### ISSUE TITLE
Freehand drawing is constrained to straight line.

### ISSUE THREAD

**Issue by Albois** [wonderunit/storyboarder#1374]
I'm using the pencil and it won't draw freehand.
The line is almost always a straight line.
It reverst back to freehand but only for a line or two.
Same problem with all the tools.
I am not trying to make a straight as recommended.

UPDATE: Restarted App 3 times and now all is fine.

**Comment by audionerd** [comment]
You could also try turning off the High Quality Drawing Engine, which might result in better performance. https://wonderunit.com/storyboarder/faq/#Drawing-is-laggy-or-slow-How-can-I-make-it-faster
