### ISSUE TITLE
Turn off line smoothing?

### ISSUE THREAD

**Issue by bengibous** [wonderunit/storyboarder#1377]
I really tried to see if I could find something already covering this but no luck. I'm just not a fan of the auto line smoothing that occurs and you draw and would just like to know how to turn it off.

**Comment by audionerd** [comment]
There are currently no controls in Storyboarder to change the line smoothing.

But the line smoothing shouldn't be too obvious. Could you be more specific about what you don't like, and we could try to improve it?

You could try turning off the High Quality Drawing Engine, which will switch Storyboarder into a different mode that might work better for you. It's more like the old Storyboarder. https://wonderunit.com/storyboarder/faq/#Drawing-is-laggy-or-slow-How-can-I-make-it-faster
