### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by ArtVogt** [wonderunit/storyboarder#1380]
If I edit anything in "keymap.json", I get this error on restart...

"Whoops! An error ocurred while trying to read /Users/Art/Library/Application Support/Storyboarder/keymap.json.
Using default keymap instead.

SyntaxError: Unexpected token “ in JSON at position 1568"

"position" always changes to where I've made an edit. Are key bindings not user editable?

macOS 10.12.2, Storyboarder 1.8.0

Thanks!

**Comment by audionerd** [comment]
Keymap is user editable, although we haven't tested it much in the wild.

Looks like a JSON error, maybe a missing comma or quotation mark. Make sure your edits validate as JSON, maybe try checking with a JSON validator online.

If you want to post your changes here we can help troubleshoot.

**Comment by ArtVogt** [comment]
Wow, thanks for the quick feedback! I literally just replaced the existing entries... ie. Changing "left" to "a", or "1" to "2". :/

**Comment by audionerd** [comment]
What text editor did you use? Some editors might change characters on save unexpectedly. Try a JSON validator, best way to check your changes.

**Comment by ArtVogt** [comment]
OK, I figured it out.... I don't know why I didn't think of this before I posted, but I had this same issue just a month ago with editing bitmap font file. You CANT edit the JSON in "TextEdit", or, I assume, any text editor that isn't made for code. I'm an artist, not a programmer, so I didn't think about this right away. So I edited it AGAIN just now in XCode and it worked! 

     I don't know if your standard user will think of this, or have XCode or a similar program installed. Is it difficult to build a preference editor into the UI preference panel?

Thanks again!

**Comment by ArtVogt** [comment]
You posted as I was typing this. You nailed it :)

**Comment by ArtVogt** [comment]
God, this is my first time using GitHub, sorry for the post formatting ridiculousness, but thanks for the immediate help. I feel way more comfortable using Storyboarder now :)

**Comment by audionerd** [comment]
Sure, happy to help! Glad it's working for you now.

My guess is that TextEdit is turning quotes into “smart quotes”, which look similar but are not valid JSON. “” vs ". Reference: https://apple.stackexchange.com/questions/120486/quotes-problem-in-mavericks-or-textedit

**Comment by ArtVogt** [comment]
Whoah, I would never have caught that visually! I had no idea there were different types of quotes, great info! I bet that was the same problem with my bitmap font file issue. Thanks!

**Comment by audionerd** [comment]
Very thorough reference here if you're curious https://practicaltypography.com/straight-and-curly-quotes.html

**Comment by ArtVogt** [comment]
Wow, great link! I'm always curious to learn, and that was a great article.

Thanks again :)
