### ISSUE TITLE
No pen pressure control with Wacom Cintiq 21 UX

### ISSUE THREAD

**Issue by EdgarHuebert** [wonderunit/storyboarder#1387]
my Brushes are drawing always with the same presure. Im using Wacom Cintiq 21 UX
My Pen is working in other Programs fine.

**Comment by audionerd** [comment]
Thanks for the report.

There's more information here about pen pressure support:
https://github.com/wonderunit/storyboarder/wiki/Previously-Answered-Questions

The short answer is, the technology Storyboarder is built on (Electron/Chromium) doesn't support all devices and there's not a lot we can do about it unfortunately. Hopefully the support will get better with time, :(
