### ISSUE TITLE
[Bug] Lasso tool is activated when 'L' key is pressed (even when typing) 

### ISSUE THREAD

**Issue by Usernameisalreadytaken99** [wonderunit/storyboarder#1389]
Hi team,

With the addition of the lasso tool, I've had the issue of it being activated every time the 'L' key is pressed, even when I'm typing captions, for example.

The expected behaviour is that the hotkey only works when the canvas is active.

Thanks,

**Comment by audionerd** [comment]
Whoops! Thanks for the bug report. This will be fixed in the next release.

**Comment by CuberToy** [comment]
Following my duplicate (regarding the same issue reported over on fb).
I tried it in 1.9.1 freshly installed. Still have the issue (windows version).
