### ISSUE TITLE
User is notified when app update is available

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#139]
On app startup,
App checks to see if an app update is available,
if so, user is asked "An update is available. Would you like to update now? There will be a short delay while we download the update and install it for you"
If yes, pause the app, download, install, restart

- [x] ensure binaries are distributed as ZIP files (updater expects ZIP)
- [x] ensure `latest.yml` and `latest-mac.yml` are accurately generated (with correct download url, date, sha-1) and uploaded to releases

REFERENCE
https://github.com/electron-userland/electron-builder/wiki/Auto-Update
http://bretahajek.com/2016/11/electron-builder-appveyor-travis-ci-memory-king/

**Comment by setpixel** [comment]
http://www.theodo.fr/blog/2017/05/set-up-continuous-deployment-on-electron-using-squirrel/
