### ISSUE TITLE
Autosave. Is this really a feature?

### ISSUE THREAD

**Issue by Usernameisalreadytaken99** [wonderunit/storyboarder#1390]
Hey,

When I press CTRL+S to save, I get a smart message telling me that saving is automatic and I don't need to do it manually (I'm guessing this is similar to Google Docs, etc.).

At the same time, I get a warning message when closing the application that my changes aren't saved.

I feel like I'm getting mixed messages...
![image](https://user-images.githubusercontent.com/42954310/46777768-2fb01b80-cd6d-11e8-8484-06921141155b.png)

Thanks,

**Comment by audionerd** [comment]
For better performance, Storyboarder don't try to save when you're busy drawing something. 

Unfortunately, Storyboarder currently thinks you're busy drawing whenever the Lasso is being used, even when you don't have an active selection. That's an issue we'll fix soon. https://github.com/wonderunit/storyboarder/issues/1391

For now, switch tools away from the lasso tool and you should be able to autosave + quit without warnings.
