### ISSUE TITLE
add "New Board" fails

### ISSUE THREAD

**Issue by cgboxer** [wonderunit/storyboarder#1394]
I have already created 19 boards.
Adding a new board via the plus button is not possible.
Adding a new board via the shortcut N is not possible.
Adding a new board via the Menu: Boards>New Board is not possible.

If I add a new board by pressing "D" a new board is added, then I can work on this duplicated board in Photoshop and save my changes in PS, the board gets updated in SB. 

But, when reopening the scene, these boards that have been added by creating a duplicate, are gone in SB. Re-adding those by creating duplicates and repasting the layers inside PS brings those images back, but also only temporarily. As soon as the .stoyboarder file is reopned, the changes are gone.

**Comment by audionerd** [comment]
Can you try opening the Developer Tools and let us know what you see in the logs? Try adding new boards via duplicate with Developer Tools open. Paste the logs (or a screenshot if you can). I'm wondering if an error is happening behind the scenes.

**Comment by cgboxer** [comment]
Yes. Sure. So, I opened the Developer Tools and switched to the Console Tab. Hit clear console. 
I get many warnings.
warning:
![image](https://user-images.githubusercontent.com/44056645/46814468-0e552c80-cd79-11e8-8f84-2603b6f25485.png)

Then, I set the logs filter to shows errors only.
When I have been trying to add a board via the "+" button. I got the following error:
![image](https://user-images.githubusercontent.com/44056645/46814024-24aeb880-cd78-11e8-8ada-f97b39681a55.png)

When hitting "d" with one board selected, it is added a duplicate with this error popping up:
![image](https://user-images.githubusercontent.com/44056645/46814306-ab639580-cd78-11e8-8e97-fdb2679abe2e.png)

**Comment by audionerd** [comment]
Was this after using the Lasso Tool? If so, try switching out of the Lasso Tool (to a brush for example). before adding new boards. Does that help?
There's a known issue with the Lasso Tool that I think might be causing this https://github.com/wonderunit/storyboarder/issues/1391

**Comment by audionerd** [comment]
If this _wasn't_ after using the Lasso Tool, can you describe what you did before trying to add the new boards?

**Comment by cgboxer** [comment]
I just created the project one day before the update including the lasso tool. so, I have not yet used the lasso tool at all. 

But, as soon as I created the board, I would link it to a PSD.file. Inside Photoshop I duplicated layers, created new ones and copied and pasted between several documents. So the PSDs now include more than just the default ones. When masking layers, I would get other errors, but then I applied all masks and this made Storyboarder accept the files again. The issue could be part of me destroying the PSD default structure.

**Comment by bobzombi** [comment]
I'm having a similar problem in 19.1. just created a new project. could add boards, went to photoshop on one board. created a new layer drew, than merged it with reference layer. went back to storyboarder board was updated, but could not add more boards, not with the + or shortcut. Closed and opened the project and could add boards again. Created another board went to photo shop and drew some. went back same issue. But the problem stops when I unlink the board from photoshop.

**Comment by audionerd** [comment]
Related to https://github.com/wonderunit/storyboarder/issues/1429

Should be fixed in Storyboarder 1.9.2.
