### ISSUE TITLE
Super lag in new version 1.9.0

### ISSUE THREAD

**Issue by bobzombi** [wonderunit/storyboarder#1396]
Just installed the latest version 1.9.0 (windows 10)
And it appears to be unsuable. the lag is massive, it keeps going to straight line, and lines draw without the pen touching the surface. And even though autosafe is on, it warns that when closing the file is not saved.\, but it does safe. Is there a way to get the previous version 1.8.0 for now, because I'm on a deadline?
Last night version 1.8.0 was working like a charm.

**Comment by bobzombi** [comment]
Just found the previous versions. Reainstalled 1.8.0 and it works superduper smooth.

**Comment by setpixel** [comment]
Would you be willing to try an experimental version?

**Comment by bobzombi** [comment]
Sure, but can I install it parrallel, and are the files backwards compatible?

**Comment by audionerd** [comment]
Can you give Storyboarder 1.9.1 a try? Just released. It should be an improvement.

**Comment by bobzombi** [comment]
Just updated, seems to be running smoothly as v. 18. By the way, the auto updater keeps failing. Did a manual download and install (did the same thing with v19.0).

**Comment by bobzombi** [comment]
ps. where or how do I submit ideas for improvement or possible changes?
And how about a donate option, would like to.
