### ISSUE TITLE
Cannot draw and typing stopped after "L"

### ISSUE THREAD

**Issue by samathajwatson** [wonderunit/storyboarder#1397]
**Describe the bug**
Typing in Dialog, Action, and so on stops when "L" (if shift is held, problem is not present) is pressed and lasso is then selected and typing stops. Tried to remove "l" as the shortcut for the lasso, but it is not set.
Drawing is impossible within storyboard. [Video of problem here.
](https://adobe.ly/2yB73Xl)

**Expected behavior**
For typing to not stop and for sketches to be possible.

**Screenshots**
[Video of problem here.
](https://adobe.ly/2yB73Xl)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version ? WONDER UNIT // v1.9.0

**Comment by samathajwatson** [comment]
Yes. I start to draw, and the stroke does not follow. Almost like a lag? I tested my tablet in other programs to ensure it was not that. I downloaded an older version (1.8.0) and it works just fine. I apologize for not making that clearer!

**Comment by setpixel** [comment]
@samathajwatson can you please check the newest update (released minutes ago)

I really hope I fixed it!!!!
