### ISSUE TITLE
Lag and Straight Lines

### ISSUE THREAD

**Issue by thejazzyg** [wonderunit/storyboarder#1398]
Hello there. So I just finished downloading the new version of storyboarder. There is a lot of lag when using any of the brushes. The lines end up being straight. When my drawing pen is off the screen, the brushes are still active and the lines are continuous . I also can't use the lasso tool at all.  I had the previous version installed and that worked well for my laptop(windows 10) and tablet. 
![image](https://user-images.githubusercontent.com/44105161/46899653-8435c280-ce63-11e8-9efd-df45c10fe29b.png)

**Comment by audionerd** [comment]
Can you give Storyboarder 1.9.1 a try? It should fix these issues.

**Comment by audionerd** [comment]
I think this is caused by https://github.com/wonderunit/storyboarder/issues/1405 which we'll be fixing in the next release very soon.

**Comment by thejazzyg** [comment]
I installed 1.9.1 and it is working well!
