### ISSUE TITLE
problem with tablet drawing in build 1.9

### ISSUE THREAD

**Issue by knuxte** [wonderunit/storyboarder#1399]
When using my tablet to draw in Storyboarder 1.9, cursor jumps all over and only does a small scratch or dot, or if I hold down the pen long enough and do straight lines.  Tried fixing the issue by doing the following:

Disabling the high quality drawing engine and restarting
Disabled and lengthened the straight lines time frame
Made sure my keyboard and video tablet didn't have alt,ctrl, shift held down
Reinstalled my tablet drivers (Artisul D13)
Uninstalled and Reinstalled Storyboarder 1.9.

Problem wasn't present on Storyboarder 1.8

a guess of what the problem may be-   you noted on preferences if you hold down alt- it will make straight lines snap, on my copy of storyboarder it switches to the eraser when I hold down Alt.   - this may give you a clue of what the problem is.

Just want to let you know- I really enjoy your software and hope you continue to come out with awesome revisions.

**Comment by skoypidia** [comment]
I confirm the issue. Using a Wacom tablet. Used to work fine in previous version.

**Comment by setpixel** [comment]
Please check the newest update! I hope it's fixed!

**Comment by knuxte** [comment]
Seems to have done the charm......
![shipleaving](https://user-images.githubusercontent.com/40477907/46912670-a99cfc00-cf49-11e8-9ee6-65dec2b41cac.png)
