### ISSUE TITLE
Typing is interrupted frequently in board detail boxes.

### ISSUE THREAD

**Issue by spgilmore** [wonderunit/storyboarder#1400]
I upgraded to version 1.9.0 per the prompt on startup. I start Storyboarder and create a new project.  I create a new board, then edit the details on the right. First I click in the Action box and start typing.  Within a few characters, a helpful balloon tip appears to tell me that I'm editing the _ACTION FOR BOARD_.  At this point, keyboard input is no longer accepted in the action detail box.  I can click out and click back into the box and resume typing, but then the problem happens again.  After the first time, the balloon tip may not appear, but the interrupted typing behavior continues after just a few characters.  This problem exists in at least the Dialogue, Action and Notes edit boxes.  It is severe enough that I cannot use the software anymore.    I've attached a video.

[Storyboarer 1.0.9 keyboard input problem.zip](https://github.com/wonderunit/storyboarder/files/2475957/Storyboarer.1.0.9.keyboard.input.problem.zip)

**Comment by spgilmore** [comment]
This appears to be a duplicate of #1397, which is reported fixed.

**Comment by audionerd** [comment]
Yeah that looks like the `l` key bug. Should be fixed in Storyboarder 1.9.1, which was just released.
