### ISSUE TITLE
Unable to export as PDF and has stopped saving

### ISSUE THREAD

**Issue by BunnyAMP** [wonderunit/storyboarder#1421]
**Describe the bug**
When I go to Export to PDF or print, I get the error "Unknown image format"
Also, it has stopped auto saving, I now need to "save as" and save my boards as a copy for it to save. 

**To Reproduce**
1. Go to File>Print or export as PDF
2. Click on Print or export as PDF
3. See error

**Expected behavior**
Normally it displays a preview of how it would save and allows me to save.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 home 64
 - Browser Chrome

**Additional context**
These are old storyboards that I worked on before the update. I've gone through and flattened all the images to give it less information to work with and still have this issue. I need to be able to export these in a way where the client can see all the text that goes along with it. 
![screencap](https://user-images.githubusercontent.com/44504057/47575692-a2de9380-d910-11e8-89c6-f9414e7a9788.jpg)

**Comment by BunnyAMP** [comment]
![javascript](https://user-images.githubusercontent.com/44504057/47575940-48920280-d911-11e8-8373-d14786ff316b.jpg)

**Comment by audionerd** [comment]
As soon as you see "unknown image format" can you try opening "View > Toggle Developer Tools" and let us know what you see in the log for the pdf export window?

Could you try exporting a PDF with a new Storyboarder project with a single simple board? Does that work?

**Comment by BunnyAMP** [comment]
Due to the deadlines I am on, I uninstalled it and installed the 1.7.0 version (which is the one I'm pretty sure I created them in) while it didn't keep any of my saves, I was able to export the one (I just had to re-do the changes). When I'm done with these projects, I'll re-upgrade and then try to open them again/save them.
