### ISSUE TITLE
Pen input does not work for file menus

### ISSUE THREAD

**Issue by jimbiladas** [wonderunit/storyboarder#1430]
Hi Gurus,

I can't access the menu bar using a pen input. This happens across multiple devices. I have sent a video link:

https://youtu.be/xmyL2YN7st4

The devices  are both using Windows 10. One is a tablet pc, the other a desktop pc. I'd love to take my tablet pc on the road and work in storyboarder, but I'd have to drag a mouse along. Eww.

Regardless, love the software, keep up the good work!

**Comment by jimbiladas** [comment]
Nice.  Thanks so much Storyboarder Devs!

**Comment by audionerd** [comment]
Glad to know this is working now. 👍
