### ISSUE TITLE
photoshop error reports

### ISSUE THREAD

**Issue by bobzombi** [wonderunit/storyboarder#1436]
Since the new photoshop update (20.0) , I get constants errors when returning form photoshop to storyboarder (see attached). It's mostly annoying and distracting.

Next to that, the update of adjusted frames in photoshop within storyboarder is very variable, sometimes it works immediately, sometimes it takes a while, of I have to reopen it in shop, resave and close. Sometimes that helps. By the way, had this before the error updates mentioned above.

![untitled-1](https://user-images.githubusercontent.com/43379134/48122006-c097eb00-e276-11e8-852e-3a06553926a4.jpg)

And something else, the use of the lasso seems to get slower and slower with long board sequences (approx 89/90).

**Comment by audionerd** [comment]
PSD reloading should be improved in the next release. Tracking as issue #1656.
