### ISSUE TITLE
dialogue box fills with coding

### ISSUE THREAD

**Issue by potatopixie** [wonderunit/storyboarder#1437]
I've been using this software for a while and there are a few little bugs I keep seeing, one of which being is that every once and a while when I open up a storyboard one of the dialogue boxes will be filled with coding. it seems to usually be the last board with any lines on it. and it takes forever to backspace all of it off, and it makes the program go slowly.

Unfortunately, I have no idea how to reproduce this, all I do is open a storyboard up and sometimes its there, and it doesn't happen every time.

![image](https://user-images.githubusercontent.com/41837895/48147871-fb515180-e27d-11e8-9224-6f3fd3eb002c.png)

**Comment by audionerd** [comment]
WOW. Very odd. It looks like the JSON code for a copied board via clipboard. Does this tend to happen after you copy/paste boards?

**Comment by audionerd** [comment]
Can you send us a ZIP copy of the project where this happens? We'll try to re-create the bug.

**Comment by potatopixie** [comment]
now that I think about it, I think it does happen when I copy and paste, how do I send a zip copy?

**Comment by potatopixie** [comment]
hello? I figured out how to send a zip I think, although now I just deleted the board with the coding on it so now it's running fine.
[camp eldritch storyboard 1-2018-11-07 02.54.00.zip](https://github.com/wonderunit/storyboarder/files/2559154/camp.eldritch.storyboard.1-2018-11-07.02.54.00.zip)

**Comment by audionerd** [comment]
Thanks, yeah it looks to me like pasted data from the clipboard got into the text box. For now just keep in mind that Storyboarder clipboard data will show up as text if accidentally pasted and it'll look garbled so avoid that 🙃 
Thanks for the report.

**Comment by audionerd** [comment]
Tracking as #1440
