### ISSUE TITLE
Create a snap package for Linux

### ISSUE THREAD

**Issue by KristijanZic** [wonderunit/storyboarder#1438]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to download a software package from the web. Could you please provide a snap package and deliver it over Ubuntu Snap store?

**Describe the solution you'd like**
Check documentation on snapcraft.io

**Comment by audionerd** [comment]
Hey Kristijan, thanks for the feedback. We’ll consider the request but with our small team, we cant really maintain another release channel right now. Maybe in the future. 

After you have the app downloaded once, it should handle its own autoupdates.
