### ISSUE TITLE
Download link on website doesn't email me.

### ISSUE THREAD

**Issue by Koherty** [wonderunit/storyboarder#1441]
**Describe the bug**
I've tried a few times to download from the website but I don't get any confirmation email or download link. I've checked to make sure I'm inputting the correct email address, and I've waited a few days after as well but still nothing.

Thanks for looking into it!

**Comment by audionerd** [comment]
Sorry about that. Have you checked your spam/junk folder?

In the meantime, there is a direct download here:
https://github.com/wonderunit/storyboarder/releases

**Comment by Koherty** [comment]
Thank you for the link! Also, yes I have.

**Comment by Koherty** [comment]
Hi again Eric.

Thanks again for the help last time, but I think I might've gotten to the
download link you provided too late. Its telling me that the server IP
address can't be found. Would you be able to send me the link again?

Sorry for the hassle!

**Comment by audionerd** [comment]
Should still work: https://github.com/wonderunit/storyboarder/releases

**Comment by Koherty** [comment]
My bad! There was something wrong with my internet.

Link works fine!

thanks again for you help
