### ISSUE TITLE
Export to Affinity Designer/Photo

### ISSUE THREAD

**Issue by reanimastudios** [wonderunit/storyboarder#1442]
Request an alternative to Photoshop and that being Affinity Designer and Photo

It would seem the perfect fit to have. The over 1,000,000 Affinity users on OS X and Windows would make this a perfect fit.

**Comment by audionerd** [comment]
In Storyboarder’s preferences, you can choose which PSD editor to use with Storyboarder. So if Affinity Designer can read and write PSDs, this should already be possible.

**Comment by reanimastudios** [comment]
Glad to read that and yes both Designer and Photo read PSDs. Both phenomenal applications at a fraction of the price of Photoshop/illustrator.
