### ISSUE TITLE
Clip Studio sync

### ISSUE THREAD

**Issue by jbleau** [wonderunit/storyboarder#1445]
I am using Clip Studio Paint ver. 1.7.4 as my external image software for drawing.  I have installed Storyboarder 1.9.2 ...

**Issue:** I get a long, long  lag between saving a Clip Studio file and seeing it show up in Storyboarder.  At times it will not show.  I also get an error message. "{Warning} Error Command Failed" followed by the location of my Clip exe file and the Storyboard file location...

I have turned off/on the preference _"Force reload of watched PSD when storyboarder regains focus" with no difference in performance. Not sure what to try next...Is this common? 

I love the program and really hope it can work with Clip Studio as it is my primary drawing tool. It looks like you addressed a similar issue in 2017.  Can you offer any suggestions please.

**Comment by audionerd** [comment]
The next time you get the error, try opening Developer Tools from the View menu. There should be some logged information about what Storyboarder tried and what failed. Post a screenshot of that if you can.

**Comment by jbleau** [comment]
I have no idea what to look for under Developer window ...here is what I see...
![storyboarder arning](https://user-images.githubusercontent.com/45053912/48598670-f94c5a00-e931-11e8-9e21-dfe81f404e4b.PNG)

**Comment by jbleau** [comment]
Has anyone got any suggestion for this? Does anyone have a similar issue?
