### ISSUE TITLE
Audio manipulation?

### ISSUE THREAD

**Issue by jgv** [wonderunit/storyboarder#1462]
When I'm listening to music on Spotify and open Storyboarder, all of the bass and midrange cuts out. The music sounds very tinny. This happens even if I enable high quality audio. 

The issue is resolved when I quit Storyboarder.

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the next release.

Fixed by https://github.com/wonderunit/storyboarder/commit/11c67fb0f7bb42293515eab9a57f68341989193f
