### ISSUE TITLE
Audio never perfectly synchronizes with storyboard

### ISSUE THREAD

**Issue by EleanorLB** [wonderunit/storyboarder#1467]
**Describe the bug**
For a current project Im working on in storyboarder, I need to sync up my boards to a specific song, so I upload the audio file starting right at the first panel. However, what's been happening over and over again is that the audio player and the loading time for each panel isn't very precise. The audio constantly goes out of sync with the boards, even when I perfectly timed them before. Sometimes the program apparently takes longer to jump to the next panel. I end up having to replay the whole scene multiple times until it suddenly syncs up with the audio again. Working on panels in between is an absolute nightmare. If you start playing your board not from the beginning, but somewhere in the middle, the audio will play in 1-2 seconds delayed from the original time and your timing will no longer be accurate.

This is something I've been having problems with over multiple projects already and it really needs an urgent fix. I'd suggest adding a visible audio track underneath the boards instead of binding an audio file to a single panel, It would make working on such projects in storyboarder far more convenient.

**System**
Windows 64bit, Windows 10

**Comment by MamaBacon** [comment]
I've had this problem too, and found that even exporting a video the frames are still off, up to 3 or 2 behind the audio, when I had them in sync when I drew them. Even opening the project again hasn't fixed the problem, and the boards are still falling behind almost right from the beginning.

**Comment by audionerd** [comment]
This will be fixed in the next release.
