### ISSUE TITLE
Audio forces 8bit, sounds like phone recording

### ISSUE THREAD

**Issue by alexburnett553** [wonderunit/storyboarder#1474]
Hey there, 

So I am using a pair of Sony bluetooth headphones, and whenever I open a project it forces 8bit audio upon them. I tried changing in the Mac system prefs after I open a Storyboarder project and it forces it back to 8 bit. As soon as I quit the program, my audio switches back. Is there anyway I can change this somehow? I enjoy listening to music while storyboarding and would be bummed if I couldn't. Thanks in advanced!

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the next release.

Fixed by https://github.com/wonderunit/storyboarder/commit/11c67fb0f7bb42293515eab9a57f68341989193f
