### ISSUE TITLE
Canvas/Thumbnail failed to refresh and update

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#15]
![scrshot_canvas not showing image_a](https://cloud.githubusercontent.com/assets/14130545/22504207/3d296156-e843-11e6-8726-c07f348fb4a6.jpg)
![scrshot_canvas not showing image_b](https://cloud.githubusercontent.com/assets/14130545/22504213/4347fd18-e843-11e6-8dc4-8c17305aac3e.jpg)
![scrshot_thumbnail failed to updateupdatet](https://cloud.githubusercontent.com/assets/14130545/22504230/4e0fd91e-e843-11e6-9967-af8ec4b2b4bc.jpg)

**Comment by setpixel** [comment]
We think we fixed this. Please reopen if you see it in the next release!
