### ISSUE TITLE
Alternate photoshop programs result in errors

### ISSUE THREAD

**Issue by jimbiladas** [wonderunit/storyboarder#1519]
Alternate photoshops programs are not working with storyboarder. I looked at other threads mentioning this issue, and it appears it was discussed at length in 2017.

I have been experimenting with this, I have tried Gimp, and Sketchbook with no luck. Steps taken:

-Set my system preferences to an alternate photoshop program, in this case sketchbook.exe, or gimp.exe
-Close Storyboarder
-Reopen Storyboarder
-Edit a board panel with the PS button
-PS button Opens panel with associated new PSD editor
-Edit the board.psd, save
-Error message in Storyboarder, (see attached image)

Personally, I'd love to use sketchbook when drawing new stuff for Storyboarder, Photoshop is too bloated to be practical trying to draw quick on my machines. I figured I'd mention this as a "nice to have" since there have been mentions that Storyboarder allows for external PSD editor alternates. I haven't had any luck with alternates. Any thoughts?

![photshop_alt_req](https://user-images.githubusercontent.com/40301961/51498004-e6169a00-1d79-11e9-8a58-7b7c861f3566.png)

**Comment by audionerd** [comment]
Can you try opening Developer Tools from the View menu when this happens? Let us know what you see in the logs.

The library Storyboarder uses to read PSD files is very particular about formatting, as is Storyboarder’s routines. Unless the PSD is saved very similar to the way Photoshop would save it, and without certain features Storyboarder doesn’t support (like text or vector layers) it will fail.

Do the alternate programs have compatibility options you can try that might save PSDs differently?

**Comment by jimbiladas** [comment]
In this case I made a test for you based on your request. See zip file for the project file and resulting PSD, images, etc. The PSD is called "board-1-S94RI"

Steps:
-Open Storyboarder/Create new Storyboarder File
-Click the Photoshop Button/Opens Alternate PSD editor
-Edit the PSD/Save/Error in Storyboarder
-Close Storyboarder/Reopen new Storyboarder file/No changes can be seen on the board
-Right click on the PSD in external file window/using Properties from right click Open with Photoshop/Lines show up in the PSD to confirm changes are made.
[test_PS_alternate.zip](https://github.com/wonderunit/storyboarder/files/2780568/test_PS_alternate.zip)

**Comment by Hillman79** [comment]
I encounter the exact same issue here with AutoDesk Sketchbook. Sketchbook is free of charge now and it is such a fantastic programme it would be great if it could work together with a geat programme like storyboarder seemlessly.
Would appreciate if there would be a solution for this issue.

**Comment by Hillman79** [comment]
any news on this?

**Comment by audionerd** [comment]
PSD reloading should be improved in the next release. We're using a method of reading PSDs that should allow for broader compatibility. Tracking as issue #1656.
