### ISSUE TITLE
shot generator: rendered shot should exclude helpers

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1550]
### Problem

Sometimes the BonesHelper of a selected Character shows up in the snapshot we send to Storyboarder.

This is a total hack and needs to change: https://github.com/wonderunit/storyboarder/blob/shot-generator/src/js/shot-generator/Editor.js#L2878-L2882

### Solution:

Use Layers:
https://threejs.org/docs/#api/en/core/Layers

> A Layers object assigns an Object3D to 1 or more of 32 layers numbered 0 to 31 - internally the layers are stored as a bit mask, and by default all Object3Ds are a member of layer 0.
> This can be used to control visibility - an object must share a layer with a camera to be visible when that camera's view is renderered.

Our layers will be:
```
0: Always rendered
1: Rendered for "live" camera
2: Rendered for "top-down" camera
```

And layer assignments would be:
```
BoneHelper: 1, 2
CameraHelper: 2
Perspective Cameras (including Live camera): 0, 1
Top-Down Camera: 0, 2
Objects: 0
Characters: 0
Lights: 0

Image Export Perspective Cameras: 0
Image Export Top-Down Camera: 2
```

In the future, we might also have:
```
3: Rendered for "live" image export
4: Rendered for "top-down" image export
5: Helpers only
```

Is there a way to put the outline effect on a layer?

**Comment by setpixel** [comment]
i'd like to move this up in priority.

**Comment by setpixel** [comment]
even if it's just a bigger hack (delay) for now
