### ISSUE TITLE
Opening storyboard disables audio from other sources

### ISSUE THREAD

**Issue by matineemonkey** [wonderunit/storyboarder#1590]
Windows 10 Enterprise version 1709
Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz 3.50 GHz
24.0 GB installed RAM

Storyboarder version 1.9.2

Opening a project file in Storyboarder disables audio from other sources. I'm experiencing this specifically on Bluetooth headphones and don't have another audio device to test with. No sound from web, music players, or system audio.

Seems to be similar to #1119 , only I get no audio at all while the project file is open. Unchecking "Save Project Data Automatically," "Force reload of watched PSD when Storyboarder regains focus," "Show Hourly Affirmations," "Drawing Sound Effects," "Drawing Melodies," "User Interface Sound Effects," "Enable High Quality Audio," and "High Quality Drawing Engine" does not appear to help.

**Comment by matineemonkey** [comment]
Disabling the headset in the recording devices menu, so there are no enabled recording devices, seems to resolve the issue.

Does Storyboarder take control of the microphone whenever it's launched?

**Comment by audionerd** [comment]
> Does Storyboarder take control of the microphone whenever it's launched?
Yes, it opens the audio input at startup. But, we're fixing it in the next release to only request microphone access when an artist actually wants to record board audio!

Thanks for the report.

Fixed by https://github.com/wonderunit/storyboarder/commit/11c67fb0f7bb42293515eab9a57f68341989193f
