### ISSUE TITLE
Canvas failed to Clear entirely

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#16]
Tried clearing the canvas. Lest only my first stroke. I had to "Undo" to clear it

![scrshot_canvas did not clear](https://cloud.githubusercontent.com/assets/14130545/22504299/9e26539c-e843-11e6-9d36-15279c6f18dd.jpg)

**Comment by setpixel** [comment]
Drawing lingering on drawing layer, should be cleared

**Comment by setpixel** [comment]
This will be fixed with new sketch pane. Not closing yet.
