### ISSUE TITLE
Error creating storyboard from .fountain

### ISSUE THREAD

**Issue by brencerddwr** [wonderunit/storyboarder#1608]
**Describe the bug**

**To Reproduce**
1. Open storyboarder
2. Click on 'create new storyboard'
3. Click on 'Select Script'
4. Select .fountain file
5. See Error image attached

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome

![error_box](https://user-images.githubusercontent.com/10186906/54143839-e3363e00-43e7-11e9-93d6-96fbeff02829.png)

**Comment by audionerd** [comment]
Could you send us a ZIP of an example .fountain file that has this problem?

**Comment by brencerddwr** [comment]
here you go.

[script.zip](https://github.com/wonderunit/storyboarder/files/2953555/script.zip)

**Comment by brencerddwr** [comment]
I tried a remove and reinstall, same issue.

**Comment by brencerddwr** [comment]
I found the issue. there was a Note: that did not have a blank line before it and was right below a scene marker.

Adding a blank line above it, fixed the problem.
