### ISSUE TITLE
Throws an error when I open 3d guide

### ISSUE THREAD

**Issue by nedgip** [wonderunit/storyboarder#1617]
I get an error when I open the 3d guide on a new project.

![image](https://user-images.githubusercontent.com/17900897/54792378-8fe6aa00-4c89-11e9-925b-12120d06157c.png)

**Comment by simonscheiber** [comment]
Yeah, same here: 

![error](https://user-images.githubusercontent.com/600736/54817254-c119a700-4c96-11e9-8713-db1395346b25.png)

**Comment by audionerd** [comment]
Related to https://github.com/wonderunit/storyboarder/issues/1573

**Comment by audionerd** [comment]
Tracking in #1573
