### ISSUE TITLE
Saving a preset removed all the existing presets

### ISSUE THREAD

**Issue by codenift** [wonderunit/storyboarder#1619]
Saving a preset for a character in shot generator removed all the default presets it had for poses. I reinstalled the application but they're all gone except the new preset I saved. Don't know how to get them back.

**Comment by setpixel** [comment]
are you on mac or pc?

**Comment by codenift** [comment]
I'm on a Mac using macOS Mojave.

**Comment by audionerd** [comment]
> Saving a preset for a character in shot generator

Was this after saving a new Character Preset or a new Pose Preset?

Characters have two preset lists, one for Character Presets at the top (which include the model, height, morphs) and another one for Pose Presets at the bottom (which describe the pose the character's "bones" are in).
![image](https://user-images.githubusercontent.com/23459/54851808-19fa3700-4cb9-11e9-983b-1588ee25d8cc.png)

Is it possible you were looking at the wrong list?

Can you post screenshots of the content you see for both preset lists?

Shot Generator saves presets to JSON files in `~/Library/Application Support/Storyboarder/presets`. Do you see two JSON files there? Do they have any content?

**Comment by codenift** [comment]
Yes. I got confused since one said 'Preset' and the other one didn't, instead it says "Pose'. It's all there. Thanks.
