### ISSUE TITLE
Photoshop to Storyboarder does not immediately refresh/update

### ISSUE THREAD

**Issue by fignutz** [wonderunit/storyboarder#1623]
This is the same error that was reported here: 
https://github.com/wonderunit/storyboarder/issues/1170

Having same exact issues as the OP' was having.

**Comment by sifutao** [comment]
Same error here. Sometimes the modification does not appear at all. Either with photoshop or Affinity photo.

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
