### ISSUE TITLE
Please support the Chinese characters!

### ISSUE THREAD

**Issue by PIECAISKY** [wonderunit/storyboarder#1624]
Today I download your software, it's super great! and goodlooking!
i love your creation.
but when i use Chinese script, the software cannot load any files i sketched or record. i think the software did not support the Chinese characters folder.
<img width="2011" alt="图片" src="https://user-images.githubusercontent.com/49209233/55429219-8b8d8b80-55bd-11e9-8ff3-b1d7aaf6ef17.png">

so every line i sketched always disappeared
<img width="2032" alt="图片" src="https://user-images.githubusercontent.com/49209233/55429555-62212f80-55be-11e9-8d21-a93daf8a9d50.png">

thanx!
you r amazing!

**Comment by audionerd** [comment]
Can you send a ZIP of an example project with this issue?

Looks like the board image files do seem to be created, but they're empty? Weird ...

**Comment by PIECAISKY** [comment]
[YJZS.zip](https://github.com/wonderunit/storyboarder/files/3035584/YJZS.zip)
thanx
I think the software cannot load any files i sketched or recorded by the software, becausce the software cannot load the Chinese character folder.

thanx!

**Comment by PIECAISKY** [comment]
i solved the problem~about the folder i created is wrong.
Do not use  folder like this(in mac)
![图片](https://user-images.githubusercontent.com/49209233/55433294-9fd68600-55c7-11e9-964e-61484fe009ac.png)

thanx

**Comment by PIECAISKY** [comment]
i use normal folder and it works。

thanx！！！！！！！！
