### ISSUE TITLE
BUG CCS IMAGE

### ISSUE THREAD

**Issue by liobenelli** [wonderunit/storyboarder#1628]
tengo un bug cuando utilizo la herramienta 3d guide, empieza a arrojarme un error "Uncaught Type error: Faile to execute "drawImage on cavas Rendering context2d" The provided value is not of type "(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideo Element or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)"  

Thanks fot your Help

![imagen](https://user-images.githubusercontent.com/16541302/55565280-2e79fe80-56bf-11e9-9aa3-924b0a2273a7.png)

**Comment by audionerd** [comment]
Thanks for the report. This seems to happen when the 3D guide is selected, which isn't complete yet. We're working on it.

Tracking this under issue #1573
