### ISSUE TITLE
Odd thing in shot generator

### ISSUE THREAD

**Issue by joz5** [wonderunit/storyboarder#1633]
This is great. But SG won't save work through closings unless the image has been saved to the board. 

Id be very interested in ANY adjustments you make to this function of storyboarder.

**Comment by audionerd** [comment]
Not sure I follow you. Can you explain this a little more?

Storyboarder should auto-save your images, and will auto-save your .storyboarder data file (unless you turn it off in Preferences)

**Comment by audionerd** [comment]
To save an image made in Shot Generator, you must press the "Save to Board" button. It won't auto-save from Shot Generator, which was a decision we made so that you can try different ideas in Shot Generator without committing to them.
