### ISSUE TITLE
iPhone connection no longer works

### ISSUE THREAD

**Issue by bcassin** [wonderunit/storyboarder#1634]
using the QR code no longer works to manipulate models using the iPhone.
![IMG_721BF0C6274D-1](https://user-images.githubusercontent.com/16521244/56164429-aa692600-5f9e-11e9-9dbb-b1977bf6c91a.jpeg)

There is some data below the circular arrow but can't access it.

Using and iPhone SE

**Comment by audionerd** [comment]
Yeah we should probably fix the layout for smaller phones.

There's also a problem where recent updates to mobile browsers have disabled the feature we were using for the phone controller. We're working on a fix but it might take some time.

Tracking at https://github.com/wonderunit/storyboarder/issues/1663
