### ISSUE TITLE
Rotating object in Shot Generator not working

### ISSUE THREAD

**Issue by Tavarino** [wonderunit/storyboarder#1636]
QR code brings up Safari screen on iPhone with rotation control which seems unresponsive. This is an iPhone 6+. Is it supported? If so, is there something else I could be doing wrong?

**Comment by audionerd** [comment]
Try selecting a character, bone, or object. On the phone, hold the large rotate button while moving the phone. What happens?

**Comment by Tavarino** [comment]
Thanks for the response. Nothing happens. Is the rotate button supposed to change in appearance when touched? It doesn’t, as if the control is disabled.

**Comment by eAi** [comment]
Just in case anyone else comes across this wondering where the QR code rotation thing is that is referred to the documentation - it's been removed. Not sure why - presumably because it didn't work well.

https://github.com/wonderunit/storyboarder/commit/1bb81bf0c69c180add8c35948b3c0a9353d0ce1e

**Comment by setpixel** [comment]
Yes - you can no longer get the accelerometer data through HTTP anymore. So it stopped working, and to make it work would involve sending the data through a live internet server which would be costly and slow. We decided to eliminate the feature in favor of VR.
