### ISSUE TITLE
Storyboarder freezes on start at 'Initializing'

### ISSUE THREAD

**Issue by ehcla** [wonderunit/storyboarder#1640]
Hi!

I was really happy to find 'Storyboarder' and couldn't wait to try it out (almost bought a drawing tablet before i even tried the app because i was so excited). Turns out though that it doesn't work on my computer.

Bug:

When i install Version 1.9.2 for OS X 10.9.5 i can create a new project, but it hangs on the window 'Initializing' and doesn't boot up or go any further. Behaviour doesn't change if i try it again and again.

Reproduce:

Start Version 1.9.2 on OS X 10.9.5 and create new Project. See Screenshot nothing further happens: 

<img width="635" alt="Bildschirmfoto 2019-05-05 um 13 03 30" src="https://user-images.githubusercontent.com/50292020/57192928-3b944280-6f36-11e9-9a3a-03c4fd7fe539.png">

Is there something i can do to fix this? I am in desperate need of this Program. I have the feeling like it found me, it could be so perfect! :)

Thank you for any help in advance! -> Where can i donate?

Cheers, Max

**Comment by audionerd** [comment]
When you see “initializing” there should be a View Developer Tools option in the top menu. Open that. Might need to resize it a bit. Should see some log messages. What do they say? If you can post a screenshot of any errors you see we can help debug.

**Comment by ehcla** [comment]
Thank you for the quick response! It's really hard to get a hold of the 'View Developer Tools' Window since it only shows for a second and then disappears. But once every 30 times i open it, it does stay opened. Under which column do i look for the log message? 
What i found was this, is it helpful?:

![Bildschirmfoto 2019-05-05 um 19 28 25](https://user-images.githubusercontent.com/50292020/57197844-381bae00-6f6c-11e9-9c5a-bf93b92a899b.png)

**Comment by audionerd** [comment]
Choose “Console”, thats the one we need to see.

**Comment by ehcla** [comment]
If i try to click on 'Console' it immediately closes the window. In the Splitsecond that it shows, there is no Text there though.

**Comment by audionerd** [comment]
OK, sounds similar to this issue:

https://github.com/wonderunit/storyboarder/issues/1435#issuecomment-436405570

If you can get _any_ console window to open in Developer Tools (even the Welcome window), you can try typing:

`require('electron').remote.BrowserWindow.getAllWindows().forEach(w => w.show())`

That will show _all_ windows, including the large Workspace window. From there you can see developer tools logs, which hopefully will have some errors logged we can work from to try to troubleshoot.

**Comment by audionerd** [comment]
Can you try the latest version of Storyboarder and let us know if that fixes the issue?
