### ISSUE TITLE
Microphone triggers on opening file, creates audio issues on Bluetooth headphones

### ISSUE THREAD

**Issue by garretvoorhees** [wonderunit/storyboarder#1641]
**Describe the bug**
When I open a file, I can hear my bluetooth headphones switch over to a microphone mode that lets in ambient sound, and effectively shreds the audio quality of anything I was listening to. I've tried to disable microphone access to the application, but it still triggers consistently. Unfortunately, this makes the software completely unusable for me!

I'd love to see an option in Preferences to disable microphone entirely to prevent this from happening.

**Comment by garretvoorhees** [comment]
I just found a weird workaround to "fix" this:

In terminal, I ran the command `tccutil reset Microphone`to reset Microphone privacy settings. The next time I launched Storyboarder, I was prompted to grant access to the Microphone and hit Block instead of Allow. Now, the microphone isn't triggering although I obviously can't use any mic-specific features.

Still, works for me! (for now)

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the next release.

Fixed by https://github.com/wonderunit/storyboarder/commit/11c67fb0f7bb42293515eab9a57f68341989193f
