### ISSUE TITLE
Double click scriptpane item to insert data into board

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#165]
If user "double-clicks" (with pointer, so this could include pen), trigger the behavior.

If board already has data, prompt before overwriting.

*Script Data:*
- New Scene: Script duration, slug line, synoposis
- Scene Item: Action (has text), Dialogue (has character, text), Transition (has text)

*Board Data:*
- Dialogue
- Action
- Notes
- Duration/Timing?

---

- [ ] Test Wacom tablet

**Comment by audionerd** [comment]
Could do a better job of stripping out HTML to leave only the raw text, e.g.:

> Something happens now and this describes it.<br />
