### ISSUE TITLE
Recommendations on 3d model formats / export settings

### ISSUE THREAD

**Issue by pvlvsk** [wonderunit/storyboarder#1650]
**Describe the bug**
Many .obj and .glb files won't open in Storyboarder. 

**To Reproduce**
Load model in Shot generator. Some models are displayed, some not. All controls freeze, when it is not supported model.

**Expected behavior**
Expected behavior is the quick and easy loading of externally downloaded 3d models for efficient storyboarding.  Any recommendations how to prepare models that are compatible with Storyboarder?

Thank you!

**Comment by pvlvsk** [comment]
Here is a free 3d model i attach to check. 


[table.zip](https://github.com/wonderunit/storyboarder/files/3194319/table.zip)

**Comment by pvlvsk** [comment]
I opened developer tools and that is what i see, when i load a model, that is not displayed:

`/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:3339 Uncaught TypeError: Cannot read property 'elements' of undefined
    at Matrix3.copy (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:3339)
    at refreshUniformsCommon (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:24107)
    at setProgram (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23872)
    at WebGLRenderer.renderBufferDirect (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:22738)
    at renderObject (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23436)
    at renderObjects (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23406)
    at WebGLRenderer.render (/Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23209)
    at THREE.OutlineEffect.render (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/vendor/OutlineEffect.js:421)
    at animatedUpdate (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:542)
    at /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:122
copy @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:3339
refreshUniformsCommon @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:24107
setProgram @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23872
WebGLRenderer.renderBufferDirect @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:22738
renderObject @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23436
renderObjects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23406
WebGLRenderer.render @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/three/build/three.js:23209
render @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/vendor/OutlineEffect.js:421
animatedUpdate @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:542
(anonymous) @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:122
(anonymous) @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:11
(anonymous) @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/redux/lib/redux.js:468
animator.current @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:490
requestAnimationFrame (async)
animator.current @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:556
requestAnimationFrame (async)
useEffect @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:560
commitHookEffectList @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17079
commitPassiveHookEffects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17103
callCallback @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:149
invokeGuardedCallbackDev @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:199
invokeGuardedCallback @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:256
commitPassiveEffects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18570
wrapped @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler-tracing.development.js:207
flushPassiveEffects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18618
dispatchAction @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13441
requestAnimationFrame @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:3029
requestAnimationFrame (async)
ClosestObjectInspector.useEffect @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:3021
commitHookEffectList @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17079
commitPassiveHookEffects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17103
callCallback @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:149
invokeGuardedCallbackDev @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:199
invokeGuardedCallback @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:256
commitPassiveEffects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18570
wrapped @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler-tracing.development.js:207
flushPassiveEffects @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18618
dispatchAction @ /Applications/Storyboarder.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:13441
onBlur @ /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:262
/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:565 cameraControls setter cleanup
/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:431 camera changed
/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-generator/Editor.js:436 new CameraControls`

**Comment by audionerd** [comment]
The source files for the built-in Shot Generator models, and some other compatible models are here:

https://github.com/wonderunit/shot-generator-models

We haven’t tested with much beyond that yet, although we’d definitely like to expand compatibility! 

Short term we should probably document what the loader currently expects.

**Comment by pvlvsk** [comment]
> Short term we should probably document what the loader currently expects.

That would be great. Thank you!
