### ISSUE TITLE
Shot generator doesn't work

### ISSUE THREAD

**Issue by asilnevs** [wonderunit/storyboarder#1676]
I'm trying out the appimage version 1.10.1 on Ubuntu 18.04
When I click on the little (white) screen under the text "Shot generator" on the right side, a new screen appears but it's all black. I can't do anything in it.
Beta Version 1.9.4 is still working ok.
And is it normal that the downloaded appimage file for version 1.10.1 (111.8Mb) is smaller then version 1.9.4 (124.7Mb) ?

**Comment by audionerd** [comment]
When the new Shot Generator window appears can you try opening Developer Tools and let us know if you see any errors?

Re: file size — we tried to trim the download size for this release so i think that makes sense.

**Comment by asilnevs** [comment]
Error: Cannot find module 'dualshock'
By right clicking in that Development screen I could save a log file with this text:
`/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/windows/shot-generator/window.js:10 Console was cleared
/tmp/.mount_VerwijZiWhIp/resources/app.asar/node_modules/three/build/three.js:12692 THREE.SpriteMaterial: 'useScreenCoordinates' is not a property of this material.
setValues @ /tmp/.mount_VerwijZiWhIp/resources/app.asar/node_modules/three/build/three.js:12692
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/OBJLoader2.js:20 Using THREE.OBJLoader2 version: 2.5.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:350 Using THREE.LoaderSupport.MeshBuilder version: 1.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:718 Using THREE.LoaderSupport.WorkerSupport version: 2.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/node_modules/three/build/three.js:22137 THREE.WebGLRenderer 100
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/OBJLoader2.js:20 Using THREE.OBJLoader2 version: 2.5.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:350 Using THREE.LoaderSupport.MeshBuilder version: 1.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:718 Using THREE.LoaderSupport.WorkerSupport version: 2.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/OBJLoader2.js:20 Using THREE.OBJLoader2 version: 2.5.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:350 Using THREE.LoaderSupport.MeshBuilder version: 1.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:718 Using THREE.LoaderSupport.WorkerSupport version: 2.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/OBJLoader2.js:20 Using THREE.OBJLoader2 version: 2.5.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:350 Using THREE.LoaderSupport.MeshBuilder version: 1.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/vendor/three/examples/js/loaders/LoaderSupport.js:718 Using THREE.LoaderSupport.WorkerSupport version: 2.3.0
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/shot-generator/DualshockController.js:46 dual shock controller class
/tmp/.mount_VerwijZiWhIp/resources/app.asar/node_modules/electron-log/lib/transports/console.js:72 19:23:29.010 › Error: Cannot find module 'dualshock'
Require stack:
- /tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/shot-generator/DualshockController.js
- /tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/windows/shot-generator/window.js
- /tmp/.mount_VerwijZiWhIp/resources/app.asar/src/shot-generator.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (/tmp/.mount_VerwijZiWhIp/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/shot-generator/DualshockController.js:50:12)
    at Object.<anonymous> (/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/shot-generator/DualshockController.js:251:3)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
consoleLog @ /tmp/.mount_VerwijZiWhIp/resources/app.asar/node_modules/electron-log/lib/transports/console.js:72
/tmp/.mount_VerwijZiWhIp/resources/app.asar/src/js/shot-generator/IconSprites.js:313 sprites updated`

**Comment by cobledik** [comment]
I have the same issue as asilnevs: appimage version 1.10.1 on Kubuntu 18.04.2; new all black screen.

**Comment by asilnevs** [comment]
Version 1.11.3 is working now on my Ubuntu 18.04
Thanks for fixing.
