### ISSUE TITLE
Saving a character preset results in a 'non exitable' popup

### ISSUE THREAD

**Issue by pearnold** [wonderunit/storyboarder#1679]
Clicking the plus sign close to the preset in a character, results in the situation in the screenshot.

Clicking ok or cancel doesn't change anything.

Only exiting the app bring the shot generator back to life.
![Bildschirmfoto 2019-06-18 um 12 47 14](https://user-images.githubusercontent.com/23722222/59676264-7640fa00-91c7-11e9-9745-2bee837733ff.png)

**Comment by audionerd** [comment]
Should be fixed in the latest release.
