### ISSUE TITLE
Custom 3d models do not show up in VR shot generator

### ISSUE THREAD

**Issue by satishgoda** [wonderunit/storyboarder#1689]
**Describe the bug**
Any 3D models that I have imported in my scene do not show up in the VR Shot Generator 

**To Reproduce**
1. Open Shot Generator
2. Add an Object
3. Select a Custom file to load for the Object
3. Open the Shot Generator in VR (Oculus Quest Web Browser in my case)
4. I only see the built-in objects and characters and not my custom object models.

**Expected behavior**
Builtin and custom 3D objects must be shown

**Screenshots**

![image](https://user-images.githubusercontent.com/536008/59979261-42385100-959a-11e9-9aba-fc118f5d43a5.png)

![64962801_10156015892875163_1083949835981160448_o](https://user-images.githubusercontent.com/536008/59979426-ad832280-959c-11e9-88bc-bf688e78d3f5.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Oculus Quest Web Browser]
 - Version [Storyboarder v1.10.1]

Thank you,
Satish.

**Comment by audionerd** [comment]
Hmm I couldn't replicate this issue.

I was able to load both custom character and object models in VR, using model files from https://github.com/wonderunit/shot-generator-models.

Could you send us the `.glb` you're using? Maybe it's specific to the file?

**Comment by SatishGodaPearl** [comment]
Hi audionerd. I will send you the files today evening. Thank you.

**Comment by setpixel** [comment]
Any update for this?

**Comment by setpixel** [comment]
Will reopen if still an issue
