### ISSUE TITLE
Playback sync

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1694]
During playback, audio and board art should be synchronized.

Quick fix: on every setTimeout callback, use delta to determine next frame timing.
Better fix: use Tone's timeline code for sample-accurate sync

Playback code:
https://github.com/wonderunit/storyboarder/blob/c0bf35c4eba51bcda702836a785807f88a40239f/src/js/window/main-window.js#L4802

Related:
https://github.com/wonderunit/storyboarder/issues/1467

Reference:
https://github.com/Tonejs/Tone.js/wiki/TransportTime
https://www.html5rocks.com/en/tutorials/audio/scheduling
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques#Playing_the_audio_in_time

**Comment by esotericDisciple** [comment]
Stroyboarder would be be studio-ready by now if the audio timeline was separate from the storyboards themselves...
