### ISSUE TITLE
Software Not compatible with Windows 10 v1903 (May 2019 release)

### ISSUE THREAD

**Issue by tigyii** [wonderunit/storyboarder#1699]
Bug1: 
Panels disappear; drawing an image on the first panel, then creating a second or any amount of subsequent panels, all previous panels disappear. when returning to previous panels, they can no longer be modified. When closing and reopening file, all panels are blank and cannot be modified.

Bug2:
Photoshop launch button will not work, even when directing settings to "PSD editing" software in preferences. 

**To Reproduce**
Install Storyboarder software (1.11.3, 1.11.1, or 1.9.2) on machine running Windows 10 release v1903 (May 2019 Update)

**Expected behavior**
Bug 1, expected panels to maintain modifications
Bug 2, without prefereces, expected software to launch system default PSD editor, or with preferences to use the specified software.

**Screenshots**

![capture1](https://user-images.githubusercontent.com/40827327/60233519-8014ce00-9855-11e9-822b-aec5c81edd67.JPG)
![capture2](https://user-images.githubusercontent.com/40827327/60233520-8014ce00-9855-11e9-94e6-4715356c1e6a.JPG)
![capture3](https://user-images.githubusercontent.com/40827327/60233521-80ad6480-9855-11e9-8e35-fd735c8f577f.JPG)
![capture4](https://user-images.githubusercontent.com/40827327/60233522-80ad6480-9855-11e9-9fc5-4692d9cb8b7e.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903 (May 2019 Update)
 - Browser Chrome
 - Version 75.0.3770.100

**Additional context**
Tested working on system running Windows 10 v1803; will test soon on Windows 10 1809 and report back.

**Comment by TimTeamer** [comment]
Installed and tested on Windows 10 v1809 and the software works perfectly. It has been tested across several v1903 machines with the same errors. The problem is the latest windows release.

**Comment by tigyii** [comment]
1.11.3 Spacebar only triggers playback and not panning.

**Comment by tigyii** [comment]
Fresh install of Windows 10 v1903 with minimum driver and software install, and software (including panning) works... I don't know anymore... Anyone else have issues?

**Comment by tigyii** [comment]
It was all a user error, I was initiating projects into a User/Documents/#storyboarder folder. 

if you have your project files in a folder preceding with a 'hashtag', nothing works. pretty unique situation, but maybe someone will find errors in the future and see that the error is also caused by their folder structure. 

Thanks for this software!
