### ISSUE TITLE
Support for long paths

### ISSUE THREAD

**Issue by pearnold** [wonderunit/storyboarder#1705]
Storyboarder doesn't show posterframes, when paths get too long.

I created an Storyboarder Project from a fountain file in the folder :
C:\Users\Pirmin\Film Theater Forum e.V\Vereinsdateien - Dokumente\Projekte\Libra\Kamera\Storyboards-Shotlisten\Hochstaetter\14-(nullZweiBisNullAcht)\

so the storyboarderfile is in:
C:\Users\Pirmin\Film Theater Forum e.V\Vereinsdateien - Dokumente\Projekte\Libra\Kamera\Storyboards-Shotlisten\Hochstaetter\14-(nullZweiBisNullAcht)\storyboards\Scene-1-INT-Hochstätters-Wohnung---Arbeitszimmer-Nacht-14-(02bis08)\Scene-1-INT-Hochstätters-Wohnung---Arbeitszimmer-Nacht-14-(02bis08).storyboarder

and the images are in:
C:\Users\Pirmin\Film Theater Forum e.V\Vereinsdateien - Dokumente\Projekte\Libra\Kamera\Storyboards-Shotlisten\Hochstaetter\14-(nullZweiBisNullAcht)\storyboards\Scene-1-INT-Hochstätters-Wohnung---Arbeitszimmer-Nacht-14-(02+04+06+08\_images\

This are 241 letters.
The image names exceed the 255 letter limit and storyboarder can't show the previews anymore.

**Comment by audionerd** [comment]
I think this is a Windows limitation, not a Storyboarder limitation.

Which version of Windows are you running? I think in some recent versions of Windows you can configure/disable the limit.

**Comment by audionerd** [comment]
> Starting in Windows 10, version 1607, MAX_PATH limitations have been removed from common Win32 file and directory functions. However, you must opt-in to the new behavior.

https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

**Comment by pearnold** [comment]
I use Windows Version 1803.
I enabled long paths via regedit and in the group policies.
Now the result is a little better, but the boards are still not shown.
![01](https://user-images.githubusercontent.com/23722222/60488758-16f0e880-9ca3-11e9-9f8c-59e5d03fe072.JPG)
![02](https://user-images.githubusercontent.com/23722222/60488760-16f0e880-9ca3-11e9-9e4f-38bce80cf119.JPG)

**Comment by pearnold** [comment]
> > Starting in Windows 10, version 1607, MAX_PATH limitations have been removed from common Win32 file and directory functions. However, you must opt-in to the new behavior.
> 
> https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

The opting-in is on the software-side. The file-acces-operations with the support of long paths have to be used, for my understanding.

**Comment by audionerd** [comment]
Storyboarder is built using Electron, and my guess is that Electron does not support long file paths on Windows.

Best solution would be to use a short path for the project folder if possible.

**Comment by pearnold** [comment]
Thanks for your explanation.
We use storyboarder for a very large, complex project, so the folder structure gets this big quiet easy.
I fixed it with shortening the paths where ever possible. 

It would be nice if this wouldn’t be a restriction in the future :)
