### ISSUE TITLE
Shot Generator IK: gizmo disappears after drag outside

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1711]
there’s a gizmo for rotating bones. but if you drag outside of it and then release, it disappears. would be nice if it knew your had just finished dragging and didn’t disappear.

**Comment by VladStepura** [comment]
I've fixed it in the last commit should work fine now.

**Comment by audionerd** [comment]
Fixed in dc4cc560408cdb7294b94d2858e19b5d08d94c03
