### ISSUE TITLE
Shot Generator does not open on Surface Book 2

### ISSUE THREAD

**Issue by Toorah** [wonderunit/storyboarder#1715]
When I use Storyboarder on my Microsoft Surface Book 2 using the Touchscreen or the Pen/Stylus, I cannot open the Shot Generator.
Clicking with my Pen or tapping with my finger does not open the Shot Generator window.
I have to use the Mousepad to click to open it, which isn't possible as I use my laptop in Tablet mode (ie. don't have the mousepad accessible).

**Comment by audionerd** [comment]
Thanks for the report. Might be because Storyboarder is listening for `click` events instead of `pointerdown` events. I'll take a look.

**Comment by audionerd** [comment]
Can you try again with the latest version of Storyboarder?

**Comment by Toorah** [comment]
It works now, thanks.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Eric Skogen <notifications@github.com> Datum: 13.07.19  16:46  (GMT+01:00) An: wonderunit/storyboarder <storyboarder@noreply.github.com> Cc: Toorah <tugratoorah@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [wonderunit/storyboarder] Shot Generator does not open on Surface Book 2 (#1715) Can you try again with the latest version of Storyboarder?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wonderunit/storyboarder/issues/1715?email_source=notifications\u0026email_token=AB5NTQOINRMPAKK25EO6WDDP7HTDVA5CNFSM4H7MAHF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ3S7VA#issuecomment-511127508",
"url": "https://github.com/wonderunit/storyboarder/issues/1715?email_source=notifications\u0026email_token=AB5NTQOINRMPAKK25EO6WDDP7HTDVA5CNFSM4H7MAHF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ3S7VA#issuecomment-511127508",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
