### ISSUE TITLE
GLB import doesnt import full environment

### ISSUE THREAD

**Issue by pearnold** [wonderunit/storyboarder#1716]
The provided glb file opens just fine in windows 3d-viewer, but only imports the pillows and the window thing in the shot generator.

System is Windows 10 1803
Storyboarder v1.12.0
Blender 2-80

[Bedroom.zip](https://github.com/wonderunit/storyboarder/files/3376950/Bedroom.zip)

Blender:
![blender](https://user-images.githubusercontent.com/23722222/60961043-9322a600-a30b-11e9-927f-4b2391f0024c.JPG)

Windows-3d-Viewer:
![windows-viewer](https://user-images.githubusercontent.com/23722222/60961045-9322a600-a30b-11e9-8850-d5b2c340ae6b.JPG)

Shot-Generator:
![shot-generator](https://user-images.githubusercontent.com/23722222/60961044-9322a600-a30b-11e9-806e-a53983eaa2f1.JPG)

**Comment by setpixel** [comment]
Yes - we should fix this soonish!  Currently I think we are bringing in the first set of child objects. We need to bring in all of them. 

BTW... your scale is way way off. Your walls are 10 meters tall.

**Comment by setpixel** [comment]
also, your scene is 20k polys which is kinda crazy for how simple the scene is.. but it just means that your framerates will be slow while editing.

**Comment by audionerd** [comment]
The next release of Storyboarder should fix this bug.

While debugging, I did notice some problems with the `.glb` file attached (the walls weren't importing the way I'd expect). Not sure what the issue was. I had to import it in Blender 2.8 and re-export, then it worked.

So try that once the new Storyboarder release is out :)

**Comment by pearnold** [comment]
Thanks a lot for fixing :)
