### ISSUE TITLE
Eraser sometimes erases all

### ISSUE THREAD

**Issue by Toorah** [wonderunit/storyboarder#1718]
**Describe the bug**
When using the back of my stylus to erase on a board which has content from the Shot generator, I can easily erase my extra drawn content. However if I explicitly select the eraser and use the front of my stylus, then it erases the entire image including the shot generator content (going to white).

**To Reproduce**
1. Select eraser with a Stylus
2. Use the front of the Stylus to draw
3. See error

**Expected behavior**
Only drawn lines should erase, not the Shot generator content in the back

**Screenshots**
![image](https://user-images.githubusercontent.com/8051137/61175054-933fd180-a5a9-11e9-834e-cd3ee004d047.png)

**Desktop:**
 - OS: Windows 10; Microsoft Surface Book 2

**Comment by audionerd** [comment]
I don't think this is a bug.

When the Eraser tool is selected, it erases all layers. For other tools, hold the option/alt key while drawing to erase from only that tool's layer.

This is explained in the tooltip for the Eraser tool.
