### ISSUE TITLE
Missing and model-related issues

### ISSUE THREAD

**Issue by thevalo** [wonderunit/storyboarder#1720]
After the last update (to 1.13) I can see that some built-in models are missing, such as this tree:

![009](https://user-images.githubusercontent.com/28608203/61210776-d4e19100-a6fd-11e9-8ebe-557879f8a639.png)

Also, where can I find skinned mesh model that fit well into Storyboarder? I really can't seem to find them.

**Comment by audionerd** [comment]
Tree was removed from the main model list, but you can add it as a custom model if you like.

There is a library of model files here:
https://github.com/wonderunit/shot-generator-models
