### ISSUE TITLE
AppImage Only Launches Manually via Konsole and Only If The Flag '--no-sandbox' Is Applied

### ISSUE THREAD

**Issue by esotericDisciple** [wonderunit/storyboarder#1722]
Otherwise, the app goes (when launching from Konsole) (On Manjaro):
"
[360:0715/142003.509989:FATAL:setuid_sandbox_host.cc(157)] 
 The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_StorybX21EnK/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
"

...And how much of my privacy am I jettisoning in running an app that's so codependent on chrome like this?

**Comment by setpixel** [comment]
we can't really support linux since we dont use it.

privacy? no idea. electron is open source and so is chromium. so you could either trust in that or f off?

**Comment by audionerd** [comment]
@esotericDisciple You could try the Snap package instead, which might be configured to run without the sandbox flag? This is an Electron issue. More info here: https://github.com/electron/electron/issues/17972

**Comment by esotericDisciple** [comment]
@setpixel have you not heard of 'ungoogled-chromium?'

**Comment by setpixel** [comment]
i havent heard of it, but we use plain vanilla electron, so we are at their mercy

**Comment by esotericDisciple** [comment]
> @esotericDisciple You could try the Snap package instead, which might be configured to run without the sandbox flag? This is an Electron issue. More info here: [electron/electron#17972](https://github.com/electron/electron/issues/17972)

Snap tends to have too messy a directory structure, but I can edit the desktop file for the appimage to include the --no-sandbox flag

**Comment by setpixel** [comment]
https://github.com/electron/electron/issues/14784
