### ISSUE TITLE
PC - Java Script Error

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#173]
Get this when ever I open app

![2017-04-26_3-14-28_sb-java error](https://cloud.githubusercontent.com/assets/14130545/25436876/98b92fd6-2a62-11e7-835d-af7f6603dcf8.jpg)

**Comment by setpixel** [comment]
Question: do you have two versions of storyboarder open?

**Comment by setpixel** [comment]
Does this still happen? Reopen if it does
