### ISSUE TITLE
Unable to open app with my script (script is a fountain file)

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#174]
The app did create the "storyboard" folder with the below contents.

![2017-04-26_9-36-21](https://cloud.githubusercontent.com/assets/14130545/25437289/db4f3006-2a63-11e7-961f-5d0b82e0a3d4.jpg)

NOTE: I'm running Windows 7

**Comment by setpixel** [comment]
Can you send me the fountain file?
