### ISSUE TITLE
Hard to tell what brush I have selected

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#175]
If i look away, i cant easily tell what tool i have selected easily by just glancing  at them.

 I would draw , see i had the wrong tool selected, undo what i did, and then select the correct tool.

some rough samples of what may help. The top sample is what it is now. 

![2017-04-26_9-48-14](https://cloud.githubusercontent.com/assets/14130545/25438907/d74b09b2-2a68-11e7-8702-ab0c97344ab9.jpg)

**Comment by setpixel** [comment]
Ok - At first I wanted to: ![image](https://media.giphy.com/media/GODSCQebffJzW/giphy.gif)

But we will make the other tools darker.
