### ISSUE TITLE
no place to enter text for automatic shot generation v 1.13.0

### ISSUE THREAD

**Issue by dwdragon-x** [wonderunit/storyboarder#1750]
Hi,
I've got windows 10 pro and storyboarder 1.13.0  I can't see any place to enter the text for automatic shot generation in the shot generator sidebar (ex "close up" etc).  I've attached screen shots showing what I see in the interface as I scroll down.  There's an arrow at the bottom of the shot generator sidebar, but nothing happens when I click on it.  This feature is what attracted me to this software, and I'd love to be able to use it.  I must be missing something!  Any help is greatly appreciated  :)

![image](https://user-images.githubusercontent.com/53650466/62411341-5fac0200-b5bf-11e9-927f-bbd3444a2e55.png)
![image](https://user-images.githubusercontent.com/53650466/62411353-82d6b180-b5bf-11e9-965a-b0441df10c51.png)
![image](https://user-images.githubusercontent.com/53650466/62411357-8b2eec80-b5bf-11e9-8472-2aa0dddef093.png)
![image](https://user-images.githubusercontent.com/53650466/62411360-93872780-b5bf-11e9-9a6c-f87f8f909a40.png)

**Comment by audionerd** [comment]
The “describe a scene” feature to generate a shot automatically was removed when Shot Generator was redesigned.
You can edit a Shot Generator shot manually now by clicking the thumbnail in the sidebar to open the editor.

If you like the old feature, you could install an older release of Storyboarder. The shots it creates will not be compatible with newer versions however.

**Comment by dwdragon-x** [comment]
Thanks!
