### ISSUE TITLE
Would like a harder edge for the "brush" tool

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#176]
Would like a harder edge for "brush" tool.

If a soft edge is needed, maybe add an "airbrush" tool or have a slider to control edge softness.

![2017-04-26_10-38-29](https://cloud.githubusercontent.com/assets/14130545/25440557/cc7e502a-2a6d-11e7-9deb-0efafa0c3e8f.jpg)

**Comment by setpixel** [comment]
Agreed - we will change for the next build.

**Comment by setpixel** [comment]
Fixed!
