### ISSUE TITLE
Y and Z axis

### ISSUE THREAD

**Issue by ChrisAtNKU** [wonderunit/storyboarder#1794]
This isn't a bug as much as a mis-labeling. In the shot generator the Y and Z axis are incorrectly labeled. Z should be dealing with the depth on the screen (it is currently the vertical axis) and Y should be the vertical, but is labeled as the depth. Beyond that, we appreciate the update - the details and control make the software even more useful.

**Comment by setpixel** [comment]
it's intentional. we think of x,y as floorplan and z as height. blender uses this notation as well.

**Comment by ChrisAtNKU** [comment]
Oh, OK. Huh. That's just opposite a typical filmmaker storyboard orientation, which follows the traditional geometry coordinates of x=horizontal, y=vertical, and z=depth.

**Comment by setpixel** [comment]
:D i'm sure you'll live

**Comment by ChrisAtNKU** [comment]
Yeah, sure. We'll live. But to choose Blender's orientation over what is the wider understanding of coordinates is certainly, well, a...choice. :-)

**Comment by setpixel** [comment]
yeah - im sure you guys know what it's like at north korea university.

**Comment by ChrisAtNKU** [comment]
Not sure why a suggestion about the use of basic screen coordinates became a name calling thing. I mean, I get the attitude that you curate and project on the software's website and that may be part of your brand, but not sure why trying to insult a user would be even close to useful.

**Comment by setpixel** [comment]
you brang the snark bitch, just serving it back

**Comment by ChrisAtNKU** [comment]
Dude. Really? Yes, I disagree with your choice on how you're portraying the X, Y and Z axis coordinates in your software. Just not how the film world deals with them. Seems like that would be somewhat important for some storyboarding software. But, whatever.

**Comment by ChrisAtNKU** [comment]
I should have included this above, but I was a bit taken aback by the interaction’s shift in tone. Perhaps how the coordinates are labeled are a preference - Blender or Maya style. But maybe not - it is your software. Regardless, as I stated in the first message, you and your team have created a nice tool that helps filmmaking teams plan and pre-vis. We appreciate what it does.

**Comment by setpixel** [comment]
sorry dude - i hear you. maybe we can make a label change in the future.
