### ISSUE TITLE
Easier way to upload photo reference feature with phone

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#180]

**Comment by setpixel** [comment]
What do you mean by easier?

**Comment by Soba77** [comment]
App sets it up for you , 

 press of  a button and finds your ip address. gives a little tutorial, etc

 A way a non-tech person can get set up.

**Comment by setpixel** [comment]
This is a new feature not finished yet. Will be part of a larger feature.

**Comment by setpixel** [comment]
This will be fixed with photo importing/worksheets
