### ISSUE TITLE
Storyboarder is Recording Me Despite Not Having Permission?

### ISSUE THREAD

**Issue by azraylpughcook** [wonderunit/storyboarder#1801]
I have bluetooth earbuds. I want to listen to my music. Upon opening Storyboarder, the music fades to a quiet low quality background noise and if I move my finger across the microphone on my earbuds I can hear noise from the friction in my earbuds, as if it recording me and playing it back to me. I changed my computer settings to disallow Storyboarder access to my microphone but upon restarting the application it is still happening. I do not see any option to stop this in the program's preferences. Is Storyboarder recording me against my wishes? I just want to listen to my music while I work. 
<img width="650" alt="Screen Shot 2019-09-21 at 10 40 08 AM" src="https://user-images.githubusercontent.com/55628520/65374836-691b2780-dc5c-11e9-8a47-a286250490e7.png">

**Comment by audionerd** [comment]
Storyboarder will only record audio with permission. You can press a button in Storyboarder’s side panel to intentionally record brief audio from a microphone to add to a board. But Storyboarder won’t record on its own.

There is a problem however that Storyboarder initializes audio input on startup so it’s ready to record. It should be changed to only initialize audio input when you actually need it. This is a known bug we plan to fix.

**Comment by audionerd** [comment]
Related https://github.com/wonderunit/storyboarder/issues/1119
