### ISSUE TITLE
1.13 Issues - NO IK in VR, NO PS Controller

### ISSUE THREAD

**Issue by thelanj** [wonderunit/storyboarder#1802]
1.13 on Mojave 10.14.6

- IK control points show up in shot generator, but not in shot generator VR.
- PS Controller doesn't work anymore

Love what you're creating, please let us know how we can support you in continuing to develop this project!

**Comment by setpixel** [comment]
hi!

haha - actually, ik isn't in VR yet. BUT it is totally the thing we are working on RIGHT NOW, literally! As well as a COMPLETE vr rewrite. The framerate should be buttery smooth in the next version.

ps controller is an unfortunate issue. we depend on an external library for that. the guy that makes it is slow to update his binaries so we could include for the last release.
