### ISSUE TITLE
Lose drawing when using "Fill" tool

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#181]
![2017-04-26_11-09-03](https://cloud.githubusercontent.com/assets/14130545/25442111/24c76862-2a72-11e7-8f3f-b68c7d88b7d6.gif)

The way fill works now is too destructive to the drawing I feel.

If I want the entire canvas  to be filled, I would clear it first. 
I would find the bottom two results in the below sample image acceptable.

![2017-04-26_11-13-09](https://cloud.githubusercontent.com/assets/14130545/25442366/dca85f0e-2a72-11e7-85cc-de79450b0fb6.jpg)

**Comment by setpixel** [comment]
Fill layer using globalcompositeoperation like 'screen' or other
