### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Vista1942** [wonderunit/storyboarder#1828]
I reordered a panel while it was still connected to the Shot Generator. It gave the error:
  Uncaught TypeError: Cannot read property 'parentNode' of null
  In File: C:\Program Files\Storyboarder\resources\app.asar\node_modules\tether-drop\dist\js\prop.js#423:24

After that error, the storyboard could not be edited. Has to start a new storyboard from the very begining.

**Comment by audionerd** [comment]
Thanks for the report. Should be fixed in an upcoming release.
