### ISSUE TITLE
Shot Generator: Character can't be posed when a secondary camera is selected

### ISSUE THREAD

**Issue by eAi** [wonderunit/storyboarder#1852]
**Describe the bug**
When a second camera is active, characters can't be posed. Dragging the rotation handle has no effect.

**To Reproduce**
1. Create a Board
2. Open the Shot Generator
3. Add a character
4. Select a bone on the character and drag the rotate handle to try to rotate it - it should work.
5. Add a second camera
6. Select a bone on the character and try to drag the rotate handle. Notice that it doesn't do anything.
7. Drag Camera 2 on top of Camera 1 in the top-down view.
8. Select Camera 2
9. Select a bone and try to rotate it. Notice that this now works (how effectively this works depends how precisely the two cameras are overlaid over each other).

**Expected behavior**
Bone rotation handles always work, whatever camera is selected.

**Desktop (please complete the following information):**
OS: macOS 10.14.6
Storyboarder version: 1.15.0

**Comment by eAi** [comment]
Based on Steps 7 - 9, this is presumably because the rotation handle interaction code is always using the first camera's transform.

**Comment by setpixel** [comment]
@VladStepura we should fix this...

**Comment by AVTConnect** [comment]
Thanks for fixing this in the latest version!

**Comment by setpixel** [comment]
@AVTConnect you're welcome! @eAi should be fixed now in v1.17.0
