### ISSUE TITLE
Feature requests: Shot generator Lock/Freeze objects and Undo-button in VR

### ISSUE THREAD

**Issue by JonasEditH** [wonderunit/storyboarder#1866]
When working in the shot generator (especially in VR), we often move or rotate things by accident. 
It would be real nice to be able to lock/freeze certain objects while being able to modify other objects.
Either that, or an undo-button in VR would be great too!

Thanks for an awesome software!

**Comment by VladStepura** [comment]
Hi! You actually can undo/redo in VR by pressing A/B buttons accordingly. Also, feature to lock objects is currently in progress so it will be available soon.
