### ISSUE TITLE
A more friendly dialoged captions

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#188]
I think the all uppercase makes it hard to read. Also maybe a different font.

Some samples of other caption styles

![2017-04-26_13-18-22](https://cloud.githubusercontent.com/assets/14130545/25449932/5b2a6210-2a8b-11e7-9bca-58c978f55b76.jpg)

**Comment by setpixel** [comment]
I think its ok 
![image](https://media.giphy.com/media/GODSCQebffJzW/giphy.gif)
