### ISSUE TITLE
Can't find guides?

### ISSUE THREAD

**Issue by Costello8** [wonderunit/storyboarder#197]
I'm not sure if it's staring me in the face and I just can't see it, or if it's a feature that will be added later, or whether it's something specific to the Darwin build but I can't turn on the guidelines (the onion skin or reference layer for example)? Otherwise ,it's great — I like it a lot, thank you!

**Comment by setpixel** [comment]
Are you in the newest build? If so, can you post a screenshot?

**Comment by Costello8** [comment]
Thanks for the prompt reply. 
Yes, I think it is — 0.2.0.dmg — that was released a few days ago?
Here's a screenshot (I'm running macOS 10.12.3).
<img width="1221" alt="screen shot 2017-04-27 at 07 20 43" src="https://cloud.githubusercontent.com/assets/27743678/25470648/0aaca146-2b1b-11e7-9894-2c4edad77cc8.png">
Thanks for your help.

**Comment by setpixel** [comment]
Thanks a lot.. I see the issue. What kind of computer are you on? Retina macbook?

**Comment by Costello8** [comment]
Hi, yes, it's a Retina Macbook, 13 Inch. I have a 15 inch Retina Macbook book — I can try on that too if it helps.

**Comment by setpixel** [comment]
We should add them to the View menu to toggle. Also we should scale the view for small retina displays.

**Comment by Costello8** [comment]
It still works great in the meantime — but thanks!

**Comment by setpixel** [comment]
Fixed! Added to the menu.

**Comment by Costello8** [comment]
Oh, this is great! Lots of nice improvements and features. Improved performance. Sounds are great. This is a lot of fun — thanks for this!

**Comment by setpixel** [comment]
Thanks!!! Please keep submitting issues / feedback! It helps us know what to work on next.
