### ISSUE TITLE
pdf file will not import; Storyboarder asks for a layer

### ISSUE THREAD

**Issue by dilarababy** [wonderunit/storyboarder#1986]
When I try to import or drag and drop a PDF image into a new board into Storyboarder, I get the following message.

<img width="338" alt="Screen Shot 2020-04-30 at 6 17 29 PM" src="https://user-images.githubusercontent.com/64616400/80764619-1d443100-8b0f-11ea-8929-4c066d253ef5.png">

I have added a layer and named it Reference, I have called the image layer Reference, I have put a layer named reference above and below the image layer... I just keep getting the above message.

Any ideas? are vectors an issue? I was not having this problem with the raster version of the same image, but needed the image to be vector.)

THX

**Comment by audionerd** [comment]
Storyboarder will import JPG, PNG, or PSD, but it won’t import PDF. You’ll need to convert the PDF to one of the accepted formats.

**Comment by dilarababy** [comment]
I did just try with a pdf As well and got the same message. However, thank you I had not found acceptable import file formats for Storyboarder listed anywhere. I will try again tomorrow and see if there’s something I’m missing.
