### ISSUE TITLE
Save as... function not working

### ISSUE THREAD

**Issue by streamlabtech** [wonderunit/storyboarder#1987]
**Describe the bug**

I am trying to save a new version of a storyboard.  "Storyboard v02" for example.  When I use "save as..." function and save to the same location, I get the following error...

ENOENT: could not find source file /Volumes/SL2018-01 RAID/SL2018-01 PART 3/SL2020-013 - NVM - Console Vault Demos/01 Production Documents/Storyboards/CV SBs 04/Console Vault SBs v02-2020-05-04 05.12.03/images/board-2-D6VPL-camera-plot.png

I've tried the same location, making a new folder, etc. Nothing seems to work.

**To Reproduce**
1. File > Save as...
2. then I get error
3. See below...

It does create the new version with a new folder, but none of the content or links seem to move over with it.  When I open the new version it shows the first board and that's it.

**Expected behavior**

Just make a new version, make correct links to assets and open the next version
I need to version my changes.  Not just have one constantly changing original version.

**Screenshots**

<img width="587" alt="Screen Shot 2020-05-04 at 5 34 24 PM" src="https://user-images.githubusercontent.com/64811282/81015997-a8823700-8e2d-11ea-8cc2-80848543f280.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.13.3 iMac 2017 27"
Google Chrome
Google Chrome is up to date
Version 81.0.4044.129 (Official Build) (64-bit)

Really cool product!  Thanks for your help!

**Comment by streamlabtech** [comment]
Follow up...

These errors were generated on the side after trying to open a Save As version of file:

<img width="331" alt="Screen Shot 2020-05-04 at 6 21 17 PM" src="https://user-images.githubusercontent.com/64811282/81019249-46790000-8e34-11ea-8d61-6428afeb7241.png">

**Comment by streamlabtech** [comment]
Finally,  I downloaded the "Ducks" storyboard and was able to do a save as and increment the versions.  What am I doing wrong with my version?  Is it because of the PSD file edits?  That's seems to be what missing.  Thanks

**Comment by audionerd** [comment]
Can you send us a copy of the project that is causing the error?

Does the project have any boards created with Shot Generator? Were they possibly created with an older version of Shot Generator?

I think the problem is, the project copying code expects _all_ Shot Generator-created boards to _always_ have camera plot image files, and if any of them don't, it will throw an error.

You might be able to work around this by re-opening and re-saving each of the Shot Generator boards.

**Comment by audionerd** [comment]
Related to https://github.com/wonderunit/storyboarder/issues/1155
