### ISSUE TITLE
PC - Drawing issues

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#199]
- Drawing very laggy. (work way better after restarting app)

- Not able to draw Short strokes well. often the stoke would not appear. Makes it hard to draw small and draw details

- Stroke would some times die during mid stroke, and tapering to a point

![2017-04-27_7-53-32](https://cloud.githubusercontent.com/assets/14130545/25483259/1a9add22-2b23-11e7-8903-25cc890122e4.jpg)

![2017-04-27_7-55-57](https://cloud.githubusercontent.com/assets/14130545/25483271/20f1828e-2b23-11e7-849a-ca3f696de786.jpg)

![2017-04-27_8-06-09](https://cloud.githubusercontent.com/assets/14130545/25483278/2559e0f0-2b23-11e7-9c37-b7d075808a43.jpg)

**Comment by setpixel** [comment]
I think this has to with with Windows Ink. We see this on the PC here. 

Also @audionerd says that we should profile the app to check for memory leaks - but I dont think this is the issue here. I think its the Wacom support on Windows.

**Comment by setpixel** [comment]
duplicate #194
