### ISSUE TITLE
Web VR not supported

### ISSUE THREAD

**Issue by fekodeluxe** [wonderunit/storyboarder#1999]
Just wanted to try out the amazing VR features of Storyboarder v1.18 - but my occulus and fire fox vr browser display 'WebVR not supported'.
What can I do?
Or what am I doing wrong?

Keep up the great work!

**Comment by SatishGodaPearl** [comment]
I am seeing the same issues too with the latest updates to Oculus Browser.

Thank you,
Satish.

**Comment by SatishGodaPearl** [comment]
Nevermind. Looks like this issue was already logged at https://github.com/wonderunit/storyboarder/issues/1958

**Comment by audionerd** [comment]
We’re working on an update that will use WebXR instead of WebVR. Code is done actually, just working on the release. Should be out soon.

Dupe of https://github.com/wonderunit/storyboarder/issues/1958

**Comment by SatishGodaPearl** [comment]
Thank you for the update Eric :)
