### ISSUE TITLE
Feature request: Flip/mirror boards

### ISSUE THREAD

**Issue by JonasEditH** [wonderunit/storyboarder#2004]
**Feature request**
When working creatively, we often flip/mirror images in order to view it from a different perspective.

It would be great to have a **neat little button to flip a board!**

Thanks! :)

**Comment by audionerd** [comment]
You can flip a board image horizontally/vertically from the Tools menu. Is that what you’re looking for?

**Comment by JonasEditH** [comment]
Yes, exactly this! Thank you so much. I abolsutely love this software. :)
