### ISSUE TITLE
Playback and Dialogue

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#201]
- Weird bug, Two boards with Dialogue playing back to back. 
The second  board would not play/mute its dialogue ( Note: it did show its caption). 

If I create a new blank board in-between the boards, it fixed the problem ,but now i have a blank board in the middle. Coping, duplicating, or deleting the original boards did not help. 

My fix/cheat, 
was to create the new blank board between them. open the blank board in Photoshop, then copy the contents of the second board  into the bank board; save; and in the app and set it to a duration of .5 sec. 

- During playback, when reaching the last board which  happen to have had dialogue. This single board would be looped, repeating the dialogue infinitely, like a broken record.
EG - Reach last board; play dialogue "The End"; then it would keep reading "the End", "The End", "The,...

**Comment by setpixel** [comment]
I think we want the ability to mute robovoice altogether.

**Comment by setpixel** [comment]
Speaking playback is off by default now.. you have to toggle it on.
