### ISSUE TITLE
"Open in Photoshop" button

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#202]
ability to utilize Photoshop quickly.

In Storyboarder;
Select board(s);
"Click" button;
File(s) open in PS;
Make adjustments in PS;
Save in PS;
File(s) update in Storyboarder;
Go back to Storyboarder

**Comment by deomacius** [comment]
It would be great if the user had the ability to specify an alternate external editor like Affinity Photo or Sketchbook as well as PhotoShop.

**Comment by setpixel** [comment]
for reference: https://github.com/Agamnentzar/ag-psd

**Comment by garyritchie** [comment]
@deomacius I quickly solved this by telling my OS to use a different default editor for PNG but, I agree, it would be nice to simply set a path to my editor in the prefs window/file.

**Comment by setpixel** [comment]
Just so everyone knows, the plan is to actually create a layered photoshop document and that will be the working file for the document. When you edit the board and save, Storyboarder will pick up the changes and update the board. It's just a hack ATM.
