### ISSUE TITLE
Properties in Shot Generator impossible to access on smaller screens

### ISSUE THREAD

**Issue by Doolien** [wonderunit/storyboarder#2021]
Hello, firstly congratulations on the release of Storyboarder 2.0! I've really enjoyed using it and it has become a real lifeline for my students who used it to visualise their films during lockdown. 
The update brings loads of new functions, BUT some can't access the Properties panel, as when you have 4+ elements inserted, the Properties bar is too small to be of any use (see image) 
![image](https://user-images.githubusercontent.com/66066419/83132799-d62f6880-a0d9-11ea-8cd5-14e4eac09f0f.png)
.... and this is only after I changed my Windows settings to hide the Taskbar. 

Could the Properties panel rather be a floating panel? 

best
Julien

**Comment by audionerd** [comment]
Should be fixed now in Storyboarder 2.0.1.

**Comment by Doolien** [comment]
That's great to hear! Thank you very much for fixing this
