### ISSUE TITLE
Could not parse Final Draft data

### ISSUE THREAD

**Issue by UlrichThomsen** [wonderunit/storyboarder#2041]
anyone knows what this is?

![Screenshot 2020-06-14 at 20 33 24](https://user-images.githubusercontent.com/66775717/84601161-9e1c7980-ae7e-11ea-8528-1fd3909066f6.png)

**Comment by audionerd** [comment]
Can you send us a copy of the Final Draft script? Can you send us the log file?

Log file location is:
on Linux: ~/.config/Storyboarder/logs
on macOS: ~/Library/Logs/Storyboarder
on Windows: %USERPROFILE%\AppData\Roaming\Storyboarder\logs

**Comment by UlrichThomsen** [comment]
I don't have this 

 ~/Library/Logs/Storyboarder

I have : ~/Library/Logs — and then a bunch of other folders 

Med venlig hilsen / Best regards

Ulrich Thomsen

PRO TEMPORE FILM APS <https://www.facebook.com/pg/gutterbeefilm/posts/?ref=page_internal>


Sales Pro Tempore Film
salesptf@gmail.com

**Comment by UlrichThomsen** [comment]
Whoops looked under wrong string 



Med venlig hilsen / Best regards

Ulrich Thomsen

PRO TEMPORE FILM APS <https://www.facebook.com/pg/gutterbeefilm/posts/?ref=page_internal>


Sales Pro Tempore Film
salesptf@gmail.com

**Comment by audionerd** [comment]
Can you upload the script and the log to this issue page? https://github.com/wonderunit/storyboarder/issues/2041

It won’t come through via email.

**Comment by UlrichThomsen** [comment]
What won’t come through ?

Med venlig hilsen / Best regards

Ulrich Thomsen

PRO TEMPORE FILM APS <https://www.facebook.com/pg/gutterbeefilm/posts/?ref=page_internal>


Sales Pro Tempore Film
salesptf@gmail.com

**Comment by UlrichThomsen** [comment]
If I drag the FDX file to the here  #2041 <https://github.com/wonderunit/storyboarder/issues/2041> it won’t accept that file format.

Med venlig hilsen / Best regards

Ulrich Thomsen

PRO TEMPORE FILM APS <https://www.facebook.com/pg/gutterbeefilm/posts/?ref=page_internal>


Sales Pro Tempore Film
salesptf@gmail.com

**Comment by audionerd** [comment]
try making a zip of it

**Comment by UlrichThomsen** [comment]
[Untitled 4.fdx.zip](https://github.com/wonderunit/storyboarder/files/4777075/Untitled.4.fdx.zip)
[log.log](https://github.com/wonderunit/storyboarder/files/4777076/log.log)

**Comment by UlrichThomsen** [comment]
Done now. Made a gibberish FDX file. And it does the same as the real length script, so I presume it’s the same error.  

Med venlig hilsen / Best regards

Ulrich Thomsen

PRO TEMPORE FILM APS <https://www.facebook.com/pg/gutterbeefilm/posts/?ref=page_internal>


Sales Pro Tempore Film
salesptf@gmail.com

**Comment by UlrichThomsen** [comment]
Even a complete blank FDX file does it 

Med venlig hilsen / Best regards

Ulrich Thomsen

PRO TEMPORE FILM APS <https://www.facebook.com/pg/gutterbeefilm/posts/?ref=page_internal>


Sales Pro Tempore Film
salesptf@gmail.com
