### ISSUE TITLE
IMPORT ERROR using sketchbook as external editor

### ISSUE THREAD

**Issue by Ethanblah** [wonderunit/storyboarder#2048]
![storyboarder error](https://user-images.githubusercontent.com/67466955/85855342-04be6300-b7ae-11ea-9eb8-a43b45be2ab3.jpg)

Hi, I get an import error when using sketchbook as the external editor - see image. It works fine with an old version of photoshop (CS6) just wondered if anyone else has this problem - sketchbook is my go to for sketching and storyboarding. Storyboarder is a great program, just need to get it working with sketchbook.
cheers Ethanj

**Comment by junefish** [comment]
Experiencing the same issue.

**Comment by Ethanblah** [comment]
Hi Junefish, well, it's not just me then. Do you get this error with any other external editor software, or just sketchbook? - trying to work out if it's an issue with sketchbook.
Neil

**Comment by junefish** [comment]
I don't think I have any other software that can open .psd files - happy to download and try if there are any free ones.  (I don't have photoshop.)

**Comment by audionerd** [comment]
Thanks for the report. Tracking this issue at #2100 now.
