### ISSUE TITLE
More quotes/ tips

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#205]
Add some quotes/ tips artist old and new, from various. 

EG- Glenn Keane, Leonardo da vinci, Sid Mead, etc,

**Comment by setpixel** [comment]
Can you add the quotes you want in this format: https://github.com/wonderunit/storyboarder/blob/master/src/data/messages.json

**Comment by setpixel** [comment]
So a text file that looks like a bunch of these:

    {
      "type": "quote",
      "message": "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
      "author": "Thomas Edison"
    },

**Comment by setpixel** [comment]
Do you want to compile a list of quotes?

**Comment by Soba77** [comment]
“We don’t make mistakes, just happy little accidents” -Bob Ross


“As my artist’s statement explains, my work is utterly incomprehensible and is therefore full of deep significance” -Calvin from Calvin &Hobbes


“Have no fear of perfection, you’ll never reach it” – Salvador Dali


“You can’t wait for inspiration, you have to go after it with a club” – Jack London

“Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last, you create what you will” – George Bernard Shaw


“Creativity is more than just being different. Anybody can plan weird; that’s easy. What’s hard is to be as simple as Bach. Making the simple, awesomely simple, that’s creativity” – Charles Mingus


“You see things; and you say, ‘Why?’ But I dream things that never were; and I say, ‘Why not’?” – George Bernard Shaw


“Creativity is contagious, pass it on” – Albert Einstein


“The older get, the more I look at movies as a moving miracle. Audiences are harder to please if you’re just giving them special effects…but they’re easy to please if it’s a good story.” – Steven Spielberg


“If it can be written or thought, it can be filmed.” – Stanley Kubrick
 

“If a million people see my movie, I hope they see a million different movies.” – Quentin Tarantino


“I was frustrated because I just kinda didn’t know what I was here for. I didn’t know why I was put on this earth.

"I think other filmmakers are inherently more brilliant than me, but I know I can work harder than they can.” – James Cameron

“I think people who have faults are a lot more interesting than people who are perfect.” – Spike Lee


“You have to find something that you love enough to be able to take risks.” – George Lucas


"If you're going to have a story, have a big story, or none at all." --Joseph Campbell


"There is no greater agony than bearing an untold story inside you." --Maya Angelou


"There's always room for a story that can transport people to another place." --J.K. Rowling


"Believe the impossible is possible."  _Glen Keane


"I thought of the character being real, a living person, not a drawing." -Ollie Johnston


"James Baxter!" horse, Adventure Time


"If it’s a good movie, the sound could go off and the audience would still have a perfectly clear idea of what was going on.” -Alfred Hitchcock


"I want to push technology boundaries to be more efficient." _ Robert Rodriguez

"I do not make films primarily for children. I make them for the child in all of us, whether we be six or sixty." -WALT DISNEY

**Comment by setpixel** [comment]
You can add way more if you want, there are like 300 already in there. Either way, I'll add these! Thanks!!!!!!

**Comment by Soba77** [comment]
“Fiction is the truth inside the lie.” -Stephen King

“Let me say it again: You must not come lightly to the blank page.” -Stephen King

“Life isn’t a support system for art. It’s the other way around.” –Stephen King

“The miracle is this: the more we share the more we have.” -Leonard Nimoy

“Insufficient facts always invite danger.” -Leonard Nimoy

“As a street artist, I'm used to sharing my stuff with the public. It's a communal experience. I've learned not to be so precious, but rather to enjoy the process.”  -Shepard Fairey

“The way I make art, the way a lot of people make art, is as an extension of language and communication, where references are incredibly important.” -Shepard Fairey

"Don’t count the days; make the days count." -Muhammad Ali

“It isn’t the mountains ahead to climb that wear you out; it’s the pebble in your shoe.” -Muhammad Ali

“I need to have my hands on the DNA of a film.” -Kathryn Bigelow

“You can't do it unless you can imagine it.” –George Lucas

“Storytelling is about two things; it's about character and plot.” –George Lucas

“Digital technology allows us a much larger scope to tell stories that were pretty much the grounds of the literary media.”  –George Lucas

“A fool thinks himself to be wise, but a wise man knows himself to be a fool.” –William Shakespeare
“Better three hours too soon than a minute too late.” –William Shakespeare

“According to the song, Rudolph’s nose is shiny, which means it reflects rather than emits light. Useless for navigating fog.” — Neil deGrasse Tyson

“Just to settle it once and for all: Which came first the Chicken or the Egg? The Egg — laid by a bird that was not a Chicken” Neil deGrasse Tyson

“Just an observation: I’ve never, ever, ever, ever, ever, heard a female voice as the narrator of a movie trailer.” — Neil deGrasse Tyson

“Everybody can draw, in my estimation. If you give a man 50 years, he'll come up with the Mona Lisa.” - Jack Kirby

“I'm a fan of animation and so, the more stuff that doesn't look like the other stuff that's out there, I'm in favor.” - Matt Groening

“This cosmic dance of bursting decadence and withheld permissions twists all our arms collectively, but if sweetness can win, and it can, then I'll still be here tomorrow to high-five you yesterday, my friend. Peace.” ― Pendleton Ward, Adventure Time Vol. 1

“The thing about any character is that you want to be sincere.” - Genndy Tartakovsky

“As for me, I am in pursuit of excellence. I have no time to get old.” - Will Eisner
“Works of art make rules; rules do not make works of art.” -CLAUDE DEBUSSY

“Art is the concrete representation of our most subtle feelings.” -AGNES MARTIN

“Art is not what you see, but what you make others see.” -EDGAR DEGAS

“Where the spirit does not work with the hand, there is no art.” - LEONARDO DA VINCI

“I found I could say things with color and shapes that I couldn't say any other way - things I had no words for.” -GEORGIA O'KEEFFE

“A good story cannot be devised; it has to be distilled.” - RAYMOND CHANDLER

"Artists should always think of themselves as cosmic instruments for storytelling." - TED LANGE,

“People have forgotten how to tell a story. Stories don't have a middle or an end any more. They usually have a beginning that never stops beginning.” - STEVEN SPIELBERG

“Storytelling is the most powerful way to put ideas into the world today.” -DONALD DAVIS

“You can fix anything but a blank page.” - NORA ROBERTS

“Visual storytelling of one kind or another has been around since cavemen were drawing on the walls.” -FRANK DARABONT
