### ISSUE TITLE
Clip Studio

### ISSUE THREAD

**Issue by UlrichThomsen** [wonderunit/storyboarder#2080]
trying to open clip studio instead of Photoshop. it doesn't seem to work. Clip Studio does open but doesn't drag the character from Storyboarder over.   I have fully functional TRIAL version of Clip Studio

**Comment by elazinsu** [comment]
I have clip studio and don't have the issue, what is the path you choose for your software

**Comment by UlrichThomsen** [comment]
fixed it. there's the app file and then the exe file . the exe file opens it. and it works. thank though
