### ISSUE TITLE
Dude the worksheet thing doesn't work

### ISSUE THREAD

**Issue by vxfmatt** [wonderunit/storyboarder#210]
When I try with my printer hooked up, it decides OH NO THANKS MAN IM JUST GONNA MAKE YOU DRAW WITH A GOD DAMN MOUSE INSTEAD OF THE MORE EFFICIENT EASIER WAY OF USING A PEN

and yea

**Comment by setpixel** [comment]
haha yeah - will be done in less than a month!

**Comment by vxfmatt** [comment]
thank you

**Comment by vxfmatt** [comment]
WAIT WHAT BETA 5 IM PRETTY SURE THATS MORE THAT A MONTH

**Comment by setpixel** [comment]
@audionerd I think he's right. a month is way too short. Should we move this to Beta 10?

**Comment by setpixel** [comment]
Working on implementing this now. Duplicate of #29 and #30

**Comment by vxfmatt** [comment]
thank

**Comment by setpixel** [comment]
A version of this works in the current build

**Comment by vxfmatt** [comment]
lol my printer broke

**Comment by setpixel** [comment]
time to steal a new one

**Comment by DCNielsen** [comment]
I've tried the printing out and love it. That small size is great for fast blocking. Stoked for when the whole workflow is in place.

**Comment by setpixel** [comment]
I'm working on it all today!

**Comment by DCNielsen** [comment]
Rad!
