### ISSUE TITLE
Error When Using PSD functionality with Autodesk Sketchbook

### ISSUE THREAD

**Issue by maxhudetz** [wonderunit/storyboarder#2100]
Hey there, 

Thanks for making Storyboarder! I love it. The other day I learned that Autodesk Sketchbook is now free and I thought, "Storyboarder for sequencing and Sketchbook for drawing?? That'd be a killer combo!!"

Unfortunately, when I set Autodesk Sketchbook as Storyboarder's default .PSD editor, I get the following warning and error after updating and saving the PSD in Sketchbook.

"[Warning] Could not import from file board-1-MC5DX.psd.
Error: Invalid RLE data: exceeded buffer size 38/38"

![PSD_ERROR](https://user-images.githubusercontent.com/33703426/91197442-ed71f800-e6c0-11ea-93e3-7e1d76977c0f.PNG)

Hoping/wondering if this could be fixed, as it would make all my storyboarding dreams come true.

Thanks again!
-Max

**Comment by gajaman** [comment]
I have the same issue with Autodesk Sketchbook, but works fine with Medibang and Krita. I hope they solve this because I prefer Sketchbook Pro

**Comment by greenman2** [comment]
I'm having the same issue. I'm using a 16:9 blank board and my error is "Error: Invalid RLE data: exceeded buffer size 58/58".

**Comment by audionerd** [comment]
Can you attach an example PSD created with Autodesk Sketchbook which causes this error?

**Comment by greenman2** [comment]
Yes, I just made a quick scribble and received the same error. Thank you for looking into this!

I had to put it in a zip folder in order to upload it to GitHub btw.


[board-1-KHXDX.zip](https://github.com/wonderunit/storyboarder/files/5156804/board-1-KHXDX.zip)

**Comment by audionerd** [comment]
Does Autodesk Sketchbook provide any options when a PSD is saved that might improve compatibility?

**Comment by greenman2** [comment]
I will play around with the settings and see if I can get anything to work. Sketchbook went free a year or two ago, so if you have time, you can take a look too: https://www.sketchbook.com/

**Comment by audionerd** [comment]
Can you share a screenshot of any PSD-related settings?

**Comment by greenman2** [comment]
Yes, no problem, I'm looking through things right now.

**Comment by audionerd** [comment]
Storyboarder uses the `ag-psd` JavaScript library to read/write PSD files. I've reported the issue there, too.

https://github.com/Agamnentzar/ag-psd/issues/32

**Comment by greenman2** [comment]
I didn't find any relevant PSD settings in Sketchbook that made a difference. Like I checked the DPI, canvas size, and other options.

I also tested editing a PSD created by Sketchbook and then edited in Photoshop. As well as a PSD created in Photoshop and then edited in Sketchbook. The results of those tests were that once a file has been edited in Sketchbook, it would no longer import into Storyboarder. And that's even after re-saving the PSD in Photoshop.

**Comment by audionerd** [comment]
I was able to re-save in Photoshop and then import to Storyboarder without error. I selected the "Maximize Compatibility" setting in PS.

**Comment by audionerd** [comment]
Got a fix working with the latest `ag-psd`. Should make it into the next Storyboarder release.

**Comment by maxhudetz** [comment]
You guys rock! Thanks so much for looking into this :D

**Comment by Ethanblah** [comment]
Hi, I posted the original error back in June. I see the error 'using PSD functionality with autodesk Sketchbook' will be fixed in the next build ( thanks for checking this out) I wondered when version 2.10 will be released. I checked today and the current build version is 2.01 - the build I am currently using, that still throws up the import error. Cheers EJ
