### ISSUE TITLE
Project wiped clean for no reason

### ISSUE THREAD

**Issue by LAdu3L** [wonderunit/storyboarder#2109]
I opened my project afte 2 days of letting it be and it only had the script in it. All the photos and the 3d shot maker stuff simply gone.

**Comment by audionerd** [comment]
Do you still have a .storyboarder file? Do you still have an `images` folder?

Can you send a screenshot of what you're seeing in the file system?

**Comment by audionerd** [comment]
Closing this issue for now because there's not enough information provided for us to proceed.
