### ISSUE TITLE
Unable to see where I am about to draw

### ISSUE THREAD

**Issue by tony902** [wonderunit/storyboarder#2134]
The mouse pointer is nice and big when it is over the drawing tools , other tools, timeline etc but the moment it goes anywhere near the sheet to draw on it, the pointer disappears.  Consequently it is impossible to draw anything other than lines in random places.  This is not much help!  Windows 10.

**Comment by audionerd** [comment]
Try making your brush size larger, either from the Tools menu, or by scrubbing the brush size number under the large color swatch.
