### ISSUE TITLE
Accidental Click Outside of Window = Runaway Shot Generator Camera

### ISSUE THREAD

**Issue by Taschia** [wonderunit/storyboarder#2150]
While using the WASD keys to maneuver the camera, I dragged my mouse too far adjusting the view and accidentally clicked a window on my second monitor. The camera continued flying in the last direction I pressed, and clicking back into the window allowed me to try to move in the other directions - but I could only slow/stop the camera movement in the direction it wanted to go, and the moment I let go of the keys it would continue flying in said direction. 

I was able to quickly reset it by clicking "Insert as New Board" so I didn't lose the scene I made in Shot Generator, and then closed everything and reopened again. But anytime I accidentally click outside of Storyboarder while piloting the camera it seems to do the same thing. Just a head's up!

**Comment by audionerd** [comment]
Thanks for the report! This issue will be fixed in the next release.
