### ISSUE TITLE
Could not export animatic.

### ISSUE THREAD

**Issue by PolyStoryGuy** [wonderunit/storyboarder#2160]
Hello, GitHub, this is PolyStoryGuy, and this is my first report. I use this program, and I have a problem exporting my animatic to a video. Here is this screengrab.
<img width="1792" alt="Screen Shot 2020-11-18 at 10 28 30 PM" src="https://user-images.githubusercontent.com/74742318/99730078-e07b5f80-2a89-11eb-9e3f-1296a8ae40a6.png">
It says that it could not export my animatic, and I've got a TypeError on this software. Could anybody please do something?

Thanks in advance.

**Comment by audionerd** [comment]
This is a known issue but there will be a fix in the next version of Storyboarder.

Until then you can try an older version (Storyboarder 2.0.1) where video export works. More info here: https://github.com/wonderunit/storyboarder/issues/2107

Closing this issue since it's a duplicate of #2107
