### ISSUE TITLE
microphone access privacy security issue

### ISSUE THREAD

**Issue by dongalor** [wonderunit/storyboarder#2163]
Having trouble with recording audio in application, it's all because of privacy and security problem. When I launch application from terminal system asks about permission to use microphone as a terminal, not storyboarder...

 - OS: MacOS Catalina
 - Version [latest]

**Comment by audionerd** [comment]
You’re running Storyboarder from within Terminal.app? Why not just run it from Applications?

Can you attach a screenshot of the message you’re seeing that is preventing you from recording?
