### ISSUE TITLE
files won't show up in krita for edit

### ISSUE THREAD

**Issue by usna26** [wonderunit/storyboarder#2164]
I tried multiple times to edit in Krita but it only opens Krita but no layers or files would show up other than the Krita default one. please let me know how to fix it.

**Comment by audionerd** [comment]
Can you try it again, and then send us your Storyboarder log file (`Help > Show Log File`)?

**Comment by usna26** [comment]
I am very happy to get a reply from you, It is working now. Thank you so
much for taking the time and replying :)
