### ISSUE TITLE
Properties in Shot Generator impossible to access on smaller screens

### ISSUE THREAD

**Issue by RaphAldis** [wonderunit/storyboarder#2166]
Just downloaded storyboarder.  Working off a laptop without a scrollwheel.  Can't scroll the left-side screen to reach properties on shot generator

**Comment by audionerd** [comment]
Can you send a screenshot?

**Comment by RaphAldis** [comment]
Hi,
Screen shot attached.

 I can drop objects onto the main screen, but I can't scroll the properties menu on the left.  I am currently using Windows 8.

-----Original Message-----

**Comment by audionerd** [comment]
Can you upload the screenshot here on GitHub instead of an attachment?

If you don't have a scrollwheel or touchpad, you can click to focus an area in properties (or Tab to it) and use the up/down arrow keys to scroll.

**Comment by RaphAldis** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/75538238/102256314-2699d680-3f03-11eb-860f-4df09e884aab.png)

Thanks for the reply, but that method does not work.  I can tab across to the properties, but scrolling up and down with the arrow keys, only moves the lower few millimetres of the the properties menu, so can't see any of the options to change the object.

Hope that makes sense.

**Comment by audionerd** [comment]
From the View menu, try Scale UI Down.

**Comment by RaphAldis** [comment]
Originally, that didn't work - but I've just re-installed everything and the 'Scale UI Down' now works!
Awesome.
Thanks you!

**Comment by RaphAldis** [comment]
Actually - the Scale UI Down now doesn't seem to be working.  I've tabed around various areas of the screen, but not working???
