### ISSUE TITLE
Preferences: make fewer calls to getGlobal

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#217]
To many calls to `remote.getGlobal('sharedObj').prefs`

**Comment by audionerd** [comment]
Possibly related to https://github.com/wonderunit/storyboarder/issues/211

**Comment by audionerd** [comment]
Oops. Looks like I just changed the syntax around. The problem is still there.

We need a better long-term solution for:
- main can load settings from disk
- renderer can see and mutate those settings
- main can save settings back to disk without blocking

**Comment by setpixel** [comment]
I have a fix for this and revised prefs
