### ISSUE TITLE
Cmd Z for AZERTY keyboards

### ISSUE THREAD

**Issue by jeremouans** [wonderunit/storyboarder#218]
Hey, looks like command Z is not working on AZERTY keyboard. Cmd W works as such !

**Comment by setpixel** [comment]
Oh hmm. What is an azerty keyboard? Is it on Mac?

**Comment by jeremouans** [comment]
Azerty keyboards are french keyboards - Yours is a Qwerty :)

**Comment by setpixel** [comment]
I DONT BELIEVE IT. PICS OR IT DIDN'T HAPPEN. 

We will try to fix!

**Comment by jeremouans** [comment]
hey Charles,

a screencast would be handy ?

2017-05-10 17:23 GMT+02:00 Charles Forman <notifications@github.com>:

**Comment by setpixel** [comment]
We know how to simulate this... going to replicate and fix.

**Comment by setpixel** [comment]
Hi @jeremouans 

https://codepen.io/miduga/pen/ujolf

Can you tell me the codes for C V Z?

I can fix this now probably if you let me know

Thanks!!!!

**Comment by jeremouans** [comment]
C = 67 
V = 86
Z = 90
A = 65
Q = 81

**Comment by setpixel** [comment]
Thanks!
