### ISSUE TITLE
Storyboarder is not supported on your device because WebGL could not be initialized

### ISSUE THREAD

**Issue by jensy** [wonderunit/storyboarder#2192]
**Describe the bug**
I started using Storyboarder today and could run it no problem, after I closed it and started it up again, I am seeing "Storyboarder is not supported on your device because WebGL could not be initialized" now. It does not matter if I open an existing file or try create a new storyboard.

**To Reproduce**
1. Open App
2. Open Recent Storyboard or Create New Storyboard
3. See error

**Expected behavior**
Storyboarder opening my file. ;)

**Screenshots**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/105723/104678096-ebc4c300-56a7-11eb-9895-f852aa3e070a.png">

**Desktop (please complete the following information):**
 - OS: MacOS, M1
 - Version: Latest (2.0.1)

**Comment by VFabrice** [comment]
Using Kubuntu 20.04.2 Same kind of message while WebGL is activated (hardware accelerated), verified and tested using Chrome and Firefox.
"Sorry, Storyboarder is not supported on your device because WebGL could not be initialized".

**Comment by audionerd** [comment]
@jensy Thanks for the report. This is a known issue with M1 and we're tracking it here: #2175. Should have a new M1 build of Storyboarder up soon.
@VFabrice Not sure about that one, could be hardware related.
