### ISSUE TITLE
Storyboarder Error

### ISSUE THREAD

**Issue by cjdraper** [wonderunit/storyboarder#2193]
I recently upgraded to the MacBook Pro M1. The first time I opened Storyboarder, it opened fine. The next time I tried to open I got the following error: "Sorry, Storyboarder is not supported on your device because WebGL could not be initialized" Please assist with possibly fixing this error. I am assuming it has to do with the new M1 processor but not sure since it worked the first time I opened the app.

**Comment by audionerd** [comment]
Thanks for the report @cjdraper. We're still working on M1 support, you can track the progress in issue #2175. Should have a new build soon.
