### ISSUE TITLE
Watch Storyboard Full Screen

### ISSUE THREAD

**Issue by Sahil-Desu** [wonderunit/storyboarder#2200]
Please add a feature so that we can view our storyboards in fullscreen. Like in Premiere there is an option ' Ctrl+` ' which makes the output window full screen.

**Comment by audionerd** [comment]
Try `View > Cycle View Mode` (there are six modes, the sixth shows the board taking up almost all of the screen) and `View > Toggle Fullscreen`.

**Comment by Sahil-Desu** [comment]
Thank you. It works.
