### ISSUE TITLE
WebGL error

### ISSUE THREAD

**Issue by zamo21** [wonderunit/storyboarder#2210]
**Describe the bug**
When trying to open an existing project in storyboarder on an M1 mac mini running BigSur 11.1, I get the following error. "Sorry, Storyboarder is not supported on your device because WebGL could not be initialized." I used the software 1 week ago with no issues. The only update that has been made on my computer recently was to Safari. 

**To Reproduce**
1. Start a new storyboarder project
2. Open an existing storyboarder project

**Expected behavior**
The open process is initialized, the Loading... screen appears on the screen, and then the error message stops the loading process. 

**Screenshots**
<img width="630" alt="Screen Shot 2021-01-31 at 1 50 23 PM" src="https://user-images.githubusercontent.com/78319186/106394901-3d21c180-63cd-11eb-9e42-5070f34c1dd7.png">

**Desktop (please complete the following information):**
 - OS: Mac BigSur 11.1
 - Browser Safari
 - Version 14.0.2

**Additional context**

**Comment by audionerd** [comment]
Thanks for the report. M1 support is coming soon, you can track the progress on #2175.
