### ISSUE TITLE
Cannot export to pdf since fonts are missing

### ISSUE THREAD

**Issue by vibby** [wonderunit/storyboarder#2213]
**Describe the bug**
When I try to export the storyboard to a pdf, I get error : ```Unknown Font Type```

**To Reproduce**
1. Open a board
2. Go to 'Files / Print or Export to pdf'
3. The popup should opens
4. And the message error appears

**Expected behavior**
Just working

**Screenshots**
![image](https://user-images.githubusercontent.com/1181902/107260796-cde84500-6a3e-11eb-9a98-7ca189590ff9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser : chromium,
 - Version : no idea
 - Launched app through a «npm start»

**Additional context**
I found the cause of problem : font files are 404 html errors from github, like this one : https://github.com/wonderunit/storyboarder/blob/master/src/fonts/thicccboi/THICCCBOI-Bold.ttf
Just replace the files with real fonts ;)

**Comment by audionerd** [comment]
Fixed in 4f5fef43

**Comment by vibby** [comment]
Thanks !
