### ISSUE TITLE
Random Generator Not Visible

### ISSUE THREAD

**Issue by rabaksh42** [wonderunit/storyboarder#2215]
I see on the webpage that there is an option for randomly generating a scene based on description. I do not see this feature in my Storyboarder installation. Has this feature been removed?

 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.146

**Comment by audionerd** [comment]
That feature was removed after Storyboarder v1.9.2. 

But you can still download and run that older version of Storyboarder from https://github.com/wonderunit/storyboarder/releases/tag/v1.9.2
