### ISSUE TITLE
Storyboarder fails to install

### ISSUE THREAD

**Issue by SS122** [wonderunit/storyboarder#2219]
![image](https://user-images.githubusercontent.com/79115227/107993066-fee1f000-6fd1-11eb-81b5-cd411eefd5c8.png)

Hi, trying to install Storyboarder and the installation bar continuously gets stuck here and stops progressing. Been like this for 4 hours.

I've tried restarting my comp and the installation. Also tried running as admin. No success.

Appreciate any suggestions

**Comment by audionerd** [comment]
You could try downloading it from the Releases page here on GitHub and installing it manually.
