### ISSUE TITLE
Should dispose of tooltip after it disappears

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#222]
Triggering all tooltips causes lots of zombie DOM elements, slows down drawing after triggered. Re-draws are triggered for them even though they're not user visible.

**Comment by audionerd** [comment]
If we're force-setting `visibility` (even when set) that might be causing re-renders?
 https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

**Comment by setpixel** [comment]
I'm not sure this is still an issue. I added a delay on open and even though the items are there, they are behaving nicer.
