### ISSUE TITLE
Printing control MAC

### ISSUE THREAD

**Issue by timovirtaneva** [wonderunit/storyboarder#2247]
Hi

I wanted to print the Storyboard Worksheet.
The program prints it directly to a wrong printer (I have 24" roll paper printer for DAC work).

I need to have control where the program prints the documents.

Thanks for a great program.

I use MAC Big Sur and version 3.0.0

--Timo

**Comment by audionerd** [comment]
You could try "Export PDF" and print the PDF instead (from Preview.app for example).
