### ISSUE TITLE
Layers UI

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#225]
notes: visible on and off toggle (opacity behind-the-scenes)
notes: clear notes layer

main layer: visible on and off toggle (opacity behind-the-scenes)
main layer: move down to reference layer

reference layer: visible on and off toggle (opacity behind-the-scenes)
reference layer: change opacity
reference layer: move up to main layer (respect opacity)
reference layer: clear

**Comment by setpixel** [comment]
Related to #34
