### ISSUE TITLE
Unable to load/open image using the Edit in Photoshop Button

### ISSUE THREAD

**Issue by Weiro-O** [wonderunit/storyboarder#2250]
**Describe the bug**
Error occurs when pressing the Edit in Photoshop button

**To Reproduce**
1. Open Storyboarder and open any file
2. Click 'Edit in Photoshop'

**Expected behavior**
Expected photoshop to open and be able to draw and edit boards from that program

**Screenshots**
![Editor Error Message](https://user-images.githubusercontent.com/82772683/115153808-ae682c80-a02c-11eb-9aa2-5f1b7d0f4dcc.png)
![Console Error Message](https://user-images.githubusercontent.com/82772683/115153809-af00c300-a02c-11eb-8af2-8ad6bf5c8518.png)
![Developer Tools Error Message](https://user-images.githubusercontent.com/82772683/115153810-af00c300-a02c-11eb-8493-c002315b303c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
1. Tried opening the file directly in photoshop and saving any changes did not get reflected in Storyboarder
2. After using the 'Edit in Photoshop' button, I was locked out of drawing on Storyboarder
3. Restarting storyboard returns the ability to draw, but the drawing is only visible on the small preview of the timeline
4. As I just started using Storyboarder, I have yet been able to use this feature successfully

**Comment by audionerd** [comment]
Does that file exist on the drive?

**Comment by Weiro-O** [comment]
It does, but it looks like a PSD file wasnt created in the images folder. Not sure why it didnt work this time, but I reinstalled everything and now its working as intended. A PSD file is produced and photoshop is opened. Maybe it was unintentionally deleted or something, but everything is now working. Thanks!!

**Comment by audionerd** [comment]
👍
