### ISSUE TITLE
please add ability to scale character models.

### ISSUE THREAD

**Issue by ecofriend** [wonderunit/storyboarder#2258]
In the shot generator, I import images of the location where I'll be shooting the video. 

It would be awesome if I could scale the character models (like I can for objects) so I can place them in front of the image so that it looks like one character is closer to the camera than another. 

Simulating distance between characters by moving them back and forth in 3D space doesn't always work since sometimes that means placing the character behind the image plane so they cannot be "seen" by the camera.

**Comment by audionerd** [comment]
A Character’s “Height” property can be used to set the scale of the Character. Double-click the Height input to manually enter a value in meters.

**Comment by ecofriend** [comment]
Thanks, @audionerd! Didn't realize I could just click in there and type in smaller numbers.
