### ISSUE TITLE
I wanted to use vertical HD but "please don't select vertical HD - we added it as a joke"

### ISSUE THREAD

**Issue by alankent** [wonderunit/storyboarder#2263]
**Is your feature request related to a problem? Please describe.**
I was looking for a tool to storyboard Web Stories (https://stories.google/). Web stories are a vertical format for encoding stories in a web page.  I mainly wanted to make sure the "please don't select vertical HD" warning was not actually a problem as I do want to use it!

**Describe the solution you'd like**
First question was to make sure if there actually is a problem using vertical format. It is becoming more popular with TikTok, Instagram etc. Not a full movie, but still useful to prototype the creative story format.

I am personally using it with web stories. To maximize support for aspect ratios, you actually want an image of size of say 868 by 1462 pixels with a safe zone of 760 by 1280 (the 7% bleed is to cope with wider or taller mobile devices). This covers a wide range of devices.

After creating a storyboard with timings etc, it would be a bonus to add "Export a Web Story" - a series of image files (one per page). Here is an example script to create a web story: https://github.com/alankent/web-story-storyboarding/blob/main/scripts/makestory.sh (the poster images can be left out since they are different dimensions, or use 4:3, 1:1, and 3:4 for the three posters, say of the first page).

Note that you could do fancy things like text overlays of the script with Web Stories. Web Stories also support an auto-next slide with timing ability. Depends how far you want to go.

**Describe alternatives you've considered**
I have tried to use Artboards in Adobe Illustrator (https://alankent.me/2021/05/22/storyboarding-web-stories-with-adobe-illustrator/) but it's pretty painful.

**Additional context**
I am not suggesting your tool is actually a useful for production quality web stories - it is still for storyboarding (prototyping) and experiencing what the story might feel like. (I personally want to try a lightly animated comic in Web Story format - the storyboard is to get the story pacing right before creating more detailed pages, then I am going to animate short sequences, like eyes looking left/right, on each web story page.)

**Comment by audionerd** [comment]
Vertical should mostly work and it’s something Storyboarder technically does support. It just hasn’t been tested in real use as much as 16:9 and 4:3, so if you find bugs please report them.
