### ISSUE TITLE
Great application, one issue

### ISSUE THREAD

**Issue by eltonbean** [wonderunit/storyboarder#2274]
I find the automatic play is not in sequence with the storyboard on the timeline. If I press the play button it's fine.
It would be great if there was a toggle switch in preferences to turn off autoplay (I find it really annoying). I work on Music Videos and I'm testing Storyboarder.

Great intuitive application.

Thanks very much.

Simon

**Comment by dreamparacite** [comment]
If you are referring to the automatic playback of audio when you click a board, that can be disabled at Navigation > Audition Board Audio.

I uncheck that, but Storyboarder never saves that preference so I have to disable it every time I open my file.

**Comment by audionerd** [comment]
@dreamparacite That's interesting. It looks like "Audition Board Audio" is _read from_ preferences, but couldn't find where it's _stored to_ preferences.

For now, you could modify your preferences file manually if you want it disabled every time you open Storyboarder. Open the `pref.json` file in a code editor and change `enableBoardAudition` from `true` to `false`.

On macOS, the file is in `~/Library/Application Support/Storyboarder/pref.json`.

Related to a known bug: #984.
