### ISSUE TITLE
Total Time shows incorrect duration

### ISSUE THREAD

**Issue by qian2501** [wonderunit/storyboarder#2275]
**Describe the bug**
Total time calculation is wrong, in both `exporters` and `scene-timeline-view`.
Should not store `board.time` and `board.duration` as string

**To Reproduce**
Type any duration, cross multiple board is easier to trigger.

**Detail Explain**
Currently total time is calculated as `lastboard.time + lastboard.duration`,
when there is no `board.duration` we have it simply signed as `(int)2000`, but when there is duration, for example 2000, we have `(string)”2000”`.
When trying to add them we have `20002000` instead of `4000` since string add means append, thus you get total time 5:33:22 for two 2000ms board.
Also, save as int can save your time for cast it to int for math, there is simply no reason to save as string.

**Comment by qian2501** [comment]
Sorry, I double checked the json file, `board.time` is ok, `board.duration` is wrong.

**Comment by audionerd** [comment]
Can you describe which bugs this causes that an artist would see while using the program, and steps a tester could take in the program to reproduce those bugs?

**Comment by qian2501** [comment]
I draw a 10 minute like script, the timeline and exported pdf have a total duration of thousands hours.
I have described how it happens, to make things clear: make two board, leave 1A unchanged, type 2A’s duration as 2000, you’ll get total duration of 5:33:22. Both release 3.0.0 and master branch have this issue.
And I just found the issue point. At line 1066 and 1082 of `main-window.js`, the `e.target.value` should be inside parseInt(), or you must do parseInt before add duration.

**Comment by audionerd** [comment]
Good catch. Thanks.

**Comment by audionerd** [comment]
Steps
- Create a new Blank Storyboard
- Leave Board 1A duration as default
- Add a Board 2A, with duration set (e.g.: 3000)

Expected
- Value for total time in bottom right should be 0:05 (2000, the default board duration for 1A + 3000, the value entered for 2A)

Actual
- Value for total time in bottom right is 5:33:25

**Comment by audionerd** [comment]
Related bug:

- Load a .storyboarder file which has a board duration stored as a string (e.g.: any .storyboarder where at least one duration value was entered manually from the sidebar input, created in Storyboarder in the past few years since this bug was introduced)
- Total Time shown in bottom right is wrong

So we probably need to parse board duration strings as numbers when we first load each .storyboarder file. Any code which loads a .storyboarder file will need to do this conversion. For the main window, we could do this alongside (or in) `verifyScene`. Do we have other places in the code which load .storyboarder files?

**Comment by qian2501** [comment]
I tried to do parseInt inside verifyScene, it can convert `board.duration` to `int` in the saved file, but it also make `board.time` `null`, which seems related to other code I haven’t read yet.
Also it’s clear that `board.duration` Is actually converted to `int` somewhere, `board.time` can’t be right otherwise, can you tell me where it is handled?

**Comment by audionerd** [comment]
Could be related to boardDuration

https://github.com/wonderunit/storyboarder/blob/master/src/js/models/board.js#L63

that function is used to determine the board duration when none is set — it falls back to scene.defaultBoardTiming which is a user-configurable setting, by default its 2000 msecs.

that function ALSO converts any string to Number.

not sure it’s wise to do both, but that’s what it does right now.
