### ISSUE TITLE
[bug] straight line delay not disabling

### ISSUE THREAD

**Issue by arjeff3** [wonderunit/storyboarder#2280]
Under "edit > preferences > straight line delay" I have set the slider to disabled so I can draw curved lines, yet it keeps snapping my lines straight.

**Comment by audionerd** [comment]
Did you try restarting Storyboarder after changing the setting?

**Comment by arjeff3** [comment]
ah, I've restarted and it does seem to be working now.
In the future maybe a "restart the program for this change to take effect" hint or popup might make it clearer to the user.
