### ISSUE TITLE
Won't install on Windows 10

### ISSUE THREAD

**Issue by Dinocanid** [wonderunit/storyboarder#2314]
**Describe the bug**
Just downloaded 3.0 and it just won't install. I get a blue pop-up saying "This app can't run on your PC". I have a 64-bit PC by the way, not 32-bit

**To Reproduce**
1. Download Storyboarder 3.0 setup
2. Click on the setup file
3. See error
(This may not be reproducible on every PC, but are the exact steps to what happened)

**Expected behavior**
Clicking on the setup should install the program.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 3.0

**Additional context**
The alpha versions worked on my computer way back when, although I'm not sure how relevant that is.

**Comment by audionerd** [comment]
which version of windows? which processor? can you attach a screenshot of the error?

**Comment by Dinocanid** [comment]
Here's a screenshot, although it doesn't give any additional information:
![storyboarder error](https://user-images.githubusercontent.com/20864790/142468334-5fdefa40-a6b9-4f96-aa72-f53565169a75.png)

My processor is: AMD FX(tm)-4300 Quad-Core Processor 3.80 GHz

**Comment by Dinocanid** [comment]
So I,,, noticed the problem after looking at the files again. The website kinda gave me an empty download? I received two files:

- Storyboarder-Setup-3.0.0 (0kb)
- Storyboarder-Setup-3.0.0.exe.part (84,330kb)

It installed successfully after I downloaded it from github. I'm not sure if the website download is just wonky or the browser messed something up while downloading.

**Comment by audionerd** [comment]
A .part file indicates the browser didn’t complete the download, possibly a network connection problem. Sounds like with the full download it worked so I’ll close this issue. Glad its working now.
