### ISSUE TITLE
Sketchpane cursor a little above actual drawing.

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#240]
Probably because the canvas isnt positioned prop or the resize event is not triggering at the right time. Idk eric knows this stuff.

**Comment by audionerd** [comment]
this is most noticeable when the scrollbar appears and allows the actual canvas location to be shifted from the calculated location.

Related: the bug where the scrollbar apppears :/

**Comment by audionerd** [comment]
Does the scrollbar ever appear in "real" production usage, or only with the developer tools open?

**Comment by audionerd** [comment]
Confirmed this is still happening on laptops with small-ish screens.
