### ISSUE TITLE
Temporary move/scale mode sometimes freezes until a new tool/mode is selected

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#245]
Steps
- rapidly switching tools/modes via keyboard while drawing (frequent pointer up/down)

Expected
- should never freeze on a tool/mode

Actual
- sometimes freezes in (what should be temporary) 'move' or 'scale' mode and reports console log: pointer is already down`

**Comment by setpixel** [comment]
Likely not an issue with v2
