### ISSUE TITLE
Exporting Video Not Working

### ISSUE THREAD

**Issue by BadAppleDesignz** [wonderunit/storyboarder#2539]
I keep getting an error when trying to export my video. The error is: Could not export. An error Occurred. TypeError: Cannot read property 'on' of undefined. 

Any help with this would be greatly appreciated

**Comment by BadAppleDesignz** [comment]
I was able to get Storyboard 3.0. That fixed the issue. Thank you.

**Comment by OctopusEnthusiast** [comment]
Any clue as to get the 3.0 version? On the site it still has an older version it seems and I'm having this error.
