### ISSUE TITLE
New Blank Storyboard - replace doesn't do anything

### ISSUE THREAD

**Issue by DCNielsen** [wonderunit/storyboarder#276]
From the starting menu, if I:
- Create New Storyboard
- Create a blank
- Use a name of an existing board (planning to overwrite it)
- It asks me if I want to replace it, I say yes.
- Nothing happens.

I'm expecting Replace to go ahead and overwrite the previous board and go into the new file.
PS, loving the development on this. It's awesome.

**Comment by setpixel** [comment]
Ahh good catch.. I know what's happening here.

**Comment by audionerd** [comment]
Fixed by https://github.com/wonderunit/storyboarder/pull/450
