### ISSUE TITLE
Delete frame doesn't update thumbnail

### ISSUE THREAD

**Issue by DCNielsen** [wonderunit/storyboarder#277]
If I press the Delete key, the drawing window updates, but the thumbnail does not.
I'm expecting the thumbnail view to match what I see in my work space.

**Comment by DCNielsen** [comment]
This appears somewhat fixed in Beta 6, but is still funky with Undo/Redo factored in.

**Comment by setpixel** [comment]
Oh - can you explain in more detail?

I try not to update the thumbnail too often because it hits the disk... but I think I know what you're saying.

**Comment by DCNielsen** [comment]
Thanks! Yeah. What I'm getting is apparent inconsistency where I can draw several strokes and nothing on the thumbnail updates. I can reorder the thumbnails, and it still doesn't update. Then I do a Cmd+Z or switch to another frame and it updates. If I delete, the thumbnail updates, but if I Undo, it doesn't update. If I Redo, it doesn't update.

My first expectation is that what I see is going to be what I get between the thumbnail and the board. Probably what I'm used to from Adobe products/etc. I appreciate the sentiment of not slowing things down, and I'm not technically versed enough to know how you might attempt a more synchronized feel through other means. What it comes down to is that the working space and thumbnails seem more disconnected than I'm used to.

**Comment by setpixel** [comment]
Ahh - yeah. There is a sort of intentional delay of 5 seconds to avoid slowing down actual drawing. I wonder if we can make it a setting, or put a slight timeout after pen up for some more responsive thumbnail updating.

**Comment by setpixel** [comment]
Woot - this is fixed in the newest release cc @audionerd
