### ISSUE TITLE
Some Lag

### ISSUE THREAD

**Issue by CuberToy** [wonderunit/storyboarder#278]
Tried the last built, first since a few.
So here's my first feedback while doing some stress stuff :

Got some weird lag, or some processor drops (I guess). 

Here's some video of the issue. 
- 1st "drawing" lines accross the whole area. Part of it do not output correctly. (Start @0'16'')
https://drive.google.com/open?id=0B_duL9AEjIplRURzQ1NKczhzR0E

- 2nd is doing some circle. I draw left side, then right... Lag when putting the nib down the second time. So I get some vertical lines instead of semi circle.
https://drive.google.com/open?id=0B_duL9AEjIplWXV6dEdxQ0k2OXM

Note that I only get this while in fullscreen.

_Wacom Intuos 5 M
Win 10
Intel i7 6700K
nVidia 1070_

**Comment by setpixel** [comment]
Ah --- so I think this has to do with windows not actually having pen support yet.. We've been noticing some weird stuff too. I dont know when the new Chromium is coming out.. it should have been last week. 

Can you try it with the console window open?

I think you can press ctrl+option i and make sure console is open.

**Comment by CuberToy** [comment]
Oh yeah, totally thought it had something to do with Pen Support, forgot to mention.
Same thing with console openned. Though I only get the problem of the first video. With console opened, the circle test is a success.

I also noticed the lag seems to also comes each time a tooltip div is called.

Will continue trying to stress it a bit.

**Comment by setpixel** [comment]
AHHH - I def think some funny business is going on with the tooltips. I don't think we are destroying them properly.

**Comment by CuberToy** [comment]
Majority of the tooltips that pop stay in console and don't destroy, yeah.

**Comment by setpixel** [comment]
Curious, does this still occur with a newer build?

**Comment by setpixel** [comment]
Can you try this now? I think it's fixed with the newest build.
