### ISSUE TITLE
Ability to import final draft script

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#279]
OVERVIEW
- Write scene ids (if missing) to .FDX
- Parse .FDX files for scene data
- Ensure .FDX scenes are created properly on filesystem and in script/scenes views
- Use `storyboards/storyboard.settings` to determine if project is multi-scene (instead of looking only for .fountain)
- Add an .FDX multi-scene fixture for testing

---
FEATURES
- Artist can create a new multi-scene project based on .FDX
- Artist can load an existing new multi-scene project based on .FDX

---
TEST
- [x] Loading a new .fdx file (with no storyboards)
- [x] Loading a new .fountain file (with no storyboards)
- [x] Loading an existing .fdx project (with storyboards)
- [x] Loading an existing .fountain project (with storyboards)
- [x] Loading an existing standalone .storyboarder scene
- [x] Loading an existing storyboarder scene within a .fdx project
- [x] Creating a new .storyboarder project with the same name as an existing folder (should prompt and then allow overwrite)
- [ ] Creating a new .storyboarder project with the same name as an existing file (should cancel) _EDIT: does not cancel, allows `Untitled.storyboarder` as the folder name._
- [ ] Creating a new .fdx project with the same name as an existing folder (should overwrite) _EDIT: does not overwrite, just opens existing project_
- [ ] Creating a new .fdx project with the same name as an existing file (should cancel) _EDIT: does not overwrite, just opens existing project_
- [x] Cleaning up a scene
- [x] Cleaning up a .fountain project
- [x] Cleaning up a .fdx project
- [x] Script watcher (.fdx and .fountain)

TASKS
- [x] Don't add to watcher until the file is actually opened
- [x] Auto script watch update on focus
- [ ] Test when a `storyboards` folder already exists. Should prompt to overwrite. https://github.com/wonderunit/storyboarder/issues/848

**Comment by setpixel** [comment]
https://github.com/azcoppen/screenplay-parser

**Comment by setpixel** [comment]
https://libertyseeds.ca/2015/07/21/Investigating-Final-Draft-s-XML-document-format-with-Ruby/

**Comment by buckymcsatan** [comment]
Are there any plans for Scrivener support?
