### ISSUE TITLE
Uncaught Error: Cannot find module 'electron-settings' module.js 472

### ISSUE THREAD

**Issue by brenopolanski** [wonderunit/storyboarder#286]
For some reason my workspace for draw is not visible.

### My enviroment:

```
- Distributor ID:	Ubuntu
- Description:	Ubuntu 16.04.2 LTS
- Release:	16.04
- Codename:	xenial
```

![screenshot from 2017-06-10 12-51-32](https://user-images.githubusercontent.com/1894191/27004245-a4388120-4ddc-11e7-8646-a45732c42af2.png)
![screenshot from 2017-06-10 12-50-52](https://user-images.githubusercontent.com/1894191/27004246-a43bdb0e-4ddc-11e7-8f68-ea3582acc394.png)

**Comment by brenopolanski** [comment]
Okay. I solved this installing the `electron-settings`.

![screenshot from 2017-06-10 12-55-19](https://user-images.githubusercontent.com/1894191/27004306-4fc11b4c-4ddd-11e7-90c4-01fef8ae6969.png)

I'll send a PR.

**Comment by setpixel** [comment]
Aha! Actually, I was trying to get electron-settings out of there.. I think I still had a require in there which caused the error :/ - I'll remove the require.

**Comment by brenopolanski** [comment]
Ahhh.. okay :+1:

**Comment by brenopolanski** [comment]
Yeah... in file `main-window.js`, `line 9`.

![screenshot from 2017-06-10 13-28-54](https://user-images.githubusercontent.com/1894191/27004530-cc8679b2-4de0-11e7-98b2-37f0427fc871.png)
