### ISSUE TITLE
Worksheet Printing

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#29]
- [x] import code from outliner
- [x] make code modular 
- [x] make dialogue box
  - [x] center preview
  - [x] add form elements and style
  - [x] save prefs
  - [x] print button
- [x] print on any platform

**Comment by vxfmatt** [comment]
dude it said this was already implemented are you serious

**Comment by setpixel** [comment]
Will generate PDF worksheet and print via command line:

For printing PDFs on mac: https://superuser.com/questions/229418/possible-to-print-to-pdf-from-mac-terminal

For printing PDFs on windows: https://www.sumatrapdfreader.org/downloadafter.html

Linux: https://makandracards.com/makandra/24202-linux-how-to-print-pdf-files-from-the-command-line

**Comment by audionerd** [comment]
See also:
https://electron.atom.io/docs/api/web-contents/#contentsprinttopdfoptions-callback
https://github.com/electron/electron/blob/44862a131cfcac055fcb9ef7651e266ccae82898/docs/api/webview-tag.md#webviewprinttopdfoptions-callback
https://fraserxu.me/2015/08/20/pdf-generation-on-the-web/
https://github.com/fraserxu/electron-pdf

**Comment by setpixel** [comment]
@audionerd oh actually I can generate the pdf just fine.. its really hard to actually print it! Especially on windows.

**Comment by setpixel** [comment]
@vxfmatt https://www.youtube.com/watch?v=wcghkL3qT2Q
