### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by brenopolanski** [wonderunit/storyboarder#291]
- [x] English
- [ ] Spanish
- [ ] Portuguese (pt and pt-BR)
- [ ] Chinese
- [ ] French
- [ ] Italian
- [ ] German

and etc :)

**Comment by SakuraNeko** [comment]
If you want the software to support Chinese, I can help. But need to provide the original language resources file, thank you!

**Comment by toybrand** [comment]
I am an animation educator in Korea.
I want to speak Korean. What should I do?:

**Comment by audionerd** [comment]
Next version of Storyboarder will have a language editor built-in.
