### ISSUE TITLE
Create CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by brenopolanski** [wonderunit/storyboarder#296]
A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community.

#### Example: http://contributor-covenant.org/version/1/4/

**Reference**: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by setpixel** [comment]
I personally don't think this needs to be in a code repository. It's like, "Don't be an asshole." I think this is specifically for Github because of their problems in the past.
