### ISSUE TITLE
"+"button to add board disappears/moves off screen when too many board-thumbs are created

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#299]

**Comment by setpixel** [comment]
What if you scroll to the right? Do you see it?

**Comment by Soba77** [comment]
yes, but  if there many  boards it gets annoy to scroll it feels like two step process. especially when in the beginning it works nice and easy, then you lose that.

**Comment by setpixel** [comment]
you should use the keyboard :) ill see what I can do to scroll it

**Comment by Soba77** [comment]
np thank
