### ISSUE TITLE
Pen pressure not working with Wacom Intuos 4

### ISSUE THREAD

**Issue by mwildancahya** [wonderunit/storyboarder#321]

**Comment by setpixel** [comment]
Hi, are you on Windows?

If so, we are waiting on a fix that should be in the next release.

**Comment by mwildancahya** [comment]
Yes i'm using windows10 64 bit. Thanks :)

**Comment by setpixel** [comment]
Thanks. Yeah. Hopefully it will be less than 2 weeks. Eraser will work too.

**Comment by setpixel** [comment]
Merging into #194
