### ISSUE TITLE
Put an icon for editing in photoshop at the top nav

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#363]
Artists dont like key commands, so they want to just press easily in ui

**Comment by audionerd** [comment]
Do we have an icon designed?

**Comment by setpixel** [comment]
Yes - there is the ps icon on the side bar.. we are essentially moving the button to the top bar because artists want it

**Comment by audionerd** [comment]
OK, so move out of sidebar. Add to top nav.
