### ISSUE TITLE
Optional Autosave

### ISSUE THREAD

**Issue by psql** [wonderunit/storyboarder#389]
I often have changes committed unintentionally. I LOVE github for version control, but loads of normal people (including ones I collab with) use dropbox/google drive in their pipelines, and that means AUTOSYNC. Stuff gets hairy...

**Comment by psql** [comment]
https://d3vv6lp55qjaqc.cloudfront.net/items/1c3T0O0y1F0I0Z1t1z2K/Image%202017-07-18%20at%205.29.26%20PM.png?X-CloudApp-Visitor-Id=2478&v=29453d89

**Comment by psql** [comment]
![image 2017-07-18 at 5 29 26 pm](https://user-images.githubusercontent.com/688842/28340728-bedd1c64-6bde-11e7-8327-f8285a857e97.png)

**Comment by setpixel** [comment]
Yeah - this should be pretty straightforward. cc @audionerd
