### ISSUE TITLE
Open multiple frames in Photoshop

### ISSUE THREAD

**Issue by DCNielsen** [wonderunit/storyboarder#397]
If I have Multiple frames selected below and I click Edit in Photoshop, it's not clear which one will open at first. It's either the last selected/current or first in a sequence?

Can we open as many as I have selected? 

It probably gets a little resource heavy to open 100 of them at once, but maybe there is a warning at 10+?

**Comment by setpixel** [comment]
@DCNielsen thats interesting! I haven't even thought of that. I think currently it doesn't open multiple or maybe it does? cc @rawbee

**Comment by setpixel** [comment]
This is fixed now in master.. will be in the next release.

**Comment by DCNielsen** [comment]
Awesome! Thanks.

**Comment by setpixel** [comment]
@DCNielsen how does it work for you now?

**Comment by DCNielsen** [comment]
That's excellent. Thank you! There is sometimes a little bit of a hiccup when I change focus to Storyboarder after saving the file. Storyboarder's apparently doing what it needs to do to update the frames. Maybe a loading message would be helpful so the user knows something's not broken? Other than that, I love it.
