### ISSUE TITLE
Improve FPS on slow computers

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#401]
Profiling on:
Late 2010 13" MacBook Air
2.13 Ghz Intel Core 2 Duo
4 GB RAM
NVIDIA Gforce 320 256MB GPU

POSSIBLE PROBLEM AREAS
- canvas scaling?
- CSS dropshadows?
- Sonifier.trigger?
- other pointermove listeners?
- try profiling built version
- try profiling with dev tools disabled
- `drawImage` might improve in chrome >= 59? https://github.com/electron/electron/issues/9765
- SVG slowdown? Toolbar, Playback, Metadata

DISCOVERIES
- Brush#drawCircle is being called every frame, unoptimized
- Metadata panel slows down rendering

TASKS
- [ ] Alternate way to show a brush cursor (its too slow as-is)
- [ ] Make stabilizer level a preference (0-10) (feels faster when set lower or off)
- [ ] Don't create Tone objects if Sound Effects are turned off (major speed increase when off entirely)

Running tests against `401-fps` branch

**Comment by setpixel** [comment]
removing brush cursor for speed boost

**Comment by audionerd** [comment]
removed some pointermove listeners that weren't necessary for drawing

**Comment by audionerd** [comment]
Sonifier.trigger is disabled

**Comment by rawbee** [comment]
Currently seeing promising performance with the following:

• Removed brush cursor
• Removed toolbar
• Removed sound effects
• Removed meta data
• Setting stabilizer to zero

**Comment by rawbee** [comment]
Add a way to toggle the following:

• Sound effects
•.Brush Cursor
• Setting Stabilizer to Zero
• Painting Canvas Opacity

**Comment by rawbee** [comment]
Also, add a throttle for generating thumbnails. Currently, it writes a new thumbnail on mouse up.

**Comment by setpixel** [comment]
Closed for now!!!!
