### ISSUE TITLE
Wacom tablet support?

### ISSUE THREAD

**Issue by selcukahmet** [wonderunit/storyboarder#402]
TLDR; I can not draw via wacom. (workz well magic mouse thats okey) There is a performance issue.

**Comment by setpixel** [comment]
Hi! Questions: What kind of computer are you on? Mac/PC? OS? 

Whats the performance issue?

Does it work well with Photoshop?

**Comment by selcukahmet** [comment]
MacOS 10.12.4
Main issue is low FPS. I can not draw continuously. Sometimes erase line.
Wacom cannot recognize Storyboarder as an app on config panel.
I use AI and PS well with tablet. (or autodesk stuff)

**Comment by setpixel** [comment]
We have identified a major slowdown in drawing speed. We are fixing it and will be the next release hopefully in a few day.

**Comment by setpixel** [comment]
Duplicate #401
