### ISSUE TITLE
Laggy when using Astropad

### ISSUE THREAD

**Issue by alexrest** [wonderunit/storyboarder#426]
When using Storyboarder with Astropad, drawing is quite laggy. I've attached an example of a circle drawn in Photoshop vs. Storyboard. I'm using a 2016 MacBook Pro (13-inch, Two Thunderbolt ports, sans Touch Bar) connected to an LG SuperFine 5K display.

Thanks!

![board-1-zg5o0](https://user-images.githubusercontent.com/8932059/28794517-957d88d8-7604-11e7-8261-2dbb9b2b432d.png)

**Comment by setpixel** [comment]
Hi Alex!

Would you be able to record a screenshot video using quicktime and post it?

That would be great.

**Comment by setpixel** [comment]
To clarify - video on the mac, not the ipad :D

**Comment by alexrest** [comment]
@setpixel Thanks Charles, here's a video. I think the QuickTime recording seriously overloaded my CPU, but it still demonstrates the difference between Photoshop and Storyboarder. 

https://www.dropbox.com/s/0f8xud2ipiue7ot/astropad.mov?dl=0

**Comment by setpixel** [comment]
This will be fixed in new sketchpane #1072
