### ISSUE TITLE
Last line on clear board (or next board)

### ISSUE THREAD

**Issue by CuberToy** [wonderunit/storyboarder#44]
This is probably to merge with #16 

So when drawing, sometimes (I don't know exactly how, I was able to repeat the process, but not to determine what is the cause of it exactly) bit of the last line get transfered on the next board (pressing N) or a clear one (backspace).

I use the word transfer, because when looking for it, I saw that this bit was missing from the original line.

I made a video (we never know). I zoomed a little bit to much so you can't see my process (the first time it happens in the video was with new board, second time with a clear board).

Hope it helps.
https://drive.google.com/open?id=0B_duL9AEjIpld3gxWFc1cHA2SG8

EDIT : Using Windows 10 (may be usefull)

EDIT 2 : Oh notice something more.
The line bit print on every boards (even the non empty ones). But save just in one.

**Comment by CuberToy** [comment]
Oh notice something more.
The line bit print on every boards (even the non empty ones). But save just in one.

**Comment by setpixel** [comment]
this is fixed by new sketchpane #87 which is not complete yet, but makes this issue null.
