### ISSUE TITLE
Dialog and action overlapping in PDF export?

### ISSUE THREAD

**Issue by ananggadipa** [wonderunit/storyboarder#443]
Here's the screenshot:

<img width="556" alt="screenshot 2017-08-02 15 11 47" src="https://user-images.githubusercontent.com/5245236/28864893-3c08db64-7798-11e7-9eb3-db0c9cfd6dfc.png">

**Comment by setpixel** [comment]
hi @ananggadipa 

Great news! I JUST fixed this late last night:

https://github.com/wonderunit/storyboarder/issues/430

It will be in the next release (Beta 9, early next week)

Great catch - loving all your feedback and bug reports!
