### ISSUE TITLE
Straight lines doesn't work?

### ISSUE THREAD

**Issue by ananggadipa** [wonderunit/storyboarder#444]
I have hold shift when drawing but couldn't get straight line? Or I'm using it wrong?
I'm using wacom on mac apps.
![straight_line](https://user-images.githubusercontent.com/5245236/28868953-4f464178-77a5-11e7-986b-19ddc4e5fe40.giF)

**Comment by setpixel** [comment]
hi @ananggadipa 

yes - it actually used to work, but we have rewritten drawing many times

our current plan is to get storyboarder released in about ~4 weeks, and then do a complete refocus on drawing tools:

https://github.com/wonderunit/storyboarder/projects/8 - if you see the drawing section, straight line is on the list.

duplicate #151
