### ISSUE TITLE
Board Re-Order Aesthetic Idea

### ISSUE THREAD

**Issue by Soba77** [wonderunit/storyboarder#48]
This was an idea i had for maybe how to show boards getting deleted. 
I felt I could lose myself when deleting/moving  board when they just quickly disappear.

Deleteing Idea:
Selected boards that are deleted show the boards behind them slide back into their spaces

EG- 

- There are boards 1, 2, 3, 4, 5, 6, 7

-  Boards 3, 4 are selected and deleted

- leaving blank spaces in there spots for about _one second_, before...

- Boards 5, 6, 7 slide back into the blank spaces filling them

- Leaving only boards 1, 2, 5, 6, 7 remaining

just an idea, hope this makes sense.

**Comment by setpixel** [comment]
We added animations and notifications and sfx. I think it fixes this issue.
