### ISSUE TITLE
Integrate Sound (SFX) Feedback into main app

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#49]
Integrate SFX for ui rollover, actuation, tooltip, etc.

Respect user preference.

Volume decay over extended usage so not annoying. Creep back up over idle.

Pen movement make light saber sound?

**Comment by audionerd** [comment]
Working on this in `sonic-sketchpane`:

Tasks:
  - [ ] Normalize inputs to be independent of canvas size
  - [ ] Record a cleaner version of the drawing sound texture
  - [ ] Unique sounds for each brush
  - [ ] Sound design for other interface elements (toolbar)

**Comment by setpixel** [comment]
Still need sounds for remaining UI elements, operations, and events, e.g.:

- New Board
- Delete Board
- Flip Board

**Comment by audionerd** [comment]
- Clear/Trash sounds
- Undo/redo sounds

**Comment by setpixel** [comment]
Tooltip

**Comment by audionerd** [comment]
Still need sounds for remaining UI elements, operations, and events, e.g.:

- [ ] New Board
- [ ] Delete Board
- [x] Clear/Trash Board
- [ ] Undo
- [ ] Redo
- [ ] Flip Board
- [ ] Tooltip appears
- [ ] Context Menu appears

**Comment by audionerd** [comment]
Added a bunch in #258

**Comment by setpixel** [comment]
Added a sound for duplicate
