### ISSUE TITLE
Storyboarded doesn't work

### ISSUE THREAD

**Issue by thvi** [wonderunit/storyboarder#506]
https://drive.google.com/file/d/0B7zCpk0Wxgb1eHMtR0s0d2paaTQ/view

Best regards,
Thierry

**Comment by setpixel** [comment]
@thierry hmmmm - we have a new version coming out on monday that should show why this error is happening. would you mind testing after we release the new version tomorrow?

**Comment by thvi** [comment]
👍



Cordialement,
Thierry Vilaysith <http://anglapar.fr/>  |  Blog
<http://anglapar.fr/blog/retours-d-experience.php>
06 26 22 52 38
Linkedin <http://www.linkedin.com/in/thierryvilaysith>, Twitter
<https://twitter.com/thvi>, Behance
<http://www.behance.net/thierryvilaysith> & Youtube
<https://www.youtube.com/channel/UC1q3msBtvqF620UEaDaosbA>.

**Comment by setpixel** [comment]
hi @thvi can you try the new version now?

**Comment by setpixel** [comment]
any luck?

**Comment by thvi** [comment]
Nope :( https://drive.google.com/file/d/0B7zCpk0Wxgb1OFVwdlc2eExBQzA/view


Storyboarder-0.10.2.dmg



Cordialement,
Thierry Vilaysith <http://anglapar.fr/>  |  Blog
<http://anglapar.fr/blog/retours-d-experience.php>
06 26 22 52 38
Linkedin <http://www.linkedin.com/in/thierryvilaysith>, Twitter
<https://twitter.com/thvi>, Behance
<http://www.behance.net/thierryvilaysith> & Youtube
<https://www.youtube.com/channel/UC1q3msBtvqF620UEaDaosbA>.

**Comment by setpixel** [comment]
Are you on skype or google hangouts? I could guide you through finding the error so I could fix it.

**Comment by audionerd** [comment]
Sounds like the same error described in #553.
