### ISSUE TITLE
UI hanging off the right edge of the screen in full screen mode.

### ISSUE THREAD

**Issue by dschuttenhelm** [wonderunit/storyboarder#521]
macOS Sierra 10.12.6

On my 1600x1200 Cintiq21UX the UI over hangs the screen on the right.
On my actual iMac monitor, it fits fine.
Screenshot:
[https://drive.google.com/file/d/0B3K6_p3edXwncWlsenctZm5SeVU/view?usp=sharing](url)

**Comment by setpixel** [comment]
@dschuttenhelm this should be fixed in the version that is currently up now.
