### ISSUE TITLE
MAC - Export to PDF Doesn't work

### ISSUE THREAD

**Issue by gumogo** [wonderunit/storyboarder#535]
When I try to export a scene pdf it never finishes, output file is 15 bytes :/ is there something I can do?

Thanks!

**Comment by setpixel** [comment]
Hmm - can you tell me more about what you're trying to export?

**Comment by gumogo** [comment]
It's the first scene of a script, 34 boards. Maybe it doesn't work because there's no boards in the other 25 scenes?

**Comment by setpixel** [comment]
Would you be able to zip the folder and send it to me?

**Comment by gumogo** [comment]
Sure thing!

[Script+Folder.zip](https://github.com/wonderunit/storyboarder/files/1254112/Script.Folder.zip)

**Comment by setpixel** [comment]
Ok! I see the bug. I've actually already fixed the bug. There will be a new release on Monday with the fix. Can you wait until then?

**Comment by gumogo** [comment]
Of Course! Thank you very much, I'll be waiting for the update on monday! Greetings from Chile, your software is awesome!!

**Comment by setpixel** [comment]
@gumogo also please try this - it should work fine now.
