### ISSUE TITLE
Pressure sensibility in windows 10 pro and surface pro

### ISSUE THREAD

**Issue by boarderfrance** [wonderunit/storyboarder#536]
In StoryBoarder, I have no pressure sensibility with Wacom Bamboo Pen or with the Stylet Surface 4 on Windows 10 pro, (both on a surface 4 and a workstation HP) even if I install Wintab Drivers.
The pressure work on other drawing programs (Photoshop CS6, Artrage, Medi Bang, Springboard, Krita...) but not on Story boarder.

**Comment by setpixel** [comment]
There is a fix for this coming very soon. We are waiting for an external library to be released. It should be this next week!

**Comment by boarderfrance** [comment]
Many thanks for your so fast answer!
Benoît

2017-08-27 8:14 GMT+02:00 Charles Forman <notifications@github.com>:

**Comment by setpixel** [comment]
Duplicate #194
