### ISSUE TITLE
"Error: I couldn't find 4 corners of the paper in the image."

### ISSUE THREAD

**Issue by gumogo** [wonderunit/storyboarder#538]
I scanned a worksheet I printed and when I try to import it into the software it shows this: "Error: I couldn't find 4 corners of the paper in the image." What does it mean? Is there something I could be doing wrong?

**Comment by setpixel** [comment]
hi!! in the next release - there is a screen for this so you can pick the corners if the algorithm doesnt find automatically.

I think the place is to release a version on monday. it will have this.

**Comment by gumogo** [comment]
Great! Thank you very much!

**Comment by setpixel** [comment]
@gumogo what other features would you like to see in storyboarder?

**Comment by gumogo** [comment]
Thanks for asking! I think it would be pretty nice to have more settings creating pdf's documents, like sort out the scenes by shooting days and the boards in order of filming, maybe put information of the location, the hour, etc... so you can print it and take the document to the set and mark every shot as you film it, A way to organize the shoot and not forget anything! :D 🎞

**Comment by setpixel** [comment]
Hmmm - so you want a way to do scheduling in the app? How do you think it should work?

Do you have any examples of the pdf output the way it should look?

**Comment by gumogo** [comment]
I made something like this for a shoot I had in my film school, but to be able to do it automatically would be great.

Here's an example I made:
![example pdf](https://user-images.githubusercontent.com/31378692/29755184-716709ee-8b6a-11e7-8457-9add7321c421.jpg)

**Comment by gumogo** [comment]
(I misspelled "Project" because I was thinking of "Proyecto" in Spanish) 😅 my bad.

**Comment by setpixel** [comment]
Cool. Where do you think is a place to enter information about shooting
days and locations?

**Comment by gumogo** [comment]
That's a good question, maybe it could be a button that opens another interface, were you have a summary of the project. Were you can see every scene and every board at once in one side, and you drag and drop the shots in the other side to start organizing the schedule, maybe an "+ Add Shoot Day" button where you put the day and location, then another button than allows you to set a time period for every sequence of shots.

In the bottom there could be a button to formats all that information in a PDF. (This could be really difficult to do and I'm just talking out of my ass here but I know nothing about programming or anything, i'm just imagining what would be the most convenient, so I apologize in advance).

I hope this could be possible in some way and I thank you again for listening to people's feedback, it's awesome to feel part of the process of making a useful tool for all the growing filmmakers out there. Cheers!

**Comment by setpixel** [comment]
@gumogo awesome!!!

Theres a new version that allows you to select the corners of the image. Please try it and tell me what you think!

**Comment by gumogo** [comment]
Thanks! I tried both things and they work just fine! Thanks :)!!!
________________________________
De: Charles Forman <notifications@github.com>
Enviado: lunes, 28 de agosto de 2017 20:48
Para: wonderunit/storyboarder
Cc: gumogo; Mention
Asunto: Re: [wonderunit/storyboarder] "Error: I couldn't find 4 corners of the paper in the image." (#538)


Closed #538<https://github.com/wonderunit/storyboarder/issues/538>.
