### ISSUE TITLE
error creating webgl context if graphics card does not support gl

### ISSUE THREAD

**Issue by deomacius** [wonderunit/storyboarder#553]
Tried launching Version 0.10.1 (0.10.1) under Mac OS 10.12.6 and creating a new project when I got the following error:

Uncaught TypeError: Cannot read property 'getExtension' of null

In file: /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/vendor/three.min.js#125:226

A black popup with the name of my project and "Loading User Interface..." is as far as it gets.

![screen shot 2017-08-29 at 7 41 55 pm](https://user-images.githubusercontent.com/5726098/29853004-29fd7988-8cf2-11e7-8627-d4125ba0cf38.png)

**Comment by setpixel** [comment]
Checking now!

**Comment by setpixel** [comment]
How did you create a new project? (I can't recreate the error yet)

**Comment by deomacius** [comment]
1. Launched the app.
2. Clicked Create New Storyboard...
3. Clicked Create a blank... on the sheet that comes up.
4. Selected HD 16:9 on the next sheet.
5. Selected a save location on the Desktop and clicked Create.

I initially noticed this while trying to open a Storyboarder file that was created in an older version of the software. Then I tried creating a new project and am seeing the same behavior.

**Comment by setpixel** [comment]
Actually could you tell me what kind of mac you are on? I think the problem might be specific to a 3d shader I wrote. It may not be supported on your computer

**Comment by deomacius** [comment]
*GULP*

MacBook Pro (13-inch, Early 2011)

**Comment by setpixel** [comment]
Also - how technical are you? would you be able to open dev tools? I can walk you through it..

**Comment by deomacius** [comment]
Fairly technical, though not a full fledged programmer. Do we need to move this out of this thread?

**Comment by setpixel** [comment]
Are you on google hangouts or skype?

**Comment by deomacius** [comment]
Google Hangouts. Invite sent.

**Comment by setpixel** [comment]
error creating webgl context.

need to check if possible first, and then if not, disable sts.

![image](https://user-images.githubusercontent.com/441117/29854347-565a61be-8d13-11e7-8ff1-1eacc626587b.png)

**Comment by setpixel** [comment]
I will be pushing up a version tonight that **should** fix this. I'll need  @deomacius to confirm

**Comment by deomacius** [comment]
App is loading!

There are some additional issues with the menus, but I'll create a new issue for those.

**Comment by setpixel** [comment]
Woot! Will follow up there.
