### ISSUE TITLE
Uncaught TypeError when accessing some menus on computers with older graphics cards

### ISSUE THREAD

**Issue by deomacius** [wonderunit/storyboarder#559]
Seeing the following error when accessing certain menus.

```
Uncaught TypeError: Cannot read property 'context' of undefined
In file: /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/shot-template-system/index.js#1452:31
```

Menus are:
View -> Toggle Thirds Guide
View -> Toggle 3D Guide

**Comment by setpixel** [comment]
Can you confirm that Toggle thirds guide creates an error? It shouldn't

Only Toggle 3D guide should.

**Comment by deomacius** [comment]
Ah yes. You're right. Just double checked the behavior and the Toggle thirds menu is behaving normally.

**Comment by setpixel** [comment]
Great thanks!!

**Comment by audionerd** [comment]
We have a fix for this now. It will disable features that require WebGL on systems that don’t support WebGL. We'll release the fix in Beta 12.
