### ISSUE TITLE
Unable to install update on a machine that requires admin authentication

### ISSUE THREAD

**Issue by alexrest** [wonderunit/storyboarder#564]
I currently have v0.10.2 and get a prompt to upgrade to v0.11 on startup. When the download completes and it tries to install, Storyboarder closes, then reopens and it's still v0.10.2. Rinse and repeat and no matter what I still have v0.10

I suspect this is because I'm using a company Mac and my user account is not an administrator. With other apps, I have to enter an admin username and password in order to complete the installation. Storyboarder never prompts me for this, so I'm guessing the upgrade fails. This makes it super painful to download new versions of Storyboarder.

**Comment by audionerd** [comment]
Thanks for the report. I suspect this is an issue with `electron-updater`, the library we're using to manage automatic updates.

Might be a good idea for Storyboarder to check if it has write access before quitting and attempting the install.

**Comment by setpixel** [comment]
Please reopen if not fixed.
