### ISSUE TITLE
High CPU usage when sound is enabled.

### ISSUE THREAD

**Issue by TunableRoom9** [wonderunit/storyboarder#565]
So I was using Storyboarder (Windows 10) and noticed that when enabling "drawing sound effects", "drawing melodies" and "interface sound effects" my CPU would go up to 54%. I don't know if this is normal but I thought I might as well let you know.

Sound enabled:
<img width="1080" alt="with sound" src="https://user-images.githubusercontent.com/11317830/30071577-798938e6-9267-11e7-8de5-e7a6d32235db.PNG">

Sound disabled:
<img width="1080" alt="without sound" src="https://user-images.githubusercontent.com/11317830/30071569-7391647c-9267-11e7-91da-eb65446e512a.PNG">

**Comment by setpixel** [comment]
Yeah :/ we know about it.. you can turn it off in prefs. We need to optimize sound generation for the future.

**Comment by Templarian** [comment]
Been playing around, it's a really nice application for quickly sketching frames, but _first_ impressions were a little negatively impacted until I turned off sound yesterday. It's probably a big enough issue to justify disabling sound as the default. I could even notice it on a Surface Pro (5).

Brings up a little larger question of is sound really needed? Not something I've ever seen.

**Comment by audionerd** [comment]
Related to #551

**Comment by setpixel** [comment]
Sound is off by default now, should readdress in the future.
