### ISSUE TITLE
No pen pressure plus super dupper laggy!!

### ISSUE THREAD

**Issue by Phoninskis** [wonderunit/storyboarder#568]
I'm having really laggy/jagged lines when i draw fast, i even turned off the stabilizer to see if it'd help but no luck!

![image](https://user-images.githubusercontent.com/12792460/30095306-8e273b12-9286-11e7-8176-cbd611fbcd5e.png)

Here's some shots of my System Info if it helps:
![image](https://user-images.githubusercontent.com/12792460/30095329-ad655162-9286-11e7-82b6-03230f7a2c1e.png)

![image](https://user-images.githubusercontent.com/12792460/30095332-b2323048-9286-11e7-8fa6-c3d7c1ead1c2.png)

**Comment by dogabner** [comment]
![Uploading image.png…]()
Pen pressure works well on Surface Pro 4. But it runs super slow and  and eats my CPU.

**Comment by dogabner** [comment]
![_20170906212746](https://user-images.githubusercontent.com/11450267/30114518-a2279598-934a-11e7-982b-62db6abc231f.png)
Pen pressure works well on my Surface Pro 4. But the program runs really slow and eats my CPU.

**Comment by madocallie** [comment]
Can second these  issues... I've been trying to work with Storyboarder and the pencil tools feel very laggy and unnatural, especially since I naturally draw my lines quite quickly. It doesn't feel very fun to draw in so far. :c

**Comment by jellofu** [comment]
I've also been having this issue on OSX 10.10.5 with a cintiq 13HD. Hope it gets resolved soon, cause this seems like it'd be a great software.

**Comment by winkwonk** [comment]
This also happens to me, please help aaaaa

**Comment by setpixel** [comment]
Will be fixed with new drawing engine.
