### ISSUE TITLE
Pen Pressure not supported with HUION tablet

### ISSUE THREAD

**Issue by nicodoll** [wonderunit/storyboarder#569]
Pen Pressure doesn't seem to be supported when using a HUION tablet. I have a HUION H610 with up-to-date drivers. 
![image](https://user-images.githubusercontent.com/1085219/30095495-0f802d3a-92a1-11e7-91f1-dd262dc0b334.png)

**Comment by setpixel** [comment]
Does this work with newer updates of the drivers?
