### ISSUE TITLE
Support Code Signing for macOS and Windows Release Builds

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#57]
Guide for macOS:
https://pracucci.com/atom-electron-signing-mac-app.html

Notes on Windows:
https://blog.dcpos.ch/how-to-make-your-electron-app-sexy

Reference:
https://github.com/electron-userland/electron-osx-sign
http://vilar.cc/2015/codesign-electron-continuous-integration/
https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md
https://epxx.co/artigos/electronsign.html
http://eragonj.me/blog/electron-how-to-codesign-your-mac-app.html
http://jbavari.github.io/blog/2015/08/14/codesigning-electron-applications/

**Comment by setpixel** [comment]
I believe this is complete
