### ISSUE TITLE
Issue with german keyboard layout

### ISSUE THREAD

**Issue by tobkum** [wonderunit/storyboarder#571]
It would be great to be able to customize the shortcuts. Since I am on a german keyboard layout, I have to press ALT GR + 8 for a open square bracket [, but that registers as option key in Storyboarder, so there's no way for me to change brush size via shortcut.

**Comment by setpixel** [comment]
Oh hmmm....

Interesting. I haven't thought much about this, but I know that we hate the way key commands currently work internally. I think in the next version we would like to support customizable commands.

**Comment by setpixel** [comment]
We will be supporting fully editable key command bindings in a very near version: please track here #887 I'm closing this to merge into that issue.
