### ISSUE TITLE
Add touch support 

### ISSUE THREAD

**Issue by eliiik** [wonderunit/storyboarder#572]
I use two fingers gesture trying to zoom in with the program running on my Surface Pro 4. 

It did zooms but the whole interface all zooms in. And it draws strange lines while my finger moving which **cannot UNDO**.

![_20170906213749](https://user-images.githubusercontent.com/11450267/30115156-701fe40e-934c-11e7-8360-2012f005eaaa.png)

**Comment by setpixel** [comment]
Will address with #1062
