### ISSUE TITLE
Worksheet Import glitches.

### ISSUE THREAD

**Issue by DCNielsen** [wonderunit/storyboarder#573]
I love this Worksheet Import feature - been trying it out a little more though and ran into some problems.

I've done some little practice studies while I watch TV. I've got a sheet printed out that's 8x8. Scanned it in at 300dpi and saved as JPG. Here's a down-rezzed preview of what I'm using.

![image](https://user-images.githubusercontent.com/8259314/30117802-ea627efe-92e6-11e7-9bd8-888d56c0e003.png)

When I went to import in Storyboarder, only half of the images made it through. I'm using all 64 panels, but I end up with only 32 scanned in.

![image](https://user-images.githubusercontent.com/8259314/30118012-8119f7c8-92e7-11e7-81c9-dc0d814e9b3f.png)

I'm also have a consistent difficulty with Storyboarder not being able to read the QR code. The auto-import is such a great feature, that I don't mind keying a code in if I have to. What could kill it is losing half my frames. 

Have you guys run into this?

**Comment by setpixel** [comment]
OH!! OK yes - I know whats going on here. I'm going to make an option to turn off a feature that doesn't import blank boards. The problem is that it thinks some of the boards are blank.

**Comment by DCNielsen** [comment]
Cool, thanks. I do like that blank boards feature. I wonder why it's seeing these as blank though? There's clearly lots of data there, yeah? I mean frame 3 is half-way filled in.

**Comment by setpixel** [comment]
@DCNielsen so the big problem is that my method of figuring out if a board is blank is pretty garbage.

Currently, it finds the edges, and if there is enough visual complexity, it's probably not empty. But its the edges are soft, like in your example, it doesnt work. So I think a much better way is actually to do a histogram. Which is also more simple. 

In the meantime it will be an option.

**Comment by DCNielsen** [comment]
👍
