### ISSUE TITLE
storyboarder no pressure sensitivity

### ISSUE THREAD

**Issue by crazylittlepotato** [wonderunit/storyboarder#575]
Hello, I just downloaded storyboarder and when I try to draw it doesn't have pressure sensitivity. I have a bamboo wacom and I was wondering if the problem could be solved. Thank you.

**Comment by setpixel** [comment]
Hi @crazylittlepotato --

Are you on windows or mac? And what operating system? Also, does pressure work fine in other apps like photoshop?

I really want to try to figure out a solution.

**Comment by thewhiteleaf** [comment]
Downloaded earlier today and have a similar issue. Zero pressure sensitivity Windows 10. Cintiq Driver 6.3.24-2 (they updated this week)

**Comment by crazylittlepotato** [comment]
I am on windows 7 and pressure works fine in photoshop.
<#m_-8331882726448712499_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-09-06 18:42 GMT-03:00 thewhiteleaf <notifications@github.com>:

**Comment by crazylittlepotato** [comment]
I am on windows 7 and pressure works fine in photoshop.

**Comment by setpixel** [comment]
hmm - I have windows 8 here. I need to get a windows 10 machine to test with.

**Comment by Templarian** [comment]
Windows 10 + Surface Pro is fine.
Windows 10 + Desktop with a 13HD Cintiq w/ latest drivers works (updated before testing).

Wacom uses the same driver release for all their products I think, so it seems odd it wouldn't work across their products (at least with Windows 10).

**Comment by thewhiteleaf** [comment]
I failed to mention I'm on a Cintiq 13HD, pressure sensitivity works fine in PS but not in storyboarder

**Comment by joluga** [comment]
Just downloaded. Not pressure sensitivity too in Storyboarder. Using Windows 10 and a Wacom Intuos 3.

**Comment by sketchyfriend** [comment]
Does anyone of you using a Wacom tablet have **Windows Ink unchecked in the Wacom default mapping?** _(It would make sense because it's bad)_ But, in that case; try making an application specific mapping for Storyboarder and check Windows Ink;

![storyboarder](https://user-images.githubusercontent.com/31743385/30244003-f7a76c10-95b5-11e7-8b78-261029e27cd7.JPG)

**Comment by setpixel** [comment]
Please comment if this is still an issues.
