### ISSUE TITLE
Save as...

### ISSUE THREAD

**Issue by kcrsl** [wonderunit/storyboarder#576]
Would be great to have a save as function for version control.

**Comment by setpixel** [comment]
Oh hmm.. how do you think it should work?

We actually use github for our version control, so we don't need to save different versions, we just check into github. But I totally understand that most people aren't into using github.

**Comment by kcrsl** [comment]
Sorry, I meant version control for boards! I am working on a scene and I
want to save a version, make a big change and compare. Currently, there is
no saving different versions correct?

**Comment by kcrsl** [comment]
btw, what you have going is dope.

**Comment by setpixel** [comment]
Oh yeah! I've thought about this before. Hmmmmm. How do you think it should work? We haven't thought much about it because it complicates the interface, but I can't argue with good ideas!

**Comment by kcrsl** [comment]
Save as function seems the most straight forward. Although it might be interesting if you had a 'snapshot' function, a la the photoshop history browser. Some clever visual way to maintain multiple versions of a scene and be able to call them up quickly. There's always going to be a moment where I want to save a current version, and branch off to try something new or to be able to pitch variations.

**Comment by datascienceteam01** [comment]
Using "Save as" function to Rename doesn't properly relink a project's object's . The duplicate project is simply unusable. Please implement a proper "Project Settings" tab to at least 1. Rename the project 2. Change the project's aspect ratio.

**Comment by audionerd** [comment]
> The duplicate project is simply unusable.
Can you describe this a bit more? What happens when you try to open the duplicate project? What logs do you see?

Can you send us an example original source project (as a ZIP) which caused "Save As" to fail?
