### ISSUE TITLE
Lag?

### ISSUE THREAD

**Issue by julielineberry** [wonderunit/storyboarder#580]
I just downloaded the program and am having an issue with some pretty intense lag. Is there any way to fix this?

**Comment by setpixel** [comment]
Hi @julielineberry,

Can you go to preferences and turn off everything, close the app, reopen and see if that affects performance?

**Comment by julielineberry** [comment]
Yes! The response is working a lot better now. There is no more lag, but
fast, curved lines are not smooth and can come out jagged. If I do it
slowly, it comes out smooth.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by setpixel** [comment]
This will be fixed with the new version of the drawing engine.

**Comment by julielineberry** [comment]
Thanks! I apprecaite your time!
