### ISSUE TITLE
Can't open main menu with Intous3 on Windows 10

### ISSUE THREAD

**Issue by vovkasolovev** [wonderunit/storyboarder#581]
Windows 10: Can't access menu items from the Wacom Intous3. They just don't open on click.
My tablet work perfect in another programs.
Maybe something with a known issue with tablets and handwriting in Windows 10?

**Comment by christiansass** [comment]
this should be consolidated to https://github.com/wonderunit/storyboarder/issues/731 since its a more general bug than just intuos 3 and windows 10   -  its all wacom tablets on any windows from what i can tell
