### ISSUE TITLE
Some problems for wacom 13hd touch

### ISSUE THREAD

**Issue by KardinalErregebe** [wonderunit/storyboarder#582]
Hi, sorry for my english, I like storyboarder a lot but I couldn´t find a way to make the sketch pane bigger, is very small. I had to cycle view modes to increase it size but I want to use it as you posted in your page. Also a zooming and rotation feature for the sketch pane would be great. Maybe the size of the brush tool is too big for a 13hd. Tried "disable display scaling on high DPI settings" but it didnt work

![image](https://user-images.githubusercontent.com/31714616/30141554-979ebe6e-9352-11e7-9bef-8e6415dbfba9.png)

-Related to this problem when Looking for a shortcut for this issue i found  that the Key commands window is cropped 

![image](https://user-images.githubusercontent.com/31714616/30141643-197c5bbc-9353-11e7-82c8-eb29d4560baa.png)

Found that Brush is a bit rough in curves

![image](https://user-images.githubusercontent.com/31714616/30142110-5c18d354-9355-11e7-97c7-f7573738b29e.png)

-I think resize and move tool could be rounded in a traditional free transform tool with rotation, skew and corner pin transform, like photoshop, not the abomination of illustrator :) 

-The preferences window have the same menu options as the main window, also a preferences option :D 
  
I Hope this will help to improve Storyboarder, is a great tool.

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
