### ISSUE TITLE
Shot generator

### ISSUE THREAD

**Issue by wadoiji** [wonderunit/storyboarder#583]
Shot generator mode didn't appear. How can I do?
https://imgur.com/AZRticF
https://imgur.com/a/cUJp7

Thank you very much.

wadoiji23@gmail.com

**Comment by satishgoda** [comment]
You need to scroll down to see the shot generator. As I was using a wacom, i had to click drag the area mext to the canvas.

**Comment by audionerd** [comment]
Some machines with older graphics cards don't support WebGL, which Storyboarder needs to run the Shot Generator. I'm guessing this is the issue you're running into.

In the upcoming Beta 12 release, we'll warn you if your graphics card is not supported, which would at least confirm if this is the problem or not. We also have fixed the error alert you were seeing as part of #626.

**Comment by Nuculeus** [comment]
Thanks a lot for the mail Eric,
Used the shot Generator for the first time today- it's been time for a
newer Mac anyway ;)

Thanks a lot for this awesome piece of Software, will make a big part of a
very happy new life!!!

Kind regards from Austria!

Sebastian

Am 13.09.2017 10:24 nachm. schrieb "Eric Skogen" <notifications@github.com>:
