### ISSUE TITLE
Key Command Screen not fully viewable?

### ISSUE THREAD

**Issue by RenaLus** [wonderunit/storyboarder#586]
Hey there!

Discovered the program yesterday and so far I really enjoy it. Great job y'all!
Only bug I've seen up to now is that the key command screen isn't fully viewable? It cuts off on the right side...

![key command screen](https://user-images.githubusercontent.com/31723195/30150036-2aab143a-93aa-11e7-8c5e-a1ee3cdedfac.PNG)

LLAP, Rena _(@vluscinias on Twitter)_

**Comment by audionerd** [comment]
Thanks for reporting this. We'll take a look.

**Comment by setpixel** [comment]
@RenaLus we fixed this!
