### ISSUE TITLE
drawing bug: edgy geometric lines

### ISSUE THREAD

**Issue by franklomb** [wonderunit/storyboarder#590]
when drawing with any tool if I make fast moves with wacom or mouse I get edgy geometric lines instead of smooth circular ones which would correspond to my move. 
maybe its because of my computer performance which is not that powerful, however in photoshop I dont have this issue.
![lines](https://user-images.githubusercontent.com/31736212/30170101-95c2f354-93c4-11e7-9c8b-d19822bd2551.jpg)

**Comment by cg-cnu** [comment]
I am on windows 10 with bamboo. I have a decent spec but It's the same for me. 
@franklomb Can you share what os are you using ?

**Comment by franklomb** [comment]
I am using Windows 8 Pro. its dual core, 6gb RAM.
but I just talked with a friend and he had the same issue.

**Comment by franklomb** [comment]
oh, and I used Wacom Intuous 4

**Comment by cg-cnu** [comment]
Yes, that seems to be universal. Thanks for confirming 👍

**Comment by franklomb** [comment]
would be good to see a fix in this, becuase it pushes you to use PS for drawing

**Comment by franklomb** [comment]
also, a layers option would be nice

**Comment by cg-cnu** [comment]
This is what readme says about it...

> There are no layers. Again, you're boarding story ideas. Managing layers creates so much uneeded complexity and ui mess. A board artist that uses layers probably voted for Trump - or paid way too much for "Pro" storyboard software.

And I pretty much agree with it. It would be a overkill for a story boarding app 🙂

**Comment by franklomb** [comment]
a camera symbol library could also help to express:
zoom in, pan, etc

**Comment by cg-cnu** [comment]
@franklomb Hmm... that's interesting. 
Try creating a new issue for each idea/bug you face.  
This will help not mixing up in the conversion and keep track of the progress. :smile:

**Comment by qs2435** [comment]
I've the same issue, 
Windows 10 + Wacom Intuos Pro

**Comment by setpixel** [comment]
Will be fixed with new drawing engine!
