### ISSUE TITLE
Pen pressure tied to Windows Ink

### ISSUE THREAD

**Issue by circusmnstr** [wonderunit/storyboarder#591]
I just downloaded the program and I super love it, very excited to use it, but I'm having a problem with pen pressure. The only way it's recognized is if Windows Ink is enabled, and drawing with Windows Ink on is a nightmare due to the double-click feedback and stuff, which is the only thing I can't turn off. 
Is there a fix for this, or is this just the only way it works right now?
I'm using Windows 7 and a Wacom Intuos Pro if it helps.

Thanks in advance and bless you for this lovely program

**Comment by sketchyfriend** [comment]
I can second this, pressure works on my Surface Pro 4 (N-trig tech, Windows ink) but is super laggy and overall horrible like everything else due to N-trig and Windows ink. On desktop with a Wacom there is no lag but also no pressure sensitivity.

It would be nice to have the same option as PS where you can choose to run the often superior Wintab (legacy) instead of Windows Ink.

**Comment by circusmnstr** [comment]
@sketchyfriend This one here! I can turn off things like flicks and certain feedbacks, but the rings/ripples you get when clicking with the pen are still there. It's not the worst thing in the world but it does create a tiny amount of "stick" and latency when drawing, especially if you make quick successive lines ):
![2017-09-08_22-19-46](https://user-images.githubusercontent.com/31739146/30236273-e1c35a8a-94e3-11e7-8085-8bac200cd045.png)

**Comment by sketchyfriend** [comment]
@circusmnstr I don't have them anymore and although it was a long time ago I'm pretty sure I just google "remove ripple effect wacom" everytime I get a new computer. :) 

You can also try to set double-tap distance to zero in Wacom settings, if I remember correctly that has helped some with the small quick stroke issue in other applications.

Best would of course be if we could use the legacy drivers like in PS. :/

**Comment by circusmnstr** [comment]
@sketchyfriend oh my god you're a saint, thank you! still would definitely prefer legacy drivers too but for now this is much better at least! 

for anyone else here's the steps:
1. Open Local Group Policy Editor: Run... _gpedit.msc_
2. Navigate to _User Configuration_ - _Administrative Templates_ - _Windows Components_ - _Tablet PC_ - _Cursors_
3. Enable the _Turn off pen feedback_ setting.
