### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getIsQuickErasing' of undefined

### ISSUE THREAD

**Issue by bendelaney** [wonderunit/storyboarder#595]
![bug](https://user-images.githubusercontent.com/2540708/30177856-e7382eec-93bb-11e7-92ba-9a994c1632c9.png)

This occurred after I hit command+R to **Reload**. After the app reloads, any key-press triggers this error.

**Comment by audionerd** [comment]
Thanks for the report. Can you describe step-by-step how to reproduce this error?

**Comment by audionerd** [comment]
I see. The app doesn't know how to properly reload with Command+R, so it will break. We should probably prevent that key command.

Why did you want to use Command+R?

**Comment by bendelaney** [comment]
I wanted to reload because I made changes to the script and wanted to see if those would be reloaded (btw, how is that process supposed to happen??)

It’s also in the Tools menu. So you might want to remove it from that menu if you don’t want anyone trying it for now.

Thanks!

Ben

**Comment by audionerd** [comment]
Good point, Ben. I'm now working on a fix to prevent reloading, to avoid confusion. #603

AFIAK the only way currently to refresh the screenplay is to close and re-open the project. In the future we'd like to make that process easier, maybe even automatic.

**Comment by bendelaney** [comment]
Yes, making that automatic would be great. For my list test, the script was/is still in flux and being able to change it on the fly and have Storyboarder follow along would be nice. Would be even better if one could edit the script within the app - perhaps even just being able to edit the scene name/label.

**Comment by satishgoda** [comment]
I came across this issue under the same use case as the reporter. Glad to see that it is fixed.
