### ISSUE TITLE
Make new board 'active' on creation

### ISSUE THREAD

**Issue by cg-cnu** [wonderunit/storyboarder#598]
The new board created has to be made active on creation by default. 
Currently, just a new board is created and the old board is still active.
Would love to hear what you guys think 😄

**Comment by cg-cnu** [comment]
I tried fixing it with this pr; Again, still getting used to the git flow. Please excuse me 🙂

**Comment by audionerd** [comment]
I think we ended up fixing this another way in v0.12.1. Should now behave as you describe (an artist invokes a New Board command, the new board is created, and the UI switches over to that new board).

FWIW the `newBoard` function doesn't call any navigation directly. Typically we chain it, and navigate after it completes, e.g.:
```
newBoard().then(() => gotoBoard(currentBoard + 1))
```
