### ISSUE TITLE
list all the `un-features` ;)

### ISSUE THREAD

**Issue by cg-cnu** [wonderunit/storyboarder#600]
Love the ideas and philosophy behind the project. 
Couple of things like not having layers might be a little shocking for some people. Like here.. #590 
Or people might miss out on the description provided in readme.

To avoid repeated discussions in the forums/issues... 
Can we add them as `un-features` checklist in the readme below the features. 
This give a good idea for the users as to what to expect and what not to expect from the tool.

The title can `un-features` or `won't implement` or something like that... 😄 
Again, inputs are welcome.

**Comment by audionerd** [comment]
We've been talking about better ways to introduce Storyboarder, including possibly an intro video somewhere, to outline how it works and how it differs from other programs.

Re: Layers there is a bit in the wiki about how they work: https://github.com/wonderunit/storyboarder/wiki/Layers-in-Storyboarder
