### ISSUE TITLE
simplify key commands

### ISSUE THREAD

**Issue by cg-cnu** [wonderunit/storyboarder#602]
> We got mad simple key commands: - README.md

It's great that lot of shortcuts have been mapped and it eases up the workflow but I feel we can improve on these a little here. 

Heads up! I am inspired by [mypaint](http://mypaint.org/) and its optimal use of the key commands. The idea is to have all the shortcuts mapped in such a way, where we don't need to move the hand from the left side of the keyboard.

Basically, lets say we are using `del` button to delete the current board. In the middle of painting I have to lift my hand to move to the other end of the keyboard, press the `delete` button and find my way back. And, am not sure how many can do this blindly with out looking at the keyboard. The other scenario is where `x` deletes the current board. You don't need to move your hand. And we can blindly execute `x` when compared to `del`

This is a simple scenario, but the idea is to have as many key commands as possible on the left side to reduce the hand movement. 

Couple of things which can be optimized from the current list are... 

* Clear: <kbd>Delete</kbd> or <kbd>Backspace</kbd>
* Undo: <kbd>Cmd</kbd>+<kbd>z</kbd>
* Redo: <kbd>Cmd</kbd>+<kbd>y</kbd>
* Smaller Brush: <kbd>[</kbd>
* Bigger Brush: <kbd>]</kbd>

Thanks for the amazing work you guys are doing. Really appreciate open sourcing the tool 👍

**Comment by setpixel** [comment]
You can now edit key commands :D
