### ISSUE TITLE
Storyboards not printing

### ISSUE THREAD

**Issue by lobo36o** [wonderunit/storyboarder#606]
Hi! I was trying to print out a storyboard to hand draw it, but whenever I hit print, it just exits out of the application. Also the export as pdf button does not seem to respond at all

**Comment by audionerd** [comment]
Export to PDF should write a file to the `exports` folder within your project. Are you able to find that PDF?

**Comment by lobo36o** [comment]
Hmm nope, all that gets exported is an empty image, and looking through the folders there's nothing I can find that would hint to a storyboard

**Comment by setpixel** [comment]
Can you confirm if this is fixed in the latest version?
