### ISSUE TITLE
Current panel turns black and work disappears

### ISSUE THREAD

**Issue by chiffonrose** [wonderunit/storyboarder#607]
While drawing on a panel, it randomly turns black, and progress on said panel disappears and the pens don't work afterwards.  I am using a windows surface 3.  I've included a picture.  Thank you!
<img width="586" alt="prob" src="https://user-images.githubusercontent.com/31758895/30199502-070ba0ac-9441-11e7-9e53-9cf2dd192a46.PNG">

**Comment by audionerd** [comment]
Thanks for the report. It would be great if you could describe step-by-step how to reproduce this issue so we can dig in further. I haven't seen this before.

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!
