### ISSUE TITLE
THANK YOU!!!! (Not issue)

### ISSUE THREAD

**Issue by Felina-Lain** [wonderunit/storyboarder#608]
I couldn't find anywhere else so sorry if I this is out of place here but this software is pure gold! The interface is clean, neat and easy and this tool is something I always wished for without ever finding and you guys are amazing making it!

Thank you so so much!

(also I love the jokes and others that are everywhere XD)

**Comment by satishgoda** [comment]
Let me also chime in with a big THANK YOU :) The user interface is very slick and I just got my head around installing node and setup my dev environment.

See you all around.

**Comment by cg-cnu** [comment]
Yes, not an appropriate place! But... 
I would also like to thank you guys for all the work you have put into it and more for making it open source. You guys seriously ROCK! 👏

**Comment by Banbury** [comment]
If it's not appropriate, why do you do it anyway? You're spamming everyone subscribed to this repo.

Please stop.

**Comment by Felina-Lain** [comment]
I'm sorry, feel free to close this, I just couldn't find anywhere else to thank them, and thought good work deserved thanks.
Since they also wrote "PLEASE PLEASE PLEASE submit issues with bugs, ideas, suggestions, or any feedback! Thanks!"
I figured positive feedback was alright as well. But sorry if I made a mistake and close this if it bother people.

**Comment by audionerd** [comment]
Glad to hear you’re enjoying Storyboarder @Felina-Lain! Thanks for the kind words 🙏
