### ISSUE TITLE
welcome screen buttons grey on default

### ISSUE THREAD

**Issue by cg-cnu** [wonderunit/storyboarder#609]
The `getting-started` and `open-storyboard` are greyed out by default on launch. 

Fixed it from...
![screenshot 66](https://user-images.githubusercontent.com/2767425/30228029-992f73d8-94f9-11e7-8a9f-dc42811f673c.png)

to this...
![screenshot 65](https://user-images.githubusercontent.com/2767425/30228018-93cfc122-94f9-11e7-9ccb-5f35716acdac.png)

**Comment by audionerd** [comment]
Fixed "Open" in 0ae65ef. "Getting Started" isn't ready to enable yet.
