### ISSUE TITLE
Ability to HIDE the board from playback (toggle action)

### ISSUE THREAD

**Issue by satishgoda** [wonderunit/storyboarder#611]
As per conversation on e-mail with @setpixel, I have created this issue (new feature) 

Referring to the attachment below, the idea is to quickly mute a board so that during playback, it will not be considered.

![mute_board](https://user-images.githubusercontent.com/536008/30206187-dc00c5d6-94bd-11e7-8275-86453db9f5a9.PNG)

Thank you.

**Comment by setpixel** [comment]
I like this!

**Comment by setpixel** [comment]
Merged into #1244
