### ISSUE TITLE
Extreme lag when window is moved to a cintiq13hd

### ISSUE THREAD

**Issue by Whoolkan** [wonderunit/storyboarder#612]
whether i use the mouse or the pen, if storyboarder is located on the 2nd monitor (cintiq13hd) the input lag is extreme. lines are not smoothed anymore and the cursor jumps everywhere as if it is sampling a couple of times a second instead of continuously.

**Comment by MadamLily** [comment]
I have a similar problem. I use a Cintiq Companion 2 and the lag is very noticeable, especially when drawing with fast strokes. In my case the cursor follows the pen and the lines are still smooth, but they appear on the screen a bit after the movement has been made, making it hard to be precise.

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
