### ISSUE TITLE
PDFs not exporting properly

### ISSUE THREAD

**Issue by Rosie212** [wonderunit/storyboarder#615]
Hi,

When I export a PDF it isn't exporting properly. I don't get the folder with all the images and the XML meaning I can't open the PDF.

I worked once, randomly, but apart from that it hasn't. I am working on a mac.

Thanks for your help!

**Comment by audionerd** [comment]
Does Storyboarder fail to create a PDF file? Or does it create the PDF file but the PDF file can't be opened?

Can you attach an example of a project that fails to export as PDF? We'd need a zip file of the project root folder, with .storyboarder and images folder inside. Then we can try to debug.

BTW: Export to PDF should create just a PDF in the exports file. It won't create images or XML.

**Comment by audionerd** [comment]
Should be fixed in the upcoming Beta 13 release.
