### ISSUE TITLE
Any plans for iOS/Android port?

### ISSUE THREAD

**Issue by morevnaproject** [wonderunit/storyboarder#617]
Hello! Do you have any plans for iOS or Android port? ^__^

Relevant links:

- https://github.com/node-app
- https://github.com/node-on-mobile/node-on-android

Thank you!

**Comment by stevygee** [comment]
+1
This would be so great to have on iPad Pro!

**Comment by setpixel** [comment]
ipad in the works!

**Comment by fineline** [comment]
Awesome! Will it handle pressure with iPad Pencil? Like this lib:

https://pressurejs.com/

**Comment by dervondenbergen** [comment]
Hey, are there any updates on a iPad version?
