### ISSUE TITLE
Pen pressure

### ISSUE THREAD

**Issue by superpunksuperfunk** [wonderunit/storyboarder#618]
My drawing tablet pressure stops working everytime I open up storyboarder. I try closing it and restarting the driver but that does not seem to help. Ive also tried many other tablet related solutions but I still cant get any pen pressure to work.

**Comment by sketchyfriend** [comment]
Are you using a Wacom tablet and have Windows Ink disabled in your default Windows setting?

Try creating a separate Storyboarder application setting with Windows Ink enabled and see it that helps. (It worked for me)

Of course, then you are stuck with Windows Ink drivers. :/

**Comment by superpunksuperfunk** [comment]
I do not have windows ink.

**Comment by piearty** [comment]
I'm having the same problem and I don't have windows ink either. I'm on windows 10 using a huion tablet.

**Comment by sketchyfriend** [comment]
@superpunksuperfunk Windows Ink is the standard Windows tablet driver in Win 8/10 if I'm not mistaken and it's horrible - but, if you are using a Wacom tablet and have Windows Ink unchecked if your default mapping you can try making a new Storyboarder-specific mapping and check Windows Ink in that:

![storyboarder](https://user-images.githubusercontent.com/31743385/30243956-ae84a01c-95b4-11e7-9bc2-301469ba37c0.JPG)

@piearty No ideas for the Huion, sorry

**Comment by thewhiteleaf** [comment]
Here to confirm that the Windows Ink solution above works. I had Windows Ink checked, i had to uncheck it, check it again and then pressure sensitivity kicked in. Cintiq 13HD Windows 10

**Comment by superpunksuperfunk** [comment]
cool but I don't have windows ink. I use a different version of windows

**Comment by setpixel** [comment]
Please see #690 for pen issues support
