### ISSUE TITLE
UI: Canvas too small + some wasted space

### ISSUE THREAD

**Issue by kryptot7** [wonderunit/storyboarder#620]
First of all, **THANK YOU** for making a free, open-source tool like this! I'm so excited to use it for rapid prototyping my stories! 😁 I also love most of the jokes. Triple exclamation points and vertical aspect ratios 4ever! 😜

Anyway, the UI is pretty, but it could be more space-efficient. Right now, it leaves a relatively small space for the canvas, and I was disappointed to not be able to embiggen it. I know zooming in is coming soon, but until then, consider tweaking the UI so that the canvas is as big as possible. Fortunately, there's plenty of room. For example, as nice as the tool icons are, they seem needlessly big.

**Example**
BEFORE:
![image](https://user-images.githubusercontent.com/30781325/30226621-aeb12eae-94a4-11e7-84cc-ebc55306e76a.png)
AFTER:
![image](https://user-images.githubusercontent.com/30781325/30227030-237c235a-94a6-11e7-8960-5835d8200ec9.png)

(I also made the Size changer say Size on it to make it more clear, cause I was confused about its function at first o.O)
As an artist, a bigger canvas makes it much easier to draw well. I'm not a professional UX designer or anything but I think this will help a lot.

**Comment by satishgoda** [comment]
Pressing TAB key would toggle the other UI elements and make the canvas size bigger.

**Comment by kryptot7** [comment]
True, but that solution isn't ideal, because then you can't visually tell what tool is selected, and you can't edit dialogue or other shot info. Also, there's some unnecessary space around it even in this mode:
![image](https://user-images.githubusercontent.com/30781325/30286397-7ad6b6a6-96ef-11e7-8bd9-f00c94bdeea7.png)

**Comment by setpixel** [comment]
Will have the ability to scale canvas in new drawing engine!
