### ISSUE TITLE
add "size" text in the brush size tool for more clarity

### ISSUE THREAD

**Issue by cg-cnu** [wonderunit/storyboarder#621]
@kryptot7 on #620 says...

> (I also made the Size changer say Size on it to make it more clear, cause I was confused about its function at first o.O) 

Even I got confused and agree with his idea. 😄 
Going to create a pr fixing it. 
Thanks!

**Comment by cg-cnu** [comment]
Before
![screenshot 68](https://user-images.githubusercontent.com/2767425/30229179-8294bad4-94fe-11e7-9d65-373102aef37b.png)
After
![screenshot 67](https://user-images.githubusercontent.com/2767425/30229232-b8585df6-94fe-11e7-8cac-2d94f2476dc0.png)


@kryptot7 Let me know if this is fine. Thanks 😄

**Comment by kryptot7** [comment]
Looks good!

**Comment by audionerd** [comment]
Thanks for the note but I think we're going to leave as-is for 1.0. 

We do have a tooltip for brush size, so it's not completely unexplained. I think most artists understand what that value is for after they've used it a couple times.

**Comment by cg-cnu** [comment]
@audionerd Correct me if am wrong. I still feel it's a little confusing. Especially its placement, which is below the color picker. Can we move it next to the brushes to to make it more clear ? I will update with few mocks soon.
