### ISSUE TITLE
Undo/Delete Board Bug

### ISSUE THREAD

**Issue by supersabunni** [wonderunit/storyboarder#623]
If you accidentally delete a board (via shortcut or whatever) and undo, you do not get your board back! :(

**Comment by setpixel** [comment]
What if you press undo multiple times?

**Comment by supersabunni** [comment]
It didn't work, it just started undoing brushstrokes on the previous panel that I was working on. :(

**Comment by audionerd** [comment]
Yikes, this sounds bad. But I haven't yet been able to recreate this issue. The steps I took were:

- Create a new board
- Draw on it
- Press <key>Delete</key> to clear the board
- Press <key>Delete</key> again to remove the board
- Press undo once to redo, recreating the deleted board
- Press undo again to redo, re-selecting the deleted board
- Press delete again to redo, recreating the drawing

That worked as intended.

Can you describe a way to recreate the bug you saw?

**Comment by audionerd** [comment]
Might be related to #656. Without more specific steps to recreate the issue though, we're not able to track it down.

**Comment by supersabunni** [comment]
oops sorry it's been a busy couple of days for me!

I had accidentally pressed cmd+x
Which cased the board to disappear
And when I pressed undo, it replaced it with a copy of the previous board I was working on which was very strange
I hope that information helps, sorry for not responding sooner.

**Comment by audionerd** [comment]
Ok, thanks, that is helpful to know.

I think we might have fixed this bug in the latest release (Beta 12.1). Please download that from GitHub or wonderunit.com and give it a try.
