### ISSUE TITLE
Line drawing: disappearing lines, connected lines, cursor discontinuity

### ISSUE THREAD

**Issue by BoxxKitt** [wonderunit/storyboarder#628]
Hello, I have a few problems
1. Sometimes the lines that I just drew will disappear/turn invisible because it still counts in my line miles but it doesn't show up. 
2. When I write letters out at times they will connect like cursive for no reason??
3. Sometimes there will be like a pen will pop up for a second and then disappear right after.

**Comment by satishgoda** [comment]
I also noticed this (2 & 3) with my wacom intuous tablet on Windows 10

**Comment by audionerd** [comment]
Hey @BoxxKitt thanks for the report.

Is this with a pen or mouse? Can you share your operating system & version, the name of the pen tablet you're using, and any more about your hardware specs?

Can you attach a screen recording demonstrating these issues?

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
