### ISSUE TITLE
PDF export not working if ACTION field has more than 82 characters

### ISSUE THREAD

**Issue by fedorbauer** [wonderunit/storyboarder#629]
First of all, congrats on a great app and thanks for your efforts, this is a HUGE help to us all.

I have found that exporting to PDF fails when the field ACTION has more than 82 characters on a 16:9 format storyboard. This is also the visual limit (edge to edge) of shot represented in the PDF. The possible solutions I see here are either limiting the field to XY characters (depending on selected aspect ratio) or allowing 2 (or more) lines of text.

**Comment by setpixel** [comment]
This is fixed in the next version released!
