### ISSUE TITLE
high CPU consumption

### ISSUE THREAD

**Issue by aajr11** [wonderunit/storyboarder#630]
Hello friends,
I was testing your software and when running on a 4-core pc there is a high consumption of cpu, in the task manager comes out as a normal priority, I put it in low priority and greatly improve the cpu consumption, should lower the software priority by default so that consumes less cpu and run better on pc than not so many resources.

tested on a WIN 7 x64bits SP1
AMD A10-7860K Radeon R7
6.94 GB usable memory.

Saludos.

**Comment by setpixel** [comment]
Hi! We can't support windows 7 unfortunately :(((((
