### ISSUE TITLE
after awhile of drawing, lines i had made previously would dissapear when i made new ones

### ISSUE THREAD

**Issue by bazoodle** [wonderunit/storyboarder#631]

**Comment by audionerd** [comment]
Hey @bazoodle thanks for the report. Are you able to make a screen recording to demonstrate this bug? We haven't seen it before.

Also can you please report which operating system you're using (Mac, Windows, Linux) and its version, and any other hardware details about your computer you think might help?

**Comment by audionerd** [comment]
Possibly related to #628

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
