### ISSUE TITLE
No pressure sensitivity with wacom tablet and windows 7

### ISSUE THREAD

**Issue by eimibi** [wonderunit/storyboarder#632]
I have no pressure sensitivity at all when running storyboarder; it seems to pick it up as a laggy mouse input instead. Admittedly I have an old bamboo (CTL-470) but I have no issues in photoshop or any other art programs open at the same time and my drivers are up to date. ¯ \_(ツ)_/¯ 

I saw that others had success by switching off windows ink but 7 doesn't have this function so I'm at a loss.

**Comment by Rayek** [comment]
Same issue on an Asus EPE121: windows 7, built-in Wacom digitizer with pen. No pen pressure, and the pen eraser doesn't function either.

**Comment by litvac** [comment]
Storyboard is also not giving me pen pressure with Windows 10 and a Wacom Cintiq 22HD. I tried to reinstall, but it didn't seem to work.

**Comment by faceze** [comment]
Same problem with wacom intuos pro on win7.

**Comment by setpixel** [comment]
Please see #690 for pen issues support
