### ISSUE TITLE
UI issues ubuntu

### ISSUE THREAD

**Issue by wilsoft-gt** [wonderunit/storyboarder#634]
I think it is a bug, when I open a new proyect the gui is acting weird, I'm not able to see the bottom of the software or even see the board completely, when I try to go down it does not let me.

I was expecting to have a nice gui that feet my screen and let me draw something.

The gui is not working well, here is a screenshot: 

![storyboarder bug](https://user-images.githubusercontent.com/27575726/30245202-4a19749c-958f-11e7-848e-28c7e08ccde0.png)

Operating sistem: Ubuntu 16.04.3 LTS 64bit
Procesor: Intel Core 2 Duo T6670 2.2GHz x 2
Graphics: Mobile Intel GM45 Express Chipset
Ram: 3.7Gib
Screen Resolution: 1366x768px

**Comment by audionerd** [comment]
This looks like an old version of Storyboarder. Are you sure you're running the latest version?

**Comment by jodyblender** [comment]
I confirm the same issue on linux mint 17.3

**Comment by wilsoft-gt** [comment]
**audionerd:** That is the one I downloaded from the webpage, is that version up to date or do I have to compile from here?

**Comment by audionerd** [comment]
Looks like we had an old version up on the website link for a while. Fixed now. Please try re-downloading from the webpage.

You don't have to compile from source if you don't want to. Here's a direct link to the most recent Linux binary:  https://github.com/wonderunit/storyboarder/releases/download/v0.11.0/storyboarder-0.11.0-linux-x86_64.AppImage
