### ISSUE TITLE
A Geometric Brush?

### ISSUE THREAD

**Issue by msoreocat** [wonderunit/storyboarder#636]
I was trying to sketch out rough ideas for a storyboard, but the lines came out as if I was making geometric art. All I did was draw basic circles, and I didn't get a circle that I expected but rather an octagon or something, I've inserted a screenshot. I'm on a Windows 10 HP laptop, using a Wacom tablet (a small Intous to be exact).  My processor is 64 bit - it's an AMD A6-6310 APU, with AMD Radeon R4 Graphics. 

![screenshot 72](https://user-images.githubusercontent.com/31830168/30252811-033110ea-9647-11e7-8110-06a18d31e11b.png)

**Comment by Rayek** [comment]
Same issue on an Asus EPE-121 Windows 7 slate (built-in Wacom digitizer with pen): very laggy drawing, and results in straight lines instead of smooth curves. Also no pen pressure. Core i5 cpu, 4gb ram, Intel graphics.

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
