### ISSUE TITLE
cannot bring preferences back if you clicked the document while preferences open

### ISSUE THREAD

**Issue by CoIin** [wonderunit/storyboarder#638]
Open preferences, but instead of clicking the close button, click on the document. The preferences appear to close.

Try opening preferences again. They don't reappear.

Work around is to type command-~

Two easy solutions, either close the preferences when clicking on the document, or bring the preferences back to the front if they are currently open.

**Comment by audionerd** [comment]
Thanks for the report. This is fixed now. Should be part of the Beta 12 release soon.

**Comment by CoIin** [comment]
Confirmed that it's fixed in 0.12.0.
