### ISSUE TITLE
Occasional Pen Jumps

### ISSUE THREAD

**Issue by rugiku** [wonderunit/storyboarder#639]
Hi! First of all, I want to say thanks for releasing storyboarder and making it free because honestly, it's heartening to see niche programs available to the public. (A cool future idea would be being able to import sound to work along so we know which beats go where, but that's not the point of this!)

Here's my problem: 
[https://gyazo.com/17c59a550d1c9407dd32e5606acc7f27](url)
Every so often while I'm on the small view with all the tools visible, the pen will jump to wherever my mouse is and draw a VERY unattractive line before continuing off where my pen actually is. I'm currently using a drawing tablet (Huion 580) to draw and am running on 64-bit Win10 with 8GB of RAM and a 2.5GHz cpu. I also experience a bit of lag while drawing but it's not unlike line smoothing on art programs like Paint Tool SAI or CSP, so I'm not sure whether it's a bug or not.

**Comment by setpixel** [comment]
Should be fixed with the new drawing engine!
