### ISSUE TITLE
Playing sound

### ISSUE THREAD

**Issue by Tilix4** [wonderunit/storyboarder#641]
Hi Charles !

When we work on an animatic, we may need to play sound to synchronize storyboard, and make it more palpable. The sound editing, in animation's workflow, is done before the image, and we could have to use it while storyboarding.
Adding a sound timeline should be a good feature.

Thanks a lot for your work !

**Comment by emmelyne** [comment]
Yes! If Storyboarder had the ability to add audio it really, truly would be a very powerful tool for beginner and artists vets.

Though, I must add, I don't think there should be a limit on how long the audio can be. Say, if an artist wanted to add a background song that was 4 minutes long, I believe that one should be able to do that, but a feature to also stop that track at start it again frame by frame would also be helpful.

At least, it would be helpful for me, as someone making a faux one-man storyboarded movie, adding audio would help me take it to the next level, as you need to animate OVER the audio, for the timing to be right, and not being able to do that has made the program somewhat difficult for me to use.

That's my two cents anyway. Also, Thank you for making this program! Beginning artists and broke artists need this!
