### ISSUE TITLE
Silent install. 

### ISSUE THREAD

**Issue by andrewpurvis** [wonderunit/storyboarder#644]
Doesn't appear to have a way to install silently. It doesn't prompt you, but the splash screen starts no matter what you do with any command line options. 
Thanks..

**Comment by audionerd** [comment]
Is your goal to automate the installation of Storyboarder? What operating system and version are you on?

**Comment by andrewpurvis** [comment]
Yes, and operating system version shouldn't matter. Mac can be a simply deploy with Apple Remote Desktop, via install or direct copy. Windows is the same install procedure on 7 and 10. (and the installer does the same on both).

For the most part, the install does appear to be quiet. Except that it assumes you want to use it immediately in all situations and loads the splash screen--which no program should EVER do. There is a few out there that do this, but they shouldn't. 
The installer also appears to skip over ANY command line switches, including "help" options specified by Microsoft, /h /? etc.. 
There should always be silent install options on software, regardless of what it is.

**Comment by audionerd** [comment]
We use the `electron-builder` library to build the installer, and it manages how the installer is setup.

**Comment by andrewpurvis** [comment]
The comment still stands. It needs a silent install "option". Doesn't have to be used, but it should be there. For the most part I like the app. It's just annoying when it auto launches the splash screen to start the program as soon as it finishes.

**Comment by audionerd** [comment]
OK, so you're talking about the Windows release specifically (the Mac release doesn’t have an installer, it’s just `Storyboarder.app` distributed in a zip or dmg).
And you'd like an option that prevents the installer from launching Storyboarder after the installer completes.
Correct?

**Comment by andrewpurvis** [comment]
Yes, I believe I said that. 
I don't know why it does launch. There's no reason for it. People can find it in the start menu.

**Comment by audionerd** [comment]
Hey, I'm with you buddy. It would be better to have a checkbox to prevent auto-launch post install, and ideally a command line option to prevent auto-launch as well.

For now, I think we can set `runAfterFinish: false` in the [`electron-builder` config for NSIS](https://www.electron.build/configuration/nsis). Not sure why the installer ignores command line flags though.

**Comment by setpixel** [comment]
@andrewpurvis it's the default. I think it's fine opening. you sound like you're having a bad day. someone mean to you? free hugs over here. :D

**Comment by andrewpurvis** [comment]
No, I'm not having a bad day. I don't like apps that open as soon as you finish installing. Why should it? There's no reason for it to, at all.

**Comment by setpixel** [comment]
@andrewpurvis there's actually a really good reason.

**Comment by andrewpurvis** [comment]
which is? 
You install a program to try out, you don't necessarily want to try it as soon as you install it. Good practice is to not have it open in front of the user.

**Comment by setpixel** [comment]
the reason is because I think it's a good reason. good luck. fork this shit, make your own installer, and fuck off. you sound like a real dick.

**Comment by andrewpurvis** [comment]
Says the person who's insulting me. I didn't insult you, I put in a reasonable request. The other guy replied back with decent responses and an option for it. 
You're replying back with nothing but insults, and "because I said so".  That's not a reason.

**Comment by setpixel** [comment]
you catch more bees with honey, dawg. it will be reconsidered.

**Comment by andrewpurvis** [comment]
If you develop an application, listen to the people that will use the application. Attitude like you've displayed here is not going to go well for you.

**Comment by setpixel** [comment]
All I'm hearing is that you don't actually want to use the application. And that maybe your father didn't love you enough. OR TOO MUCH?

**Comment by andrewpurvis** [comment]
Dude, seriously. I'm posting to try and help out with USER EXPERIENCE.  You're listed as a collaborator on this page, and this is a completely horrifically bad attitude to have when responding to people.  All I've said is this should install silent, and not pop up at the end which is BAD USER EXPERIENCE. Where you have just continually replied back with insults and swearing. Do you want people to use this application? Because attitudes like yours are going to push people away. 

I've posted my suggestion, the first guy was polite, helpful, and had a fix for it. This is the development process. If you don't know that, then you probably shouldn't be in this. It's not just code something and throw it out, then patch fix, and update. It's USER EXPERIENCE. 

Go ahead and learn a few things. But that's it. I don't care if you post back. I won't be replying.

**Comment by audionerd** [comment]
The best experience for most artists using our software right now is to install quickly and start the app immediately after.

For users who need an automated installation, e.g.: to install remotely on multiple machines, it is possible to build from source and distribute in-house binaries. Not ideal, but probably the best bet for that specific use case.

For 1.0, we're sticking with the default. If there's an easy way to make auto-launch optional, we'd consider that for 2.0, but it will probably involve changes to `electron-builder` which we don't want to tackle right now.
