### ISSUE TITLE
Imported Images didnt fit on canvas

### ISSUE THREAD

**Issue by mwildancahya** [wonderunit/storyboarder#645]
Hey, i have an issue, when i tried to import my storyboard images (200+ images)  that i created earlier in krita, it didnt fit in full page of the canvas, it because my krita storyboard resolution is lower than the canvas, so it snap on the top-left corner of the canvas
![issue](https://user-images.githubusercontent.com/29877806/30309208-4f47a390-97b4-11e7-9553-da687cf9364f.JPG)

**Comment by CuberToy** [comment]
I think there is no option for that yet (maybe to come?). For now, you can edit each storyboarder images on your folder with krita (or other). You'll lose resolution though... but that part of the deal. Storyboarder save all shot images separately in your project folder. It should be simple to just scale it from here. (or batch scale your originals and import them again)

**Comment by satishgoda** [comment]
You can move, scale the layer in Storyboarder using the tool icons between the trash can and undo/redo.

**Comment by CuberToy** [comment]
Damn I totally forgot that. Right in front of my eyes. Yep. Do what satishgoda said !

**Comment by mwildancahya** [comment]
yeah i know that already, but its just too tiring to scale all 200+ images that you imported earlier (T-T)

**Comment by CuberToy** [comment]
Then my best choice would be to bulk resize the whole thing to canvas size. Some softwares can do it (photoshop for exemple). Soft freeware are available too... And even some websites (some with "no upload required" so they say).

**Comment by audionerd** [comment]
As you've discovered, importing images will not scale them up.

Pasting, however, will scale the image up to fit the canvas. You might try that.

Alternately, as recommended by @CuberToy, you could batch resize all the images first before importing them. 

On command line for Mac I've used [sips](https://coderwall.com/p/ekhe8g/batch-processing-images-on-mac-with-sips) to resize images. Not sure of a good GUI for it thought tbh.

**Comment by audionerd** [comment]
It would be nice to allow images to upscale when importing. We're tracking that now as issue #658. 

I'm going to close this issue for now.
