### ISSUE TITLE
why only photoshop ?

### ISSUE THREAD

**Issue by bebinalpha** [wonderunit/storyboarder#646]
I will be nice if the storyboarder can allow the user to choose between application to edit instead of just photoshop.

**Comment by supertobi** [comment]
There is already a PR for that:
https://github.com/wonderunit/storyboarder/pull/505

**Comment by Banbury** [comment]
Indeed there is. And I'm waiting for almost two weeks for any comment on it. I don't think the interest is very great.

**Comment by rawbee** [comment]
@Banbury Sorry, I haven't had the chance to look. I will look it over today :)

**Comment by audionerd** [comment]
Artists can now choose any image editor application via Preferences. See: https://github.com/wonderunit/storyboarder/issues/868 and https://github.com/wonderunit/storyboarder/pull/879
