### ISSUE TITLE
Shot Generator not included

### ISSUE THREAD

**Issue by Nuculeus** [wonderunit/storyboarder#647]
Hey Guys
Having the same issue as others, ShotGenerator seems not to be included!?
Using MacOS Sierra 10.12.6 on a early 2011 MBP...

Super thankfull for the free software but as an not Drawer that's the most important feature for me :/

Thanks and best regards,

Sebastian

**Comment by audionerd** [comment]
Shot Generator requires WebGL support to run, and the Electron/Chromium implementation of WebGL we're using won't work on some older graphics cards. Do you know the specific name of the graphics card in your MBP?

There might be a way to hack around this, but results might not be very good or it might not work at all: https://github.com/electron/electron/issues/8217

We have an improvement coming in Beta 12 that will provide an error message so you at least know for sure if Shot Generator will boot up or not: https://github.com/wonderunit/storyboarder/issues/626
