### ISSUE TITLE
Pressure Sensitivity Not Working

### ISSUE THREAD

**Issue by IshBosamiya** [wonderunit/storyboarder#648]
I am using a Wacom One tablet (only available in India, but is very similar to the Wacom Bamboo). Ever since the installation of the program, I have not been able to use my tablets pressure sensitivity, has been tested in photoshop and it works fine there. I am using Windows 10 (with the creators update), v0.11.0 of Storyboarder. I am currently using a laptop with i5 4210u, nvidia 840m, 8gb ram, 1080p screen.

**Comment by setpixel** [comment]
Please see #690 for pen issues support
