### ISSUE TITLE
'Export a PDF' with options for how many frames per page pls!

### ISSUE THREAD

**Issue by Dre-121** [wonderunit/storyboarder#651]
Loving this software so far. Thanks so much! 
When choosing 'Export a PDF' can we get the same pop-up window that opens up asking you how many frames per page, spacing etc, as you do when choosing to 'Print a storyboard worksheet/PDF'? Seems odd you can not do the same when you just want to export?﻿ Currently, with 9 frames as a default, all my dialogue text is unreadable because the next row of frames is covering the text. Also, a 'Save as' option would also be very much appreciated.
Thanks!

**Comment by CuberToy** [comment]
In the Print Storyboarder Worksheet option... you'll find a "Export printable PDF" button right under the options (and above the "Print" button).

**Comment by Dre-121** [comment]
All that does is export a sheet with empty frames tho? I want to be able to export what I have created in Storyboarder. If you see the attached you will see frames 4 and 5 with the 'Action' text covered by the row/frame boxes below. I would like to change to six frames per page so there is more space for text.
[test 2017-09-12 08.44.30.pdf](https://github.com/wonderunit/storyboarder/files/1298427/test.2017-09-12.08.44.30.pdf)

**Comment by CuberToy** [comment]
Oh yeah right, stupid me I didn't even checked... my bad, I will not talk before thinking again! (need some sleep). For now, set "Windows PDF" as your default printer seems to be the only workaround. Good thing audinerd added it.

**Comment by Dre-121** [comment]
I'm on a Mac...doesnt look like there is that option. :(

**Comment by CuberToy** [comment]
Oh, can't help... maybe there's some similar option :/

**Comment by Dre-121** [comment]
No problem. Will you be able to do for the next release tho? Would be amazing if you can. Loving using the program :)

**Comment by CuberToy** [comment]
I not associated at all with wonderunit. Hope they'll reply :)
(I assume it wouldn't be a big challenge to add though)

**Comment by Dre-121** [comment]
Ah right ok. Fingers crossed!

**Comment by setpixel** [comment]
Hi guys!

Yes! I need to create a dialogue box for options for the pdf output. I just need to hook it up to the ui. 

QUESTION: what kind of customizations would you want? of course columns and rows, but what else?

**Comment by Dre-121** [comment]
HI,

If we could just get the same options as 'Print a worksheet'  so Columns, rows, and spacing that would be bloody amazing! Cheers bud

**Comment by setpixel** [comment]
This is fixed in the next release!
