### ISSUE TITLE
The display of the drawing often turn black,and my works will missing~

### ISSUE THREAD

**Issue by do810375** [wonderunit/storyboarder#653]
*my computer is win10
*Re-open several times and normal operation

**Comment by audionerd** [comment]
Are you able to describe the steps that you take to trigger this bug?

Sounds similar to #607.

**Comment by do810375** [comment]
The bug just like this picture.
When i have not finished the first sketch yet....😢
[image: 內置圖片 1]
2017年9月14日 上午12:31，"Eric Skogen" <notifications@github.com>寫道：

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!
