### ISSUE TITLE
Working with PSD's too destructive

### ISSUE THREAD

**Issue by daledesilva** [wonderunit/storyboarder#654]
If you click the **export to PSD** button it creates a PSD with a separate layer for notes, main, and reference. If you save that PSD it automatically updates in storyboarder (merging any new layers down into the main layer in storyboarder).
There are two issues though:

- If you close either of the programs the live link is lost, which means that even though the psd still exists with all your layers, it's useless if you want to do more edits.
- If you do try and jump back into photoshop by clicking the "edit in photoshop" button, without warning it will overwrite your PSD file.

Suggestions:
- At the very least, it should warn you that it's going to delete an existing PSD.
- If storyboarder can read and write PSD's, why is it's native file format png? - why not just use PSD's so jumping between programs would have no loss and a default live connection?

I'm on Windows 10.

**Comment by SafariMonkey** [comment]
Regarding your last point, does it really make 
sense to use .psd ([a closed format](https://en.m.wikipedia.org/wiki/Adobe_Photoshop#File_format)) as the native format for a piece of open source software? I understand that it would make interoperability with Photoshop easier, but it could be at the expense of extensibility, as well as interoperability with other (open and closed source) software.

**Comment by CuberToy** [comment]
And I would also add that some storyboarder don't use .psd in the first place and could do the whole work right in Storyboarder. And I really think it's the core of Storyboarder, being this simple tool to just draw, one panel at a time, without going back and forth between softwares and tool (as it can be useless). Then .psd would be unusable for them in a sense.

**Comment by Banbury** [comment]
I'm agreeing with @daledesilva. I'm trying to get support for OpenRaster into Storyboarder. This is, as the name says, an open format and would be ideal to replace the mess of PNGs.
The use of PSD or OpenRaster wouldn't force the user to use an external program. Storyboarder already can read and write PSD. So why use PNG?

**Comment by setpixel** [comment]
@daledesilva 👍 

We need to associate the board with the PSD file.

**Comment by daledesilva** [comment]
@SafariMonkey 
That it's a closed format is certainly something to consider, but simply using png's provides no additional functionality in any program and using any format, open or closed, still limits usability to programs that have implemented that format.
As @Banbury mentioned, the format used doesn't affect use within Storyboarder, so it's all about added functionality when working externally while preserving backward compatibility into Storyboarder.
Since any app can implement PSD read/write, I don't see the issue as being whether the format is open or closed, but rather, which format adds functionality and is more widely supported by other apps.

**Comment by SafariMonkey** [comment]
> simply using png's provides no additional functionality in any program

I would disagree here. If you simply have PNG images, those can easily be imported (programatically or manually) into most software that deals with images. PSD can only be opened by software that has implemented specific support for it, which is a more limited set.

However, if Storyboarder plans to use features of PSD, I can certainly see the appeal. My preference would be to use OpenRaster natively and support PSD import/export, but the inverse would also be acceptable. PNG export would also be nice.

I just think it would be a bit strange to use PSD as the primary (or even only!) supported format. A bit like if Blender used `.3ds` or `.fbx` as its native format.

**Comment by daledesilva** [comment]
That's a good point @SafariMonkey 
It's kind of a balancing act between the wider compatibility of png's vs the increased functionality of a layered file.
From discussions in #655 , though, the devs aren't wanting the PNG's in the images folder to be relied on in external programs - they'd prefer users focussed on exporting for that. So I'm not sure the wider compatibility of png's matters in this instance.

Regardless of what the format is, If the export to PSD function was able to maintain a reliable link (like it almost does - until you close either app), we'd have the best of PSD bidirectional compatibility as well as whatever format they went with.
ie. native might be Open Raster but once you click "convert to PSD" than that storyboard frame is now linked to the PSD instead - kind of a choose the format you want I guess.

**Comment by Banbury** [comment]
@SafariMonkey You can still export to PNG. So there isn't really a problem.

**Comment by audionerd** [comment]
Here's the current plan:

- Storyboarder should know what source is linked per board (e.g.: file path to PSD)
- `Cleanup` tasks shouldn't delete PSD files if they are actively linked
- If artist begins to draw on a linked board (pointerdown), warn first about link being broken.
- If artist continues drawing, remove linkage in board JSON, PSD file remains on filesystem until `cleanup` task is run.
