### ISSUE TITLE
Filenaming unnecessarily bizarre

### ISSUE THREAD

**Issue by daledesilva** [wonderunit/storyboarder#655]
When exporting storyboard frames as PNG, the filenames are _00001, 00002_, etc. This is good.
The native files, however, have a random section at the end, ie. _board-1-TMW7Z_ Why?
This randomness seems unnecessary and confuses and discourages direct use of those files.

ie. Many users would want to import those files directly into After Effects.

**Suggestion:**
- Just use _board-00001_, or _board-1_ for best interoperability.

**Further Suggestion:**
- In another bug report I suggested making PSD the native format, this would make it even more versatile with respect to After Effects as all files could be imported as a composition with layers (so notes could easily be turned off).
      - if the default format was PSD, this would actually create a better reason for the export as png function as well (an option to export as png's for each layer could be added - making photoshop editing better while keeping compatibility with non-psd programs).

I'm on Windows 10
ps. always happy to chinwag about design and processes.

**Comment by audionerd** [comment]
With the current export naming scheme, if you attempt to import them into After Effects, do they import out of order?

**Comment by daledesilva** [comment]
No, they import fine. The issue is that it _looks_ randomly generated so the user will likely expect the file is temporary and may change filenames - hence, they're not likely to feel they can use it in another program directly - expecting a rename might break things later.

I'm surprised that extra characters are needed to prevent filenaming collisions since Storyboarder manages the filenames itself and each board already has an incrementing number - shouldn't that number be enough?
I imagined it might be for when users re-order boards and (Guessing only the number changes). This seems true but only seems to happen when you select "clean up scene".
Any program that's referring to that file, will then lose the link to the file.

_My original suggestion was this:_
**Just use the number ***
- PRO: encourages use of these files and while scene reordering might change numbers, scenes will essentially swap numbers so links from other programs will still point to something.
- CON: when numbers swap, timing done in other programs will likely not make much sense anyway

_But in light of the other stuff mentioned, I'd now suggest this:_
**Ditch the number altogether and just use a non-random letter.
ie. Storyboard-A, Storyboard-B, Storyboard-AA, etc.**
- PRO: Doesn't look random like it might change so encourages use, de-emphasises order so you never need to update the name even if the user changes order (which means links never break or even swap).
- CON: Can't think of any negatives.

**Comment by Banbury** [comment]
The obvious problem with your suggestion is, what happens, if you delete or insert frames. Would you rename all the files? If not your filenames will end up looking random anyway.
The random filenames are much easier to work with, because you don't have to care about the order of files.

**Comment by daledesilva** [comment]
@Banbury 
You're right that incremental lettering still implies order to some extent - but far less so than numbers. Maybe it's not the right answer though, maybe it could be a date and time stamp.
The problem with a random _string_ of characters though, is that it looks like a _temporary_ file. So many users will feel nervous referencing them.

**Comment by Banbury** [comment]
I think users should be nervous about referencing them. These images are part of the internal implementation of Storyboarder. They could change at any time. One shouldn't rely on their format, naming or anything else about them.

**Comment by daledesilva** [comment]
Not relying on them because they're unreliable is part of what I'm saying.
- There doesn't seem to be a need for them to be designed to be unreliable.

There are other options for their design that allow the files better interoperability between programs. And that's always going to make the program more adaptable to different workflows.

The files are also visible to the user, so in one sense the user does feel encouraged to use them directly.
Actually, if you want to use the files in premiere or in AE _without_ the note layer overlays, currently the only way _is_ to use those files directly - unless you export each one to PSD manually and remove the layer.

**Comment by Banbury** [comment]
But it would limit the developers choices on what file format to use. We were just discussing changing to PSD or ORA in another issue. This would break a users workflow.
If direct access to images in Storyboarder is needed, some kind of API would be a better solution.

**Comment by daledesilva** [comment]
Ahhh, I started the other issue thread - nice to know you're considering it :)
I don't understand how filenaming would limit the developers choice of format though - mind explaining?

**Comment by Banbury** [comment]
If they want to change the naming for whatever reason, they couldn't do so. It would force the devs to consider how others use those files, instead of the best interests of the software design. Those files really aren't meant to be used by anyone than Storyboarder.
In software development one has to think about dependencies all the time. Creating dependencies outside of the software makes everything more complicated.

**Comment by setpixel** [comment]
Hi Friends!

We use the -A1B2C3 random value because we need the filename to be totally unique. We also can't use sequential numbers because if the user reorders or adds new boards, it will no longer work.

Also the filename is more internal than external. 

You can export a sequential list of files that would be numbered sequentially. In fact, you should really only be exporting with that method. 

I guess I don't see the problem?

**Comment by Banbury** [comment]
@daledesilva See, that's the developer's view. :)

**Comment by daledesilva** [comment]
Thanks @Banbury , I'm not suggesting it be treated as a dependency (A user shouldn't be doing a big update like that mid project anyway), I'm just suggesting designing for open versatility. Users are likely to use those files regardless - cause they're visible and in a folder called images. Many apps get used in ways the creators don't intend - my suggestion would just embrace that.
Thanks for the responses - I'm sure you're sick of me!

Thanks @setpixel , I'm aware of all of that and take it into account in my suggestions. I do have one question, though, if the big push is for those files to be internal only, why do they need an incrementing number at all? If you ditch the number and just keep the random string, you'd never have to rename the files no matter what order changes the user made - and since the user isn't meant to look in the directory, it doesn't matter if they don't order correctly there.

Thanks both of you for all your discussion, I've started a new issue thread with alternative suggestions to fix some issues related to this that would fit with your development model.
[#670](https://github.com/wonderunit/storyboarder/issues/670)

**Comment by audionerd** [comment]
We're going to keep the internal naming as-as for now, at least for 1.0. 

We want artists to be able to do their work without have to delve into the project directory. So the other improvements you mentioned – e.g.: an option to select which layers to export (#670) – sound like a good step forward. Going to focus attention there and close this issue.
