### ISSUE TITLE
FCPXML Import not linking to PNG files on import 

### ISSUE THREAD

**Issue by tpayton** [wonderunit/storyboarder#659]
When exporting a scene for Final Cut Pro X, the resulting FCPXML file does not properly open in FCPX. 

Repeatability: Always

STeps to repeat:
1. Create a scene with several shots.
2. From the file menu choose "Export Scene for Final Cut Pro and Premier"
3. Reveal resulting FCPXML in the finder and drag onto FCPX.
Results:
Error message is shown.

![screen shot 2017-09-13 at 11 08 41 am](https://user-images.githubusercontent.com/361260/30390618-ee973aa4-9873-11e7-8d03-1ae0a9014958.png)

Expected Results:
It works!

Analysis:
It appears that you are following the FCPXML specs exactly, according to this page (below) and yet it still doens't work. Frustrating. I'll do some futher research to see if I can discover what the issue is. 

https://developer.apple.com/library/content/documentation/FinalCutProX/Reference/FinalCutProXXMLFormat/Resources/Resources.html

**Comment by audionerd** [comment]
I noticed there are spaces in the filename "storyboarder test 1". If you make a new Storyboarder test without spaces in the filename, would it work?

**Comment by tpayton** [comment]
That is indeed it! Works like a charm now. So looks like it just needs some encoding on the URLs.

BTW. Tremendous job on this app. Thank you!

- T.

**Comment by audionerd** [comment]
Fixed the bug. FCPX/Premiere export will now percentage-encode the urls representing the relative paths to the exported images.

**Comment by audionerd** [comment]
I don't have FCPX so I'm not able to verify that this works. Could you try editing the "storyboarder test 1" .fcpxml file (the one with spaces) and editing the "src=" filenames to replace spaces with `%20`, then try importing? That would verify that this is indeed the fix we need...

Alternately, if you want to test this again when Beta 12 is released and report back that would be great 👍

**Comment by tpayton** [comment]
Unfortunately  encoding the urls with %20 still produces the import error in FCPX. Puzzling because exporting a XML does encode it with %20 (see attached). For the time being perhaps replacing spaces with an underscore in the filenames would be the most efficient way to give a quick fix.  

- T.

**Comment by audionerd** [comment]
Could you attach your example XML directly to this GitHub issue?

https://github.com/wonderunit/storyboarder/issues/659

(GitHub apparently omits attachments sent via email)

**Comment by tpayton** [comment]
Unfortunately  encoding the urls with %20 still produces the import error in FCPX. 

![screen shot 2017-09-14 at 10 55 02 am](https://user-images.githubusercontent.com/361260/30442955-347e8708-993b-11e7-8b0f-71cf93e2551d.png)


![pastedgraphic-1](https://user-images.githubusercontent.com/361260/30442902-113a0a24-993b-11e7-88ef-e01eef9185fb.png)

Puzzling because exporting a XML does encode it with %20 (see attached).

![pastedgraphic-2](https://user-images.githubusercontent.com/361260/30442914-19c82900-993b-11e7-9beb-2407e60a04de.png)


 For the time being perhaps replacing spaces with an underscore in the filenames would be the most efficient way to give a quick fix.

**Comment by audionerd** [comment]
In your example export from FCPX, how does the "src" line start? With a `file://`?

**Comment by tpayton** [comment]
I tried a few combinations. No workie. In fact I was able to get FCPX to crash! I sent off a bug report to Apple on that one. I also asked the FCP team for any insight on the relative paths with encoded spaces. (I worked there for a short time, they should get back to me soon.)
![screen shot 2017-09-14 at 11 16 38 am](https://user-images.githubusercontent.com/361260/30444178-449b42a8-993f-11e7-94ba-1987a62fe621.png)

**Comment by tpayton** [comment]
BTW. Changing to underscores does work just fine in my tests. It might be the best solution for both Premiere and Final Cut.

**Comment by audionerd** [comment]
Added an issue to track replacing spaces with dashes in exported filenames:  https://github.com/wonderunit/storyboarder/issues/730

**Comment by audionerd** [comment]
We'll convert spaces to dashes in the upcoming release, which should fix this issue.
