### ISSUE TITLE
stoke opacity changes 

### ISSUE THREAD

**Issue by hamzartist** [wonderunit/storyboarder#660]
[bug.zip](https://github.com/wonderunit/storyboarder/files/1301032/bug.zip)
when i draw a stroke with the brush tool or other coloring brush when i relees it changes the opacity i have a video for that 1st with mous and the second stroke with pen 
windows 8.1
cpu: pentium inside
ram: 6gb
graphics integrated intel

**Comment by CuberToy** [comment]
You can watch the video he's talking about right here : https://www.facebook.com/groups/storyboarder/permalink/691903284345937/?comment_id=691906904345575&reply_comment_id=692029154333350&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
