### ISSUE TITLE
Error when exporting PDF

### ISSUE THREAD

**Issue by hawkinshomestuff** [wonderunit/storyboarder#663]
Great app but the software errors in exporting PDFs really puts me off/is annoying.
I've tried reducing all ACTION characters down to less than 82 as the other bug reports but this does't work for me.

Please fix ASAP... it's a great app I'd happily pay for if you can solve this!

**Comment by audionerd** [comment]
Are you getting specific error messages? If so, what do they say?

Or are you just having trouble fitting the exported boards and text on the page?

**Comment by audionerd** [comment]
Can you attach an example PDF export to demonstrate the issues?

(Please upload directly to the GitHub Issues page btw. Email attachments won't come through)

**Comment by hawkinshomestuff** [comment]
No error message. It creates a PDF that’s 99KB (every time, no matter what the content) that cannot be opened with the Mac error "It may be damaged or use a file format that Preview doesn’t recognize.”

[DreamsIO-Scamps 2017-09-14 07.01.08.pdf](https://github.com/wonderunit/storyboarder/files/1304106/DreamsIO-Scamps.2017-09-14.07.01.08.pdf)
[DreamsIO-Scamps 2017-09-14 07.02.20.pdf](https://github.com/wonderunit/storyboarder/files/1304108/DreamsIO-Scamps.2017-09-14.07.02.20.pdf)
[DreamsIO-Scamps 2017-09-14 07.02.46.pdf](https://github.com/wonderunit/storyboarder/files/1304110/DreamsIO-Scamps.2017-09-14.07.02.46.pdf)
[DreamsIO-Scamps 2017-09-14 07.15.50.pdf](https://github.com/wonderunit/storyboarder/files/1304109/DreamsIO-Scamps.2017-09-14.07.15.50.pdf)
[DreamsIO-Scamps 2017-09-14 07.17.34.pdf](https://github.com/wonderunit/storyboarder/files/1304107/DreamsIO-Scamps.2017-09-14.07.17.34.pdf)

**Comment by hawkinshomestuff** [comment]
*Update. As a test I've just removed ALL action descriptions and received the "Your PDF has been exported" message and a successful export.

**Comment by setpixel** [comment]
@hawkinshomestuff I'm on this bug right now. I think I found the error, would you be able to send me a zip of your project? if so can you email to charles@wonderunit.com

**Comment by setpixel** [comment]
@hawkinshomestuff I've fixed this bug in the latest release!!! The main problem with it, is that the formatting isn't quite right.

**Comment by hawkinshomestuff** [comment]
Awesome! Is that ready to download?

**Comment by setpixel** [comment]
Yes! If, you're on windows, please download from the website again (the auto updater was broken, but we fixed it for next versions)

**Comment by hawkinshomestuff** [comment]
Brilliant, thanks.
