### ISSUE TITLE
Pen Pressure  not Working with Wacom Bamboo pen and touch, Windows 7 .

### ISSUE THREAD

**Issue by dhanaypl** [wonderunit/storyboarder#667]
Version installed v0.12.1
Tried restarting the Wacom services, restarting windows.
Tried updating the driver,
Works on other drawing softwares.

Model - Wacom Bamboo pen and Touch
Os - Windows 7 Home Premium service pack 1 64bit

**Comment by Templarian** [comment]
https://github.com/wonderunit/storyboarder/wiki/Previously-Answered-Questions#why-doesnt-the-pressure-work-on-my-pen

Probably need to start editing the above page to list "supported" devices / workarounds. Can't edit the above page, but across all the issues I think there is a good list of working/not working combinations.

**Comment by dhanaypl** [comment]
Thank you for looking into the issues and making a Consolidated list, awaiting fix for pen pressure, nonetheless 'Storyboarder' looks great , good luck for its development and holding positive hopes , cannot wait to try it with pressure sensitivity. :)

**Comment by Pullusb** [comment]
Pressure isn't working with a Wacom Intuos Pro (Medium) on Windows 10 (was reported for Windows 7 on the consolidated reports)
