### ISSUE TITLE
Auto-Updater fails (0.11->0.12.1)

### ISSUE THREAD

**Issue by flipswitchingmonkey** [wonderunit/storyboarder#671]
Running as both user and admin, on Win10:

![image](https://user-images.githubusercontent.com/6930367/30491714-71f18758-9a3e-11e7-82c0-eeef3f421dc0.png)

**Comment by setpixel** [comment]
hi! @flipswitchingmonkey Can you redownload from the site? (auto updater was broken in previous versions)

**Comment by flipswitchingmonkey** [comment]
I've built it from source in the meanwhile. Just wanted to let you know there was an issue in 0.11.
