### ISSUE TITLE
PDF export not working

### ISSUE THREAD

**Issue by flipswitchingmonkey** [wonderunit/storyboarder#672]
Export to PDF starts the popup "Exporting 3 boards to PDF" (or whatever many), which disappears after a while.
No export folder is being created, nor is a  PDF file.

Windows 10. As admin and user. 0.12.1

Checked with procmon and no actual files are every being tried to be created.

**Comment by flipswitchingmonkey** [comment]
[Issue 673](https://github.com/wonderunit/storyboarder/issues/673) is apparently the reason for this to happen, because it can't find the last png.

**Comment by satishgoda** [comment]
I just git pulled upstream master and I am also not able to see the exported GIF as well.

![electron-a_1366x768 2](https://user-images.githubusercontent.com/536008/30495497-c91b3b74-9a7e-11e7-9e8f-3358cc4b04ad.png)

**Comment by CuberToy** [comment]
To be thorough, someone posted the same issue on the Facebook page. Win10 too (though I wouldn't condemn the OS, as I'm on Win10 too and don't have the issue).

**Comment by Hatamitch** [comment]
I am on MacOS 10.12.6, and I have the exact same problem. There are times when only PNGs are exported instead of a pdf and there are times where nothing is exported as well (not even png nor any folders)

**Comment by LarkDiet** [comment]
Also have this issue, Win10. Found that sometimes a board will have a reference and thumbnail but no actual PNG file. A temporary (and probably imperfect) fix is to copy the reference images and rename them as the missing files.

**Comment by audionerd** [comment]
Should be fixed in the upcoming Beta 13 release.
