### ISSUE TITLE
Based On Script

### ISSUE THREAD

**Issue by RyanfWood** [wonderunit/storyboarder#675]
I haven't used Storyboarder that much, but I just updated and then tried starting a new board based on a fountain script. Clicking on the scenes give me Uncaught TypeError dialogs, and then more errors come up when I start to draw. It's debilitating.
![screen shot 2017-09-15 at 4 30 41 pm](https://user-images.githubusercontent.com/5452891/30507086-095838c0-9a36-11e7-857f-58dc366f48b0.png)
![screen shot 2017-09-15 at 4 30 32 pm](https://user-images.githubusercontent.com/5452891/30507087-095c3ef2-9a36-11e7-9496-3ed5f4512f75.png)
![screen shot 2017-09-15 at 4 30 09 pm](https://user-images.githubusercontent.com/5452891/30507085-09575590-9a36-11e7-95bb-42cda83eb267.png)

There was also one about zero null that I couldn't recreate.

Hope this gets sorted out. I'm on macOS Sierra 10.12.6
Going to try out based on script on the older version.

**Comment by RyanfWood** [comment]
Just reinstalled the last version and everything works fine. I'll just hold off until next update.

**Comment by setpixel** [comment]
@RyanfWood ooof. that happened right after the update, but reinstalling fixed it? can you confirm the version?

**Comment by RyanfWood** [comment]
You know what? Reinstalling did the trick. Nevermind. 0.12.1 is working just fine now as far as I can tell.

**Comment by setpixel** [comment]
eeek though - it shouldn't have happened in the first place... going to try to recreate the bug.

**Comment by audionerd** [comment]
Sounds like #685
