### ISSUE TITLE
No Pressure Sensitivity with Ugee 2150 Screen

### ISSUE THREAD

**Issue by Nox-Astru** [wonderunit/storyboarder#679]
I adore this software already but have found I do not have any pressure sensitivity with my tablet. I am using a Ugee 2150 display tablet on my Win 8 PC. It works fine in Photoshop, Paint Tool Sai 2.0 and Studio Clip.

I understand I am using a less common brand but thought I would post anyway in case there is a work around?

Thanks for the software!

**Comment by setpixel** [comment]
Hi! do you still have this issue? Please comment if you do?

**Comment by Nox-Astru** [comment]
Hello, yes I do. Just reinstalled the software today.
