### ISSUE TITLE
sketchpane - queued paint rendering/stamping

### ISSUE THREAD

**Issue by 2livebrew** [wonderunit/storyboarder#68]
Issues #16 and #44 are the result of a failing race condition. Ultimately, strokes should be queued and stamped one at a time based on `requestAnimationFrame()` as opposed to being stamped in `pointerUp()`.

I have a pair of PRs up ([66](https://github.com/setpixel/storyboarder/pull/66), [67](https://github.com/setpixel/storyboarder/pull/67)) either of which fix #16 and #44, but doesn't fix a more elusively-reproduced bug stemming from a related race condition.

Queueing stroke renders and stamping should be able to cover all related race conditions.

**Comment by setpixel** [comment]
will be fixed with new sketchpane
