### ISSUE TITLE
Storyboarder No Pressure Sensitivity/Errors

### ISSUE THREAD

**Issue by Taschia** [wonderunit/storyboarder#680]
Hey there! I was just introduced to Storyboarder and am immensely excited to use it -- I've just run into a couple issues that are preventing me from fully jumping in. Namely, I cannot seem to get pen pressure to respond within the application. I also have been getting several java errors when trying to navigate between boards or deleting them, and just at random points when using the software. Thank you so much for the assistance I hope this helps!

## **Issues/How to Recreate**:
-The pen pressure has never been responsive so I don't have a step by step for that one.
-The java errors would pop up usually after trying to reorder or delete a board by right clicking on it and selecting that way - it would then sit and freeze without actually deleting the board, and often not respond to right clicking on that board afterwards. After updating to the newest version (1.0.0), it looks like some of the error messages stopped popping up, but it will still sit and refuse to actually delete a board.
Here is an example --> [https://imgur.com/a/axk04](url)
-Occasionally I'll get a random error message that was seemingly independent of anything I was doing (i.e. I think I was just drawing or switching tools).
-Also of note: When I was notified of this latest update and clicked on the dialogue box to install the updated version it would have an error message appear and simply crash. I uninstalled and then reinstalled to get the latest version. Image here --> [https://imgur.com/a/KVe1X](url)

## **Attempts to fix Pen Pressure**:
Tablet Specs: Monoprice 10 x 6.25-inch Graphic Drawing Tablet (4000 LPI, 200 RPS, 2048 Levels)
https://www.monoprice.com/product?p_id=10594

-I did attempt the usual fixes to regain pressure sensitivity but it is localized to Storyboarder only. Pressure is completely functional in all other art software I have installed (Including Photoshop, Paint Tool SAI, FireAlpaca, etc.). 
-Reinstalled tablet drivers
-Reinstalled and then updated Storyboarder
-Restarted computer
-Checked cables, stylus, stylus battery
All signs thus far have pointed to Storyboarder being the only thing not accepting pen pressure.

## **OS Version and Build**:
Windows 10 (Education, 64 bit, Version 1607, OS Build 14393.693)

## **Hardware Specs**:
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Nvidia GeForce GTX 1070 Founder's Edition
32 GB RAM
1440 x 900 native resolution (running two cheap monitors lmao)
OS and Storyboarder both running from Samsung SSD 850 EVO 250 GB

Thanks again and I'll look forward to hearing from you when you've had the chance to look into it. Very excited to continue using your program and make some kickass storyboards!!

**Comment by setpixel** [comment]
Please see #690 for pen issues support
