### ISSUE TITLE
Weird brush lag? 

### ISSUE THREAD

**Issue by archnila** [wonderunit/storyboarder#682]
![brush problem phone recording](https://user-images.githubusercontent.com/32034715/30520766-0759a9e8-9be7-11e7-9c88-82fca02c3abf.gif)
Phone recording.
![brush problem](https://user-images.githubusercontent.com/32034715/30520690-af811eb4-9be5-11e7-931b-10ec2580dff7.gif)
Screen recording.
I'm enjoying the program but somehow, there's something weird happening with the brush. Sometimes it works fine and sometimes there's some sort of delay. However, when recording with screen capture software, the issue does not show itself. I have included a recording from my phone and screen capture software for comparison. My Intuos 5 has the touch function disabled. Also, I'm not touching my mouse at all when drawing, just in case the jump is mistaken for mouse movement. For some reason, when I reopen the program, the problem goes away for a little while and then comes back. 
I'm running Windows 10 64-bit. Intel Core i7-4700HQ, CPU @ 2.40Ghz, 12.0GB RAM,Intel HD Graphics 4600.

**Comment by Dinocanid** [comment]
I have this problem as well. It's much more noticeable with short, quick strokes, which I use a majority of the time. There's also a similar problem with longer strokes where the crosshair/circle will flicker to the default cursor for a split second after lifting the pen.

**Comment by melMass** [comment]
I had similar issues, usually restarting the app and closing opened browser solves it.

**Comment by Dinocanid** [comment]
Hmm, it seems persistent on my end. I have Windows 10 and a wacom intuos small (no screen)

**Comment by melMass** [comment]
On your end delay is not especially **increasing over time** is that right ? You always experience that delay from the start ?

I do think some combination of opened apps degrades storyboarder smoothness.

### my config:
- An old **Wacom Intuos3 A4**
- **OSX Sierra** 10.12.6 
- **12cores/24threads** (2 x 2,4 GHz 6-Core Intel Xeon)
- **64 GB** 1333 MHz DDR3
- **2x** NVIDIA Quadro 4000

**Comment by Dinocanid** [comment]
Yep, the lag is always there whenever I start the program, and continues as I use it. I don't think it gets worse over time for me, but I've never used it for very long due to this issue. I don't run it with other apps open, besides Steam which is always active in the tray. Here are my specs:

- Wacom Intuos Pen and Touch Small (approx. 4 years old)
- Windows 10 (64 Bit)
- AMD Radeon R7 200 Series
- AMD FX(tm)-4300 Quad-Core Processor
- 1 TB Hard Drive Space
- 8GB RAM
- 3800 Mhz

**Comment by fluffbirb** [comment]
Disabling the basic windows tablet drivers and flicks helped the lag a little:
http://www.volnapc.com/all-posts/how-to-get-rid-of-those-annoying-circles-from-your-wacom-cursor-in-windows-7

I'm still getting lag for short fast strokes to some extent, but that helped a lot. Went from unusable to a bit bothersome.

**Comment by melMass** [comment]
@fluffbirb I might be wrong but this is the case for windows by default since quite a few versions, so I think most wacom users know the trick. I'm not sure it's related to the lag issue.

**Comment by fluffbirb** [comment]
I was aware of flicks before, but hadn't tried disabling the windows tablet driver on startup.
Before disabling windows tablet driver:
- no noticeable pen lag in non-drawing applications
- no noticeable pen lag in low overhead drawing programs
- acceptable lag in Photoshop.
- debilitating ~1 sec delay in Storyboarder

After disabling windows tablet driver:
- no noticeable pen lag in non-drawing applications
- no noticeable pen lag in low overhead drawing programs
- acceptable lag in Photoshop.
- minor delay in Storyboarder, bit more than Photoshop
- that little ripple thing when tapping pen doesn't appear anymore, yay

So for me at least, it made a dramatic difference in lag. I specifically came to this git to see if anyone else had the debilitating lag before looking for other solutions.

**Comment by df-0** [comment]
just installed this - on OS X 10.13.2, wacom intuos P S, wacom driver 6.3.27-2 (fully updated), and it's unusably laggy. Running on a 2.8GHz i7 with 16GB RAM
- Photoshop, Toon Boom Harmony and general OS are super smooth, no perceptible lag
- Storyboarder has colossal jerky lag, often drawing lines as connected straight segments when you're trying to draw a curve, and sometimes seeming to "rush to catch up" when you've lifted the pen and put it down again. There's no way you can draw with it :.(
- OpenToonz 1.2, weirdly, displays a very similar lag/jerk behaviour with this setup, and is equally unusable...so it's not just you guys!

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
