### ISSUE TITLE
3D ?

### ISSUE THREAD

**Issue by melMass** [wonderunit/storyboarder#683]
Amazing app, great idea.
I discovered about cameras and dummy 3d but can't find it anywhere, the 3D grid defaults to a standard non modifiable view. I'm I missing something ?
Thanks

**Comment by audionerd** [comment]
The 3D Guide shows an eye-level 3D view by default. However, if you use the Shot Generator to insert a shot into the Light Layer of a Board, the 3D Guide will then reflect the 3D scene of that particular generated shot.

We've talked about giving more control over the 3D Guide in future releases of Storyboarder, and have discussed it a bit here: https://github.com/wonderunit/storyboarder/issues/563

**Comment by melMass** [comment]
Thanks but where is the shot generator ? No info in the wiki and I can't find it in the UI :/

**Comment by setpixel** [comment]
Can you scroll down on the right side of the ui?

**Comment by melMass** [comment]
Yes thanks ! 

This should definitely be written somewhere :)
