### ISSUE TITLE
Undo doesn't work when hovering over text boxes in sidebar 

### ISSUE THREAD

**Issue by songproducer** [wonderunit/storyboarder#684]
Draw starting from canvas and hover over text field.
The focus changes to the text field.
Have to click in the canvas to resume focus in drawing area.

Undo to work

Text area stole the focus

Ubuntu 16.04.3

Threadripper 1950x, 16 gb ram 1920 x 1080

**Comment by audionerd** [comment]
I'm guessing this is specific to Ubuntu.

On macOS, when I hover over a sidebar textarea, it is not focused, and I can still undo drawing. Only after I _click_ on the textarea to focus it does it prevent me from using undo on a drawing.

Is it possible your Linux window manager etc is somehow set to auto-focus any textarea you hover over?

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!
