### ISSUE TITLE
Open Fountain Script creates bugs

### ISSUE THREAD

**Issue by Voxdark** [wonderunit/storyboarder#685]
I wrote a short script in "Trelby" checked for errors and exported it as a fountain file. When i open it in Storyboarder it tells me it created id's and so on. As soon as i try to change the scene I gives me an error:

**Error
Uncaught TypeError: Cannot read property 'classList' of null**
In file: C:\Program
Files\Storyboarder\resources\app.asar\src\js\window\main-window.js#1808:74

What am i doing wrong? Can someone help me? I guess it is my mistake. I don't have any clue of fountain, i want to learn "it". I really love Storyboarder and want to write my scripts that i can import them easily into storyboarder. Can somebody tell me a Win10 program which is right for that? Is there a tutorial or something? Please Help
Thanks!

Windows 10 Home 64bit
Intel Core i5-7200U
8GB RAM

Storyboarder v0.12.1

**Comment by audionerd** [comment]
Hey @Voxdark looks like you found a bug in Storyboarder! It's not your mistake, it's a Storyboarder issue. Thanks for reporting it.

Are you able to send us a copy of the script that had the error so we can try to replicate the problem and fix it?

**Comment by Voxdark** [comment]
Sure, the Script makes no sense at all, it was just for testing. You can download it [here](https://wetransfer.com/downloads/77c064e76e2c347b2a514959b39b3b0320170919092003/2e21311462f14574113a89f8ec8cc53c20170919092003/e80bc5)

**Comment by Rayek** [comment]
Yes, this also happens with the example Fountain file: https://fountain.io/
