### ISSUE TITLE
A failed "undo"

### ISSUE THREAD

**Issue by Tin-ling** [wonderunit/storyboarder#686]
Hi! Thanks for your storyboard programme first. I've found something strange during the time I used it. There was once I undo the action and it showed the window "Uncaught TypeError" (please see the attached)
I don't know whether I should concern about it or not. It hasn't happened again so far.
<img width="1440" alt="2017-09-18 8 46 01" src="https://user-images.githubusercontent.com/32062175/30539205-b4592fba-9cb4-11e7-8553-8eba2c9d7694.png">

Thanks again for developing this programme!

**Comment by Rayek** [comment]
The latest version I downloaded and installed produces the same error message when I open a Fountain script and click on any scene/subaction in a scene list. After that the program becomes unusable.

**Comment by audionerd** [comment]
@Tin-ling @Rayek Thanks for the reports. Looking into this.

@Rayek can you confirm the error message text you see is exactly the same? E.g.: it says "cannot read property 'parentNode'" and references drop.js?

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!
