### ISSUE TITLE
Got Uncaught TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#688]
Steps
- Use the "+" button in the thumbnail drawer to create a few new boards.
- Press "D" to duplicate a board

This error occurs:
```
Uncaught TypeError: Cannot read property 'parentNode' of null
In file: […]/storyboarder/node_modules/tether-drop/dist/js/drop.js#423:23
```

If the following lines are removed, the error seems to occur more frequently – shortly after _every_ time the `+` icon button is pressed:
https://github.com/wonderunit/storyboarder/blob/2e2791815bdeeb8cac210d473b6f3ac9aa6eb002/src/js/window/main-window.js#L2409-L2411

Per #971 can also happen in a situation where they "duplicated an earlier board...then tried to drag the duplicated board to place it at the end of the timeline. When I lifted my pen off the screen to apply it storyboarder crashed"

**Comment by audionerd** [comment]
Related to #686

**Comment by audionerd** [comment]
Looks like its an un-patched bug in HubSpot’s `drop` library https://github.com/HubSpot/drop/pull/171

**Comment by potahto** [comment]
I'm seeing this intermittently on Mac 10.12.6 in version 1.1.0.

**Comment by audionerd** [comment]
@potahto can you describe what steps it takes to recreate the bug?

**Comment by potahto** [comment]
Same as above:
Use the "+" button in the thumbnail drawer to create a few new boards.
Press "D" to duplicate a board
This error occurs:

Uncaught TypeError: Cannot read property 'parentNode' of null
In file: […]/storyboarder/node_modules/tether-drop/dist/js/drop.js#423:23

**Comment by audionerd** [comment]
Related: https://github.com/wonderunit/storyboarder/issues/828

**Comment by df-0** [comment]
I'm getting this error in 1.0.0 on windows 10, when dragging a board to the end of the timeline
