### ISSUE TITLE
Pen Pressure Issues Consolidated

### ISSUE THREAD

**Issue by Templarian** [wonderunit/storyboarder#690]
https://github.com/wonderunit/storyboarder/wiki/Previously-Answered-Questions#why-doesnt-the-pressure-work-on-my-pen

Went through all the issues with Pen Pressure mentioned and updated the chart. I'm sure there are more working devices since those people probably didn't open issues. OSX seems to be mostly fine as long as Wacom drivers are fully updated.

|  | Storyboarder | Pen | Pen Driver | OS | Notes / Workaround |
| -- | -- | -- | -- | -- | -- |
| ✔️ | 0.12.1 | Surface Pro 2017 | N/A | Windows 10 | |
| ✔️ | 0.12.1 | Surface Pro 4 | N/A | Windows 10 | |
| ✔️ | 0.12.1 | Wacom 13HD | Latest | Windows 10 | |
| ✔️ | 0.12.1 | Wacom 13HD Touch | Latest | Windows 10 | |
| ✔️ | 0.12.1 | Wacom 13HD | Latest | OSX 10.10.5 | #568 Glitchy  |
| ✔️ | 0.11.0 | Wacom One Tablet | N/A | Windows 10 | Windows Ink |
| ✔️ | 0.12.1 | Wacom Cintiq 22HD | N/A | Windows 10 | Windows Ink #632 |
| :x: | 0.12.1 | Wacom Intuos 3 / 4 | N/A | Windows 10 | #575 |
| :x: | 0.12.1 | MonoPrice 10 x 6.25-inch | N/A | Windows 10 Edu | ??? |
| :x: | 0.12.1 | HUION H610 | Latest | ??? | No Pressure |
| :x: | 0.12.1 | Wacom Bamboo | N/A | Windows 7 / 8 | #667, #585, #575 |
| :x: | 0.12.1 | Wacom 13HD Touch | N/A | Windows 7 | ??? |
| :x: | 0.12.1 | Bamboo (CTL-470) | N/A | Windows 7 | #632 No Windows Ink |
| :x: | 0.12.1 | Asus EPE121 | N/A | Windows 7 | #632 No Windows Ink, No Eraser |
| :x: | 0.12.1 | Wacom Intuos Pro | N/A | Windows 7 | #632, #591 No Windows Ink |

## Windows

Recommended that you update your operating system to Windows 10 if possible.

### Windows 7

1. Open Local Group Policy Editor: Run... gpedit.msc
2. Navigate to User Configuration - Administrative Templates - Windows Components - Tablet PC - Cursors
3. Enable the Turn off pen feedback setting.

Source: https://github.com/wonderunit/storyboarder/issues/591#issuecomment-328307822

## OSX

Update to the Latest Wacom drivers seems to solve most issues.

**Comment by audionerd** [comment]
Thanks! This is super helpful! I'll update the wiki tomorrow with this info.

**Comment by audionerd** [comment]
Updated. https://github.com/wonderunit/storyboarder/wiki/Previously-Answered-Questions

Thanks again! :sunglasses:

**Comment by DCNielsen** [comment]
I ran into an interesting variation on this bug. Opened a previous file with only one frame and out of nowhere suddenly my pen pressure wouldn't take.I was running OS X El Capitan and older Wacom drivers when I encountered the problem. Switched both to the latest versions. Still had the problem. 

Deleted the artwork on the layer. Now it lets me draw with pressure. Undid back to the earlier state. Saved it. Quit and restarted Storyboarder and got the same problem. Fixed again by deleting the artwork. Weird.

Here's a link to the cursed file. Maybe it will help to troubleshoot a similar situation?
https://drive.google.com/file/d/0B7F2dPPlpXnaV1MtblVfTm9vTlE/view?usp=sharing

**Comment by audionerd** [comment]
@DCNielsen Looks like the project you attached was made with a much older previous beta of Storyboarder. We don't have a good migration path for older project files, so you might run into some weirdness there.

**Comment by DCNielsen** [comment]
Makes sense. The thought had occurred to me that this might be the cause.

**Comment by Humbuggery** [comment]
I just installed Storyboarder today but was disappointed that pen pressure isn't supported on my set-up (Monoprice/Windows 7). I have all of Windows' native tablet settings disabled, and my tablet works just fine in Photoshop and Clip Studio Paint.

I see that support is still needed for other set-ups, so I assume that it's being worked on. Ccould someone give me an idea of when I might expect support for Monoprice pressure sensitivity? I'm really excited to start learning this new program!

**Comment by thypham44** [comment]
![mmmlkll](https://user-images.githubusercontent.com/34789405/34318646-2a211a9c-e822-11e7-8386-acdf8e9ded1c.PNG)
This is my issue on the surface pro  is there a solution for this I have pen pressure but this happens also it's very laggy

**Comment by chris-lesage** [comment]
I typed this on another issue, but I'll repeat it because this page says "OSX seems to be mostly fine".

I updated to 1.9.2 on Macos, and I lost pressure sensitivity. I closed and reopened the app several times. Then I tried flipping my Wacom pen upside down to use the eraser tool. When I flipped it back to the regular pen side, the pressure sensitivity suddenly came back!
