### ISSUE TITLE
Error message and storyboarder wont run.

### ISSUE THREAD

**Issue by cboggs2** [wonderunit/storyboarder#691]
Storyboarder worked one time for an hour and now produces this error message
and won't go past it and work in any fashion.

Uncaught TypeError: Cannot read property 'url' of undefined
In file: /Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/window/main-window.js#1808:74

I have no idea how to reproduce the issue.
I deleated and tried to reload the software but it still will not work past
producing the above error.

Mac Pro laptop.
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP121.0167.B24
  SMC Version (system):	2.28f7
  Serial Number (system):	C17QL4U2FVH5
  Hardware UUID:	3C209CE6-5F31-58D7-B98B-000EEE5D3DA4

**Comment by audionerd** [comment]
We'll be releasing Beta 13 soon which should include a fix for this.

**Comment by audionerd** [comment]
Thanks for the report and sorry for the hassle. Still some beta bugs left to squash!

**Comment by cboggs2** [comment]
Thanks Eric,

Awesome program, ..

---
Curtis Boggs
http://www.cboggs.com

CONFIDENTIALITY NOTICE:
This message (including any attachments) is intended only for the use of 
the
individual or entity to which it is addressed and may contain 
information
that is proprietary, non-public, and confidential to Curtis Boggs 
Productions.
If you are not the intended recipient, you are hereby notified that any
use, dissemination, distribution, or copying of this communication is
strictly prohibited. If you have received this communication in error,
please contact the sender and delete this message immediately.
