### ISSUE TITLE
Auto Updater Not Working, Throws JS Error

### ISSUE THREAD

**Issue by LarkDiet** [wonderunit/storyboarder#696]
When choosing the option to update to newest version (0.12.1) on startup, the program instead crashes and gives this error:

> Uncaught Exception
> Error: Object has been destroyed
>    at BrowserWindow.getAllWindows.forEach.w (C:\Program Files\Storyboarder\resources\app.asar\src\js\auto-updater.js:24:56)
>    at Array.forEach (<anonymous>)
>    at Function.dialog.showMessageBox.index (C:\Program Files\Storyboarder\resources\app.asar\src\js\auto-updater.js:24:41)

System Specs:
Windows 10 Pro 64-bit
AMD Fx-6300 6-Core Processor 3.50 Ghz
8 GB RAM onboard + NVIDIA GeForce GTX 750 Ti 4 GB
Huion GT-190 Pen Display Tablet, 1440x900 native resolution

**Comment by audionerd** [comment]
Thanks for the report. [We have fixed this bug for future releases](https://github.com/wonderunit/storyboarder/issues/666), but for now please download the latest version (0.12.1) directly from wonderunit.com or the GitHub releases page.
