### ISSUE TITLE
Error when clicking on different scene

### ISSUE THREAD

**Issue by CuberToy** [wonderunit/storyboarder#697]
So, looking to find new bugs and all... I imported the Big Fish script (.fountain)
When clicking on different scene using the left cards I get an error :

> Uncaught TyperError: Cannot read property 'url' of undefined
> In file : C:\Program Files\Storyboarder\ressources\app.asar\src\js\window\main-window.js#1289:22

On Win10.

**Comment by CuberToy** [comment]
Just wanna add.
When first clicking the error is not the exact same : 

> Uncaught TyperError: Cannot read property 'classList' of undefined
> In file : C:\Program Files\Storyboarder\ressources\app.asar\src\js\window\main-window.js#1808:22

Then it's 1289:22 all the time.
I tried with an old project created in Storyboarder (in february), doing the same thing too.

**Comment by audionerd** [comment]
Good catch. Should be fixed in `master` now. Please take another look when Beta 13 is released.
