### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ScoopJohn** [wonderunit/storyboarder#700]
Finally, a free storyboard software that looks freaking good so that i don't need to waste money on expensive storyboard software, with a very humoristic premise. I still haven't started using yet but i might ask some features i want to see in future versions:

1. The ability to assign **sound effects and music** to several frames would be great, it adds more life to the storyboard and it allows the user to experience a sounding preview of its storyboard.
2. Could this software possibly have an _"Animation Mode"_? It would literally change the software's "Storyboard Mode" into a much more advanced mode that allows the user to complete an animation specified from the storyboard's frames with animation related tools. There's already something free like Pencil2D that has handdrawn animation features, but it would be great if it were to have an export module that exports as a Pencil2D file so that it would make an animation based off the storyboard.
3. **The "camera" feature.** The software has like two different view types: one is displayed ALWAYS on the editor's camera and it is not really the "camera" you could adjust. The other type of view is the "camera" itself, you could adjust it during the storyboard's frames which determine the camera shot of the actual final animation.
4. Is there perhaps a way to change the type of frame rate speed for certain animations with a longer delay duration for EVERY frame? An example is that japanese animation (Anime) have more delay in frames for each step.

**Comment by CuberToy** [comment]
Audio is something planned for the future of Storyboarder :) (for Animatic mostly)

For the rest, I won't say for the devs cause it's none of my business, but Storyboarder is a... Storyboard software. It's may be just me I guess, but if you read the github main page of Storyboarder... that's the whole deal. I'd rather have on software which does one task great, than multiple task "meh". As I would rather have a pizza from a pizzeria and not a tacos shop who happens to also do pizza (yep, I'll stick with that analogy) cause it's always better. Making it an animation software over complicate the whole thing for someone that just wanna do a Storyboard. What you're asking in "Animation Mode" is a different software. As I see it (again, it's just me), "Animation Mode of Storyboarder" could be another piece of soft by itself, and that would be fine.

I keep seeing people asking for Storyboarder to be a drawing software, or an animation software... It's not. Not as I see it though. But then again, I'm no one to decide what it is.
