### ISSUE TITLE
ability to save as and export a zip of the whole project

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#704]
save as can basically save a clone of the project with a new specified name

export a zip will zip all the files in a project and put it in the exports folder.

**Comment by satishgoda** [comment]
Will it be also possible for auto versioning the zip file for the specified project name provided?

Use case presented below.

New project
Hack on storyboard
Save as : "existing_name" OR "new_name" (defaults to the project name)
In exports folder : *_name.v0001.zip

Hack on storyboard
Save as : "existing_name" OR "new_name" (defaults to the project name)
In exports folder : *_name.v0002.zip

Thank you.

**Comment by audionerd** [comment]
@satishgoda "Export Project to ZIP" will save to the `exports` folder with an automatically generated, timestamped filename (e.g.: `project-2017-10-11 12.02.24.zip`)
"Save As …" will prompt for a file name to use for the copy.

**Comment by setpixel** [comment]
This is up live now!
