### ISSUE TITLE
Zoom?

### ISSUE THREAD

**Issue by doodleduck** [wonderunit/storyboarder#707]

**Comment by doodleduck** [comment]
I'm new to storyboarder and I'm wondering is there a way to zoom in on the storyoard panel youre drawing on? Even when i pick the biggest screen resolution its still pretty small and i would like to be able to add more small details to the panel im drawing on. Any ideas?

**Comment by CuberToy** [comment]
There is no function for that at the moment, but #33 is where you should look. It's something the devs are considering for V2.

**Comment by audionerd** [comment]
Duplicate of #33
