### ISSUE TITLE
Set frame rate

### ISSUE THREAD

**Issue by synk-a-dynka** [wonderunit/storyboarder#709]
Frame rate is set to 24 fps and there is no way of changing. This means all shot lengths will be off by a few frames (Or 4% to be accurate) when working in 25fps.

**Comment by morganwk** [comment]
I second this wholeheartedly.
I'm thinking of using Storyboarder as a Flipnote-style animation tool, and being able to animate in 30 or 60 would be neat. But also having decimal points for your FPS (23.97, etc.) as well as common PAL framerates (25 for instance) would be a godsend for anybody trying to use this software professionally.
