### ISSUE TITLE
Slow drawing

### ISSUE THREAD

**Issue by cosmicponye** [wonderunit/storyboarder#711]
Hello, i just downloaded Storyboarder and it's really cool, just i think i have a problem. When i try to draw the stabilizer goes really slow, and when i want to draw something fast it becomes kinda a pain.
The Tablet i use is a Wacom Bamboo Pen, and i tested it in other softwares like adobe sketchbook and Photoshop and it works fine. I work in Windows 10.

**Comment by boubouh** [comment]
yes...this happen to me also in my linux machine (Ubuntu 16.04)

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
