### ISSUE TITLE
storyboard disappeared

### ISSUE THREAD

**Issue by flameflamefire** [wonderunit/storyboarder#712]
I drew 4 boards and trying some other function, those 4 boards disappeared suddenly. I mean they became blanked, but I am not sure if this is a bug or I just press something wrong.

BTW the vertical HD 9:16 is nice to use, I love it as some long comic is hot now. Anyways, this storyboarder is a good software, that I hope it launched earlier for my FYP :)

**Comment by automaton-0** [comment]
I also had some panels disappear, not sure if the circumstances/causes are the same.

I had drawn about 50 panels, at some point I went back the beginning of the timeline and found that 3 panels had disappeared; the canvas was blank but the timeline thumbnails were visible.
When I exported the images, the blank panels were skipped.

I was really enjoying this software, but this issue makes it unusable for me, for fear that my whole storyboard might just disappear with dozens of hours of work.

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!
