### ISSUE TITLE
PDF export text falls of

### ISSUE THREAD

**Issue by willemscholtes** [wonderunit/storyboarder#722]
Hi there,

Love your software!! And its Free!! You and your team are good people.
I found that when i have more then two lines of dialogue and one ore more lines of actions the pdf export struggles. The text will be cut off by the frame below which makes it unreadable.. What i would love to see is that i have more pdf export options like how many frames per sheet and how big those frames are.

Also i was trying to check which version i was running for your information but i was missing the "About" tab at the Help menu. But i just downloaded the newest version today, so you probably know which version i am running ;)

Keep up the good work! We truly appreciate it.

Greetings,
Willem Scholtes

**Comment by Dinocanid** [comment]
I tried exporting as a PDF, and I get the same issue. I only have 1 or 2 word actions, and it gets cut off by the frame below it:
![PDF bug](https://img00.deviantart.net/36b1/i/2017/274/1/a/storyboarded_bug_1_by_hoafan-dbp7fq4.png)

**Comment by setpixel** [comment]
This is fixed in the next version.
