### ISSUE TITLE
Undo not affecting drawing lines or Deleted Board.

### ISSUE THREAD

**Issue by biscardicreative** [wonderunit/storyboarder#723]
Draw using any of the drawing tools.  
Use "Undo"

Or Delete a Board
Use "Undo"

The last lines drawn to disappear.
Or, the Deleted Board to re-appear.

Undo only affects what is typed in the notes in the Dialogue and Action boxes.  
Undo does not erase drawn lines, nor does it reverse Deleting a board.

Windows 10 Pro
Version 1703
OS Build 15063.608

Microsoft Surface Pro
Intel Core i5-7300 CPU @ 2.60GHz  2.71 GHz
8GB RAM
Pen and Touch Support with 10 touch points

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!
