### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Voxdark** [wonderunit/storyboarder#724]
On my other maschine i didn't use Storyboarder often. Today i wanted, but everytime i click on "Download and Install Now". I gives me this:
![wad](https://user-images.githubusercontent.com/32060765/31054160-0c302d72-a6ad-11e7-83ef-7c85a9229dd3.PNG)

I'll deinstall and install the new version in a bit

Windows 10 Home 64bit
Intel Core i7-6900K @4.10GHz
GTX 980 Ti
128GB RAM

Storyboarder v0.11.0

**Comment by audionerd** [comment]
Yeah sorry about that. Please grab the latest version from https://wonderunit.com/storyboarder or the Github releases page. Should be fixed for future release.

The full issue report for the auto update bug was: https://github.com/wonderunit/storyboarder/issues/666
