### ISSUE TITLE
Holding shift does not make straight lines. W10

### ISSUE THREAD

**Issue by Pullusb** [wonderunit/storyboarder#726]
"Straight Lines: Hold shift while drawing" - Holding shift does nothing (both tablet and mouse)
Also, Intuos stylet Pressure not detected.
Windows 10. storyboarder version 0.12.1. Tablet Wacom Intuos pro. Intel Core i7-6800k, GTX 1080, resolution 2560x1440.

**Comment by audionerd** [comment]
Straight Line drawing hasn't been implemented in v1.0. It will probably be a v2.0 feature.

We're tracking it here: https://github.com/wonderunit/storyboarder/issues/151
