### ISSUE TITLE
Eraser and ctrl + z counts towards miles?

### ISSUE THREAD

**Issue by Dinocanid** [wonderunit/storyboarder#728]
I always found it a little strange that the eraser counts towards your line miles. I suppose it does count towards the drawing process, but if I just run my eraser across the board without drawing anything, I get miles lol. Maybe the eraser tool can not give you miles?

Another suggestion of mine would be for `ctrl + z` to undo recently added miles. This is probably much easier said than done, since the program would somehow have to track how many miles were recently added.

**Comment by setpixel** [comment]
Miles were sort of added as a joke :D
