### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by milcay** [wonderunit/storyboarder#729]
I can't export my project as a pdf, or a gif. They both say "exporting" but then there's never any file. I've also tried exporting as images but it keeps skipping some of my frames and I can't work out why.

**Comment by CuberToy** [comment]
See #708 
It's an issue they're working on. The source of the problem seems to be what you just said, some board not being saved.

**Comment by audionerd** [comment]
Should be fixed in the upcoming Beta 13 release.
