### ISSUE TITLE
Update copy for "board is already linked" prompt

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#736]
Three options:

- Cancel
- Draw in Storyboarder, break the editor link
- - Are you sure?
- Open Photoshop, I'll draw there

**Comment by setpixel** [comment]
This board has been edited in Photoshop and linked to a PSD file. What would you like to do?

Cancel

Flatten and Draw in Storyboarder -> Are you sure? This will unlink the Photoshop file from the board.

Edit in Photoshop
