### ISSUE TITLE
"New Shot" acting weird

### ISSUE THREAD

**Issue by CuberToy** [wonderunit/storyboarder#740]
Hi again WonderUnit !
So, I was trying to show how the "new shot" feature works, and find out it acted... not as before. It was kinda weird. It was joining previous boards, as expected, but also the next ones... and sometimes messing up with the thumbnails and boards order (like... thumbnails not being the correct ones...).

Here the gif I made, which wasn't as helpful as I hoped. Maybe it's just to late and I tired. 
https://i.imgur.com/BgIqn5Y.gif

I was wondering if that could be linked to #708 in any way too...

Win10

**Comment by setpixel** [comment]
Thats actually correct.

If no boards have a "new shot", then every board is a new shot.

If there is one "new shot" that shot is the first shot, (or second, if not the first board). Every shot in between is a tween shot so:

1a, 1b, 2a, 2b, 2c, 2d is correct

If you made the first 2 boards "new shot", it would be:

1a, 2a, 3a, 3b, 3c, 3d

**Comment by CuberToy** [comment]
Oh yeah, make sense in fact (I am tired, I said it). Once you tick "new shot" once, every new board you create will be >B until you tick again. So if I have a shot of three board, I tick the 4th board (which become 2A)... and if I have then 50 still images I have to tick the box every time. (That doesn't sound like a good movie though).

**Comment by setpixel** [comment]
You can select the boards with shift and click new shot for all of them.
