### ISSUE TITLE
'Clean up scene' deleting panel content

### ISSUE THREAD

**Issue by automaton-0** [wonderunit/storyboarder#742]
Hi devs,

While working on storyboard, I went back to eariler panels in the timeline and found 3 panels had disappeared, the thumbnails are still visible but the canvas is blank.

Upon further testing, I found that the 'clean up scene' function might not be working as intented as it deletes content from panels in the timeline.

I've not been able to consistently replicate the issue, but it seems to be related to duplicating panels, here's what I did:

**1.** created new storyboard document.
**2.** created 20 panels and drew the corrosponding numbers on each pane.
**3.** used 'clean up scene', nothing changed.
**3.** duplicated panel 1 three times and amended each with 1a, 1b, 1c.
**4.** used 'clean up scene' and the duplicate panels were deleted altogether.
**5.** repeated the action but nothing was deleted the second time.
**6.** repeated again with other panels, sometimes with a single panel being deleted.

**TEST 2**
**1.** created one panel and drew '1' on pane.
**2.** quickly duplicated it and added '2' on pane.
**3.** repeated 7 times with numbers 1 - 7 drawn on pane.
**4.** used 'clean up scene', this time received an error: 
Uncaught TypeError: Cannot read property of 'url' of undefined
In file C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js#1289:22
**5.** this pop up appears for each of the duplicate panels, it appears, followed by a different pop up:
Uncaught TypeError: Cannot read property 'lineMileage' of undefined
In file: *same as before but ending in main-window.js#1238:14
**6.** followed by another pop up:
Uncaught you need to call 'down' first
In file: C:\Program Files\Storyboarder\resources\app.asar\src\js\sketch-pane\index.js#571:7
**7.** after this the application would either become unresponsive or continue to launch pop ups when clicking on the window.

System specs:
Windows 10 (10.0.14393 build 14393)
Cintiq 13HD with driver version 6.3.23-1
GPU: Gigabyte R9 Radeon 280x

UPDATE: Another test: repeated test 2 but after duplicating panels, I waited for several seconds before using 'clean up scene'. No errors this time and no panels deleted, so I think it's obvious what happened before was that the app was still in the process of saving the new panels.
However, this still doesn't account for how my original panels were deleted long after they had been drawn.

Feels like this is linked to #713 somehow... but doing the opposite???

**Comment by audionerd** [comment]
Thanks for the repo.

My guess is that when duplicating boards, you ran into the dreaded missing file bug (which has been fixed https://github.com/wonderunit/storyboarder/issues/708) and only became aware of it when attempting to cleanup.

I think we will have fixed this in the upcoming release (v0.13.0)

Related to https://github.com/wonderunit/storyboarder/issues/708

**Comment by OliverGuse** [comment]
:(
