### ISSUE TITLE
File --> Export a PDF .... No PDF is generated

### ISSUE THREAD

**Issue by rushramlee** [wonderunit/storyboarder#747]

**Comment by CuberToy** [comment]
Same as #672 I guess ? Common new issue sadly.

**Comment by setpixel** [comment]
This is addressed in the release! (Today maybe!?!?) cc @audionerd

**Comment by audionerd** [comment]
Related to #708

**Comment by rushramlee** [comment]
Thanks Charles !

I found a workaround .. the problem is the last frame which generated some kind of a node error.

Once I deleted last frame , I was able to export to PDF.

Best ,

Rush
