### ISSUE TITLE
look into recently opened files and figure out why they are not working properly

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#75]
1. creating a new board file doesnt add itself.

2. opening a file adds itself, but needs to add correct metadata.

**Comment by audionerd** [comment]
I fixed [adding new files to the recent menu](https://github.com/wonderunit/storyboarder/commit/53aad026f15850a0943ecdc5e47af3d5bcb61443). Did not spend any time on metadata.

**Comment by setpixel** [comment]
Will reopen for metadata if we really need it.
