### ISSUE TITLE
No wacom pressure on Linux Mint 17

### ISSUE THREAD

**Issue by rebuilder** [wonderunit/storyboarder#752]
I'm using a Wacom Cintiq 24 HD touch, and pen pressure doesn't work under Linux Mint 17. It works in e.g. Krita.

**Comment by shrinidhi666** [comment]
It not working on ubuntu 16.04 nor any linux flavour for that matter . Can we get this fixed if possible . I am planning to use this as the main story board software for the studio i am working for . Also if possible, a config file to edit the file using any  editing software.

**Comment by setpixel** [comment]
Please see #690 for pen issues support
