### ISSUE TITLE
Duration settings do not work consistently despite what the settings are.

### ISSUE THREAD

**Issue by vfxtodd** [wonderunit/storyboarder#757]

**Comment by sowebby** [comment]
having the same issue love the app tho

**Comment by vfxtodd** [comment]
Yea, the app is a great idea. I'm trying to use it to work out a one minute short I'm writing. Once the Duration feature starts working it will help me time my short.

**Comment by audionerd** [comment]
Looks like this is a problem with playback. The durations are recorded properly, but playback has a bug that is reading the wrong values.

**Comment by audionerd** [comment]
Related:
https://github.com/wonderunit/storyboarder/issues/759
https://github.com/wonderunit/storyboarder/issues/760
https://github.com/wonderunit/storyboarder/issues/761

**Comment by vfxtodd** [comment]
Will users of storyboarder be emailed when the latest update is available? Or does the app automatically detect updates?

Thanks.

**Comment by audionerd** [comment]
@vfxtodd the app will auto-update

**Comment by setpixel** [comment]
@vfxtodd its up now

**Comment by vfxtodd** [comment]
Sweet. Duration works. Now I was able to block out my one minute short with it. Thanks a million.
