### ISSUE TITLE
duration does not work, love the app tho

### ISSUE THREAD

**Issue by sowebby** [wonderunit/storyboarder#759]
Love the app but I was making my first story bored, I had a long scene over 40 second of the same shot and i had duplicated the background plate but changed duration of each segment, when playing the whole scene back it would stay to long or short on certain shots and would't change no matter what I changed the duration too. Mac newest serria, thank you for such a great app apart from that tho

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the Beta 14 release.
