### ISSUE TITLE
Board duration malfunction

### ISSUE THREAD

**Issue by automaton-0** [wonderunit/storyboarder#760]
Firstly, thanks for the work on beta 13.

Just upgraded and noticed this new bug, similar bugs reported in #759 and #757.

I've done a quick test and what is apparent is that the duration setting for me works but misbehaves in that the duration is offset forward one board, i.e.:

1. I create a series of boards and manually set all to 24 frames. This works fine.
2. Select any one board and change the duration, e.g. set board 2 to 5 frames.
3. On the playback, board 2 will last 24 frames (from previous board) and board 3 will last 5 frames.
I can do this with any number of boards, the duration will always be pushed forward one board.

System specs:
Windows 10 (10.0.14393 build 14393)
Cintiq 13HD with driver version 6.3.23-1
GPU: Gigabyte R9 Radeon 280x

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the Beta 14 release.
