### ISSUE TITLE
duration feature got messed up

### ISSUE THREAD

**Issue by diorn** [wonderunit/storyboarder#761]
Hi, i think the duration feature got messed up, after switching order in my timeline between shots, also adding fresh ones between older ones i noticed that the duration time is not working correctly anymore when i hit play

**Comment by audionerd** [comment]
Thanks for the report. This will be fixed in the Beta 14 release.

**Comment by setpixel** [comment]
@diorn this fix is up live now.

**Comment by diorn** [comment]
Thank you guys, that was fast!
