### ISSUE TITLE
Wacom Cintiq Compatibility Jagged Lagging Brush strokes 

### ISSUE THREAD

**Issue by kwadwhoa** [wonderunit/storyboarder#763]
Hello, 
This is a wonderful program with so much potential.
I'm currently using Windows 7 64 bit . My computer Hardware specs are as follows: Intel Core i7-4770K CPU @3.50Ghz , 16 GB DDR3 memory. I'm currently using a dual display 1680x 1050 on the first screen and 1600x1200 on the second (Cintiq I'm using to draw and viewing the program on primarily)
 
![sidebyside](https://user-images.githubusercontent.com/32659629/31366547-95b0e68e-ad3f-11e7-82d6-6c1099430621.JPG)
The issue I'm having with drawing is that the pen seems to be unresponsive when I increase the speed of my brush strokes. I'm currently using a Cintiq 21ux and as I increase my brush strokes the brush breaks apart and cannot complete the action. I can, however import the file into Photoshop to complete the image however thats an extra step. I did take a screen shot to show you what I'm talking about. Thank you again

Best,
Kwadwo

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072

**Comment by NeeNeeCreative** [comment]
Hi there, I am using a Wacom Cintiq 13 on a windows 10 computer. and really like the idea of the software but my cintiq does not work in any usable way. Similar the comment above. The pen makes a dot and as I move it it makes a connecting line straight line. not a wiggly one which I have drawn. then it does not draw anything.
![problem with cintiq](https://user-images.githubusercontent.com/44057847/46801485-b0155300-cd52-11e8-846f-69e7064d5794.jpg)
