### ISSUE TITLE
Key Commands window not scrolling

### ISSUE THREAD

**Issue by CoIin** [wonderunit/storyboarder#765]
I read in the 0.13.1 fixes that the key commands window should be scrollable on short screens, or something to that effect. On my 15 inch MacBook Pro Retina (Mid 2015) the lowest item I can see ins the one about Edit in Photoshop, which may well be the last one, and why there's no scrolling.

But, I have to hide the Dock to see toggle board, flip horizontal, and edit in photoshop. The height of the window should go from the menubar to the top of the Dock, if it's showing, not to the bottom of the screen.

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!

**Comment by CoIin** [comment]
Sorry for the delay in checking in. The current version's Preferences look quite different now, and they do scroll ok, thanks.
