### ISSUE TITLE
Problem with exports

### ISSUE THREAD

**Issue by brotenet** [wonderunit/storyboarder#766]
Hello, 

Exporting does not work. It shows the export compilation progress message at the bottom-right but once it is finished there are no exported files in the 'exports' directory of the project.
(tested in Linux Mint with AppImage)

1. Use Linux Mint 18.2 (or Ubuntu 16.04LTS) as testing OS
2. Download the AppImage
3. Create new project.
4. Atempt to export in GIF, PDF etc.
5. Check the 'exports' directory of the project. No files have been generated.

**Expecting:** to have files in the 'exports' directory of the project.

**What happened:** No files have been generated after export.

**OS:** Linux Mint 18.2 (or Ubuntu 16.04LTS)

**Computer Specs (lshw):**

> description: Notebook
>     product: 24296JG (LENOVO_MT_2429)
>     vendor: LENOVO
>     version: ThinkPad T530
>     serial: PK1C5EK
>     width: 64 bits
>     capabilities: smbios-2.7 dmi-2.7 vsyscall32
>     configuration: administrator_password=disabled chassis=notebook family=ThinkPad T530 power-on_password=disabled sku=LENOVO_MT_2429 uuid=0188F52E-6053-CB11-9CE1-ECD220206900
>   *-core
>        description: Motherboard
>        product: 24296JG
>        vendor: LENOVO
>        physical id: 0
>        version: 0B98417 PRO
>        serial: 1ZSF445GFUS
>        slot: Not Available
>      *-cpu
>           description: CPU
>           product: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
>           vendor: Intel Corp.
>           physical id: 1
>           bus info: cpu@0
>           version: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
>           serial: None
>           slot: CPU Socket - U3E1
>           size: 3200MHz
>           capacity: 3400MHz
>           width: 64 bits
>           clock: 100MHz
>           capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts cpufreq
>           configuration: cores=4 enabledcores=4 threads=8
>         *-cache:0
>              description: L1 cache
>              physical id: 3
>              slot: L1-Cache
>              size: 32KiB
>              capacity: 32KiB
>              capabilities: internal write-through instruction
>              configuration: level=1
>         *-cache:1
>              description: L2 cache
>              physical id: 4
>              slot: L2-Cache
>              size: 256KiB
>              capacity: 256KiB
>              capabilities: internal write-through unified
>              configuration: level=2
>         *-cache:2
>              description: L3 cache
>              physical id: 5
>              slot: L3-Cache
>              size: 6MiB
>              capacity: 6MiB
>              capabilities: internal write-back unified
>              configuration: level=3
>      *-cache
>           description: L1 cache
>           physical id: 2
>           slot: L1-Cache
>           size: 32KiB
>           capacity: 32KiB
>           capabilities: internal write-through data
>           configuration: level=1
>      *-memory
>           description: System Memory
>           physical id: 7
>           slot: System board or motherboard
>           size: 16GiB
>         *-bank:0
>              description: SODIMM DDR3 Synchronous 1600 MHz (0,6 ns)
>              product: 99U5428-063.A00G
>              vendor: Kingston
>              physical id: 0
>              serial: 5C1861DC
>              slot: ChannelA-DIMM0
>              size: 8GiB
>              width: 64 bits
>              clock: 1600MHz (0.6ns)
>         *-bank:1
>              description: SODIMM DDR3 Synchronous 1600 MHz (0,6 ns)
>              product: 99U5428-063.A00G
>              vendor: Kingston
>              physical id: 1
>              serial: 601886DC
>              slot: ChannelB-DIMM0
>              size: 8GiB
>              width: 64 bits
>              clock: 1600MHz (0.6ns)
>      *-firmware
>           description: BIOS
>           vendor: LENOVO
>           physical id: b
>           version: G4ET99WW (2.59 )
>           date: 02/25/2014
>           size: 128KiB
>           capacity: 11MiB
>           capabilities: pci pnp upgrade shadowing cdboot bootselect edd int13floppy720 int5printscreen int9keyboard int14serial int17printer int10video acpi usb biosbootspecification uefi
>      *-pci
>           description: Host bridge
>           product: 3rd Gen Core processor DRAM Controller
>           vendor: Intel Corporation
>           physical id: 100
>           bus info: pci@0000:00:00.0
>           version: 09
>           width: 32 bits
>           clock: 33MHz
>           configuration: driver=ivb_uncore
>           resources: irq:0
>         *-pci:0
>              description: PCI bridge
>              product: Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port
>              vendor: Intel Corporation
>              physical id: 1
>              bus info: pci@0000:00:01.0
>              version: 09
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
>              configuration: driver=pcieport
>              resources: irq:24 ioport:5000(size=4096) memory:f0000000-f10fffff ioport:c0000000(size=301989888)
>            *-generic UNCLAIMED
>                 description: Unassigned class
>                 product: Illegal Vendor ID
>                 vendor: Illegal Vendor ID
>                 physical id: 0
>                 bus info: pci@0000:01:00.0
>                 version: ff
>                 width: 32 bits
>                 clock: 66MHz
>                 capabilities: bus_master vga_palette cap_list
>                 configuration: latency=255 maxlatency=255 mingnt=255
>                 resources: memory:f0000000-f0ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:5000(size=128) memory:f1000000-f107ffff
>         *-display
>              description: VGA compatible controller
>              product: 3rd Gen Core processor Graphics Controller
>              vendor: Intel Corporation
>              physical id: 2
>              bus info: pci@0000:00:02.0
>              version: 09
>              width: 64 bits
>              clock: 33MHz
>              capabilities: msi pm vga_controller bus_master cap_list rom
>              configuration: driver=i915 latency=0
>              resources: irq:27 memory:f1400000-f17fffff memory:e0000000-efffffff ioport:6000(size=64) memory:c0000-dffff
>         *-usb:0
>              description: USB controller
>              product: 7 Series/C210 Series Chipset Family USB xHCI Host Controller
>              vendor: Intel Corporation
>              physical id: 14
>              bus info: pci@0000:00:14.0
>              version: 04
>              width: 64 bits
>              clock: 33MHz
>              capabilities: pm msi xhci bus_master cap_list
>              configuration: driver=xhci_hcd latency=0
>              resources: irq:25 memory:f3a20000-f3a2ffff
>            *-usbhost:0
>                 product: xHCI Host Controller
>                 vendor: Linux 4.10.0-37-generic xhci-hcd
>                 physical id: 0
>                 bus info: usb@3
>                 logical name: usb3
>                 version: 4.10
>                 capabilities: usb-2.00
>                 configuration: driver=hub slots=4 speed=480Mbit/s
>               *-usb:0
>                    description: Mass storage device
>                    product: ZTEL110
>                    vendor: ZTEL110
>                    physical id: 2
>                    bus info: usb@3:2
>                    logical name: scsi4
>                    version: ff.ff
>                    serial: 900641002214
>                    capabilities: usb-2.00 scsi emulated scsi-host
>                    configuration: driver=usb-storage maxpower=500mA speed=480Mbit/s
>                  *-disk
>                       description: SCSI Disk
>                       physical id: 0.0.0
>                       bus info: scsi@4:0.0.0
>                       logical name: /dev/sdc
>                       configuration: logicalsectorsize=512 sectorsize=512
>               *-usb:1
>                    description: Communication device
>                    product: H5321 gw
>                    vendor: Lenovo
>                    physical id: 4
>                    bus info: usb@3:4
>                    version: 0.00
>                    serial: D1DB9C40766EAAM0
>                    capabilities: usb-2.00
>                    configuration: driver=cdc_acm speed=480Mbit/s
>            *-usbhost:1
>                 product: xHCI Host Controller
>                 vendor: Linux 4.10.0-37-generic xhci-hcd
>                 physical id: 1
>                 bus info: usb@4
>                 logical name: usb4
>                 version: 4.10
>                 capabilities: usb-3.00
>                 configuration: driver=hub slots=4 speed=5000Mbit/s
>         *-communication
>              description: Communication controller
>              product: 7 Series/C210 Series Chipset Family MEI Controller #1
>              vendor: Intel Corporation
>              physical id: 16
>              bus info: pci@0000:00:16.0
>              version: 04
>              width: 64 bits
>              clock: 33MHz
>              capabilities: pm msi bus_master cap_list
>              configuration: driver=mei_me latency=0
>              resources: irq:28 memory:f3a35000-f3a3500f
>         *-network
>              description: Ethernet interface
>              product: 82579LM Gigabit Network Connection
>              vendor: Intel Corporation
>              physical id: 19
>              bus info: pci@0000:00:19.0
>              logical name: enp0s25
>              version: 04
>              serial: 3c:97:0e:8f:c4:c5
>              size: 1Gbit/s
>              capacity: 1Gbit/s
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pm msi bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
>              configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=3.2.6-k duplex=full firmware=0.13-3 ip=192.168.0.7 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
>              resources: irq:26 memory:f3a00000-f3a1ffff memory:f3a3a000-f3a3afff ioport:6060(size=32)
>         *-usb:1
>              description: USB controller
>              product: 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2
>              vendor: Intel Corporation
>              physical id: 1a
>              bus info: pci@0000:00:1a.0
>              version: 04
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pm debug ehci bus_master cap_list
>              configuration: driver=ehci-pci latency=0
>              resources: irq:16 memory:f3a39000-f3a393ff
>            *-usbhost
>                 product: EHCI Host Controller
>                 vendor: Linux 4.10.0-37-generic ehci_hcd
>                 physical id: 1
>                 bus info: usb@1
>                 logical name: usb1
>                 version: 4.10
>                 capabilities: usb-2.00
>                 configuration: driver=hub slots=3 speed=480Mbit/s
>               *-usb
>                    description: USB hub
>                    product: Integrated Rate Matching Hub
>                    vendor: Intel Corp.
>                    physical id: 1
>                    bus info: usb@1:1
>                    version: 0.00
>                    capabilities: usb-2.00
>                    configuration: driver=hub slots=6 speed=480Mbit/s
>                  *-usb:0
>                       description: Keyboard
>                       product: ActiveJet K-2024 Multimedia Keyboard
>                       vendor: Elan Microelectronics Corp.
>                       physical id: 2
>                       bus info: usb@1:1.2
>                       version: 1.07
>                       capabilities: usb-2.00
>                       configuration: driver=usbhid maxpower=100mA speed=1Mbit/s
>                  *-usb:1 UNCLAIMED
>                       description: Generic USB device
>                       product: Biometric Coprocessor
>                       vendor: Auth
>                       physical id: 3
>                       bus info: usb@1:1.3
>                       version: 0.01
>                       capabilities: usb-1.10
>                       configuration: maxpower=100mA speed=12Mbit/s
>                  *-usb:2
>                       description: Generic USB device
>                       product: BCM20702A0
>                       vendor: Broadcom Corp
>                       physical id: 4
>                       bus info: usb@1:1.4
>                       version: 1.12
>                       serial: 3C77E6EB37AD
>                       capabilities: usb-2.00
>                       configuration: driver=btusb speed=12Mbit/s
>                  *-usb:3
>                       description: Video
>                       product: Integrated Camera
>                       vendor: Chicony Electronics Co., Ltd.
>                       physical id: 6
>                       bus info: usb@1:1.6
>                       version: 5.20
>                       capabilities: usb-2.00
>                       configuration: driver=uvcvideo maxpower=200mA speed=480Mbit/s
>         *-multimedia
>              description: Audio device
>              product: 7 Series/C210 Series Chipset Family High Definition Audio Controller
>              vendor: Intel Corporation
>              physical id: 1b
>              bus info: pci@0000:00:1b.0
>              version: 04
>              width: 64 bits
>              clock: 33MHz
>              capabilities: pm msi pciexpress bus_master cap_list
>              configuration: driver=snd_hda_intel latency=0
>              resources: irq:30 memory:f3a30000-f3a33fff
>         *-pci:1
>              description: PCI bridge
>              product: 7 Series/C210 Series Chipset Family PCI Express Root Port 1
>              vendor: Intel Corporation
>              physical id: 1c
>              bus info: pci@0000:00:1c.0
>              version: c4
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
>              configuration: driver=pcieport
>              resources: irq:16 ioport:4000(size=4096) memory:f3100000-f39fffff ioport:f1800000(size=8388608)
>            *-generic
>                 description: System peripheral
>                 product: MMC/SD Host Controller
>                 vendor: Ricoh Co Ltd
>                 physical id: 0
>                 bus info: pci@0000:02:00.0
>                 version: 08
>                 width: 32 bits
>                 clock: 33MHz
>                 capabilities: msi pm pciexpress bus_master cap_list
>                 configuration: driver=sdhci-pci latency=0
>                 resources: irq:16 memory:f3101000-f31010ff
>            *-firewire
>                 description: FireWire (IEEE 1394)
>                 product: R5C832 PCIe IEEE 1394 Controller
>                 vendor: Ricoh Co Ltd
>                 physical id: 0.3
>                 bus info: pci@0000:02:00.3
>                 version: 04
>                 width: 32 bits
>                 clock: 33MHz
>                 capabilities: msi pm pciexpress ohci bus_master cap_list
>                 configuration: driver=firewire_ohci latency=0
>                 resources: irq:19 memory:f3100000-f31007ff
>         *-pci:2
>              description: PCI bridge
>              product: 7 Series/C210 Series Chipset Family PCI Express Root Port 2
>              vendor: Intel Corporation
>              physical id: 1c.1
>              bus info: pci@0000:00:1c.1
>              version: c4
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
>              configuration: driver=pcieport
>              resources: irq:17 memory:f3000000-f30fffff
>            *-network
>                 description: Wireless interface
>                 product: Centrino Advanced-N 6205 [Taylor Peak]
>                 vendor: Intel Corporation
>                 physical id: 0
>                 bus info: pci@0000:03:00.0
>                 logical name: wlp3s0
>                 version: 34
>                 serial: a4:4e:31:7c:c1:e4
>                 width: 64 bits
>                 clock: 33MHz
>                 capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
>                 configuration: broadcast=yes driver=iwlwifi driverversion=4.10.0-37-generic firmware=18.168.6.1 ip=10.0.0.140 latency=0 link=yes multicast=yes wireless=IEEE 802.11
>                 resources: irq:29 memory:f3000000-f3001fff
>         *-pci:3
>              description: PCI bridge
>              product: 7 Series/C210 Series Chipset Family PCI Express Root Port 3
>              vendor: Intel Corporation
>              physical id: 1c.2
>              bus info: pci@0000:00:1c.2
>              version: c4
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
>              configuration: driver=pcieport
>              resources: irq:18 ioport:3000(size=4096) memory:f2800000-f2ffffff ioport:f2000000(size=8388608)
>         *-usb:2
>              description: USB controller
>              product: 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1
>              vendor: Intel Corporation
>              physical id: 1d
>              bus info: pci@0000:00:1d.0
>              version: 04
>              width: 32 bits
>              clock: 33MHz
>              capabilities: pm debug ehci bus_master cap_list
>              configuration: driver=ehci-pci latency=0
>              resources: irq:23 memory:f3a38000-f3a383ff
>            *-usbhost
>                 product: EHCI Host Controller
>                 vendor: Linux 4.10.0-37-generic ehci_hcd
>                 physical id: 1
>                 bus info: usb@2
>                 logical name: usb2
>                 version: 4.10
>                 capabilities: usb-2.00
>                 configuration: driver=hub slots=3 speed=480Mbit/s
>               *-usb
>                    description: USB hub
>                    product: Integrated Rate Matching Hub
>                    vendor: Intel Corp.
>                    physical id: 1
>                    bus info: usb@2:1
>                    version: 0.00
>                    capabilities: usb-2.00
>                    configuration: driver=hub slots=8 speed=480Mbit/s
>                  *-usb
>                       description: Mouse
>                       product: USB Optical Mouse
>                       vendor: PixArt
>                       physical id: 5
>                       bus info: usb@2:1.5
>                       version: 1.00
>                       capabilities: usb-1.10
>                       configuration: driver=usbhid maxpower=100mA speed=1Mbit/s
>         *-isa
>              description: ISA bridge
>              product: QM77 Express Chipset LPC Controller
>              vendor: Intel Corporation
>              physical id: 1f
>              bus info: pci@0000:00:1f.0
>              version: 04
>              width: 32 bits
>              clock: 33MHz
>              capabilities: isa bus_master cap_list
>              configuration: driver=lpc_ich latency=0
>              resources: irq:0
>         *-ide:0
>              description: IDE interface
>              product: 7 Series Chipset Family 4-port SATA Controller [IDE mode]
>              vendor: Intel Corporation
>              physical id: 1f.2
>              bus info: pci@0000:00:1f.2
>              version: 04
>              width: 32 bits
>              clock: 66MHz
>              capabilities: ide pm bus_master cap_list
>              configuration: driver=ata_piix latency=0
>              resources: irq:19 ioport:1f0(size=8) ioport:3f6 ioport:170(size=8) ioport:376 ioport:60b0(size=16) ioport:60a0(size=16)
>         *-serial UNCLAIMED
>              description: SMBus
>              product: 7 Series/C210 Series Chipset Family SMBus Controller
>              vendor: Intel Corporation
>              physical id: 1f.3
>              bus info: pci@0000:00:1f.3
>              version: 04
>              width: 64 bits
>              clock: 33MHz
>              configuration: latency=0
>              resources: memory:f3a34000-f3a340ff ioport:efa0(size=32)
>         *-ide:1
>              description: IDE interface
>              product: 7 Series Chipset Family 2-port SATA Controller [IDE mode]
>              vendor: Intel Corporation
>              physical id: 1f.5
>              bus info: pci@0000:00:1f.5
>              version: 04
>              width: 32 bits
>              clock: 66MHz
>              capabilities: ide pm bus_master cap_list
>              configuration: driver=ata_piix latency=0
>              resources: irq:19 ioport:60c8(size=8) ioport:60e4(size=4) ioport:60c0(size=8) ioport:60e0(size=4) ioport:6090(size=16) ioport:6080(size=16)
>      *-scsi:0
>           physical id: 0
>           logical name: scsi0
>           capabilities: emulated
>         *-disk
>              description: ATA Disk
>              product: SanDisk Ultra II
>              physical id: 0.0.0
>              bus info: scsi@0:0.0.0
>              logical name: /dev/sda
>              version: 00RL
>              serial: 161322800385
>              size: 447GiB (480GB)
>              capabilities: partitioned partitioned:dos
>              configuration: ansiversion=5 logicalsectorsize=512 sectorsize=512 signature=ddd667a2
>            *-volume:0
>                 description: Linux filesystem partition
>                 vendor: Linux
>                 physical id: 1
>                 bus info: scsi@0:0.0.0,1
>                 logical name: /dev/sda1
>                 logical name: /boot
>                 version: 1.0
>                 serial: 50c0dadb-1530-4108-9bea-298579fedbd0
>                 size: 487MiB
>                 capacity: 487MiB
>                 capabilities: primary bootable extended_attributes large_files ext2 initialized
>                 configuration: filesystem=ext2 lastmountpoint=/boot modified=2017-10-10 15:51:04 mount.fstype=ext2 mount.options=rw,relatime,block_validity,barrier,user_xattr,acl mounted=2017-10-10 08:34:34 state=mounted
>            *-volume:1
>                 description: Extended partition
>                 physical id: 2
>                 bus info: scsi@0:0.0.0,2
>                 logical name: /dev/sda2
>                 size: 446GiB
>                 capacity: 446GiB
>                 capabilities: primary extended partitioned partitioned:extended
>               *-logicalvolume
>                    description: Linux LVM Physical Volume partition
>                    physical id: 5
>                    logical name: /dev/sda5
>                    serial: 5uNAen-NiM8-Mien-OQ9S-rywj-WEq2-9CW50m
>                    size: 446GiB
>                    capacity: 446GiB
>                    capabilities: multi lvm2
>      *-scsi:1
>           physical id: 3
>           logical name: scsi1
>           capabilities: emulated
>         *-disk
>              description: ATA Disk
>              product: ST1000LM014-1EJ1
>              vendor: Seagate
>              physical id: 0.0.0
>              bus info: scsi@1:0.0.0
>              logical name: /dev/sdb
>              version: SM14
>              serial: W3814DJ3
>              size: 931GiB (1TB)
>              capabilities: partitioned partitioned:dos
>              configuration: ansiversion=5 logicalsectorsize=512 sectorsize=4096 signature=f4b2ebf8
>            *-volume
>                 description: Windows NTFS volume
>                 physical id: 1
>                 bus info: scsi@1:0.0.0,1
>                 logical name: /dev/sdb1
>                 logical name: /media/DATA_EXT
>                 version: 3.1
>                 serial: bef3654c-cc50-6a45-95c3-17c8a87a011e
>                 size: 931GiB
>                 capacity: 931GiB
>                 capabilities: primary ntfs initialized
>                 configuration: clustersize=4096 created=2014-02-05 15:57:32 filesystem=ntfs label=DATA_EXT modified_by_chkdsk=true mount.fstype=fuseblk mount.options=rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096 mounted_on_nt4=true resize_log_file=true state=mounted upgrade_on_mount=true
>   *-battery
>        product: 45N1173
>        vendor: SANYO
>        physical id: 1
>        slot: Rear
>        capacity: 85860mWh
>        configuration: voltage=10,8V
>   *-network DISABLED
>        description: Ethernet interface
>        physical id: 2
>        logical name: wwp0s20u4i6
>        serial: 92:e3:4e:77:c3:6d
>        capabilities: ethernet physical
>        configuration: broadcast=yes driver=cdc_mbim driverversion=22-Aug-2005 firmware=CDC MBIM link=no multicast=yes

**Comment by audionerd** [comment]
Could you send us a ZIP'd version of the project folder (including .storyboarder and images) for the project where you're seeing this bug?

It's possible an error is being triggered but not reported. You could try "Toggle Developer Tools" on the main workspace and let us know what errors you see.

**Comment by brotenet** [comment]
hi audionerd

I've removed the app after the issue occurred. 
I'll download it again and try to replicate the issue with dev-mode and also send you the project as soon as I get the chance.
