### ISSUE TITLE
Long text blocks are being cut off in the pdf.

### ISSUE THREAD

**Issue by mariatyomkina** [wonderunit/storyboarder#771]
Hi, I just started using the tool, and it's great - thank you!

But there is one thing that makes the tool unusable for me at the moment since I can't show it to the client like this: 
I don't have a voiceover for my animation yet, so I am putting bits of written script in the "Dialog" box, and then also writing a bunch of text in the "Action" box. And then when I export pdf, some of the text is being covered by the frames. 

See attached for a sample pdf. (Frame 4A text is being covered by Frame 7A image.

Another little bug - On the PDF, sometimes text from "Dialog" box is bold and sometimes it's regular. 

I am on a Mac/Sierra OS
Processor: 2.9 GHz Intel Core i7
Graphics: Radeon Pro 460 4096 MB
                 Intel HD Graphics 530 1536 MB

thank you!
-maria.

[GCP UCAA 2017-10-11 03.27.03.pdf](https://github.com/wonderunit/storyboarder/files/1377387/GCP.UCAA.2017-10-11.03.27.03.pdf)

**Comment by setpixel** [comment]
Ah yeah! Sorry about this.. this is a bug with my layout code. It's next on the list to fix.

**Comment by setpixel** [comment]
This is fixed in the next release!
