### ISSUE TITLE
error sending to photoshop

### ISSUE THREAD

**Issue by tobitoakatsuki** [wonderunit/storyboarder#772]
After sending to edit in photoshop very times, now it doesnt work anymore, i click the button but nothing happend

work with windows 10

**Comment by jvault** [comment]
Verify that you have a default application set for psd files.

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!

**Comment by tobitoakatsuki** [comment]
No, don't have the issue but now when i send and edit un Photoshop and save
don't refresh un storyboarder until i click Edit in Photoshop again

Atte. Ricardo Contreras
