### ISSUE TITLE
The Font come out like a box.

### ISSUE THREAD

**Issue by Jooonkyuha** [wonderunit/storyboarder#774]
Hello.
If you put Korean in the program, the box looks like a box. Is there any solution?

**Comment by setpixel** [comment]
Hi @Jooonkyuha Can you zip your project and send it to me so I can debug?

**Comment by Jooonkyuha** [comment]
hi
Please.
https://drive.google.com/open?id=0B18eoWVHAkFvWGF5ZWluNWVqU1E

**Comment by Jooonkyuha** [comment]
Please.

**Comment by Jooonkyuha** [comment]
hi
Please.
https://drive.google.com/open?id=0B18eoWVHAkFvWGF5ZWluNWVqU1E

**Comment by audionerd** [comment]
Thanks for the report. Looks like the same issue as #746.
We're going to try to fix this by using a typeface or fallback for PDF that allows international characters.

**Comment by setpixel** [comment]
Korean chinese and japanese are supported in next version.
