### ISSUE TITLE
Open a new file

### ISSUE THREAD

**Issue by Butterfly59** [wonderunit/storyboarder#777]
Hi, 
i just downloaded the Storyboarder app. Everything works fine...but when i wish to start a new board it wishes me to select a file. What kind of file should it be? Something about overwriting the folder, but what kind of folder is it and where to find it? 
Please help?
Thank you

**Comment by anne-andy** [comment]
From what I can tell you don't need to select anything. Navigate to the folder you want your file to be in, enter your desired filename into the filename box (don't need to add an extension), then click create.

**Comment by Butterfly59** [comment]
Thank youuu, you don't know how long I tried to solve this. :D
