### ISSUE TITLE
Mouse cursor separated from stylus'

### ISSUE THREAD

**Issue by cencoeur** [wonderunit/storyboarder#779]
Hello, the bug i've found is that my mouse and my tablet's stylus seems to be de-synchronized on the software, the mouse cursor is independent from the stylus' one. Storyboarder seems to not know which one to choose and to switch between both, tracing undesired lines as shown below, where i placed my stylus on my tablet and turned around, using my mouse.

![storyboarder_2017-10-13_00-56-29](https://user-images.githubusercontent.com/32557426/31523033-674eb59a-afb1-11e7-9cb6-167c93733a7b.png)

If you have any tips on how to prevent this from happening ^^

My PC runs on Windows 10 64-bits.

My specs are : 
-Processor : Intel Core i5-6300HQ CPU @ 2,30GHz 
-Graphic card : Nvidia Geforce GTX 1060
-RAM : 8 Go 
-Screen resolution : 1920*1080
-Graphic tablet : Wacom Intuos Pro M

**Comment by setpixel** [comment]
related to: #1072

**Comment by setpixel** [comment]
duplicate: #927
