### ISSUE TITLE
Pen pressure don´t work

### ISSUE THREAD

**Issue by Velartius** [wonderunit/storyboarder#781]
Hi there! hope everything is Ok
Just downloaded Storyboarder an hour ago and pen pressure don´t work, pen pressure works on Photoshop and everything else.
Thanks in advance for your collaboration,
Best
Alex

**Comment by audionerd** [comment]
Can you let us know which operating system and pen tablet system you're using? Any specs on your device setup would be useful.

**Comment by Velartius** [comment]
Hello, sure, thanks, I'm using Windows 7 (64 Bits), Intel core i7 with 8 GB in RAM, Nvidia Geforce GT 540M and a EasyPen i405 Genius Tablet.
Best
Alex

**Comment by setpixel** [comment]
Please see #690 for pen issues support
