### ISSUE TITLE
Import audio

### ISSUE THREAD

**Issue by MduComicsZA** [wonderunit/storyboarder#783]
Hi There,

I just tried your software and I think it amazing. I just want to suggest that you include feature to import sound so we can render an animatic. This will really be handy for big teams to understand the and the timing in the story.

**Comment by morganwk** [comment]
This would be absolutely fantastic. Storyboarder might end up being my favorite simple animation tool with this and a few other small features.

**Comment by MrWolfhare** [comment]
Oh yeah, that would be really helpful with timing. Do think about adding that feature in the program.
