### ISSUE TITLE
Support international characters in PDF export

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#788]
Will need a fallback typeface.

RELATED ISSUES
https://github.com/wonderunit/storyboarder/issues/746
https://github.com/wonderunit/storyboarder/issues/774

REFERENCE
https://github.com/devongovett/pdfkit/issues/201
http://blog.apitron.com/2015/08/how-to-set-fallback-fonts-for-pdf-rendering-and-creation.html
https://github.com/prawnpdf/prawn/issues/103
https://stackoverflow.com/a/27650561

**Comment by setpixel** [comment]
Im going to mark this as fixed, however, we still dont properly support: hebrew, arabic, and arameic. (RTL languages)
