### ISSUE TITLE
First thoughts using Storyboarder

### ISSUE THREAD

**Issue by inefecto** [wonderunit/storyboarder#789]
Can we choose 25fps instead of 24?
The pdf export is not working with Mac?
What are the formats allowed for the script import?
Thanks for your help!

**Comment by audionerd** [comment]
FPS is 24fps only rn, but we want to make that configurable in 2.0.
Script import is .fountain only rn.
If PDF export isn't working, it's a bug.

What specifically happens when you try to export a PDF?

**Comment by inefecto** [comment]
Thanks for your quick answer!
When I try to export in pdf a window opens in the bottom right corner, then
it disappears and nothing happens.

Raul


*_________________________________**_**_**_**_**_**_**_**_**_**_**_**_**_*
*_*



*Raul Carbo Perea*Gsm : +33 (0)6 81 73 40 82
Email : raul@inefecto.com
Web : www.inefecto.com

2017-10-14 20:50 GMT+02:00 Eric Skogen <notifications@github.com>:

**Comment by setpixel** [comment]
Fixed in current release!
