### ISSUE TITLE
Bold for Dialogue

### ISSUE THREAD

**Issue by Bakeranimator** [wonderunit/storyboarder#792]
Hi. 

Great program! The only thing is I want all the dialogue to appear in bold and it doesn't always do this which means I can't use it which is a shame?

**Comment by setpixel** [comment]
Where do you mean?

**Comment by Bakeranimator** [comment]
Hi - sorry that was really unclear. When i export the storyboard to PDF, some of the bits of dialogue appear in bold (beneath the images) but some do not. It would be nice if they all did - or am I missing something? I do miss lots of things. It's good to have distinction between dialogue and stage directions.

**Comment by setpixel** [comment]
Fixed in next release! Woot!
