### ISSUE TITLE
Shot Generator disabled - though WebGl works in browsers

### ISSUE THREAD

**Issue by HighQu** [wonderunit/storyboarder#794]
Unfortunately I am not able to get Shot Generator when I open Storyboarder. 
It says it is disabled due to better performance.
I am working on a mac Pro 15’, 2011 
with an AMD Radeon HD 6750M 1024 MB graphic card and mavericks.
I found out it must be because of WebGL. 
But all my browsers are able to display WebGL.
Is there a trick or easy hack to make Shot Generator work? Or no chance?

**Comment by ugly** [comment]
Hello I have the same Mac Pro 15inch 2011, with both Intel HD Graphics 3000 and AMD Radeon HD 6750M 1024 MB graphic card, running Sierra 10.12.6  etc. I too thought Shot Generator wasn't working. After wasting a few hours of checking Activity Monitor for which graphics card was running, etc. 
Downloaded wonderunit versions 1.5.1 from [(https://kubadownload.com/storyboarder-download.1687.html)] ("Download Storyboarder directly from the developer.
")
You have to hold the right mouse key in the Storyboarder menu area and move the menu area up or down to get to the Shot Generator area. Its not obvious but it works. YES!

**Comment by HighQu** [comment]
Thank you so much for your reply - you're right it works! YES! And its cool.
I did as you said and downloaded version 1.5.1 - didn't even have to hold the right mouse to make the Shot Generator show up.
