### ISSUE TITLE
Last frame not saving when using 'time slider'

### ISSUE THREAD

**Issue by rjkoti** [wonderunit/storyboarder#807]
This was with a new Wide storyboard saved to desktop.
Draw something on the default frame, create another frame draw something. Without doing anything else, press the first frames location on the time slider. The main panel switches to the first frame. Now switch back to the second frame.
I expected to see my second drawing like the thumbnail displayed. Instead it was a blank canvas.
If you now press the first frame thumbnail again, the second frame thumbnail goes blank.

It would appear that the frame you are on does not get saved when using the time slider to switch between frames.

Windows 10 64bit.
3 * 1920 x 1200(p) (59.950Hz)
Processor: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 CPUs), ~3.4GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce GTX 1060 6GB

**Comment by audionerd** [comment]
Thanks for this report @rjkoti! Your description made it really easy to track down.

Should be fixed in the next release of Storyboarder.
