### ISSUE TITLE
Send to Photoshop > Import a b/ground image

### ISSUE THREAD

**Issue by Jamnewt** [wonderunit/storyboarder#818]

**Comment by Jamnewt** [comment]
Open the Storyboard app and export it to Photoshop. Once in Photoshop import a photo background - this is not supported by the looks of things as it doesn't update the Storyboard app.

Drawing on a photo backdrop is often an essential part of storyboarding when you have fixed locations already in place. It helps so we know where to place the camera and what lens to use etc. I've seen plenty of boards that have drawn from a 18mm lens perspective when the scene is a bathroom cubicle and just not physically possible on set.

**Comment by audionerd** [comment]
Try putting the photo on the reference layer instead of the background layer.

**Comment by Jamnewt** [comment]
Genius. Thank you.
