### ISSUE TITLE
Cropped text when exporting PDF

### ISSUE THREAD

**Issue by VictorBCN2020** [wonderunit/storyboarder#820]
When exporting to PDF, in the 3x3 panels layout, there is a lack of space below earch image for the dialogue text, description or action. It would be nice if we coould set differnts layouts (as we can when creating a Storyboarder worksheet, where we can config columns and rows).
Regards

**Comment by gordielachance** [comment]
+1
related to https://github.com/wonderunit/storyboarder/issues/836

**Comment by setpixel** [comment]
Fixed in next release! Woot!
