### ISSUE TITLE
Storyboarder & Pixelmator

### ISSUE THREAD

**Issue by MarkAlanCirino** [wonderunit/storyboarder#823]
I really like Storyboarder, but I don't use PhotoShop. On my 2017 iMac, I use Pixelmator. When I click the PS button in Storyboarder, it actually launches Pixelmator and opens the document correctly. When I save it in Pixelmator, it writes a PS file, but Storyboarder says it can't import the file. So, it's almost there. I'm hoping you can tweak the code to make it work completely. I'm attaching a PS file for an example. Thanks and keep up the good work!
[board-1-2Y3ZA.psd.zip](https://github.com/wonderunit/storyboarder/files/1407658/board-1-2Y3ZA.psd.zip)

**Comment by audionerd** [comment]
Sounds like this issue can be closed, although we still need to address #851
