### ISSUE TITLE
Whole Project Deleted. 

### ISSUE THREAD

**Issue by safy87** [wonderunit/storyboarder#827]
I drew 56 panels in my project. I was getting the same errors other mac users reported. Lines would disappear and sometimes the board I was drawing on would have drawings from a previous board in the lightbox/reference layer. When the bugs started to occur I always ran saved and save as command and restart storyboarder. When I reopened my project I got the error message that my project no longer existed. Now the folders are still in the directory I chose however there is no content in these folders. I attempted to recreate the error but now everything is working properly. 
 
I use a Mac OS Captain.

**Comment by audionerd** [comment]
This is a very weird error. Is it possible you ran out of disk space while working on the project?
