### ISSUE TITLE
Worksheet import does not work

### ISSUE THREAD

**Issue by schustudra** [wonderunit/storyboarder#829]
When I try to import a scanned worksheet, I am prompted to enter the QR-Code manually. When I do that, an error is displayed: "Hmm, I couldn't use that QR-Code"... I have checked that I am using the right Code.  

**Steps to reproduce the error:**
1. Create a new Storyboard
2. Blank Storyboard
3. Ultrawide
4. Print a Worksheet
5. Import it
6. Follow the import Dialog

I have tried this specific worksheet:

![scn2](https://user-images.githubusercontent.com/33056267/31937535-1416001a-b8b5-11e7-82dd-29d0e3198aa9.jpg)

I am using the latest version of Storyboarder (Updateted on 24th October 2017) With Windows 10. I have an Intel Core i7-4790 CPU @ 3,60 GHz, 12 Gb of RAM an AMD Radeon R9 250 Graphics Card.

**Comment by audionerd** [comment]
Looks like a bug in Storyboarder. The QR code validator is failing on the 'A4' letter size chunk.

Try using `0-LTR-4-3-30-2.390-3208` (LTR instead of A4) and it will work.

We'll take a look at a long-term fix for Storyboarder to prevent this in the future.

**Comment by audionerd** [comment]
Will be fixed in the next release.

**Comment by tjitji** [comment]
Hello, @audionerd. I just found and started using storyboarder and very thankful for the developers. I noticed that the issue with A4 output is happening again with M1 MacBook Pro. Could you please check that again when you are available?
