### ISSUE TITLE
Photoshop edits not updating Storyboarder (not creating new PNG files)

### ISSUE THREAD

**Issue by graveyarddog** [wonderunit/storyboarder#830]
First, Storyboarder is a fantastic program so thank you!  

The issue I'm having: When I open a new scene in Storyboarder, edit the first board in Photoshop and save, it updates as expected. But when creating any new boards, the changes in Photoshop do not take unless I manually save the PNG files.

**Comment by audionerd** [comment]
Each new board will have to be "linked" by pressing the "Edit in Photoshop" button again. 
Also, we fixed a Photoshop update bug in the latest Beta 14 release -- is that the version you're running?

**Comment by graveyarddog** [comment]
Ah! That does the trick. Didn't realize I had to click "Edit in Photoshop" twice. Thanks a bunch!

**Comment by audionerd** [comment]
👍
