### ISSUE TITLE
error with characteriser

### ISSUE THREAD

**Issue by MrStepheLb** [wonderunit/storyboarder#833]
![untitled](https://user-images.githubusercontent.com/33088424/31993406-b4aa947a-b985-11e7-900c-e27ad319b01d.png)
I installed storyboarder and so far falling in love with it, i tried installing characteriser and encountered a few problems(i know it is still in the very early beta phases that is why i am reporting the problem so it can help with the development :D), so first windows would not allow me to install it claiming it might harm the pc, so i had to give it an exception in order to install, beyond that it installed normally or so it seemed... once i tried opening the program i got the exception showcased in the picture attached. 

i am using windows 10 home version

Intel(R) Core(TM) i7-7500 CPU 
12 GB rams
64 bit operating system, x64 based processor 

in case any more information is required i am more than willing to submit them! 
Thanks for your support!!

**Comment by rawbee** [comment]
Hi @MrStepheLb ! Thanks for giving Characterizer a try and reporting your feedback :) We actually have a separate repository for Characterizer located [here](https://github.com/wonderunit/characterizer/issues). I'll file this issue over there, please add future issues there.

**Comment by MrStepheLb** [comment]
Thanks you for the info and for the fast response! Keep up the good work!!

**Comment by rawbee** [comment]
@MrStepheLb No problem! BTW, I updated the Windows build [here](https://github.com/wonderunit/characterizer/releases/tag/v0.2.0) if you want to give it another try :)
