### ISSUE TITLE
[Suggestion] Shift Key doesn't make straight lines

### ISSUE THREAD

**Issue by raffmarqs** [wonderunit/storyboarder#834]
Unfortunately, I have to draw screens/buttons from time to time on a few animations and the straight lines help me a lot. I can see this as a creative direction, but I still believe that a few people might be interested in it.

**Comment by audionerd** [comment]
Thanks for the note. We’re planning to write code for a new drawing engine in V2, and it will support straight line drawing. Tracking this as issue #151
