### ISSUE TITLE
Text in PDF

### ISSUE THREAD

**Issue by unionmovieworks** [wonderunit/storyboarder#836]
When I export a PDF my action text is hidden under the story board images. I thought it was an issue with the 3:3 aspect ratio so I rebuilt the thing as 4:3 thinking the wider frame would leave space for text. But on export I see the text is still hidden under the images. I think you'll need an export layout tool that lets people select text size, image size and placement ...

[balloon fashion 2017-10-25 02.34.44.pdf](https://github.com/wonderunit/storyboarder/files/1416423/balloon.fashion.2017-10-25.02.34.44.pdf)
[balloon fashion 2017-10-25 02.38.35.pdf](https://github.com/wonderunit/storyboarder/files/1416424/balloon.fashion.2017-10-25.02.38.35.pdf)

**Comment by gordielachance** [comment]
... or allow to use a "template" for the exporter (that people could eventually be able to edit)

**Comment by Woohoo61** [comment]
+1 for a template, and let users choose if they also want to include 'Dialogue' and 'Notes', not only 'Action'. Oh, and choose paper size: A4 or Letter.

**Comment by setpixel** [comment]
@unionmovieworks can you send me a zip of that storyboarder file? I think we've fixed this, but I'd like to test with your file.

**Comment by setpixel** [comment]
Fixed in next release! Woot!

**Comment by unionmovieworks** [comment]
Cool.  Thanks for following up.
