### ISSUE TITLE
*.odt (opendocument) exporter

### ISSUE THREAD

**Issue by gordielachance** [wonderunit/storyboarder#841]
Hi guys, very nice app !!!
But it fails to do what people will need the most : a good export for print.

The idea of exporting to PDF is nice but there will always be the layout problem. 
People will probably want to have their content displayed in a custom way.

Why not being able to export to the *.ODT (OpenDocument) format ?
It would export all the data in a table (image, dialogue, action, notes, etc) that people would be able to edit and customize.

I just did prepare a whole storyboard and can't send it to my client since the dialogue / action / notes are not properly exported...

Thanks !

**Comment by setpixel** [comment]
@gordielachance do you know anyone that could work on that aspect?
