### ISSUE TITLE
preferences: allow to select the FPS

### ISSUE THREAD

**Issue by gordielachance** [wonderunit/storyboarder#842]
Hi guys.
It would be logical that you allow people to choose the FPS of a project.
What if I want to work in 25 FPS instead of the (current) 24 FPS ?

Thanks !

**Comment by audionerd** [comment]
good idea @gordielachance. we're working on this next. tracking as issue #842.

**Comment by setpixel** [comment]
@audionerd I think you referenced the wrong issue
