### ISSUE TITLE
Photoshop not opening for editing

### ISSUE THREAD

**Issue by mrpaulmulligan** [wonderunit/storyboarder#852]
simple edit in PS
 open PS
 opened another application
 MAC
 intel, on board gfx, 16gb ram, 15" retina

**Comment by audionerd** [comment]
Currently Storyboarder just asks the OS to try to open the PSD file with whatever program is associated with opening that file type.

You could try associating Photoshop to PSD using the "Always Open With …" feature. See e.g.: https://www.macobserver.com/tips/quick-tip/macos-files-open-always

In the future, we want to make it possible for users to choose which program Storyboarder should use to open PSDs.

**Comment by audionerd** [comment]
Related to https://github.com/wonderunit/storyboarder/issues/868
