### ISSUE TITLE
bug: image saved in photoshop is not always refreshed in storyboarder

### ISSUE THREAD

**Issue by gordielachance** [wonderunit/storyboarder#855]
Hi;
Sometimes when I edit an image in Photoshop, it does not updates back in Storyboarder.
It works if I close and reload the software and reopen it.
PS not working when only closing/reloading project.

(Windows 10 here)

**Comment by audionerd** [comment]
Does this happen even with the latest 0.14.0 version of Storyboarder?

**Comment by gordielachance** [comment]
Yes!

2017-10-30 15:53 GMT+01:00 Eric Skogen <notifications@github.com>:

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
