### ISSUE TITLE
allow to toggle a single board between different versions

### ISSUE THREAD

**Issue by gordielachance** [wonderunit/storyboarder#856]
Hi,
Sometimes I have several different ideas for a board.
It would be awesome to be able to "toggle" a board between several versions and to choose which is the active one.

**Comment by setpixel** [comment]
@gordielachance if that is your real name!

I like this idea. However, I think we were thinking about the concept of just single boards that can be disabled for playback. Therefore you could have any arbitrary amount of boards disabled. 

I never had any friends later on like the ones I had when I was twelve. Jesus, does anyone?

**Comment by gordielachance** [comment]
ah ah :)
Yes, disabling boards could work too of course.
It should also not be included during export.
Thanks for your awesome work !

**Comment by gordielachance** [comment]
https://github.com/wonderunit/storyboarder/issues/1244
