### ISSUE TITLE
autosaving should save temporary files

### ISSUE THREAD

**Issue by gordielachance** [wonderunit/storyboarder#861]
Hi,
I like the idea of the autosave feature but I'm not sure it is a good idea.
I mean, sometimes, I work for 20+ minutes then I realize that I took a wrong way.
Autosave could be useful if something goes wrong but [should be optional](https://github.com/wonderunit/storyboarder/issues/389) and should only save temporary files, not the file the user is working on.

Thank you !

**Comment by audionerd** [comment]
You can disable autosave in preferences. When autosave is off, the project data will only be saved to disk when the user issues a save command. 

All images will be on disk for the session however (Storyboarder doesn't delete any images unless a user runs the cleanup command)

**Comment by gordielachance** [comment]
Ok,
And is autosaving saving the actual file, or is it saving temporary files ?
