### ISSUE TITLE
Unexpected token in Json at position 0

### ISSUE THREAD

**Issue by cosmicponye** [wonderunit/storyboarder#871]
Hello, I have no idea why this happens to me, I was working fine yesterday and the program sent me some errors mensages, and today send me this while trying to open my file 
![image](https://user-images.githubusercontent.com/32248461/32335633-e6e60e78-bfb2-11e7-9f7a-891695e2fafa.png)

I would like to know how to fix this, please!
thank you

**Comment by audionerd** [comment]
It's possible that the Storyboarder file is corrupt or no longer accessible. This may be happening when Storyboarder suddenly has to close and isn't able to save the file. Did you force the app to quit or lose power to your computer at some point recently? Are you low on disk space?

We've seen another report of this and would like to get a fix for it but we'll need more information.

BTW If you have an important storyboarder project that has been corrupted, we can help you try to re-create it from the remaining files. Let us know.

**Comment by audionerd** [comment]
If you see this error message again, please send us a copy of the storyboarder project and we'll take a look. Closing for now.
