### ISSUE TITLE
Uncaught “you need to call 'down' first”

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#878]
![image](https://user-images.githubusercontent.com/33359818/32395304-cc1b1340-c09d-11e7-97fa-33f8aec8a6f9.png)

**Comment by HarveyMartinez** [comment]
I'm having the same issue have  you figure out how to fix?

**Comment by audionerd** [comment]
This is a bug in the sketchpane code we're trying to track down. Can you describe how to recreate this error? Do you know what steps to take to make it happen?

**Comment by HarveyMartinez** [comment]
So i  found that it happens when i hold Option+ Command  to stretch to panel i stretch it back to the original size and it hasn’t came back yet but will keep and update for you

**Comment by HarveyMartinez** [comment]
So i  found that it happens when i hold Option+ Command  to stretch to panel i stretch it back to the original size and it hasn’t came back yet but will keep and update for you

**Comment by audionerd** [comment]
OK, I'm able to recreate this bug. I'll take a look to get it fixed for the next release.
