### ISSUE TITLE
Should provide a way to cancel "Open in Editor" dialog for existing PSD file

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#888]
Hitting <kbd>ESC</kbd> at this dialog will still open the PSD in the editor.

![screen shot 2017-11-07 at 5 20 17 pm](https://user-images.githubusercontent.com/23459/32523233-026f4cf0-c3e0-11e7-87e6-667e5465a49a.png)

Should be able to hit <kbd>ESC</kbd> to cancel. Maybe have a cancel button.

**Comment by setpixel** [comment]
Didn't we fix this?
