### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#89]
Text file describing the process of making a release,

Maybe a npm script to generate a release?

- [x] https://github.com/setpixel/storyboarder/issues/57 Code Signing
- [x] https://github.com/setpixel/storyboarder/issues/88 App Icon
- [x] Write release notes

**Comment by audionerd** [comment]
Will need configuration, see: https://github.com/electron-userland/electron-builder/wiki/Options

**Comment by audionerd** [comment]
Working on this in the `use-electron-builder` branch.

**Comment by setpixel** [comment]
Going to write a wiki page for how to make a release build

**Comment by setpixel** [comment]
Heres a stub wiki for a plan: https://github.com/wonderunit/storyboarder/wiki/How-to-make-a-Release

we can add to it as we need, make more specific.

**Comment by setpixel** [comment]
release notes are done!
