### ISSUE TITLE
Can't erase only 1 layer on an iMac

### ISSUE THREAD

**Issue by johniwhite** [wonderunit/storyboarder#900]
OS X — 10.13.1 — High Sierra

Hi There,
I don't seem to be able to erase just 1 layer, using Alt+Click —on an iMac. It erases through all layers.

Is there a solution?
Thanks ;)
John

**Comment by setpixel** [comment]
Hi John,

You have to be using that particular pen and then press alt+click, not the eraser tool. I know it's complicated. We have to design it better.

**Comment by setpixel** [comment]
Reopen this if you still have a problem.

**Comment by johniwhite** [comment]
Hi Setpixel/Charles (?)
Thanks for the replies.
I think what _I_ was missing was that the roughs pencil, pen and brush share the same layer, so erasing (alt+click) when any of those are selected erases all three of those together. Is that right?

If I was supreme dictator and could make this app even better with a wave of my hand: 
- I'd keep those on separate layers
- I'd keep pasted-in scanned drawings (like thumbnails) in the background where I can avoid rendering into them, and can switch 'em off/hide them
- And introduce a selection tool of some kind, for selectively transforming and copy+pasting stuff (though I can appreciate the problems that could cause with stuff being on separate layers

And, I don't want to look a gift horse in the mouth either.

Thanks for this app and keep up the good work ;)
