### ISSUE TITLE
Picture disappear 

### ISSUE THREAD

**Issue by Kernphysiker** [wonderunit/storyboarder#904]
First of all awesome free software you guys created. 
If I reopen the program some boards are just gone. Or they are reordered without me doing it. Or 2 Board merge in to one. If I put them back at the right order an then close it and reopen it. The same thing happens with different Boards(Which is pretty annoying). I'm on an MacBook Pro(Mid 2012) MacOS 10.12.6, i5 2,5 Ghz, Intel HD Graphics 4000, 16gb ram 

nick

**Comment by Kernphysiker** [comment]
Or some parts of the board are missing. And I can't open the broken boards in Photoshop

**Comment by setpixel** [comment]
Would you be able to record a video screencap recreating this?

**Comment by Kernphysiker** [comment]
they don't belong together

**Comment by Kernphysiker** [comment]
attachment is missing

**Comment by Kernphysiker** [comment]
GitHub doesn't support mov

**Comment by Kernphysiker** [comment]
![bildschirmfoto 2017-11-25 um 22 03 25](https://user-images.githubusercontent.com/33988881/33234772-837b708a-d22c-11e7-848d-0199b60dc71c.png)
![bildschirmfoto 2017-11-25 um 22 03 17](https://user-images.githubusercontent.com/33988881/33234773-8397294c-d22c-11e7-8281-34bd453bfdb3.png)

**Comment by Kernphysiker** [comment]
sorry video doesn't work

**Comment by Kernphysiker** [comment]
![bildschirmfoto 2017-11-25 um 22 04 25](https://user-images.githubusercontent.com/33988881/33234779-a905c0a8-d22c-11e7-81cf-89bdbb2de743.png)
That one is broken

**Comment by Kernphysiker** [comment]
while i was takeing the screenshots it was duplicating it self 
![bildschirmfoto 2017-11-25 um 22 04 39](https://user-images.githubusercontent.com/33988881/33234798-dfc690fe-d22c-11e7-9dbe-c255a131dfae.png)

**Comment by Kernphysiker** [comment]
![bildschirmfoto 2017-11-25 um 22 06 40](https://user-images.githubusercontent.com/33988881/33234802-f0323f60-d22c-11e7-9176-bff6e82f6c5e.png)
and thumbnail and actual board look different like this

**Comment by setpixel** [comment]
Can you upload the mov to youtube and link it to me?

**Comment by Kernphysiker** [comment]
i can't recreate it. Now it worked after a few times.

**Comment by setpixel** [comment]
If you can recreate it, please reopen this issue and let me know!!!
