### ISSUE TITLE
Can't export to PDF

### ISSUE THREAD

**Issue by Kernphysiker** [wonderunit/storyboarder#910]
If i hit print or export to PDF... I can't find the button to export only to print. 
MacOS 10.12.6. 
![bildschirmfoto 2017-11-30 um 21 20 28](https://user-images.githubusercontent.com/33988881/33453075-9c9abe7c-d614-11e7-9996-66d0c29d8911.png)

**Comment by setpixel** [comment]
Fixed in latest release!
