### ISSUE TITLE
Black Stripes on edges of PDF Export

### ISSUE THREAD

**Issue by dschuttenhelm** [wonderunit/storyboarder#911]
So I imported a bunch of images from Worksheet pages, and on some of them I used the move tool to adjust the positions in Storyboarder. 

Now, when I export a PDF, there are black spaces on the edges of some images. 
I thought the empty space would show up white but it seems like the empty pixles on those panels are coming out black instead of white.

(also on this export dialog, the preview for some pages are tilted slightly.)

![screen shot 2017-11-30 at 9 43 30 pm](https://user-images.githubusercontent.com/31042307/33467504-82936438-d61a-11e7-82ac-9b37a539b0b6.png)

Storyboarder Version 1.2.0
MacOS 10.13.1
iMac (27-inch, Late 2012)
Processor: 3.4 GHz Intel Core i7
Memory: 24 GB 1600 MHz DDR3
Graphics: NVIDIA GeForce GTX 675MX 1 GB

**Comment by setpixel** [comment]
Those mark new shots 💃
