### ISSUE TITLE
[REQUEST] Missing a Select All Keyboard Shortcut

### ISSUE THREAD

**Issue by raffmarqs** [wonderunit/storyboarder#915]
Whenever I'm typing something in the dialogue/action/notes, I miss the keyboard shortcut for Select all (cmd+A) and the ones that allow me to move fast through the text like cmd+left, cmd+right, option+left and option+right.

**Comment by audionerd** [comment]
Good point. I think these used to work and then I made some changes to copy/paste and messed them up. I'll take a look.

**Comment by raffmarqs** [comment]
Thanks! 
Just to updated you, I noticed that the cmd/option + directional keys are still working ;)  Just the cmd+A is missing.
