### ISSUE TITLE
Error: Command Failed when trying to save a board from Photoshop

### ISSUE THREAD

**Issue by xKiichan** [wonderunit/storyboarder#917]
When I work on boards using Photoshop, they don't always exactly automatically update when I press save. But today, after downloading & installing the new update, I started getting a message that says something like this whenever I try to save:

> 

> Error: Command failed: "C:\Program Files\Adobe\Adobe Photoshop CC 2018\Photoshop.exe" [project location]

And then the board doesn't get updated in Storyboarder. I have to keep saving repeatedly just to make the updated board appear. The delayed save thing has always happened even before the update, but it was just after I installed it that I started actually getting messages.

I use Windows 10 Home (ver 10.0.15063), processor is Intel Core i5-6200U CPU @ 2.30GHz
![image](https://user-images.githubusercontent.com/34255813/33584049-7db58d8e-d998-11e7-8dcc-b3a20cc83635.png)

**Comment by archnila** [comment]
I'm having the same problems as well.

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as #1656
