### ISSUE TITLE
Onion skin toggle doesn't work consistently

### ISSUE THREAD

**Issue by Sandros94** [wonderunit/storyboarder#918]
I copyed a board, I moved it before the last, then I fliped it horizontally and then (BAM!) the Onion skin is not working, even if close the program.

The Onion Toggle ("O" key) doesn't work anymore in this project.

Windows 10 Pro, just updated the program to the v1.2.0
i7 4790K, GTX 780, 16GB, 1920x0180, (nothing else relative to this bug comes to my mind).

**Comment by DCNielsen** [comment]
Yo. Same thing here. Onion skin broken. Mac OS X 10.12.6. Retina 15-inch 2016 Macbook pro.

**Comment by christiansass** [comment]
watching

**Comment by audionerd** [comment]
Fixed. This will be in the next release.
