### ISSUE TITLE
Ctrl-Shift-I  (on windows)

### ISSUE THREAD

**Issue by goodluckholdings** [wonderunit/storyboarder#923]
Am in love with your product and am super appreciative -

Ctrl-Shift-I is currently mapped to two functions:

View > Developer Tools
File > Import Images

Currently, Developer Tools receives the keyboard command.

Best,
sean.

**Comment by audionerd** [comment]
Good catch. We're working on editable key bindings right now, and will fix this mapping in the course of that effort. Tracking on #887.
