### ISSUE TITLE
export single panel

### ISSUE THREAD

**Issue by noorsjeel** [wonderunit/storyboarder#926]
Hi there,

Is there a way to export a single panel? So not the whole scene? 

Cheers,
Nora

**Comment by audionerd** [comment]
There's not currently a way to export a single panel.

"Export Scene as Images" is usually very fast, and you can find the board you want there.

Or, the individual layer PNGs for a board (main layer, reference, notes...) can be found by choosing "Reveal in Finder" on the right sidebar.
