### ISSUE TITLE
Can´t import final draft script .fdx (v 1.2.1)

### ISSUE THREAD

**Issue by charlyser** [wonderunit/storyboarder#928]

**Comment by setpixel** [comment]
Can you email me the script: charles@wonderunit.com so i can see what the error is?

**Comment by charlyser** [comment]
finally make it work, but now can´t print or export to pdf.... help!!!
![storyboarder](https://user-images.githubusercontent.com/34426560/33811430-4e148e98-dde1-11e7-970e-2cc53b720fa1.jpg)

**Comment by setpixel** [comment]
Can you zip the project and email it to me? 

I think there is a bug where it has a problem printing empty boards. I will know for sure if I can see what the error is.

**Comment by setpixel** [comment]
Yes! I see the error now. 

A way to "fix" this in the meantime is to click on every board, drawing a tiny little bit on each one.

The error is because the boards are blank. We will fix this for next version. Sorry about this!!!!

-c

**Comment by charlyser** [comment]
sorry, but doesn´t work. draw, but when change board, it erase the previous one. and still no print.

**Comment by charlyser** [comment]
https://www.dropbox.com/s/qrdxqoyvget0zxk/IMG_9109.MOV?dl=0

**Comment by setpixel** [comment]
Do you still have this issue with updated version? Please comment if you do!

**Comment by charlyser** [comment]
Nope, works great now…. THANKS…...

**Comment by setpixel** [comment]
:D
