### ISSUE TITLE
Super sluggish and unresponsive on Monoprice 22" Display Tablet

### ISSUE THREAD

**Issue by 3djab** [wonderunit/storyboarder#932]
Hey Charles! Love Storyboarder! Working fine on my MacBook Pro. Tonight I tried using it on my home system. Early 2009 quad core MacPro. OSX El Capitan. 16GB RAM. NVIDIA GeForce GT120 512 MB. I'm using a Monoprice 22" 1080p Display Tablet. I use this for all my graphics. Photoshop, Illustrator, Clip Studio Paint, Storyboard Pro and 3d work with Lightwave. No issues at all. But using Storyboarder, I can barely draw a line. If I draw a circle, it looks like a square. Any idea what could be causing this? I realize this machine is old, but I would think the drawing simple lines would not be such a hit on the processor. Let me know what you think. Whenever you get a chance. I'm sure you're busy. Thanks and take care.

-Joe Bauman

P.S. - Would love to get in on the Slack chat. Thanks!

**Comment by setpixel** [comment]
This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072
