### ISSUE TITLE
Storyboarder cannot update boards from PS and cannot link to PS itself

### ISSUE THREAD

**Issue by renarts** [wonderunit/storyboarder#950]
Hello, I'm just new to storyboarder and it was 2 days ago when it was working fine until it doesn't anymore. There were two issues I found:

1) The app doesn't update my latest updates in Photoshop on my boards and says that "_there must be unsupported PSD feature_".

2) The storyboarder cannot link itself to Photoshop, and that was why I cannot edit my boards on PS. I own PS CS3, and found out that it supports CS4 / CS5 that's why I changed my Photoshop, but still, the message is there. [https://i.imgur.com/WUvbEAn.png](url)

I am running Windows 7 Ultimate with 64-bit Operating System. The processor is AMD A6-5400K APU with Radeon(tm) HD graphics. My ram is 4.00 GB, and my screen resolution is 1366 x 768.

**Comment by audionerd** [comment]
Storyboarder can only load very simple PSD files. Adding vectors, text, layer effects, or masks can confuse it. You might try simplifying your PSD (rasterizing layers for example) tiger it to load. 

Also, in Storyboarder's preferences, you can choose which version of Photoshop you'd like to use to open the board.

To debug further, you could try opening Developer Tools in Storyboarder and letting us know if you see errors in the console there when trying to load the PSD.

**Comment by renarts** [comment]
Hello, thank you for telling me this. I can now choose what Photoshop to use thanks to the new update.
