### ISSUE TITLE
captions always empty

### ISSUE THREAD

**Issue by boarderfrance** [wonderunit/storyboarder#953]
Dear WonderUnit

a systematic bug : When I double click in a dial or action in the script in order to have it in the board, I can see it during a session in a sequence. But when I change sequence or if I close and reopen, the captions are always empty. Except if there is at least one action or dial caption writed directly 

I always create a project from a script.

<img width="337" alt="specs" src="https://user-images.githubusercontent.com/31380825/34454821-982f4b20-ed73-11e7-8b49-f2ce7bb9de8d.png">

Windows 10 pro Storyboarder version 1.3.0 - Surface pro 4
graphic card : intel HD graphic 520 .

**Comment by audionerd** [comment]
Good catch. I was able to replicate this, especially for boards where metadata is being overwritten -- it's not being saved on close. Will fix soon.

**Comment by audionerd** [comment]
This is fixed now and will be part of the next Storyboarder release (probably 1.5.0)
