### ISSUE TITLE
Option to change exported files' directory

### ISSUE THREAD

**Issue by renarts** [wonderunit/storyboarder#955]
Speaking of requests, I was wondering if we can add an option to change the directory of exported files in preferences? An option where users can choose where they can save their exported files? Because I'm having troubles with exporting my project. Can we also have a loading bar that indicates if our project is already exported to let us know that it's finished? It's really hard guessing when the exporting is done.

I also love how you added the photoshop options in preferences; I can finally choose what editor I can use whenever it doesn't work on other ps versions.

Thank you!

**Comment by audionerd** [comment]
> Because I'm having troubles with exporting my project

Can you tell us more about what issues you're having exporting the project? Are you running into a bug in Storyboarder?
