### ISSUE TITLE
Music / Audio Track for Entire Project (such as Music Video)

### ISSUE THREAD

**Issue by escapetheclouds** [wonderunit/storyboarder#956]
I love the software. It would be flawless for me, save for the lack of one feature: the ability to add a soundtrack for the entire project.

I'm working on several music videos, both animated and live action, and would love to be able to drop in a single song as a background for the entire project, so I can then sync my boards to it. I know right now I could chop up the song into fragments and load them into each board, but that's frankly quite cumbersome and doesn't lend itself to the creative process.

Are there plans to add a project-length audio track in the future? It would just need to be a single track, not layered with other audio files. 

Thanks for all the hard work on this beauty!

**Comment by audionerd** [comment]
Have you tried adding your background music to the first board? Music added on the first board will continue to play while paging through the other boards, or when playing the entire scene via the transport play button.

**Comment by audionerd** [comment]
Marking this as closed, as this feature is available in the app now.
