### ISSUE TITLE
All Blacks Are Turning Grey on Import of Worksheets

### ISSUE THREAD

**Issue by Meemoo-twenny-too** [wonderunit/storyboarder#961]
Hey guys, so I'm going to try and just fill in all the default blocks of text here and hope this makes sense!

1. Print a worksheet 2. Draw 3. Scan it in 4. Aw, nuts. All my blacks have turned to a lightish grey

I would have expected my blacks to stay black!

When I open them in Clip Studio (I don't have Photoshop) they show up as black. So I can't bring the brightness down in the Storyboarder where the only problem seems to be

I double checked by just importing an regular image and it's also making my blacks grey. I really hope there's a solution for this somewhere

Original:
![img_1859](https://user-images.githubusercontent.com/35272238/34738677-aec77fb4-f571-11e7-8628-8b0dbcd02dc9.jpg)

Worksheet Import:
![justice league-board-00018](https://user-images.githubusercontent.com/35272238/34738678-aeeb32ec-f571-11e7-98a8-836c2ec60762.png)

**Comment by CuberToy** [comment]
I believe (can be wrong) that's because it goes on the light layer. Try playing with the opacity slider of the light layer in the right sidebar.

**Comment by Meemoo-twenny-too** [comment]
@CuberToy Good lord, I never knew! Thank you **so** much! :D You’ve solved so many issues I was having at once. Officially I can now feel fully comfortable recommending  this app to people!
