### ISSUE TITLE
Exporting to Photoshop, doing edits with multiple layers then saving won't update accordingly in Storyboarder

### ISSUE THREAD

**Issue by jessielamworkshop** [wonderunit/storyboarder#963]
When layers are flattened to the Main layer and then saved when a Storyboarder board is exported to Photoshop, the timeline doesn't refresh or update to reflect that change. Sometimes doing another export to photoshop fixes the refresh issue but it's finicky.

**Comment by audionerd** [comment]
Do you get an error notification in Storyboarder when this happens?

**Comment by jessielamworkshop** [comment]
Hey there,

I don't get any prompts/notifications in my case.

**Comment by camilogta** [comment]
same problem here, it doesn't refresh properly, you need to start over the software and then seconds later it refresh.

**Comment by dubmatix** [comment]
same issue here as well. working off a local drive using photoshop cs6

**Comment by derwok** [comment]
Same here: On MacOS with CS5:
* Export from Storyboarder to PS -  works (opens up PS with layered PSD file)
* Do some editing in PS
* Saving PSD, Closing PS
=> Frame does not update in StoryBoarder. Even not after re-starting SB.

{By the way - did I mention, I really love this great piece of software!!! DUDE!!!}

**Comment by setpixel** [comment]
Editing in photoshop also slows down storyboarder according to #1077

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
