### ISSUE TITLE
refresh board

### ISSUE THREAD

**Issue by jeva72** [wonderunit/storyboarder#967]
When I open a board in photoshop and get back to storyboarder the board does not refresh. I manual refresh option would be very useful.

I am using a Surface Pro 4 with Huion GT221pro, Storyboarder 1.3 and the latest Adobe CC. 

Thank you,

Ivan

**Comment by audionerd** [comment]
Is this happening even after you've clicked the "Open in Photoshop" button in Storyboarder and "linked" the board to a PSD? Every time you open Storyboarder again, you'll have to use the "Open in Photoshop" button to re-establish the link and watch the file.

**Comment by jeva72** [comment]
I just reopened the storyboard. Clicked on the panel and then on open photoshop. I was asked if I want to overwrite or open the existing one. I opened the existing one. Edited it a bit to be able to save it. I saved it. Got back to storyboarder ... and now it is there. I still think that a manual refresh might sometimes be useful. :)

Thank you !

**Comment by audionerd** [comment]
Should be improved in the next release. Tracking as issue #1656.
