### ISSUE TITLE
Scene Timeline View

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#972]
![img_20180115_145703](https://user-images.githubusercontent.com/23459/34965017-acc34992-fa16-11e7-9183-88c276100982.jpg)

Artists can see a Scene Timeline, representing board duration and audio duration.
Some kind of toggle switches between the existing Thumbnail View and this new Scene Timeline View.
The Transport Timeline represents the entire scene – a "mini-map" – and can be scrubbed.
On the Transport Timeline is a zoom control for setting the "window" start/end of the Scene Timeline.
The Scene Timeline represents a zoomed window into the scene.
Boards have thumbnails and a duration. The width of the board depends on its duration. Small widths may crop the board thumbnails. There will probably be a minimum width so they don't disappear.
New shots are represented by a dark border on the left of the board.
Boards are labeled according to shot + board number (e.g.: 2A)
Audio will have duration. Audio lanes will be selected automatically.

First version of the Scene Timeline is not interactive (it will be "read-only").
First version of the Scene Timeline will not have waveform rendering on the audio.

To consider:
- Persistent backgrounds. Shot 1 with boards A, B, C, D might have a background on board A that persists through to D. Future feature we should plan for.

**Comment by christiansass** [comment]
is this completed?
