### ISSUE TITLE
[Suggestion] Show the timecode / elapsed time per scene when drawing to audio

### ISSUE THREAD

**Issue by christiansass** [wonderunit/storyboarder#973]
When drawing thumbnails to an audio track it would be very useful to see some sort of time count that resets per each scene . that would allow me to enter duration easier or at least show the time code of the play head on the audio track being played.

**Comment by ThatOneAiden** [comment]
Agreed. Needed this very much with my last project. Got through it, but would make the next one much easier.

**Comment by christiansass** [comment]
https://github.com/wonderunit/storyboarder/issues/1054

**Comment by setpixel** [comment]
Duplicate #1054
