### ISSUE TITLE
[Suggestion] Timecode display by shot

### ISSUE THREAD

**Issue by christiansass** [wonderunit/storyboarder#974]
I found myself making a video to a full audio track and it would be helpful if the app calculated the beginning of each scene and displayed the time code  in one of or both of the places pictured

![2018-01-15 18_24_03-](https://user-images.githubusercontent.com/35471675/34966532-0be55fe0-fa22-11e7-84da-06844e05e9a4.png)

**Comment by christiansass** [comment]
this was before the timeline view was available. https://github.com/wonderunit/storyboarder/issues/972
please combine this request with https://github.com/wonderunit/storyboarder/issues/1054

**Comment by setpixel** [comment]
duplicate #1054
