### ISSUE TITLE
Audio starts on first window, not on play button.

### ISSUE THREAD

**Issue by nigrath** [wonderunit/storyboarder#975]
Selecting the first storyboard window starts the audio track. The return to start button also starts the audio track. Only the play button should start the audio track?

Mac OS - Storyboarder v1.3.0
iMac Retina 5k, 4GHz Intel Core i7, 32 GB 1867 MHz DDR3, AMD Radeon R9 M395X 4 GB

**Comment by audionerd** [comment]
This is "auditioning" a board, which means playing a board's audio when you navigate to it. You can turn this off from the Navigation menu.
