### ISSUE TITLE
[Suggestion] Scaling of Drawing Area in UI

### ISSUE THREAD

**Issue by rlelache** [wonderunit/storyboarder#976]
Using this on Dell XPS 2-in-1 laptop running Windows 10 with 1920x1080 display resolution.

I installed this software today based on the product website you set up, but noticed after installing that the app's display did not mirror what was shown in the screenshots. (Notably, the icons on the top row were much larger, and the drawing area was very small and not adjustable.)

It turns out for my laptop, the default display setting is to scale up all text, apps, etc. by 150%. Turning this down to 100% seems to fix this issue with your app, but renders all of my other apps with text that is much smaller than is usable day-to-day.

It would be great if the icons on the top and the drawing area could scale together, vs. only the icons growing larger and forcing the drawing area to become too small to be usable. Either that, or have an option to customize the sizing of elements in the app UI so on displays like this, the user can scale up the areas of the app that they need to be larger to be more usable.

<img width="960" alt="storyboarder screencap" src="https://user-images.githubusercontent.com/35513938/35023006-c7684ff4-fb06-11e7-96e1-4841249cb00e.png">

**Comment by Masa-S-Ayarama** [comment]
Have same problem on Windows 10 64bit. I want to scale up canvas for easier drawing. It would be great if the canvas adjustable, drawing tools is smaller than this,  and can hide scene shot description panel. Anyway thank you so much for develop this free program.

**Comment by setpixel** [comment]
If you press tab a few times, ill will change the layout. However, we are planning a fix for this in #33
