### ISSUE TITLE
[Suggestion] can we get a copy and paste that only deals with the image content ONLY instead of the entire "scene"?

### ISSUE THREAD

**Issue by christiansass** [wonderunit/storyboarder#977]
i have a storyboard where I have spent considerable time getting the frames all timed to the audio and the script and notes in. if i want to go back through and start adding images , many times i want to just copy the contents of an image into another frame without changing anything else. not everything is linear. i think that's my main issue with the software.. it assumes and only allows you to work linearly with it.. sooo a control+shift+c maybe??

**Comment by christiansass** [comment]
based on how you are specifying "layer specific" actions in the wiki
https://github.com/wonderunit/storyboarder/wiki/Layers-in-Storyboarder

i would suggest you make an alt+control+c  and alt+control+v option for copying a layer only from scene to scene

**Comment by christiansass** [comment]
maybe this could be as simple as a paste image only option! alt+control+v = "paste into current scene" or a right click paste context specific...

**Comment by christiansass** [comment]
the more i use this in a production environment .. the more valuable/critical the lack of this funtion becomes. need to be able to copy and past contents of a drawing without copying the whole slide. . im hoping this is incorporated into the new timeline ive seen.

**Comment by christiansass** [comment]
again. i am working on a storyboard and for all the compelling reasons to use this software. they all melt away without the ability to copy and paste ONLY image elements in a scene without creating a scene. it one of those deal breaking things. kills my workflow completely. which if i understand correctly goes against the entire goal of the software.   PLEASE CAN I GET A SIMPLE IMAGE COPY AND PASTE?????!???

**Comment by christiansass** [comment]
How am I the only one to have this issue??

**Comment by bitbutter** [comment]
Yes. Would love to have a copy/paste option for image only. Use case: i have a bunch boards with narration text or other notes all entered in. I've just drawn an image for one of those boards and want to repeat the exact same image for a board later on in the project. Seems there's currently no convenient way to do that.

**Comment by christiansass** [comment]
while taking some time to understand the underpinnings of this process, i came across this video on Charles webpage:
http://setpixel.com/tools/drawing-a-story/
https://youtu.be/EOI0wDqc5Bg

this should prove a strong argument for being able to copy and paste elements without duplication of boards since this example shows the software has many board with duplicated content. 

I realize the main difference is im working with an audio track vs just talking through the script.

but this is what causes my problems.. once boards are scaled and synced to the audio. duplicating and inserting a board shifts all board following rendering all the time to sync to an audio track useless

**Comment by setpixel** [comment]
This should be easy to do.

**Comment by audionerd** [comment]
Cool. To summarize: Copy will work as-is. We'll add a "Paste Image without Board Data" command.

**Comment by audionerd** [comment]
So I'm thinking about this again. I think it's more like: "Paste in Place"

- If the clipboard contains _a single image_, it will replace the current layer of the current board.
- If the clipboard contains _a Storyboarder board_ (i.e.: layers), it will replace all layers of the current board but it will _not_ overwrite any metadata.

And if you did want duplicate metadata but a new image, you could always 1) duplicate the board, 2) clear its layers, and 3) "Paste in Place" to change the image(s).

**Comment by setpixel** [comment]
I think we need two different menu items:

Paste image into board
Paste (will make a new board)

I think we need something similar for import.

**Comment by gordielachance** [comment]
@setpixel : have a look at my suggestion #1247 - where copy/cut/paste are in two different menus : timeline and viewport.

**Comment by audionerd** [comment]
This feature will be part of the next release.
