### ISSUE TITLE
pause button does not pause audio

### ISSUE THREAD

**Issue by nigrath** [wonderunit/storyboarder#978]
"pause" playback of boards does not stop audio as per previous version. Press play and audio starts over existing audio that has not stopped.

"Export video" does not include captions if on.

"Audition board audio" is on by default and setting not remembered if unchecked and file closed and reopened.

Storyboarder v1.4

MacOS High Sierra, Mac (Retina 5K, 27-inch, Late 2015), 4 GHz Intel Core i7, 32 GB 1867 MHz DDR3, AMD Radeon R9 M395X 4 GB

**Comment by christiansass** [comment]
same issues here

**Comment by audionerd** [comment]
I'm going to make separate issues for each bug you reported.
Audition Board Audio setting not remembered: https://github.com/wonderunit/storyboarder/issues/984
Export video doesn't include captions: https://github.com/wonderunit/storyboarder/issues/985

**Comment by audionerd** [comment]
Fixed. Will be in the next release.
