### ISSUE TITLE
file naming not matching boards

### ISSUE THREAD

**Issue by christiansass** [wonderunit/storyboarder#979]
![image](https://user-images.githubusercontent.com/35471675/35065027-8866fb62-fb91-11e7-95fe-dec75badc935.png)

what would it take to keep these image file names in sync with their boards?? seems like its doing everything else in a human readable format but adding board numbers sequentially as you make hem only not renaming all existing images. I would prefer and expect to be able to look up board-44A.png

**Comment by setpixel** [comment]
because they can be reordered, we maintain a unique filename so when they shift, we dont have to rename all the other files.

**Comment by christiansass** [comment]
what if you made a command to sync them all up when you do a cleanup or maybe adding a resync command that renames all the files to match and reopens the file. kind of a last step tool

**Comment by setpixel** [comment]
when you export boards it does that if i remember correctly. I don't think cleanup does this though

**Comment by christiansass** [comment]
i was only doing this during my workaround for duplicating image contents without messing up timing and notes

**Comment by christiansass** [comment]
@setpixel can this be reopened? you can see this was from using the export scene as images option in the dropdown menu
![image](https://user-images.githubusercontent.com/35471675/38107829-a23eefe6-3358-11e8-8f27-0aaf1f17086d.png)


![2018-03-29 13_52_40-chronicles storyboarder](https://user-images.githubusercontent.com/35471675/38107782-7f89d7a4-3358-11e8-8950-492ada6b32ff.png)
