### ISSUE TITLE
Text in Hebrew problem

### ISSUE THREAD

**Issue by dciabo** [wonderunit/storyboarder#982]
Hi, when writing in Hebrew (i guess if you try Arabic as well, any language written right to left), while you're inside the software it will look good, but once you export it instead of the correct dialogs and actions it will export the words backwards!

Windows 10 Pro
Intel Xeon E3 1240v5
16GB RAM
Amd Firepro W4300

**Comment by setpixel** [comment]
We can not fix for a while because of the way the pdf engine is working. Sorry :( I hope this can be fixed soon!
