### ISSUE TITLE
[Suggestion] Export file name options

### ISSUE THREAD

**Issue by SaulSalsa** [wonderunit/storyboarder#989]
Before anything else, thanks everyone for this awesome piece of software you are doing a great job!

So here's my suggestion: Adding option to rename exported images based on board number (ProjectName-board-**1A, 1B, 2A**, etc), aside from default sequential number (ProjectName-board-**0001, 0002, 0003** etc). I think it would help identifying exported files with the same numbering shown in SB's timeline and exported PDF storyboards.

Also I'd like to automatically add the current board number to my sequence on PPro via _"Clip Name"_ effect for animatic draft reviews (pictured below), PPro's effect works using either the file name or _"project file name"_, the later seems to assigned by PPro using text from SB's _Action field_, in which I type the board number to get it embedded on each exported file.

Later on PPro I have to delete rest of the _"project file name"_ up to the number for each file since it contains my action script and don't need that shown on screen... It's an extra step which I don't mind, but after adding or deleting boards on each revision renaming gets very complicated (if it was in file name it could be easily batch-renamed with apps like Bridge).

<img src="https://www.evernote.com/shard/s279/sh/cb1762d2-3c22-4e87-b668-e9b5b21ecd60/5505cd585d0e1e73/res/190074dd-5896-4944-b032-8e527b3c2d1f/skitch.png?resizeSmall&width=832">

Running on:
macOS 10.12.6
Storyboarder ver 1.4.0
Premiere Pro CC 12.0

**Comment by christiansass** [comment]
I also highly endorse this idea... export without board identifiers is almost useless

**Comment by christiansass** [comment]
looks like this is getting traction on issue https://github.com/wonderunit/storyboarder/issues/699

**Comment by setpixel** [comment]
Duplicate #699
