### ISSUE TITLE
turn off GPU blacklist for next release

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#992]
`app.commandLine.appendSwitch('ignore-gpu-blacklist')`

https://github.com/electron/electron/issues/8217
https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

**Comment by audionerd** [comment]
Not sure if this will work, as `ignore-gpu-blacklist` is not on the "supported" list in the Electron docs :/

**Comment by setpixel** [comment]
It's just a chromium flag so it should work

**Comment by gormonn** [comment]
Unfortunately this only works through passing an argument at startup. See https://github.com/electron/electron/issues/15339
> It's just a chromium flag so it should work

**Comment by audionerd** [comment]
@gormonn Are you seeing problems with a GPU in Storyboarder?

I believe that switch does work as we're using it - `app.commandLine.appendSwitch('ignore-gpu-blacklist')` - in the version of Electron we're on - currently `8.4.0`. 

I think you misread the discussion on the issue you linked.
