### ISSUE TITLE
After Effects importer

### ISSUE THREAD

**Issue by Nico-Duduf** [wonderunit/storyboarder#999]
Hi,

I've noticed the .storyboarder file is JSON, and I'm thinking about writing a simple script to import this in Adobe After Effects (which would be simpler than implementing an "export to AE" feature in storyboarder)

Is there anything special I should know about how the data is saved in this JSON? Or a document with the file specifications? Anyway, what I can read in the file is pretty simple and I can work with that.

I'll let you know when it's available, it should not take long.

**Comment by setpixel** [comment]
No it's pretty straightforward! We sometimes make minor additions. For example, we will be adding the duration of audio attached to a board. But that shouldn't create a problem with your script!

**Comment by setpixel** [comment]
cc @audionerd

**Comment by audionerd** [comment]
We started documenting the file format in the wiki, although it's incomplete (doesn't have the new audio object for example) https://github.com/wonderunit/storyboarder/wiki/Storyboarder-File-Format

I'd recommend looking at the Final Cut Pro 7/X exporters code and associated tests for reference.

If you're interested in writing an AE exporter for Storyboarder I could help scaffold a branch for you that ties it into the UI and you could take it from there.

**Comment by mrharris** [comment]
Do you think it would be possible to have an [OpenTimelineIO](https://github.com/PixarAnimationStudios/OpenTimelineIO) adapter for the .storyboarder format? That might make it easier to get storyboarder into a wider range of apps 

I already opened an issue here for this here https://github.com/wonderunit/storyboarder/issues/948 but this one looks related to it

**Comment by Nico-Duduf** [comment]
For this specific case, I don't think using an intermediary format like OpenTimeLineIO would be helpful, as After Effects is not an editor and works with layers and there's no support of this format.
It will be easier to parse the data in the .storyboarder file.

But I agree to the fact that exporting (and importing) to OpenTimeLineIO from storyboarder could be useful, as there is support for this format both in Final Cut and Premiere (and maybe Avid or even Lwks?)

@audionerd I don't think it's possible to export directly from storyboarder to an After Effects project, as the format is binary and closed source (even the so-called AEP XML contains binary data). I don't know anybody who knows how to do this, so the simplest way would be to write an After Effects tool to parse the .storyboarder file.

**Comment by Nico-Duduf** [comment]
I've finished the script, it's available [there](https://github.com/Rainbox-dev/DuAEF_Duik/tree/master/Release/WUStoryboarder).

I used, and included, my own After Effects framework to make this quickly, which is under GNU-GPL-3.
The library with the methods used is [this one](https://github.com/Rainbox-dev/DuAEF_Duik/blob/master/src/libs/DuWUStoryboarderLib.jsxinc).

The framework is [documented here](https://rainbox-dev.github.io/DuAEF_Duik/).

I've posted more end-user details [there](http://duduf.com/storyboarder-and-after-effects/)

**Comment by setpixel** [comment]
It would be cool to link to this within the app as I think it's really useful! @Nico-Duduf if you submit a PR that adds a menu item to import After effects and links to your GH repo, I will approve it!

**Comment by Nico-Duduf** [comment]
I'll have a few issues to fix first (and handle linked psd, which I just completely forgot) and yes, I'll do this as soon as I have a little time ;)

Thanks
